// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug uno-show-em-no-mercy
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Classic color-matching turns meaner through hand management, with stackable draw cards, hand swaps, and penalties that swell a single turn.",
  default:
    "A familiar discard race becomes a grudge machine where one stacked penalty can bury a hand. Its core is hand management: match color, number, or symbol, then time draw cards, 7 swaps, and 0 passes. Victory comes by emptying a hand or surviving the 25-card Mercy rule.",
  loose:
    "A familiar discard race becomes a grudge machine where one stacked penalty can bury a hand. Its core is hand management: match color, number, or symbol, then time draw cards, 7 swaps, and 0 passes. Victory comes by emptying a hand or surviving the 25-card Mercy rule. The 168-card deck adds Wild Draw 10 and Wild Color Roulette, a color call that draws until the color appears.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:30.774Z",
  model: "gpt-5.5",
  durationMs: 29524,
  sources: [
    "https://service.mattel.com/us/productPopup.aspx?prodno=HWV18&siteid=27",
    "https://service.mattel.com/instruction_sheets/HVW18-Eng.pdf",
    "https://www.64ouncegames.com/pages/uno-no-mercy-rules",
    "https://cardgameuno.fandom.com/wiki/UNO_Show_%27Em_No_Mercy",
  ],
} as const;
