// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug uno-show-em-no-mercy
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Take-that shedding card game where players match color, number, or symbol while stacking draw penalties onto rivals.",
  default:
    "Mean take-that shedding card game where players race to empty a hand while dumping huge draw penalties on each other. On a turn, play one card matching color, number, or symbol; without a match, draw until one appears. Playing the last card wins, or the last survivor wins after rivals hit the 25-card Mercy Rule.",
  loose:
    "Mean take-that shedding card game where players race to empty a hand while dumping huge draw penalties on each other. On a turn, a player plays one card matching color, number, or symbol; without a match, they draw until one appears. Playing the last card wins, or the last survivor wins after rivals hit the 25-card Mercy Rule. The 168-card deck adds Wild Draw 6, Wild Draw 10, Skip Everyone, Discard All, stacking, 7s hand swaps, and 0s hand passes.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:33.722Z",
  model: "gpt-5.5",
  durationMs: 32063,
  sources: [
    "https://shop.mattel.com/en-ca/products/uno-show-em-no-mercy-hwv18-en-ca",
    "https://m.service.mattel.com/us/Technical/productDetail?prodno=HWV18",
    "https://service.mattel.com//instruction_sheets/HVW18-Eng.pdf",
    "https://www.unorules.com/uno-show-em-no-mercy-rules/",
    "https://www.reddit.com/r/unocardgame/comments/1bnhw4m/uno_no_mercy/",
  ],
} as const;
