// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug frosthaven
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative campaign dungeon-crawler where heroes pick paired action cards, fight standees on map tiles, and build the outpost.",
  default:
    "Cooperative campaign dungeon-crawler with card-driven tactical combat and town building between missions. Each round, heroes choose two cards, use one top action and one bottom action, then act by initiative while monster decks reveal attacks. The party wins a scenario by completing its objective before cards or hit points run out.",
  loose:
    "Cooperative campaign dungeon-crawler with thinky, card-driven tactical combat and a between-missions town-building layer. Each round, every hero secretly chooses two cards, uses one top action and one bottom action, then acts by initiative while monster decks reveal attacks. The party wins a scenario by completing its printed objective before too many cards or hit points run out, unlocking new branches toward the campaign finale. After missions, loot turns into crafted items, upgraded buildings, map stickers, event cards, and sealed character boxes.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:26.669Z",
  model: "gpt-5.5",
  durationMs: 16599,
  sources: [
    "https://cephalofair.com/products/frosthaven-bundles",
    "https://pikdonker.github.io/frosthaven-rule-book/",
    "https://www.boardgamequest.com/frosthaven-review/",
  ],
} as const;
