// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug frosthaven
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A starving northern outpost turns every dungeon crawl into triage, with hand management powering brutal card tactics.",
  default:
    "A starving northern outpost makes each mission feel like triage: loot pays for gear, walls, and buildings, not just sharper swords. Hand management drives the combat. The campaign ends by pushing branching scenario chains toward a final narrative while the town keeps changing.",
  loose:
    "A starving northern outpost makes each mission feel like triage: loot pays for gear, walls, and buildings, not just sharper swords. Hand management drives the combat, as mercenaries burn cards for big turns and risk exhaustion. The campaign wins by pushing branching scenario chains toward a final narrative, while the town keeps changing afterward. Each outpost phase marks a week; ten weeks flip the season and event deck.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:54.137Z",
  model: "gpt-5.5",
  durationMs: 23576,
  sources: [
    "https://cephalofair.com/collections/board-games/products/frosthaven-bundles",
    "https://cephalofair.com/pages/frosthaven",
    "https://pikdonker.github.io/frosthaven-rule-book/",
    "https://www.nopunincluded.com/npi/frosthaven",
  ],
} as const;
