// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug chess-bughouse
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Team chess variant on paired boards where partners pass captured pieces across and drop reserves to make sudden mates.",
  default:
    "Fast team chess variant played on paired boards, with normal chess moves plus captured pieces passed to a partner as reserves. On a turn, move a board piece or drop a reserved piece onto an empty square. A team wins when either opponent is checkmated, timed out, or resigns.",
  loose:
    "Fast team chess variant played on paired boards, with normal chess moves plus captured pieces passed to a partner as reserves. On a turn, a player either moves a board piece or drops a reserved piece onto an empty square, often while asking for a knight, pawn, or no trades. The team wins when either opponent is checkmated, timed out, resigns, or loses by rule. The table sound is constant cross-board shouting, because one sacrifice can hand over the exact piece that mates elsewhere.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:21.040Z",
  model: "gpt-5.5",
  durationMs: 22127,
  sources: [
    "https://www.chess.com/terms/bughouse-chess",
    "https://en.wikipedia.org/wiki/Bughouse_chess",
  ],
} as const;
