// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug slay-the-spire
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative roguelike deck-builder where players spend energy on cards, kill hallway monsters, draft rewards, and push toward bosses.",
  default:
    "Cooperative roguelike deck-builder where the group climbs branching acts and fights monsters. Each combat, players draw hands, spend energy on attacks, blocks, powers, potions, and relic triggers. The party wins by defeating the chosen final boss; if any hero hits 0 HP, the run is lost.",
  loose:
    "Cooperative roguelike deck-builder where the table climbs branching acts, fights monsters, and tunes character decks after each encounter. In combat, each player draws a hand, spends energy on attacks, blocks, powers, potions, and relic triggers, then enemies strike back. The party wins by defeating the chosen final boss; if any hero drops to 0 HP, the run ends in a loss. The box leans into physical card play with hundreds of sleeved, double-sided upgrade cards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:10.354Z",
  model: "gpt-5.5",
  durationMs: 20186,
  sources: [
    "https://www.gamesradar.com/tabletop-gaming/slay-the-spire-the-board-game-review-a-pitch-perfect-tabletop-adaptation/",
    "https://coopboardgames.com/cooperative-board-game-reviews/slay-the-spire/",
  ],
} as const;
