// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug slay-the-spire
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A solitary roguelike becomes a shared climb, with deck-building turns that turn tiny card upgrades into life-or-death plans.",
  default:
    "The digital roguelike’s nervous math becomes a cooperative climb where one bad room can wreck a run. Deck-building drives each fight as heroes trim weak cards, add rewards, and spend energy. The party wins by beating the chosen act boss before any hero dies.",
  loose:
    "The digital roguelike’s nervous math becomes a cooperative climb where one bad room can wreck a run. Deck-building drives each fight as heroes trim weak cards, choose rewards, and spend energy in shared plans. The party wins by beating the chosen act boss before any hero dies, or the run collapses to the start. A single die sets enemy patterns and relic triggers, turning hidden video-game bookkeeping into a table ritual.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:57.356Z",
  model: "gpt-5.5",
  durationMs: 55033,
  sources: [
    "https://contentiongames.com/games/slay/",
    "https://contentiongames.myshopify.com/products/slay-the-spire-board-game-retail-edition",
    "https://www.pcgamer.com/games/board-games/the-slay-the-spire-board-game-might-be-a-little-too-faithful-to-the-videogame-but-its-co-op-mode-offers-a-whole-new-perspective-on-the-iconic-roguelike/",
    "https://www.meeplemountain.com/reviews/slay-the-spire-the-board-game/",
  ],
} as const;
