// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug blood-on-the-clocktower
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Social deduction party game where secret roles trade claims by day, wake for powers by night, and vote to execute suspects.",
  default:
    "Social deduction party game about a good village hunting a hidden Demon. Each day, players share claims, whisper privately, nominate a suspect, and vote on an execution. Good wins if the Demon dies; evil wins if the town is cut down to two living players.",
  loose:
    "Social deduction party game about a good village trying to find the hidden Demon while evil players lie with cover roles. Each day, players talk openly or whisper in pairs, nominate a suspect, and vote; each night, the Storyteller wakes roles to give clues, poison, or kill. Good wins by executing the Demon, while evil wins by reducing the town to two living players. Dead players still talk and each keeps one ghost vote, so early kills stay in the argument.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:34.937Z",
  model: "gpt-5.5",
  durationMs: 16177,
  sources: [
    "https://bloodontheclocktower.com/",
    "https://boardgamegeek.com/boardgame/240980/blood-on-the-clocktower",
    "https://www.wargamer.com/blood-on-the-clocktower/review",
  ],
} as const;
