// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug blood-on-the-clocktower
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A dead Storyteller runs a village of whispering liars, using social deduction where corpses still argue and every claim can poison the case.",
  default:
    "A murder village turns every whisper into evidence, since even the dead keep talking. It is social deduction, with a Storyteller managing secret roles, night powers, false information, and public executions from a hidden Grimoire. Good wins by killing the Demon; evil wins by lasting until only two-l",
  loose:
    "A murder village turns every whisper into evidence, since even the dead keep talking. It is social deduction, with a Storyteller managing secret roles, night powers, false information, and public executions from a hidden Grimoire. Good wins by killing the Demon; evil wins by lasting until only two living players remain. Each dead player keeps one ghost vote, so a corpse can still swing the final execution.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:26.490Z",
  model: "gpt-5.5",
  durationMs: 46529,
  sources: [
    "https://bloodontheclocktower.com/",
    "https://bloodontheclocktower.com/pages/buy",
    "https://bloodontheclocktower.com/products/blood-on-the-clocktower-the-game",
    "https://wiki.bloodontheclocktower.com/Setup",
    "https://wiki.bloodontheclocktower.com/States",
    "https://www.wargamer.com/blood-on-the-clocktower/review",
  ],
} as const;
