// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug deadwood-1876
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Semi-cooperative bluffing card game where crews play gun cards and special actions to steal hidden safes, then turn on allies.",
  default:
    "Semi-cooperative social deduction card game about stealing hidden safes for a crew. On a turn, play one card as an item, or as a gun to rob a safe or duel over positions while dice settle fights. The crew with the most gold reaches the Final Showdown, and the last survivor wins.",
  loose:
    "Semi-cooperative social deduction card game about uneasy crews stealing hidden safes of gold, badges, and showdown guns. On a turn, play one card as a special item, or as a gun to rob a safe or duel over positions while defenders answer with guns and both sides roll matching dice. After badge bonus turns, the establishment with the most gold reaches the Final Showdown, where the last survivor keeps the gold and wins. The faux book box holds wooden saloon platforms, star pawns, and chunky weapon dice.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:04.716Z",
  model: "gpt-5.5",
  durationMs: 36630,
  sources: [
    "https://facadegames.com/products/deadwood-1876",
    "https://cdn.shopify.com/s/files/1/0028/2964/7961/files/Deadwood_1876_Rules_English.pdf?4346553514003986582=",
    "https://zatu.com/blogs/reviews/deadwood-1876-review",
  ],
} as const;
