// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug deadwood-1876
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A gold-rush alliance curdles into a last-gun duel, with hand management driving robberies, safes, and nervous partnerships.",
  default:
    "Alliances in Deadwood last only until enough gold hits the table. Hand management drives each robbery as cards become weapons or one-shot items. The richest team reaches the Final Showdown, then partners shoot each other until one outlaw remains.",
  loose:
    "Alliances in Deadwood last only until enough gold hits the table. Hand management drives each robbery, as cards become weapons or one-shot items while safes hide gold, badges, or guns. The richest team reaches the Final Showdown, then its partners shoot each other until one outlaw remains. The faux book box holds wooden star pawns, engraved dice, and characters based on real Deadwood figures.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:30.561Z",
  model: "gpt-5.5",
  durationMs: 39457,
  sources: [
    "https://facadegames.com/products/deadwood-1876",
    "https://cdn.shopify.com/s/files/1/0028/2964/7961/files/Deadwood_1876_Rules_English.pdf?4346553514003986582=",
    "https://www.reddit.com/r/boardgames/comments/112zxeu/im_the_founder_of_facade_games_and_the_inventor/",
    "https://www.boardgameoracle.com/en-GB/boardgame/price/Ly8bIdfd0Y/deadwood-1876",
  ],
} as const;
