// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-castles-of-burgundy
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Dice-driven tile-placement Euro where each of two dice takes a hex tile from its numbered depot or places one on a matching space of a growing estate.",
  default:
    "Dice-driven tile-placement Euro about filling a hex estate of colored regions. Two dice each take a tile from a depot, place a stored tile, sell goods, or hire workers that nudge a die. Finished regions score size plus a shrinking phase bonus; high score wins.",
  loose:
    "Dice-driven tile-placement Euro about filling a hex estate of colored regions. Two dice each take a hex tile from a depot, place a stored tile on a matching space, sell goods for a silverling, or hire workers that nudge a die. Finished regions score size plus a shrinking phase bonus; high score after five phases wins. Castles grant a free extra action, ships pull goods and turn order, mines mint silverlings, and yellow knowledge tiles bend the rules.",
};

export const meta = {
  generatedAt: "2026-09-14T12:36:24.000Z",
  model: "claude-opus-5 (simulated run — gateway throttled)",
  durationMs: 286674,
  sources: [
    "https://www.shutupandsitdown.com/review-castles-burgundy/",
    "https://www.meeplemountain.com/reviews/the-castles-of-burgundy/",
    "https://www.yucata.de/en/Rules/CastlesOfBurgundy",
    "https://www.geeksundergrace.com/tabletop/review-castles-of-burgundy-anniversary-edition/",
    "https://www.ontabletop.com/board-games/alea-celebrate-20-years-the-castles-of-burgundy/",
    "https://en.wikipedia.org/wiki/The_Castles_of_Burgundy",
  ],
} as const;
