// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug ready-set-bet
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time party betting game where players slap wager tokens onto numbered horses while a dice-rolling bookie races them down the track.",
  default:
    "Real-time horse-racing betting party game. One player rolls two dice again and again to move horses numbered 2 to 12, while everyone else grabs betting spaces, with the earliest bets paying the best odds. After four races, the richest bettor wins.",
  loose:
    "Real-time horse-racing betting party game with no turns. One player rolls two dice nonstop to advance the horse matching each total, while the rest race to claim win, place, and show spaces before betting closes near the finish. Correct bets pay out and most wrong ones cost money; after four races, the player with the most cash wins. Horse 7 moves most often, so its spaces pay the least.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.334Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 150000,
  sources: [
    "https://www.boardgamequest.com/ready-set-bet-review/",
    "https://punchboard.co.uk/ready-set-bet-review-worth-taking-a-gamble-on/",
  ],
} as const;
