// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug just-one
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative word-party game where clue-givers write single-word hints, duplicate clues vanish, and the guesser names the card.",
  default:
    "Cooperative word-party game about helping one guesser identify a mystery word. Each round, everyone else writes one-word clues on easels, cancels matching clues, then shows only the survivors. The team scores for correct guesses and counts successes when the deck runs out.",
  loose:
    "Cooperative word-party game about helping one guesser identify a mystery word from a few surviving hints. Each round, the guesser picks a numbered word on a card while everyone else secretly writes one-word clues, compares them, and removes any matches. A correct guess scores the card, a skip loses that card, and a wrong guess also burns the next card; when the deck empties, the team counts successes toward 13. The dry-erase easels double as card stands, and matching “clever” clues get flipped facedown before the guesser sees them.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:53.888Z",
  model: "gpt-5.5",
  durationMs: 15942,
  sources: [
    "https://www.rprod.com/en/press/just-one",
    "https://cdn.svc.asmodee.net/production-rprod/storage/downloads/games/justone/jo-en01-rules-1612262916hCy2w.pdf",
    "https://coopboardgames.com/cooperative-board-game-reviews/just-one-review",
  ],
} as const;
