// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug just-one
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Duplicate clues vanish before the guesser opens their eyes, turning cooperative clue-giving into a quiet fight for originality.",
  default:
    "Obvious clues become dangerous because matching words disappear before the guesser sees them. Clue-giving drives each round as teammates write one-word hints in secret. The group scores by solving as many of 13 mystery cards as possible, while a wrong guess burns an extra card.",
  loose:
    "Every clue is a gamble because the obvious words cancel each other out before the guesser sees them. Clue-giving drives each round as hidden teammates write one-word hints, compare them, and discard duplicates. The group wins by banking as many of 13 mystery cards as possible, with a wrong guess costing an extra card. The plastic easels make the table look like a tiny gallery of bad handwriting and sudden groans.",
};

export const meta = {
  generatedAt: "2026-05-13T16:36:24.458Z",
  model: "gpt-5.5",
  durationMs: 48614,
  sources: [
    "https://www.rprod.com/en/games/just-one",
    "https://x.boardgamearena.net/data/rules/justone/JO_EN_Rules.pdf",
    "https://boardgamegeek.com/boardgame/254640/just-one",
  ],
} as const;
