// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug liars-uno
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Face-down Liar's cards turn familiar color matching into bluffing, with every claim inviting a callout from the table.",
  default:
    "Face-down Liar's cards make ordinary UNO turns feel suspicious. Bluffing drives each turn as hidden cards are announced, challenged, and sometimes exposed. The first player to empty their hand wins, but a caught final lie keeps the round alive.",
  loose:
    "Face-down Liar's cards turn familiar UNO tempo into shaky claims and sudden callouts. Bluffing drives each turn: a hidden card may match the pile, or only sound legal. The first player to shed every card wins, unless a final facedown lie gets exposed. The 112-card deck pairs each colored number with a regular card and a Liar's version; action cards feed the same suspicion engine.",
};

export const meta = {
  generatedAt: "2026-05-13T16:36:45.719Z",
  model: "gpt-5.5",
  durationMs: 38684,
  sources: [
    "https://shop.mattel.com/products/liars-uno-card-game-jlh43",
    "https://service.mattel.com/instruction_sheets/JLH43%20English.pdf",
    "https://www.geekyhobbies.com/liars-uno-rules/",
  ],
} as const;
