// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug trivial-pursuit
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Classic trivia party game where players roll around a wheel board, answer category questions, and collect pie wedges.",
  default:
    "Classic trivia party game about general-knowledge questions in six color-coded categories. On a turn, a player rolls, moves along the wheel-and-spoke board, and answers the category they land on. Fill all six pie wedges, reach the center, and answer the final question to win.",
  loose:
    "Classic trivia party game about general-knowledge questions in six color-coded categories. On a turn, a player rolls a die, moves around the wheel-and-spoke board, and answers the color category they land on. Correct answers keep the turn going, and correct answers on headquarters spaces earn matching pie wedges. Fill all six wedges, reach the center, and answer the opponents’ chosen final category to win.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:01.658Z",
  model: "gpt-5.5",
  durationMs: 16946,
  sources: [
    "https://www.hasbro.com/common/instruct/TrivialPursuitGenusIV.PDF",
    "https://www.pocketgamer.com/real-arcade-trivial-pursuit-genus-edition/review/",
    "https://en.wikipedia.org/wiki/Trivial_Pursuit",
    "https://dicetower.com/board-game/2952",
  ],
} as const;
