// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug trivial-pursuit
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Colored wedges turn bar-room facts into a public trial of memory, with roll-and-move steering each player toward favored categories.",
  default:
    "Colored wedges turn stray facts into a public trial of memory, where one missed answer can end a hot streak. The core mechanic is roll-and-move. A player wins by filling all six category wedges, reaching the center, and answering an opponent-chosen category.",
  loose:
    "Colored wedges turn stray facts into a public trial of memory, where one missed answer can end a hot streak. The core mechanic is roll-and-move. A player wins by filling all six category wedges, reaching the center hub, and answering a final opponent-chosen category. The original Genus set covered Geography, Entertainment, History, Arts & Literature, Science & Nature, and Sports & Leisure.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:01.250Z",
  model: "gpt-5.5",
  durationMs: 24084,
  sources: [
    "https://www.hasbro.com/common/instruct/46015.pdf",
    "https://www.britannica.com/topic/Trivial-Pursuit",
    "https://www.thehenryford.org/collections/explore/artifact/303713",
  ],
} as const;
