// Round-level samples for the learned evaluation (plan "Kami", Phase 0.2 / 2).
// Not bundled. One process per seed block:
//
//   tsx .../collect-value.ts <players> <games> <seedOffset> <outPrefix>
//        [budgetMs=100] [population=tenka:0.5,shogun:0.3,heuristic-v1:0.1,aggressive:0.1] [counterfactuals=8] [plyRate=0.25]
//
// For every round end it records the board and standings BEFORE the rewards
// phase, the trick-count vector, the full tier table (what the live leaf would
// predict for each perspective), and the standings AFTER the rewards phase as
// the real engines played it (after the round-4 bonus where applicable); at
// game over the final scores, placements and winners. Variant 0 is the round
// as played; variants 1..K replay the rewards phase from the same board for
// perturbed trick vectors — the contrast a leaf has to resolve, at the cost
// of a few milliseconds each. Seats are drawn from a population of engines so
// the targets cover weak and strong continuations.
//
// It also samples trick-phase decisions (`plyRate`) for the expected-tier net
// (plan Phase 3): the FULL dealt world at that moment (every hand, since the
// collector sees everything) and, once the round's tricks are over, the
// realized trick counts — the target a value over a determinized world must
// predict, generated by seats acting under their own information.
//
// Output: `<outPrefix>.rounds.bin` and `<outPrefix>.plies.bin` (+ `.cols.json`), see sample-file.ts.

import { createRng } from "../../../lib/rng";
import { evalPosition, lightClone, NO_WEIGHTS } from "../ai-rewards";
import { tierTable, voidsOf } from "../ai-search";
import { pickAiAction } from "../ai-strategies";
import { applyAction, buildRewardQueue, createInitialState, settleTrick } from "../game-engine";
import { SQUARE_COUNT } from "../map";
import { getActivePlayer } from "../rules";
import { computeScores, cubesPerSeat } from "../scoring";
import { type AIStrategyId, CLANS, type GameState } from "../types";
import { fastFromState, N_CARDS } from "./fast-round";
import { SampleWriter } from "./sample-file";

const SEATS = 5;
const TIERS = 5;
export const STRATEGY_INDEX: readonly AIStrategyId[] = [
  "random",
  "heuristic-v1",
  "aggressive",
  "shogun",
  "tenka",
];

export const ROUND_COLUMNS = {
  columns: [
    "game",
    "round",
    "variant",
    "n",
    "emperorSeat",
    "firstPlayer",
    "hasFinal",
    `strategy[${SEATS}]`,
    `clan[${SEATS}]`,
    `square[${SQUARE_COUNT}]`,
    "supply[4]",
    `scoreBefore[${SEATS}]`,
    `cubesBefore[${SEATS}]`,
    `standingBefore[${SEATS}]`,
    `tricks[${SEATS}]`,
    `tier[${SEATS * SEATS * TIERS}]`,
    `scoreAfter[${SEATS}]`,
    `cubesAfter[${SEATS}]`,
    `standingAfter[${SEATS}]`,
    `squareAfter[${SQUARE_COUNT}]`,
    "supplyAfter[4]",
    `finalScore[${SEATS}]`,
    `finalPlacement[${SEATS}]`,
    `win[${SEATS}]`,
  ],
} as const;

export const PLY_COLUMNS = {
  columns: [
    "game",
    "round",
    "n",
    "seat",
    "leader",
    "trump",
    "firstPlayer",
    "pliesPlayed",
    "tableLen",
    "table[5]",
    `owner[${N_CARDS}]`,
    `tricksWon[${SEATS}]`,
    `handSize[${SEATS}]`,
    `voids[${SEATS}]`,
    `finalTricks[${SEATS}]`,
  ],
} as const;

const [
  playersArg = "5",
  gamesArg = "20",
  offsetArg = "0",
  outPrefix = "scratch/value/rounds",
  budgetArg = "100",
  populationArg = "tenka:0.5,shogun:0.3,heuristic-v1:0.1,aggressive:0.1",
  counterfactualsArg = "8",
  plyRateArg = "0.25",
] = process.argv.slice(2);

interface Snapshot {
  round: number;
  before: GameState;
  tricks: number[];
  tier: number[];
  standingBefore: number[];
  scoreBefore: number[];
  cubesBefore: number[];
}

function phaseOf(state: GameState): GameState["phase"] {
  return state.phase;
}

function standings(state: GameState): number[] {
  return state.players.map((_, s) => evalPosition(state, s));
}

/** Play the rewards (and bonus) phase to its end with each seat's own engine. */
function playRewards(sim: GameState, strategies: readonly AIStrategyId[], budgetMs: number): void {
  let guard = 0;
  while ((sim.phase === "rewards" || sim.phase === "bonus") && guard++ < 200) {
    const seat = getActivePlayer(sim);
    const id = strategies[seat];
    const budget = id === "tenka" && budgetMs > 0 ? { timeMs: budgetMs } : undefined;
    applyAction(sim, pickAiAction(sim, seat, id, budget));
  }
}

/** Perturbed trick vectors: move one to three tricks between seats, distinct from the actual. */
function perturbedTricks(actual: readonly number[], count: number, rng: () => number): number[][] {
  const seen = new Set<string>([actual.join(",")]);
  const out: number[][] = [];
  const n = actual.length;
  for (let attempt = 0; attempt < count * 4 && out.length < count; attempt++) {
    const v = [...actual];
    const moves = 1 + Math.floor(rng() * 3);
    for (let m = 0; m < moves; m++) {
      const donors = v.map((t, i) => (t > 0 ? i : -1)).filter((i) => i >= 0);
      if (donors.length === 0) break;
      const from = donors[Math.floor(rng() * donors.length)];
      let to = Math.floor(rng() * (n - 1));
      if (to >= from) to++;
      v[from]--;
      v[to]++;
    }
    const key = v.join(",");
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
}

function main(): void {
  const players = Number(playersArg);
  const games = Number(gamesArg);
  const offset = Number(offsetArg);
  const budgetMs = Number(budgetArg);
  const counterfactuals = Number(counterfactualsArg);
  const population = populationArg.split(",").map((part) => {
    const [id, w] = part.split(":");
    if (!STRATEGY_INDEX.includes(id as AIStrategyId)) throw new Error(`unknown strategy ${id}`);
    return { id: id as AIStrategyId, w: Number(w) };
  });
  const totalW = population.reduce((s, p) => s + p.w, 0);

  const plyRate = Number(plyRateArg);
  const writer = new SampleWriter(`${outPrefix}.rounds.bin`, "SNVR", players, ROUND_COLUMNS);
  const row = new Float32Array(rowLength(ROUND_COLUMNS.columns));
  const plies = new SampleWriter(`${outPrefix}.plies.bin`, "SNVT", players, PLY_COLUMNS);
  const plyRow = new Float32Array(rowLength(PLY_COLUMNS.columns));
  /** Ply rows of the round in progress, waiting for its final trick counts. */
  let pendingPlies: Float32Array[] = [];
  let rounds = 0;
  const t0 = performance.now();

  for (let g = 0; g < games; g++) {
    const gameIndex = offset + g;
    const seed = (Math.imul(gameIndex + 1, 0x9e3779b1) ^ 0x5e750) >>> 0;
    const rng = createRng(seed ^ 0x51a4);
    const strategies: AIStrategyId[] = [];
    for (let s = 0; s < players; s++) {
      let u = rng() * totalW;
      let pick = population[population.length - 1].id;
      for (const p of population) {
        u -= p.w;
        if (u <= 0) {
          pick = p.id;
          break;
        }
      }
      strategies.push(pick);
    }
    const state = createInitialState(players, strategies, seed, { log: false });
    const pending: Snapshot[] = [];
    let captured = 0;
    let guard = 0;
    while (state.phase !== "game-over" && guard++ < 5000) {
      if (state.phase === "trick-settle") {
        settleTrick(state);
        continue;
      }
      if (state.phase === "rewards" && captured < state.round) {
        captured = state.round;
        pending.push(snapshot(state));
        // The round's tricks are settled: label and flush its sampled plies.
        const finalTricks = state.players.map((p) => p.tricksWon);
        for (const pr of pendingPlies) {
          for (let i = 0; i < SEATS; i++)
            pr[pr.length - SEATS + i] = i < players ? finalTricks[i] : 0;
          plies.push(pr);
        }
        pendingPlies = [];
      }
      const seat = getActivePlayer(state);
      if (state.phase === "trick" && rng() < plyRate) {
        pendingPlies.push(plySample(plyRow, gameIndex, state, seat));
      }
      const id = strategies[seat];
      const budget = id === "tenka" && budgetMs > 0 ? { timeMs: budgetMs } : undefined;
      applyAction(state, pickAiAction(state, seat, id, budget));
      // The round advanced (or the game ended): close the pending snapshot.
      if (
        pending.length > 0 &&
        (state.round > pending[0].round || phaseOf(state) === "game-over")
      ) {
        const snap = pending.shift() as Snapshot;
        emit(writer, row, gameIndex, snap, state, strategies, 0);
        rounds++;
        // Counterfactual rewards phases from the same board.
        for (const [k, tricks] of perturbedTricks(snap.tricks, counterfactuals, rng).entries()) {
          const sim = lightClone(snap.before);
          sim.players.forEach((p, i) => {
            p.tricksWon = tricks[i];
          });
          sim.rewardQueue = buildRewardQueue(sim);
          sim.affected = [];
          sim.bonusQueue = [];
          sim.phase = "rewards";
          if (sim.rewardQueue.length === 0) continue;
          playRewards(sim, strategies, 0);
          emit(writer, row, gameIndex, { ...snap, tricks }, sim, strategies, k + 1);
        }
      }
    }
    if (state.phase === "game-over") trailer(writer, row, gameIndex, state);
    if ((g + 1) % 5 === 0 || g === games - 1) {
      const s = (performance.now() - t0) / 1000;
      process.stdout.write(
        `${outPrefix}: ${g + 1}/${games} games · ${rounds} rounds · ${writer.count} rows · ${s.toFixed(0)} s\n`,
      );
    }
  }
  const total = writer.close();
  const totalPlies = plies.close();
  console.log(
    `${outPrefix}.rounds.bin: ${total} rows · ${outPrefix}.plies.bin: ${totalPlies} rows · from ${games} ${players}p games`,
  );
}

function rowLength(columns: readonly string[]): number {
  let n = 0;
  for (const c of columns) {
    const m = /\[(\d+)\]$/.exec(c);
    n += m ? Number(m[1]) : 1;
  }
  return n;
}

/** One trick-phase decision with the full dealt world; the target columns are filled at round end. */
function plySample(
  row: Float32Array,
  gameIndex: number,
  state: GameState,
  seat: number,
): Float32Array {
  const n = state.players.length;
  const f = fastFromState(state, -1);
  let k = 0;
  const put = (v: number) => {
    row[k++] = v;
  };
  put(gameIndex);
  put(state.round);
  put(n);
  put(seat);
  put(state.leader);
  put(f.trump);
  put(state.firstPlayer);
  put(state.tricks.reduce((m, t) => m + t.plays.length, 0) + state.table.length);
  put(f.tableLen);
  for (let i = 0; i < 5; i++) put(i < f.tableLen ? f.table[i] : -1);
  for (let c = 0; c < N_CARDS; c++) put(f.owner[c]);
  for (let s = 0; s < SEATS; s++) put(s < n ? f.tricksWon[s] : 0);
  for (let s = 0; s < SEATS; s++) put(s < n ? f.handSize[s] : 0);
  const voids = new Uint8Array(SEATS);
  for (const v of voidsOf(state)) {
    const [vs, suit] = v.split(":");
    const idx = CLANS.indexOf(suit as (typeof CLANS)[number]);
    if (idx >= 0) voids[Number(vs)] |= 1 << idx;
  }
  for (let s = 0; s < SEATS; s++) put(voids[s]);
  for (let s = 0; s < SEATS; s++) put(0);
  if (k !== row.length) throw new Error(`ply row filled ${k} of ${row.length}`);
  return Float32Array.from(row);
}

function snapshot(state: GameState): Snapshot {
  const before = lightClone(state);
  const n = state.players.length;
  const tier: number[] = new Array(SEATS * SEATS * TIERS).fill(0);
  for (let s = 0; s < n; s++) {
    const table = tierTable(state, s, NO_WEIGHTS);
    for (let p = 0; p < n; p++) {
      for (let t = 0; t < TIERS; t++) tier[(s * SEATS + p) * TIERS + t] = table[p][t];
    }
  }
  return {
    round: state.round,
    before,
    tricks: state.players.map((p) => p.tricksWon),
    tier,
    standingBefore: standings(state),
    scoreBefore: computeScores(state),
    cubesBefore: cubesPerSeat(state),
  };
}

function emit(
  writer: SampleWriter,
  row: Float32Array,
  gameIndex: number,
  snap: Snapshot,
  after: GameState,
  strategies: readonly AIStrategyId[],
  variant: number,
): void {
  const n = snap.before.players.length;
  let k = 0;
  const put = (v: number) => {
    row[k++] = v;
  };
  const putSeats = (values: readonly number[], fill = 0) => {
    for (let s = 0; s < SEATS; s++) put(s < n ? values[s] : fill);
  };
  put(gameIndex);
  put(snap.round);
  put(variant);
  put(n);
  put(snap.before.emperorSeat ?? -1);
  put(snap.before.firstPlayer);
  put(0);
  putSeats(
    strategies.map((id) => STRATEGY_INDEX.indexOf(id)),
    -1,
  );
  putSeats(
    snap.before.players.map((p) => (p.clan === null ? -1 : CLANS.indexOf(p.clan))),
    -1,
  );
  const seatOfClan = new Map<string, number>();
  snap.before.players.forEach((p) => {
    if (p.clan !== null) seatOfClan.set(p.clan, p.index);
  });
  for (const squares of snap.before.board) {
    for (const cube of squares) put(cube === null ? -1 : (seatOfClan.get(cube) ?? -2));
  }
  for (const clan of CLANS) put(snap.before.supply[clan]);
  putSeats(snap.scoreBefore);
  putSeats(snap.cubesBefore);
  putSeats(snap.standingBefore);
  putSeats(snap.tricks);
  for (let i = 0; i < SEATS * SEATS * TIERS; i++) put(snap.tier[i]);
  putSeats(computeScores(after));
  putSeats(cubesPerSeat(after));
  putSeats(standings(after));
  for (const squares of after.board) {
    for (const cube of squares) put(cube === null ? -1 : (seatOfClan.get(cube) ?? -2));
  }
  for (const clan of CLANS) put(after.supply[clan]);
  // Final outcome columns are carried by the game's trailer row (variant −1).
  putSeats([], 0);
  putSeats([], 0);
  putSeats([], 0);
  if (k !== row.length) throw new Error(`row filled ${k} of ${row.length}`);
  writer.push(row);
}

/**
 * The final outcome is only known after the last round was already written.
 * Rather than buffering a game's rows, append one trailer row per game
 * (variant −1, hasFinal 1) that the reader joins on `game`.
 */
function trailer(
  writer: SampleWriter,
  row: Float32Array,
  gameIndex: number,
  state: GameState,
): void {
  if (!state.result) return;
  const n = state.players.length;
  row.fill(0);
  let k = 0;
  const put = (v: number) => {
    row[k++] = v;
  };
  const putSeats = (values: readonly number[], fill = 0) => {
    for (let s = 0; s < SEATS; s++) put(s < n ? values[s] : fill);
  };
  put(gameIndex);
  put(state.round);
  put(-1);
  put(n);
  put(state.emperorSeat ?? -1);
  put(state.firstPlayer);
  put(1);
  // Everything up to the final columns stays zero; only the trailer's tail matters.
  k = row.length - 3 * SEATS;
  putSeats(state.result.scores);
  putSeats(state.result.placements);
  putSeats(state.result.placements.map((p) => (p === 1 ? 1 : 0)));
  writer.push(row);
}

main();
