// Ridge regression for the board evaluator: predicts the final (own − best
// rival) score from collect-board.ts rows; writes eval-weights.ts.
//   tsx .../fit-evaluator.ts <files...> [--lambda 1e-2] [--out eval-weights.ts]
import { readFileSync, writeFileSync } from "node:fs";
import { BOARD_FEATURES } from "./board-features";

interface Row {
  n: number;
  round: number;
  y: number;
  x: number[];
}
const files: string[] = [];
let lambda = 1e-2;
let out = "src/games/senso-battle-for-japan/mcts/eval-weights.ts";
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  if (argv[i] === "--lambda") lambda = Number(argv[++i]);
  else if (argv[i] === "--out") out = argv[++i];
  else files.push(argv[i]);
}
const rows: Row[] = [];
for (const file of files)
  for (const line of readFileSync(file, "utf8").split("\n"))
    if (line) rows.push(JSON.parse(line) as Row);
const held = rows.filter((_, i) => i % 10 === 0);
const train = rows.filter((_, i) => i % 10 !== 0);
const F = BOARD_FEATURES;

function solve(set: Row[]): Float64Array {
  const a = Array.from({ length: F }, () => new Float64Array(F + 1));
  for (const r of set) {
    for (let i = 0; i < F; i++) {
      const xi = r.x[i];
      if (xi === 0) continue;
      const row = a[i];
      for (let j = 0; j < F; j++) row[j] += xi * r.x[j];
      row[F] += xi * r.y;
    }
  }
  for (let i = 0; i < F - 1; i++) a[i][i] += lambda * set.length; // no penalty on the bias (last)
  // Gaussian elimination with partial pivoting.
  for (let c = 0; c < F; c++) {
    let p = c;
    for (let r = c + 1; r < F; r++) if (Math.abs(a[r][c]) > Math.abs(a[p][c])) p = r;
    [a[c], a[p]] = [a[p], a[c]];
    const piv = a[c][c] || 1e-12;
    for (let r = 0; r < F; r++) {
      if (r === c) continue;
      const m = a[r][c] / piv;
      if (m === 0) continue;
      for (let j = c; j <= F; j++) a[r][j] -= m * a[c][j];
    }
  }
  return Float64Array.from({ length: F }, (_, i) => a[i][F] / (a[i][i] || 1e-12));
}

function report(label: string, set: Row[], w: Float64Array): void {
  let ss = 0;
  let ssGap = 0;
  let mean = 0;
  for (const r of set) mean += r.y;
  mean /= set.length;
  let tot = 0;
  for (const r of set) {
    let pred = 0;
    for (let i = 0; i < F; i++) pred += w[i] * r.x[i];
    ss += (pred - r.y) ** 2;
    ssGap += (r.x[F - 4] * 10 - r.y) ** 2; // "final gap = current gap" baseline
    tot += (r.y - mean) ** 2;
  }
  console.log(
    `${label}: n=${set.length} R²=${(1 - ss / tot).toFixed(3)} rmse=${Math.sqrt(ss / set.length).toFixed(2)} · current-gap baseline R²=${(1 - ssGap / tot).toFixed(3)} rmse=${Math.sqrt(ssGap / set.length).toFixed(2)}`,
  );
}

const w = solve(train);
console.log(`${rows.length} rows, ${F} features, λ=${lambda}`);
report("train", train, w);
report("held-out", held, w);
for (const round of [1, 3, 5, 7, 8]) {
  const sub = held.filter((r) => r.round === round);
  if (sub.length > 30) report(`held-out round ${round}`, sub, w);
}
writeFileSync(
  out,
  `// Generated by fit-evaluator.ts on ${new Date().toISOString().slice(0, 10)} from ${rows.length} positions. Do not edit by hand.
export const EVAL_WEIGHTS = Float64Array.from([
${Array.from(w, (x) => x.toFixed(5)).join(", ")},
]);
`,
);
console.log(`wrote ${out}`);
