// Which trained cell net the "vround" leaf uses per table size. A table size
// without a net falls back to the plain tier table, so a partially trained
// registry is safe to ship. Weight modules are generated by
// scripts/senso-train/train_vround.py (--out) and never edited by hand.
import type { MlpModel } from "./mlp";
import { VROUND_MODEL_5P } from "./vround-weights-5p";

export const VROUND_MODELS: { [players: number]: MlpModel } = { 5: VROUND_MODEL_5P };

export function vroundModelFor(players: number): MlpModel | null {
  return VROUND_MODELS[players] ?? null;
}
