// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug set
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time pattern-recognition card game where everyone scans a shared grid and grabs trios whose four traits all match or differ.",
  default:
    "Real-time pattern-recognition card game where everyone studies the same face-up grid, with no turns, looking for legal trios. A trio is legal when color, shape, count, and shading each either all match or all differ. When the deck and remaining matches run out, the biggest collected pile wins.",
  loose:
    "Real-time pattern-recognition card game where everyone studies the same face-up grid, with no turns, looking for legal trios. A trio is legal when color, shape, count, and shading each either all match or all differ, so two matching traits and one odd trait spoil it. Claim a trio, take those three cards, and refill the grid; when the deck and remaining matches run out, the biggest collected pile wins. The deck has every combination of the four traits exactly once, creating a silent-scan-then-sudden-grab table rhythm.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:50.928Z",
  model: "gpt-5.5",
  durationMs: 23892,
  sources: [
    "https://www.setgame.com/sites/default/files/teacherscorner/SETPROOF.pdf",
    "https://www.brettspielwelt.de/Hilfe/Anleitungen/Set/?nation=en",
    "https://officialgamerules.org/game-rules/set/",
    "https://www.geekyhobbies.com/set-card-game-review/",
  ],
} as const;
