// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug set
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A 12-card grid becomes a real-time logic race as pattern recognition rewards the first eye to spot three traits in perfect agreement or contrast.",
  default:
    "Every layout is a silent sprint, with twelve abstract cards daring the table to see order first. Pattern recognition drives the play. Correct calls claim cards, and the largest pile at the emptied deck wins.",
  loose:
    "Every layout is a silent sprint, with twelve abstract cards daring the table to see order before anyone else does. Pattern recognition drives the play as everyone searches for trios whose four traits are each all matching or all different. Correct calls claim cards, and the largest pile at the emptied deck wins. The 81-card deck grew from Marsha Falco’s genetics notes on German Shepherd data.",
};

export const meta = {
  generatedAt: "2026-05-13T16:39:44.109Z",
  model: "gpt-5.5",
  durationMs: 24510,
  sources: [
    "https://www.playmonster.com/product/set/?bvstate=pg%3A2%2Fct%3Ar&pr_current_page=1",
    "https://www.playmonster.com/set-marsha-falco/",
    "https://www.playmonster.com/wp-content/uploads/2019/10/set.pdf",
  ],
} as const;
