// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug catan
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Gateway trading strategy game where dice produce resources, players barter, and roads, settlements, and cities score points.",
  default:
    "Gateway trading strategy game about building across a hex island with resource cards. On a turn, roll two dice, collect matching terrain resources, trade with rivals or ports, then spend cards on roads, settlements, cities, or development cards. First to 10 victory points wins.",
  loose:
    "Gateway trading strategy game about building across a hex island with resource cards. On a turn, roll two dice, collect matching terrain resources, trade with rivals or ports, then spend cards on roads, settlements, cities, or development cards. First to 10 victory points wins, counting settlements, cities, bonuses, and hidden cards. A 7 moves the robber, blocks one hex, and lets the roller steal a card.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:07.336Z",
  model: "gpt-5.5",
  durationMs: 16911,
  sources: [
    "https://www.catan.com/catan",
    "https://catanboard.com/en/rules/turnOverview",
    "https://catanboard.com/en/rules/gettingStarted",
  ],
} as const;
