// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug catan
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A hex island turns every dice roll into public pressure, with trading driving roads, settlements, and grudges over sheep.",
  default:
    "A modular hex island makes scarcity visible, so every roll changes who has leverage. Trading drives roads, settlements, and cities. The first player to reach 10 victory points wins through building, cards, and bonuses.",
  loose:
    "A modular hex island makes scarcity visible, so every roll reshapes the table’s mood. Trading is the core mechanic: brick, lumber, wool, grain, and ore move between players to fund roads, settlements, and cities. The first player to reach 10 victory points wins through buildings, cards, and bonuses. The robber turns a 7 into a blockade and a theft, making one rich hex everyone’s problem.",
};

export const meta = {
  generatedAt: "2026-05-13T16:26:20.907Z",
  model: "gpt-5.5",
  durationMs: 21384,
  sources: [
    "https://www.catan.com/catan",
    "https://www.newyorker.com/business/currency/the-man-who-built-catan",
    "https://apnews.com/article/catan-cookbook-board-game-food-b14710bf57b5019f7490909684286a09",
  ],
} as const;
