// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wo-wars
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Electronic children’s sound-deduction game where players follow noises, move pawns on a grid, and try to catch a thief.",
  default:
    "Electronic children’s sound-deduction race about tracking a thief by sound. Each round, the dragon plays noises tied to board spaces, then players move their pawns toward the suspected square. Catch the thief to earn a dragon coin; first to three coins wins.",
  loose:
    "Electronic children’s sound-deduction game about following a thief across a picture grid. Each round, the dragon rock plays a trail of noises, such as animals, bells, or other board icons, and players use the clues to move their pawns toward the likely hiding place. When the round ends, the device reveals coordinates; a pawn on that square earns a dragon coin, and first to three coins wins. The big red dragon and battery-powered rock are the table centerpiece.",
};

export const meta = {
  generatedAt: "2026-05-13T20:24:23.457Z",
  model: "gpt-5.5",
  durationMs: 49797,
  sources: [
    "https://www.spielregeln.de/wo-wars.html",
    "https://www.hall9000.de/html/spiel/wo_wars",
    "https://fragames.com/en/game/wo-wars-mini/",
  ],
} as const;
