// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wo-wars
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A red plastic dragon turns a thief’s trail into bleats, bells, and birdsong in a children’s deduction race across a gridded kingdom.",
  default:
    "A red dragon reports a hidden thief’s route through animal calls, bells, and other place sounds. Deduction drives the chase as players match each noise to repeated board images. Most dragon chips after the timed rounds wins.",
  loose:
    "An electronic red dragon turns a hidden thief’s path into a trail of bleats, bells, birds, and other place sounds. Deduction drives the chase as players match each sound to repeated board images and move toward the likely final square. Most dragon chips after the timed rounds wins. Roberto Fraga said the idea came from Sneakers, where a blindfolded captive remembers a route by its sounds.",
};

export const meta = {
  generatedAt: "2026-05-13T16:43:10.830Z",
  model: "gpt-5.5",
  durationMs: 37936,
  sources: [
    "https://www.spielregeln.de/wo-wars.html",
    "https://www.hall9000.de/html/spiel/wo_wars",
    "https://www.reich-der-spiele.de/specials/fraga-wo-wars",
    "https://www.cliquenabend.de/spiele/914000-Wo-war-s.html",
  ],
} as const;
