// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug dungeon-mayhem
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light take-that card brawl where each adventurer draws, plays attacks or shields, and tries to knock everyone else out.",
  default:
    "Light take-that card brawl about fantasy adventurers blasting each other down. On a turn, draw a card, play at least one card, then attack, heal, shield, draw, or chain extra plays. The last adventurer with hit points wins.",
  loose:
    "Light take-that card brawl about fantasy adventurers blasting each other down, closer to a chaotic filler than a strategy duel. On a turn, draw one card and play at least one card for damage, healing, defense, card draw, or extra plays. Hit points start at 10; knocked-out adventurers leave, and the last one still standing wins. Each class has its own small deck, with Kyle Ferrin art and swingy powers like Fireball hitting the whole room.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:54.875Z",
  model: "gpt-5.5",
  durationMs: 20693,
  sources: [
    "https://dnd-support.wizards.com/hc/en-us/articles/360039309571-Dungeon-Mayhem",
    "https://www.ultraboardgames.com/dungeon-mayhem/game-rules.php",
    "https://www.tabletopgaming.co.uk/Reviews/dungeon-mayhem-review/",
    "https://www.strangeassembly.com/2019/review-dungeon-mayhem",
  ],
} as const;
