// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug dungeon-mayhem
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A dungeon party settles loot disputes with slapstick spells and axes in a brisk hand-management brawl.",
  default:
    "A dungeon party turns treasure sharing into a cartoon fight of shields, spells, and sudden healing. Hand management drives each turn through quick draws and icon-heavy attacks. The last adventurer with hit points wins.",
  loose:
    "A dungeon party turns treasure sharing into a cartoon knife fight of shields, spells, and sudden healing. Hand management drives each turn, with a card played after a draw and icons handling damage, shields, extra plays, and healing. The survivor who keeps any hit points after the other adventurers drop to zero wins. Each class has its own deck, so Sutha hits hard while Azzan banks tricks that can swing a table in one turn.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:33.569Z",
  model: "gpt-5.5",
  durationMs: 19295,
  sources: [
    "https://wpn.wizards.com/en/products/dungeon-mayhem",
    "https://droplowest.com/2018/11/15/review-dungeon-mayhem/",
  ],
} as const;
