// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug bristol-1350
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Chaotic social-deduction race where players reroll cart dice, swap seats, and shove suspected plague carriers off apple carts.",
  default:
    "Chaotic social-deduction race about escaping town in apple carts before plague spreads. Each round, players reroll cart dice, draw Remedy cards, move between carts, or push suspected infected riders backward. The first cart to cross with only healthy riders wins together; a cart with any plague carrier dies and play continues.",
  loose:
    "Chaotic social-deduction race about escaping town in apple carts while hidden Symptom cards may mark riders as infected. Each round, players reroll shared dice, draw Remedy cards, elbow forward, dash to another cart, or push suspected plague carriers backward. Rat results trigger Mingles, where cartmates shuffle Symptom cards and may secretly catch the plague. The first cart to cross with only healthy riders wins together; infected carts die and play continues.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:52.415Z",
  model: "gpt-5.5",
  durationMs: 18225,
  sources: [
    "https://facadegames.com/products/bristol-1350",
    "https://fgbradleys.com/wp-content/uploads/Bristol-1350-Rulebook.pdf",
    "https://tabletopping.games/2021/09/10/bristol-1350/",
    "https://therewillbe.games/articles-boardgame-reviews/8497-bristol-1350-bring-out-your-dead",
  ],
} as const;
