// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug bristol-1350
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Rival apple carts flee plague-struck Bristol with social deduction, as shared dice make rats, apples, and suspicion move together.",
  default:
    "Plague escape becomes a trust problem, because every apple-cart passenger may be hiding a fatal cough. The core mechanic is social deduction. Healthy riders win by leaving town in the first clean cart; infected riders try to ruin every escape.",
  loose:
    "Plague escape becomes a trust problem, because every apple-cart passenger may be hiding a fatal cough. The core mechanic is social deduction: players change seats, tweak shared dice, and keep symptom cards secret. A healthy group wins by riding the first clean cart out; infected players try to spoil every escape. Travis Hancock said it began as Roman chariot racing, then clicked when people shared carts.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:30.686Z",
  model: "gpt-5.5",
  durationMs: 20575,
  sources: [
    "https://facadegames.com/products/bristol-1350",
    "https://boardgamegeek.com/boardgame/308989/bristol-1350",
    "https://www.reddit.com/r/boardgames/comments/1cru5he/im_travis_hancock_founder_of_facade_games_and/",
    "https://fgbradleys.com/wp-content/uploads/Bristol-1350-Rulebook.pdf",
  ],
} as const;
