// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug connect-4
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Abstract connection game where rivals drop colored discs into columns, blocking threats while trying to line up four.",
  default:
    "Abstract connection game played on a vertical grid, with each side trying to build a line of matching discs. On a turn, a player chooses an open column and drops one disc; gravity slides it to the lowest empty slot. The first side with four discs in a horizontal, vertical, or diagonal row wins.",
  loose:
    "Abstract connection game played on a vertical grid, with each side trying to build a line of matching discs. On a turn, a player chooses an open column and drops one disc; gravity slides it to the lowest empty slot, often creating blocks or stacked threats. The first side with four discs in a horizontal, vertical, or diagonal row wins; a full grid with no four is a draw. The release bar at the bottom dumps every disc out for an instant reset.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:42.411Z",
  model: "gpt-5.5",
  durationMs: 15426,
  sources: [
    "https://instructions.hasbro.com/en-gb/instruction/the-classic-game-of-connect-4",
    "https://playabstractgames.com/en/connect-four/rules/",
  ],
} as const;
