// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug chess
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Perfect information turns every tempo into pressure through grid movement across sixty-four squares.",
  default:
    "Perfect information makes each pawn push a public wager, with no dice or hidden cards to blame. The core mechanic is grid movement across an eight-by-eight board. Victory comes by checkmate, not by taking the king.",
  loose:
    "Perfect information makes each pawn push a public wager, with no dice or hidden cards to blame. The core mechanic is grid movement: pieces follow distinct lines, leaps, or steps across an eight-by-eight board. Victory comes by checkmate, while stalemate and dead positions can turn domination into a draw. After 1475, the queen’s expanded range helped give modern chess its sharper attacking shape.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:51.103Z",
  model: "gpt-5.5",
  durationMs: 24612,
  sources: [
    "https://handbook.fide.com/chapter/E012023",
    "https://www.britannica.com/topic/chess",
    "https://www.britannica.com/topic/queen-chess",
  ],
} as const;
