// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug carcassonne
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Tile-laying game where players grow a shared medieval map, claiming its cities, roads, cloisters, and fields with meeples to score them as they finish.",
  default:
    "Tile-laying game where players grow a shared map and claim its features with meeples. On a turn, draw a land tile, fit it so roads and cities line up, then optionally stand a meeple on it. Cities, roads, and cloisters score when done, fields at the end, and the highest total wins.",
  loose:
    "Tile-laying game where players grow a shared medieval map and claim its features with meeples. On a turn, draw a land tile, fit it so roads meet roads and cities meet cities, then optionally stand a meeple on it as a knight, thief, monk, or farmer. Finished cities, roads, and cloisters score at once and free their meeples, fields score only at the end, and the highest total wins. The little wooden follower in this box gave the hobby the word meeple.",
};

export const meta = {
  generatedAt: "2026-09-14T12:36:16.000Z",
  model: "claude-opus-5 (simulated run — gateway throttled)",
  durationMs: 201000,
  sources: [
    "https://www.zmangames.com/game/carcassonne/",
    "https://www.ultraboardgames.com/carcassonne/game-rules.php",
    "https://www.meeplemountain.com/reviews/carcassonne/",
    "https://en.wikipedia.org/wiki/Carcassonne_(board_game)",
  ],
} as const;
