// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug phase-10
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Contract-rummy card game where players draw and discard to finish numbered meld phases before rivals move ahead.",
  default:
    "Contract-rummy card game about climbing through ten required melds. On a turn, draw from the deck or discard pile, lay the current phase when complete, hit extra cards onto face-up phases, then discard. First to complete Phase 10 wins, with low penalty points breaking ties.",
  loose:
    "Contract-rummy card game about climbing through ten required melds: sets, runs, and one-color hands. On a turn, draw from the deck or discard pile, lay the current phase only when complete, hit extra cards onto face-up phases, then discard. After each hand, finishers advance, unmade phases repeat, and the first to complete Phase 10 wins, with low penalty points breaking ties. Wild cards plug holes in runs or colors, while Skip cards steal a turn.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:05.141Z",
  model: "gpt-5.5",
  durationMs: 34136,
  sources: [
    "https://www.phase10games.com/wp-content/uploads/2017/01/PHASE-10-Card-Game-Instructions.pdf",
    "https://retrochronicle.com/card-game-review-phase-10-1982-mattel/",
  ],
} as const;
