// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug phase-10
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Ten escalating rummy contracts turn set collection into a traffic jam of almost-finished hands, wild rescues, and spiteful skips.",
  default:
    "One missed contract can strand a hand while the table advances to harder rummy chores. Set collection drives each round: draw, discard, lay down required sets, runs, or one-color groups, then shed leftovers. Complete phase ten first, with low penalty points breaking ties.",
  loose:
    "One missed contract can strand a hand while the table advances to harder rummy chores. Set collection drives each round: draw, discard, lay down required sets, runs, or one-color groups, then shed leftovers onto open phases. The first player to complete phase ten wins, with low penalty points breaking ties. The 108-card deck includes eight Wilds and four Skips, enough for rescues and petty delays.",
};

export const meta = {
  generatedAt: "2026-05-13T16:38:37.872Z",
  model: "gpt-5.5",
  durationMs: 65023,
  sources: [
    "https://service.mattel.com/instruction_sheets/W4729-Eng.pdf",
    "https://www.phase10games.com/wp-content/uploads/2017/01/PHASE-10-Card-Game-Instructions.pdf",
    "https://shop.mattel.com/products/phase-10-card-game-w4729?bvstate=pg%3A2%2Fct%3Ar&currency=USD&variant=41330749702309",
    "https://www.museumofplay.org/press-release/2024-toy-hall-inductees-revealed/",
  ],
} as const;
