// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug captain-sonar
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time team hidden-movement submarine duel where crews shout courses, trace enemy routes, charge systems, and fire weapons.",
  default:
    "Real-time team hidden-movement game about rival submarine crews hunting each other behind screens. Captains call compass moves while crewmates trace the enemy path, ready sonar, torpedoes, and mines, and manage breakdowns. The first crew to deal four damage sinks the enemy and wins.",
  loose:
    "Real-time team hidden-movement game about rival submarine crews hunting each other behind screens. Captains call north, south, east, or west while crewmates trace the enemy path, ready sonar, torpedoes, and mines, and mark system breakdowns. The first crew to deal four damage sinks the enemy and wins. Dry-erase role sheets and a transparent radio-operator overlay make the table feel like two command rooms yelling over a sonar screen.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:58.913Z",
  model: "gpt-5.5",
  durationMs: 23976,
  sources: [
    "https://www.matagot.com/en/strategy-games/133-captain-sonar.html",
    "https://fgbradleys.com/wp-content/uploads/rules/Captain%20Sonar%20-%20rules.pdf?srsltid=AfmBOorXW2sKViCJuskEhZYIhWkE6r8lKmO9Z6kn8f_Y3f1D4ibd3WZZ",
    "https://www.play-board-games.com/captain-sonar-review/",
  ],
} as const;
