// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug captain-sonar
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Rival submarine crews turn a quiet grid into panic, with real-time orders, repairs, and tracking racing across both sides of the table.",
  default:
    "A quiet grid becomes a shouting match as two crews hunt each other through unseen water. The core mechanic is real-time play. Crews win by finding the rival sub and landing enough hits before their own hull fails.",
  loose:
    "A quiet grid becomes a shouting match as two crews hunt each other through unseen water. The core mechanic is real-time play: captains call headings while teammates charge weapons, mark damage, and track the rival course. Victory goes to the crew that finds the enemy sub and sinks it first. Radio operators write on transparent sheets, turning shouted compass points into a shrinking suspect area.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:46.038Z",
  model: "gpt-5.5",
  durationMs: 29946,
  sources: [
    "https://www.matagot.com/fr/strategy-games/133-captain-sonar.html",
    "https://www.northstreetgames.com/images/Rulebooks/Captain-Sonar-Rules-v5.pdf",
    "https://store.asmodee.com/products/captain-sonar",
    "https://boardgamegeek.com/wiki/page/thing%3A171131",
  ],
} as const;
