// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug sidereal-confluence
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time sci-fi trading game where asymmetric alien races haggle over colored cubes and ships to feed their resource converter cards.",
  default:
    "Open-table negotiation game about asymmetric alien economies. Each round everyone trades cubes, ships and colonies at once, runs converter cards that swap inputs for richer goods, then bids on new planets. Most points after six rounds wins.",
  loose:
    "Open-table negotiation game about asymmetric alien economies whose converter cards never produce what they need. Each round all players trade cubes, ships, colonies and promises at once, then simultaneously run converters that swap inputs for richer goods. In the Confluence, researched technologies are shared with everyone for points and players bid on new planets and research teams. Every promise is binding, and the most points after six rounds wins.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.332Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 150000,
  sources: [
    "https://www.tabletopgaming.co.uk/reviews/sidereal-confluence-remastered-edition-review/",
    "https://www.meeplemountain.com/reviews/sidereal-confluence/",
  ],
} as const;
