// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug vantage
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight: "Co-op open-world adventure where players pick one action, spend skill tokens, roll challenge dice, and park results on a 3x3 card grid to avoid penalties.",
  default: "Co-op open-world adventure where separated explorers roam different locations and share intel aloud. Each turn, a player chooses one action, reads its storybook entry, and spends matching skill tokens to cut cost.",
  loose: "Co-op open-world adventure where separated explorers roam different locations and share intel aloud. Each turn, a player chooses one action, reads its storybook entry, and spends matching skill tokens to cut cost. They roll challenge dice for the rest, cover results with matching slots on a 3x3 card grid, and lose time/morale/health for leftovers. The group wins by completing the mission, a found destiny, or both before any tracker hits 0; each location card stays hidden in a holder.",
};

export const meta = {
  generatedAt: "2026-09-03T02:30:39.974Z",
  model: "openai/gpt-5.2",
  durationMs: 78300,
  sources: [
    "https://gamers-hq.de/media/pdf/dd/2a/dc/Vantage_Rulebook_r26_web_Compressed.pdf",
    "https://store.stonemaiergames.com/products/vantage",
    "https://geekdad.com/2025/11/vantage-explore-an-alien-planet/",
    "https://www.wargamer.com/vantage/board-game-review",
    "https://www.avclub.com/the-board-game-vantage-is-too-big-for-its-own-good",
    "https://meepleandthemoose.com/2026/04/29/vantage-board-game-review/",
    "https://www.player2.net.au/2026/06/vantage-review-its-just-a-box-of-cards/"
  ],
} as const;
