// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug spirit-island
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Heavy cooperative area-defense puzzle: choose Growth, spend energy on power cards, and stop invaders from Ravage/Build/Explore.",
  default:
    "Heavy cooperative area-defense puzzle where spirits with unique decks defend an island from invaders. Each round, choose Growth to add Presence and gain energy, then play Fast and Slow power cards around the invaders’ Ravage/Build/Explore. Earn Fear to raise Terror Level and win by clearing invaders, then towns+cities, then only cities.",
  loose:
    "Heavy cooperative area-defense puzzle where spirits with unique decks defend an island from invaders. Each round, choose Growth to add Presence and gain energy, then play Fast and Slow power cards, with Fast before Ravage/Build/Explore and Slow after. Earn Fear to raise Terror Level; win by clearing invaders, then towns+cities, then only cities. Lose if Blight runs out, the Invader deck empties on Explore, or any spirit has no Presence left.",
};

export const meta = {
  generatedAt: "2026-09-03T02:56:55.043Z",
  model: "openai/gpt-5.2",
  durationMs: 121249,
  sources: [
    "https://shop.greaterthangames.com/products/spirit-island",
    "https://www.rulespal.com/spirit-island/rulebook",
    "https://desktopgames.com.ua/games/5683/SpiritIsland_RulesReference_v1.2.pdf",
    "https://www.boardgamequest.com/spirit-island-review/",
    "https://discussion.tekeli.li/t/su-sd-review-spirit-island/4252",
  ],
} as const;
