// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug codenames-duet
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative word-clue game where partners trade one-word clues and numbers to find agents on a shared grid.",
  default:
    "Cooperative word game about reading a partner’s associations on a grid of word cards. Each turn, one side gives a one-word clue plus a number, and the other points to matching words while dodging bystanders and assassins. Find all agents before the timer tokens run out to win.",
  loose:
    "Cooperative word game about reading a partner’s associations on a 5×5 grid of word cards. Each turn, one side gives a one-word clue plus a number, and the other points to matching words while avoiding bystanders and assassins. Find all 15 agents before the timer tokens run out to win; hit an assassin and the mission fails. The mission map adds preset challenges that reward safer clues or bigger multi-word leaps.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:26.984Z",
  model: "gpt-5.5",
  durationMs: 13602,
  sources: [
    "https://www.codenamesgame.com/boardgames/codenames-duet",
    "https://www.tabletopgaming.co.uk/reviews/codenames-duet-review/",
  ],
} as const;
