// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug codenames-duet
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A shared key turns every familiar word into a risk, driven by cooperative word association across a 5-by-5 grid.",
  default:
    "A double-sided key makes each clue feel risky, since neither partner sees the whole map. Cooperative word association drives the game. The team wins by finding all 15 agents before the timer runs out, but one assassin ends everything.",
  loose:
    "Double-sided key cards make the table feel unstable, since a safe clue on one side can point toward danger on the other. Cooperative word association drives play: partners alternate one-word clues and numbered guesses across a 5-by-5 grid. The team wins by finding all 15 agents before timer tokens run out, and loses immediately to an assassin. One visible assassin may be an agent for the partner.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:00.159Z",
  model: "gpt-5.5",
  durationMs: 21216,
  sources: [
    "https://www.czechgames.com/games/codenames-duet",
    "https://filemanager.czechgames.com/storage/files/codenames-duet/rules/codenames-duet-rules-en.pdf",
    "https://www.thegamingreview.com/10732/2017/09/20/board-game-review-codenames-duet/",
  ],
} as const;
