// GENERATED by scripts/gen-cpp-hunger.ts — DO NOT EDIT. Run `pnpm gen-cpp-hunger`.
#pragma once

namespace hg {

constexpr int MAX_PLAYERS = 6;
constexpr int NUM_DEFS = 121;
constexpr int NUM_CARDS = 161;
constexpr int NUM_HUNT = 122;
constexpr int NUM_ROOKIE_A = 26;
constexpr int NUM_ROOKIE_REST = 96;
constexpr int NUM_ROSES = 3;
constexpr int NUM_STARTING = 6;
constexpr int NUM_FAMILIES = 2;
constexpr int FAM_ROSE = 0;
constexpr int NUM_MISSIONS = 50;
constexpr int NUM_BONUS = 26;
constexpr int MAX_SPACES = 62;
constexpr int MAX_CHESTS = 11;
constexpr int MAX_CRYPTS = 6;

}  // namespace hg
