// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug my-first-uno
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/web/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Children’s hand-shedding card game where each turn drops a matching color, number, or character, or draws a card.",
  default:
    "Children’s hand-shedding card game, a simplified UNO with character matching. On a turn, play one card matching the discard pile’s color, number, or character, use a Wild to call a new color, or draw one card. First player to empty their hand wins.",
  loose:
    "Children’s hand-shedding card game, a simplified UNO with bright character cards and very little planning overhead. Each turn, play one card onto the discard pile by matching its color, number, or character, play a Wild to call a new color, or draw one card and play it if it fits. A Draw 2 makes the next player take two cards and skip, and the first player to empty their hand wins. The little shout matters: a player who forgets to call “UNO” on the next-to-last card draws two if caught.",
};

export const meta = {
  generatedAt: "2026-05-23T15:05:54.190Z",
  model: "gpt-5.5",
  durationMs: 15545,
  sources: [
    "https://service.mattel.com/instruction_sheets/K5847.pdf",
    "https://www.ultraboardgames.com/uno/my-first-uno.php",
    "https://boardgamewikia.com/my-first-uno/",
  ],
} as const;
