// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug forbidden-island
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative survival board game where adventurers spend actions moving, shoring flooded tiles, trading cards, and claiming treasures.",
  default:
    "Light cooperative survival game about looting four treasures from a modular island that sinks tile by tile. On a turn, an adventurer moves, shores up flooded tiles, gives cards, or claims a treasure, then draws treasure and flood cards. The team wins by claiming all treasures, gathering at Fool’s Landing, and escaping by helicopter.",
  loose:
    "Light cooperative survival game about looting four treasures from a modular island that sinks tile by tile. On a turn, an adventurer takes up to three actions to move, shore up flooded tiles, give cards, or claim a treasure, then draws treasure and flood cards. The team wins by claiming every treasure, gathering at Fool’s Landing, and escaping by helicopter. Chunky treasure figures and the rising water meter make the table feel like a shared fire drill.",
};

export const meta = {
  generatedAt: "2026-08-17T00:31:40.174Z",
  model: "gpt-5.5",
  durationMs: 16066,
  sources: [
    "https://gamewright.com/product/Forbidden-Island",
    "https://www.whistlerlibrary.ca/cover-images/forbiddenislandrules.pdf",
    "https://www.kidsplayboardgames.com/games/forbidden-island-review/",
  ],
} as const;
