// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-hunger
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Vampire deck-building race where players spend card speed to cross the night map, hunt human cards for points, and reach the castle before dawn.",
  default:
    "Vampire deck-building race where hunted humans score points but slow the deck. On a turn, play three cards, total their speed, move along the map, then hunt a pile off the hunt track. At dawn, vampires short of the castle burn to ashes and the survivor with the most points wins.",
  loose:
    "Vampire deck-building race where hunted humans score points but clog the deck with zero-speed cards. On a turn, play three cards, total their speed, move along the map, then hunt a pile off the hunt track or pluck a rose in the labyrinth. At dawn, vampires short of the castle burn to ashes and the survivor with the most points wins. Unhunted cards slide down the track each round into one-speed piles, a cheap feast landing when the deck can least afford it.",
};

export const meta = {
  generatedAt: "2026-09-14T12:36:25.000Z",
  model: "claude-opus-5 (simulated run — gateway throttled)",
  durationMs: 251000,
  sources: [
    "https://renegadegamestudios.com/content/File%20Storage%20for%20site/Rulebooks/The%20Hunger/The%20Hunger-Rules-US_v3.pdf",
    "https://eu.renegadegamestudios.com/the-hunger/",
    "https://renegadegamestudios.com/blog/announcing-the-hunger-a-new-game-by-richard-garfield/",
    "https://www.meeplemountain.com/reviews/the-hunger/",
    "https://opinionatedgamers.com/2022/01/07/dale-yu-review-of-the-hunger/",
    "https://gamingtrend.com/feature/reviews/the-hunger-review-deckbuilding-with-a-twist/",
  ],
} as const;
