// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug ark-nova
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Heavy euro zoo-builder where sliding action cards drive drawing animals, placing enclosures, playing sponsors, and funding conservation.",
  default:
    "Heavy euro zoo-building game about balancing visitor appeal with conservation work. Each turn, choose one of five sliding action cards to draw cards, build enclosures, add animals, play sponsors, or send association workers. When appeal and conservation markers cross, finish the round; highest final score wins.",
  loose:
    "Heavy euro zoo-building game about growing visitor appeal while funding conservation projects. Each turn, choose one of five sliding action cards to draw zoo cards, place enclosure tiles, add animals, play sponsors, or send association workers. When appeal and conservation markers cross, everyone gets a final turn; highest final score after end-game cards wins. The table feel is mostly heads-down planning, with a huge animal-and-sponsor deck and some fights over the shared card row.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:28.797Z",
  model: "gpt-5.5",
  durationMs: 28456,
  sources: [
    "https://www.feuerland-spiele.de/spiele/arche-nova/",
    "https://www.wargamer.com/ark-nova/review",
    "https://en.doc.boardgamearena.com/Gamehelparknova",
    "https://frontlinegaming.org/2025/09/17/board-game-review-ark-nova/",
  ],
} as const;
