// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug ark-nova
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A modern zoo becomes a timing puzzle where every enclosure, animal, and sponsor waits for the right action-selection slot.",
  default:
    "A zoo plan becomes a pressure map of habitats, money, icons, and species that rarely arrive in the ideal order. Action selection drives the game through five cards that gain strength as they shift. Victory comes from making appeal and conservation tracks cross.",
  loose:
    "A zoo plan turns into a pressure map of habitats, money, icons, and species that never arrive in the ideal order. Action selection drives the game, with five cards growing stronger as they drift across the bottom of the player board. The scoring tracks run toward each other: appeal funds growth while conservation closes the race. A cheap animal now can cost the chance to build a stronger enclosure later.",
};

export const meta = {
  generatedAt: "2026-05-13T16:32:50.899Z",
  model: "gpt-5.5",
  durationMs: 37430,
  sources: [
    "https://capstone-games.com/board-games/ark-nova/",
    "https://www.feuerland-spiele.de/spiele/arche-nova/",
    "https://thinkygames.com/features/an-interview-with-ark-nova-designer-mathias-wigge/",
    "https://gamesnightguru.com/game/ark-nova/",
    "https://boardgamegeek.com/boardgame/342942/ark-nova",
  ],
} as const;
