// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug rummy
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A visible discard pile turns every throwaway into bait in a hand-management game of runs, sets, and nervous timing.",
  default:
    "Every discard gives away a clue, and useful cards can become traps. Hand management drives the play: draw, meld runs and sets, lay off matching cards, then discard. A hand ends when one player empties their hand, leaving opponents' deadwood to score.",
  loose:
    "Every discard advertises too much, turning a simple card table into a watchful trap. Hand management drives the play: draw, meld runs and sets, lay off matching cards, then discard. A hand ends when one player empties their hand, and opponents' deadwood becomes the score across deals. In 500 Rummy, a buried discard can be claimed, but every card above it comes along too.",
};

export const meta = {
  generatedAt: "2026-05-13T16:39:19.599Z",
  model: "gpt-5.5",
  durationMs: 66142,
  sources: [
    "https://www.britannica.com/topic/rummy",
    "https://www.pagat.com/rummy/",
    "https://www.pagat.com/rummy/rummy.html",
    "https://www.pagat.com/rummy/500rum.html",
  ],
} as const;
