// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug rummy
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Classic meld-scoring card game where players draw from stock or visible discards, lay sets and suited runs, then discard.",
  default:
    "Classic meld-scoring card game about emptying a hand while banking points in sets and suited runs. On a turn, a player draws from the stock or visible discard pile, lays melds or adds cards to existing melds, then discards. Each hand scores played cards minus cards left in hand, and the highest score after someone reaches 500 wins.",
  loose:
    "Classic meld-scoring card game about emptying a hand while banking points in sets and suited runs. On a turn, a player draws from the stock or takes a useful card from the visible discard pile, lays new melds or adds cards to existing melds, then discards. Each hand scores played cards minus cards left in hand, and the highest score after someone reaches 500 wins. The fanned discard pile is the hook: taking a buried card also drags every card above it into hand.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:12.718Z",
  model: "gpt-5.5",
  durationMs: 16348,
  sources: [
    "https://www.pagat.com/rummy/500rum.html",
    "https://www.rummy500.com/rules",
    "https://rummyrulebook.com/pages/rummy-500/",
  ],
} as const;
