// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug pandemic
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative crisis-management game where the team spends actions flying between cities, clearing disease cubes, and building cure sets.",
  default:
    "Cooperative crisis-management game about stopping four diseases on a world map. Each turn, a specialist takes four actions to move, treat cubes, trade city cards, or build research stations. Discover all four cures to win before outbreaks, empty decks, or cube shortages end the game.",
  loose:
    "Cooperative crisis-management game about stopping four diseases on a world map before the decks and outbreak track crush the team. Each turn, a specialist spends four actions to move between city nodes, remove cubes, trade city cards, or build a research station. Then cards spread new cubes, and epidemic cards recycle infected cities back onto the top of the infection deck. Discover all four cures to win; lose to too many outbreaks, an empty player deck, or a cube supply running out.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:46.537Z",
  model: "gpt-5.5",
  durationMs: 22835,
  sources: [
    "https://www.zmangames.com/game/pandemic/",
    "https://cdn.svc.asmodee.net/production-zman/uploads/2024/09/Pandemic_Rulebook.pdf",
    "https://www.wargamer.com/pandemic/review",
  ],
} as const;
