// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug pandemic
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Old hotspots return when Epidemic cards recycle the infection deck, turning hand management into urgent triage.",
  default:
    "Old hotspots keep coming back, so yesterday’s cleanup can become tomorrow’s outbreak. Hand management drives the race, as city cards fuel travel, research, and cures. The team wins by curing all four diseases before the deck, cubes, or outbreak track collapse.",
  loose:
    "Old hotspots keep coming back, so yesterday’s cleanup can become tomorrow’s outbreak. Hand management drives the race, as city cards fuel travel, research, and cures. The team wins by curing all four diseases before outbreaks, cube shortages, or an empty deck ends the game. Each Epidemic infects from the bottom, then stacks the shuffled discard pile on top.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:54.246Z",
  model: "gpt-5.5",
  durationMs: 39501,
  sources: [
    "https://www.zmangames.com/game/pandemic/",
    "https://cdn.svc.asmodee.net/production-zman/uploads/2024/09/Pandemic_Rulebook.pdf",
    "https://www.thinkglobalhealth.org/article/pandemic-game-gone-viral",
  ],
} as const;
