// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug one-night-ultimate-werewolf
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Fast social-deduction party game of secret roles, night powers, accusations, and one final vote to kill a werewolf.",
  default:
    "Social-deduction party game where villagers hunt hidden werewolves after one secret night. Each round, role cards peek, swap, or lie while the table argues over broken alibis. The village wins by voting out a werewolf; werewolves win if they survive.",
  loose:
    "Social-deduction party game where villagers hunt hidden werewolves after one secret night. Each round, everyone gets a role card, closes their eyes while the app calls roles to peek, swap, or learn cards, then argues over whose story no longer fits. The village wins if the final vote kills a werewolf; the werewolves win if no werewolf is killed. The phone narration runs the night phase, so no moderator sits out.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:35.441Z",
  model: "gpt-5.5",
  durationMs: 18307,
  sources: [
    "https://beziergames.com/collections/hot-items/products/one-night-ultimate-werewolf",
    "https://www.ultraboardgames.com/one-night-ultimate-werewolf/game-rules.php",
    "https://www.wargamer.com/one-night-ultimate-werewolf/review",
  ],
} as const;
