// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug one-night-ultimate-werewolf
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A single night turns hidden roles into shaky alibis, with social deduction driven by swapped cards and sudden accusations.",
  default:
    "Every accusation rests on a role card that may have changed during the night. Social deduction drives the table through claims, bluffs, and peeks. A final vote must expose at least one werewolf, unless another role has warped the target.",
  loose:
    "Every accusation rests on a role card that may have changed during the night. Social deduction drives the table as the Seer peeks, the Robber steals, and the Troublemaker swaps cards. A final vote kills one suspect; the village wins by hitting a werewolf, while roles like the Tanner may want a different outcome. Thick role tiles make midnight card swaps easier to grab without bending paper.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:57.546Z",
  model: "gpt-5.5",
  durationMs: 48552,
  sources: [
    "https://beziergames.com/collections/hot-items/products/one-night-ultimate-werewolf",
    "https://cdn.shopify.com/s/files/1/0740/4855/files/ONUW_rules-updated_for_BGG.pdf?337=",
    "https://www.theboardgamefamily.com/2014/05/one-night-ultimate-werewolf-game-review/",
    "https://www.theologyofgames.com/blog/2014/03/19/one-night-ultimate-werewolf-a-double-take-review",
  ],
} as const;
