// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug secret-hitler
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Hidden-role social deduction game where elected presidents and chancellors pass policies while everyone argues who lied.",
  default:
    "Hidden-role social deduction party game where liberals hunt fascists and Hitler. A president names a chancellor, all vote Ja or Nein, and the pair filters three policy cards down to one law. Liberals win with five liberal laws or dead Hitler; fascists win with six fascist laws or Hitler as late chancellor.",
  loose:
    "Hidden-role social deduction party game where liberals try to identify fascists and keep Hitler out of power. Each round, a president nominates a chancellor, the table votes Ja or Nein, and an approved pair secretly discards policy cards before one law hits the board. Liberals win by passing five liberal laws or executing Hitler; fascists win by passing six fascist laws or electing Hitler chancellor after three fascist laws. The memorable prop is the Ja/Nein vote, followed by loud claims about who threw away which policy.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:02.468Z",
  model: "gpt-5.5",
  durationMs: 49750,
  sources: [
    "https://www.secrethitler.com/assets/Secret_Hitler_Rules.pdf",
    "https://secrethitler.io/rules",
  ],
} as const;
