// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug secret-hitler
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A rigged parliament turns every vote into an accusation in this social deduction game of elections, policy tiles, and concealed loyalties.",
  default:
    "A rigged parliament turns every vote into evidence as hidden fascists exploit a liberal majority. Social deduction drives elections, policy choices, and arguments over who lied. Liberals win by passing five liberal policies or killing Hitler; fascists can win by electing him chancellor after the law",
  loose:
    "A rigged parliament turns every vote into evidence as hidden fascists exploit a liberal majority. Social deduction drives elections, policy choices, and arguments over who lied. Liberals win by passing five liberal policies or killing Hitler; fascists win with six fascist policies or by electing Hitler chancellor after the third. Separate role and party cards let investigations reveal allegiance without exposing Hitler.",
};

export const meta = {
  generatedAt: "2026-05-13T16:39:49.377Z",
  model: "gpt-5.5",
  durationMs: 50115,
  sources: [
    "https://www.secrethitler.com/?ICID=ref_fark",
    "https://www.secrethitler.com/assets/Secret_Hitler_Rules.pdf",
  ],
} as const;
