// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-crew-mission-deep-sea
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Silent trick-taking turns every won card into shared risk, as submarine trumps and shifting task cards squeeze the table.",
  default:
    "A quiet hand of cards becomes a pressure gauge, with every trick either solving the mission or wrecking it. The core mechanic is trick-taking, with submarine trumps and one-card sonar clues. The crew wins by completing all assigned tasks before any task becomes impossible.",
  loose:
    "A quiet hand of cards becomes a pressure gauge, with every trick either solving the mission or wrecking it. The core mechanic is trick-taking, with submarine trumps and one-card sonar clues. The crew wins by completing all assigned tasks before any task becomes impossible. The 96-card task deck can ask for odd-only tricks, exact color counts, or a final-trick 2, so the same mission number rarely feels identical.",
};

export const meta = {
  generatedAt: "2026-05-13T16:41:24.353Z",
  model: "gpt-5.5",
  durationMs: 31857,
  sources: [
    "https://www.thamesandkosmos.com/manuals/full/691869_Crew_Deep%20Sea_Manual.pdf",
    "https://boardgamegeek.com/boardgame/324856/the-crew-mission-deep-sea",
    "https://geekdad.com/2021/11/return-to-cooperative-trick-taking-with-the-crew-mission-deep-sea/",
  ],
} as const;
