// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug medical-mysteries-nyc
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative medical deduction game where the table reads patient files, orders tests, checks codes, and chooses treatment.",
  default:
    "Cooperative medical deduction game about solving an ER case from patient records. The team asks questions, orders tests, consults specialists, tracks time, and checks result codes. Win by diagnosing the condition and treating it before the patient dies.",
  loose:
    "Cooperative medical deduction game about an overnight ER case, closer to a case-file mystery than a party game. The team reads the intake interview and records, then spends time to ask questions, order tests, consult specialists, and look up result codes. Win by diagnosing the condition and giving the right treatment before morning; fatal delay or bad care loses. The box is built from patient envelopes, research sheets, story cards, status cards, and a Nurse Judy tutorial.",
};

export const meta = {
  generatedAt: "2026-08-14T22:19:50.658Z",
  model: "gpt-5.5",
  durationMs: 16049,
  sources: [
    "https://medicalmysteriesgame.com/us/editions/",
    "https://coopgestalt.com/2024/03/14/play-an-episode-of-house-a-review-of-nyc-emergency-room-a-medical-mystery/",
    "https://tbgd.blog/2024/11/06/case-file-medical-mysteries-new-york-emergency-room/",
    "https://etspeaksfromhome.co.uk/2024/06/medical-mysteries-board-game-review.html",
  ],
} as const;
