// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug schafkopf
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A called Ace can hide an ally across the table in a Bavarian trick-taking game of Obers, Unters, and costly solos.",
  default:
    "A called Ace can turn a quiet opponent into a secret ally across the table. The core mechanic is trick-taking. The declarer’s side needs 61 of the deck’s 120 card points, unless a soloist rejects help and faces all three defenders.",
  loose:
    "A called Ace can turn a quiet opponent into a secret ally across the table. The core mechanic is trick-taking. The declarer’s side needs 61 of the deck’s 120 card points, unless a soloist rejects help and faces all three defenders. A 32-card Bavarian or Franconian pack gives the game its texture, with Acorns, Leaves, Hearts, Bells, and the high-ranking Obers and Unters.",
};

export const meta = {
  generatedAt: "2026-05-13T16:39:10.769Z",
  model: "gpt-5.5",
  durationMs: 32897,
  sources: [
    "https://www.pagat.com/schafkopf/bavarian.html",
    "https://www.schafkopfschule.de/regeln.html?file=files%2Finhalte%2Fdokumente%2FSpielen%2FRegeln%2FSchafkopfregeln-Archiv-29.3.2007-English.pdf",
  ],
} as const;
