// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug schafkopf
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Hidden-partner point-trick card game where bidders call an Ace or go solo, then follow suit to capture high-value tricks.",
  default:
    "Traditional Bavarian point-trick card game with bidding, fixed trumps, and a hidden partner in the called-Ace contract. After the deal, someone passes, calls an Ace, or announces a Solo or Wenz. The declarer’s side wins with at least 61 of 120 card points; defenders win on 60 or more.",
  loose:
    "Traditional Bavarian point-trick card game with bidding, fixed trump ranks, and a hidden partner in the common called-Ace contract. After the deal, someone passes, calls an Ace, or announces a Solo or Wenz; each trick starts with a led suit, everyone follows suit if able, and the highest trump or led-suit card takes it. The declarer’s side wins by collecting at least 61 of the 120 card points; the defense wins on 60 or more, with solos paying more. The called Ace reveal is the signature moment: the partner may stay unknown until that suit is finally led.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:27.036Z",
  model: "gpt-5.5",
  durationMs: 21539,
  sources: [
    "https://www.pagat.com/schafkopf/bavarian.html",
    "https://www.sauspiel.de/hilfe/schafkopf-regeln",
    "https://schafkopfschule.de/spielanleitungen.html",
  ],
} as const;
