// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug exit
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative escape-room puzzle game where players inspect a booklet, cards, and cardboard bits to crack cabin codes.",
  default:
    "Cooperative escape-room puzzle game about escaping a locked cabin by solving linked riddles. The group studies booklet art, riddle cards, and cardboard props, then checks three-part codes on a decoder wheel. Open the final lock to win, with a star rating based on hints used.",
  loose:
    "Cooperative escape-room puzzle game about getting out of a locked cabin by solving linked riddles. The group studies the booklet, riddle cards, and cardboard props, writes notes, cuts or folds parts when needed, then enters a three-part answer on the code wheel. Correct answers point to numbered answer cards that unlock more riddle cards; opening the final lock wins, with a star rating based on hints used. It is a one-shot box, so expect to mark, fold, or cut components rather than reset it.",
};

export const meta = {
  generatedAt: "2026-08-14T22:19:52.117Z",
  model: "gpt-5.5",
  durationMs: 17509,
  sources: [
    "https://thamesandkosmos.com/products/exit-abandoned-cabin",
    "https://roomescapeartist.com/2017/07/06/exit-the-game-the-abandoned-cabin-the-secret-lab-the-pharaohs-tomb-review/",
    "https://www.boardgamequest.com/exit-the-game-review/",
    "https://www.geeksundergrace.com/tabletop/reviews-tabletop/review-exit-the-game-the-abandoned-cabin/",
  ],
} as const;
