// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug happy-little-dinosaurs
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light party card game where everyone reveals numbered cards to dodge disasters, score points, and avoid elimination.",
  default:
    "Light party card game about unlucky cartoon dinosaurs dodging disasters. Each round flips a disaster, everyone secretly plays a numbered card, and the lowest total takes the hit while others score. First to 50 points wins, or last dinosaur standing wins.",
  loose:
    "Light party card game about unlucky cartoon dinosaurs dodging Natural, Predatory, and Emotional disasters. Each round flips a disaster, everyone secretly chooses a numbered Point card, then reveals together; the lowest total takes the disaster while the others move on their Escape Route. First dinosaur to 50 points wins, unless every rival is eliminated first by collecting three matching disasters or one of each type. The reveal is the table moment: a 0, 9, or Instant card can decide who gets ghosted, eaten, or flattened by a meteor.",
};

export const meta = {
  generatedAt: "2026-08-17T00:31:43.696Z",
  model: "gpt-5.5",
  durationMs: 19588,
  sources: [
    "https://www.unstablegameswiki.com/index.php?title=Happy_Little_Dinosaurs_-_Rules_of_Play",
    "https://www.tabletopgaming.co.uk/reviews/happy-little-dinosaurs-review/",
    "https://coopboardgames.com/cooperative-board-game-reviews/happy-little-dinosaurs/",
  ],
} as const;
