// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug chess-for-three
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Abstract strategy chess variant on a circular board where each turn moves one familiar piece across rings, arcs, or the center void.",
  default:
    "Abstract strategy chess variant played on a circular board, with familiar pieces aimed at two rival kings. On a turn, a player moves one piece across rings, curved diagonals, or the center void. Checkmate or capture a king to eliminate that army; the last active army wins.",
  loose:
    "Abstract strategy chess variant played on a circular board, with familiar pieces aimed at two rival kings. On a turn, a player moves one piece: rooks sweep around a ring, bishops follow curved guide lines through the center, and no piece stops in the central void. Checkmate or capture a king to eliminate that army; the last active army wins. Green moats and creeks block early border attacks until moats are bridged or pawns push past the fourth rank.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:29.189Z",
  model: "gpt-5.5",
  durationMs: 22097,
  sources: [
    "https://images1.vat19.com/manuals/3-man-chess.pdf",
    "https://www.vat19.com/item/three-man-chess/_escaped_fragment_/",
    "https://www.slashgear.com/3-man-chess-runs-rings-around-the-classic-game-27198169/",
  ],
} as const;
