// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug durak
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Social shedding card game where attackers throw matching ranks at a defender, who covers them with higher suits or trumps.",
  default:
    "Social shedding card game built around attacking one defender and emptying hands before the stock runs out. An attacker leads a card; the defender covers it with a higher card of that suit or any trump. Failed defenses pick up the pile, and the last hand with cards is the fool.",
  loose:
    "Social shedding card game built around attacking one defender and emptying hands before the stock runs out. An attacker leads a card; the defender covers it with a higher card of that suit or any trump, while others add matching ranks. If the defense holds, the pile is discarded; if it fails, the defender picks it all up, and the last hand with cards is the fool. The face-up card tucked under the deck fixes trump for the hand.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:13.255Z",
  model: "gpt-5.5",
  durationMs: 21213,
  sources: [
    "https://playjoy.com/en/durak/rules/",
    "https://arcadiagames.io/guides/durak",
    "https://en.wikipedia.org/wiki/Durak",
  ],
} as const;
