// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug dorfromantik
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative tile-laying puzzle where the table places hexes into shared countryside to complete tasks and chase a high score.",
  default:
    "Cooperative tile-laying puzzle about one shared countryside map. On a turn, draw a task or landscape hex, rotate it into place, connect rivers and rails cleanly, and fill numbered terrain tasks. When the stacks run out, total the score and try to beat the campaign high score.",
  loose:
    "Cooperative tile-laying puzzle about building one shared countryside map and scoring it as a group. On a turn, draw a task or landscape hex, rotate it into the map, connect rivers and rails cleanly, and aim at numbered terrain tasks. When the stacks run out, total tasks, enclosed flags, longest river, and longest rail; success means beating the campaign high score. The campaign pad opens sealed boxes with new tiles and small scoring rules.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:54.737Z",
  model: "gpt-5.5",
  durationMs: 21782,
  sources: [
    "https://coopboardgames.com/cooperative-board-game-reviews/dorfromantik-review/",
    "https://news.pegasus.de/en/interview-dorfromantik-the-board-game-authors-and-toukana-interactive/",
    "https://weeklygeek.net/video-games/dorfromantik-the-board-game-review/",
  ],
} as const;
