// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug dorfromantik
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A calm countryside puzzle hides pressure in every hex, using tile placement to balance village tasks, rivers, rails, and loose terrain.",
  default:
    "A calm countryside puzzle hides pressure in every hex as the shared map keeps asking for just one cleaner edge. The core mechanic is tile placement, with task tiles, landscape tiles, rivers, and rails shaping one growing countryside. The group wins against its own score, then unlocks new material to",
  loose:
    "A calm countryside puzzle hides pressure in every hex as the shared map keeps asking for just one cleaner edge. The core mechanic is tile placement: each revealed hex extends one shared map, with streams and rails forced to match while fields, forests, and villages can sprawl. The group wins against its own score, collecting points from completed tasks, long river and rail lines, and flags sealed inside closed regions. A campaign sheet turns scores into",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:29.597Z",
  model: "gpt-5.5",
  durationMs: 28879,
  sources: [
    "https://pegasusna.com/Dorfromantik-The-Boardgame/PNA51240.USA",
    "https://www.rulespal.com/dorfromantik/rulebook",
    "https://www.connexxion24.com/downloads/anleitungen/dorfromantik-spielregeln-auf-englisch-2.pdf",
    "https://www.wargamer.com/dorfromantik-board-game/review",
  ],
} as const;
