// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug carcassonne-winter-edition
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Snowbound tile-laying game, the classic edition plus twelve extra animal tiles, where players grow a shared winter map and claim it with meeples.",
  default:
    "Snowbound tile-laying game with the classic edition's rules plus twelve animal tiles. Each turn, draw a tile, fit it so roads and city walls continue, then optionally add a meeple. Finished cities, roads, and cloisters score at once, fields at the end, and the highest total wins.",
  loose:
    "Snowbound tile-laying game with the classic edition's rules plus twelve animal tiles. Each turn, draw a tile, fit it so roads and city walls continue, then optionally add a meeple. Finished cities, roads, and cloisters score at once, fields at the end, and the highest total wins. Some print runs tuck in a mini-expansion, the Gingerbread Man or a wintry River, and one animal tile hides a Wolpertinger, the antlered, winged rabbit of Bavarian folklore.",
};

export const meta = {
  generatedAt: "2026-09-14T13:46:02.000Z",
  model: "claude-opus-5 (simulated run — gateway throttled)",
  durationMs: 339000,
  sources: [
    "https://cdn.1j1ju.com/medias/db/66/ef-carcassonne-winter-edition-rulebook.pdf",
    "https://www.ultraboardgames.com/carcassonne/winter-edition.php",
    "https://boardgameextras.info/2013/11/08/winter-has-arrived-in-carcassonne/",
    "https://www.thegamingreview.com/10467/2017/06/20/board-game-review-carcassonne-winter-edition/",
    "https://www.kjwrede.de/spiele/carcassonne-winter-edition-2020/",
  ],
} as const;
