// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug perudo
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Bluffing dice game where everyone shakes five dice under a cup and bids on how many of one face sit hidden around the table.",
  default:
    "Pub-style bluffing game of hidden dice and rising bids, with ones counting as wild. Each turn a player raises the claim, like seven fours, or calls dudo to lift every cup. The loser of each challenge drops a die; the last player with dice wins.",
  loose:
    "Pub-style bluffing game of hidden dice and rising bids, with ones counting as wild. Each turn a player raises the claim on how many of one face lie under all the cups, like seven fours, or calls dudo to reveal every die. The loser of each challenge drops a die, and the last player still holding dice wins. A player down to one die triggers a palifico round, where ones stop being wild and nobody may change the face being bid.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.336Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 36339,
  sources: [
    "https://en.wikipedia.org/wiki/Dudo",
    "https://gamerules.com/rules/perudo/",
    "https://www.finazzofun.com/2025/09/05/perudo-cups-full-of-fun/",
  ],
} as const;
