// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug brass-pittsburgh
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Heavy economic network game where players play cards to build mills, rails, pipelines, and sell goods for victory points.",
  default:
    "Heavy economic network game about building industries and transport links across a shared Steel Belt map. Each turn, a player spends cards, cash, and resources to build tiles, lay rails or pipelines, take loans, develop, or sell goods. Highest victory point total after final scoring wins.",
  loose:
    "Heavy economic strategy game about competing industrial empires on a shared Steel Belt map. Each turn, a player spends cards, cash, coal, iron, steel, oil, or coke to build industry tiles, lay rails or pipelines, develop better tiles, take loans, or sell goods to connected cities. Industries flip when their goods or resources are used, and the highest victory point total after final scoring wins. Oil fields feed pipelines before rail, so another player’s refinery can pay the pipeline owner.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:28.086Z",
  model: "gpt-5.5",
  durationMs: 59289,
  sources: [
    "https://roxley.com/products/brass-pittsburgh",
    "https://www.gamesradar.com/games/board-games/brass-pittsburgh-features-the-most-innovative-mechanisms-and-dynamics-its-designer-could-imagine/",
    "https://gamingtrend.com/news/brass-pittsburgh-trades-scouting-for-whiskey/",
    "https://gamingtrend.com/news/steel-and-oil-play-a-big-part-in-brass-pittsburgh/",
  ],
} as const;
