// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug brass-pittsburgh
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Gilded Age Pittsburgh turns Brass into taut route-building, where rails, pipelines, steel, and oil feed a shared industrial machine.",
  default:
    "America’s Steel Belt gives Brass a harsher industrial map of railways, pipelines, steel mills, and oil fields. Route-building drives the game through cards, cash, and shared resources. Winning means flipping industries and links at the moment rivals need them most.",
  loose:
    "The Steel Belt turns Brass into a denser web of railways, pipelines, steel, oil, and hungry cities. Route-building drives the game: cards, cash, coal, coke, and oil turn city spaces into shared supply lines. Profit rises when industries flip, but victory comes from timing flips, loans, links, and network points better than rivals. Heavy trains can survive the midgame reset, so an early rail plan can become a long bet.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:19.468Z",
  model: "gpt-5.5",
  durationMs: 28569,
  sources: [
    "https://roxley.com/products/brass-pittsburgh",
    "https://roxley.com/blogs/news/join-us-on-the-road-to-pittsburgh",
    "https://www.gamesradar.com/games/board-games/brass-pittsburgh-features-the-most-innovative-mechanisms-and-dynamics-its-designer-could-imagine/",
    "https://boardgamewire.com/index.php/2026/04/27/deluxe-editions-have-become-sort-of-an-arms-race-we-often-do-the-opposite-roxley-ceo-gavan-brown-on-the-stellar-success-of-brass-pittsburghs-9-1m-crowdfund/",
  ],
} as const;
