// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug monopoly
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A lap around Atlantic City turns lucky dice into rent traps, using roll-and-move to feed auctions, trades, and hostile development.",
  default:
    "Atlantic City real estate becomes a slow squeeze, as cheap deeds turn into rent traps after one completed color group. Roll-and-move sets the tempo: dice choose the space, then auctions and trades decide who can build. Victory means staying solvent while every rival goes bankrupt.",
  loose:
    "Atlantic City real estate becomes a slow squeeze, as cheap deeds turn into rent traps after one completed color group. Roll-and-move sets the tempo: dice choose the space, then buying, auctions, mortgages, and deals decide who can build. Victory means staying solvent while every rival goes bankrupt. The 1904 ancestor, Lizzie Magie’s Landlord’s Game, was meant to expose landlord power.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:44.122Z",
  model: "gpt-5.5",
  durationMs: 61139,
  sources: [
    "https://instructions.hasbro.com/en-us/instruction/monopoly-game",
    "https://www.britannica.com/sports/Monopoly-board-game",
    "https://www.museumofplay.org/toys/monopoly/",
  ],
} as const;
