// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug monopoly
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Family-weight roll-and-move property trading game where players buy streets, auction deeds, charge rent, and cut deals.",
  default:
    "Family-weight roll-and-move property trading game about buying streets and squeezing rent from rivals. A turn is a dice roll around the board, then a purchase, auction, rent payment, card draw, tax, or jail space. The last solvent player wins after everyone else goes bankrupt.",
  loose:
    "Family-weight roll-and-move property trading game about buying streets and squeezing rent from rivals. A turn is a dice roll around the board, then a purchase, auction, rent payment, Chance or Community Chest card, tax, or jail space. Owning a full color set allows houses and hotels, and the last solvent player wins after everyone else goes bankrupt. The table fills with title deed cards, paper cash, green houses, red hotels, and little tokens circling Go.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:23.701Z",
  model: "gpt-5.5",
  durationMs: 16068,
  sources: [
    "https://instructions.hasbro.com/en-my/instruction/monopoly-classic-game",
    "https://www.hasbro.com/common/instruct/Monopoly_Vintage.pdf",
    "https://en.wikipedia.org/wiki/Monopoly_%28game%29",
  ],
} as const;
