// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug telestrations
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Drawing party game where a secret word passes around the circle in flip books, alternating quick timed sketches and written guesses.",
  default:
    "Drawing party game built on the telephone game. Each player sketches a secret word against a sand timer and passes the flip book; the next player writes a guess, alternating until books return home. Optional points reward matching guesses.",
  loose:
    "Drawing party game built on the telephone game, where a word mutates as it travels around the table. Each player sketches a secret word against a sand timer and passes the flip book left; the next player writes a guess of the drawing, the one after draws that guess, and so on. When books return home, owners flip through them aloud, and optional scoring rewards correct guesses and helpful sketches. Letters and numbers are banned from drawings.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.335Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 95000,
  sources: [
    "https://www.geekyhobbies.com/telestrations-rules/",
    "https://boardsandbees.wordpress.com/2015/02/24/0433/",
  ],
} as const;
