// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug betrayal-at-house-on-the-hill
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Hidden-traitor horror adventure where explorers add room tiles, draw creepy cards, then split into heroes and traitor.",
  default:
    "Hidden-traitor horror adventure about exploring a modular haunted mansion before the haunt hits. On a turn, move an explorer, add a room tile if entering a new doorway, and resolve an item, event, or omen card. After the haunt, the first side to complete its secret scenario goal wins.",
  loose:
    "Hidden-traitor horror adventure about exploring a modular haunted mansion before the haunt hits. On a turn, move an explorer, add a room tile if entering a new doorway, and resolve an item, event, or omen card. After enough omens, heroes and traitor read separate booklets; the first side to complete its scenario goal wins. The box includes 50 haunts, so one game might be a monster hunt and the next an escape ritual.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:38.529Z",
  model: "gpt-5.5",
  durationMs: 20937,
  sources: [
    "https://consumercare.hasbro.com/en-us/product/avalon-hill-betrayal-at-house-on-the-hill-second-edition-cooperative-board-game-for-ages-12-and-up-for-3-6-players/8450F69A-05BE-4BB2-8146-EBCE86E4C868",
    "https://www.shelfside.co/reviews2020/betrayal-review",
    "https://www.bigredbarrel.com/2015/02/22/review-betrayal-at-house-on-the-hill/",
  ],
} as const;
