// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug betrayal-at-house-on-the-hill
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Every new doorway redraws the mansion, and hidden roles turn a shared horror crawl into a knife fight after the haunt breaks.",
  default:
    "Every door changes the house, and every omen can trigger a new horror scenario. Hidden roles take over when the haunt starts. Heroes race to solve that haunt before the traitor finishes a secret goal.",
  loose:
    "Every door changes the house, and every omen can push the table toward a new horror scenario. Hidden roles take over when the haunt starts, turning one explorer against the rest with secret rules. Victory depends on the haunt: heroes might escape, kill a monster, or stop a ritual while the traitor pursues a private goal. Two haunt books, Traitor's Tome and Secrets of Survival, let each side read rules the other cannot see.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:38.942Z",
  model: "gpt-5.5",
  durationMs: 85473,
  sources: [
    "https://consumercare.hasbro.com/en-us/product/avalon-hill-betrayal-at-house-on-the-hill-second-edition-cooperative-board-game-for-ages-12-and-up-for-3-6-players/8450F69A-05BE-4BB2-8146-EBCE86E4C868",
    "https://instructions.hasbro.com/en-ca/instruction/avalon-hill-betrayal-at-house-on-the-hill-second-edition-cooperative-board-game-for-ages-12-and-up-for-3-6-players",
    "https://boardgamegeek.com/boardgame/10547/betrayal-at-house-on-the-hill",
    "https://www.gamesradar.com/betrayal-at-house-on-the-hill-2nd-edition-review/",
  ],
} as const;
