// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug last-one-drunk
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/web/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Adult drinking party game where players draw challenge cards, do dirty dares, or drink for refusing and failing.",
  default:
    "Adult drinking party game built around a deck of dare and prompt cards. On a turn, a player flips a card, reads its challenge, and the named player either does the task or drinks. The last player still willing and able to keep playing wins.",
  loose:
    "Adult drinking party game built around a deck of dare, voting, and prompt cards. On a turn, a player flips a challenge card, reads it aloud, and the targeted player either performs the task, answers the prompt, or drinks for refusing. Play continues until people bow out, fail too many challenges, or stop keeping up, and the last player still in the game wins. The box centers on 100 challenge cards, with dirty dares and uncomfortable truths doing most of the work.",
};

export const meta = {
  generatedAt: "2026-05-23T15:06:42.943Z",
  model: "gpt-5.5",
  durationMs: 12971,
  sources: [
    "https://www.giftrepublic.com/games-room/last-one-drunk",
    "https://www.kkec.nl/last-one-drunk.html",
    "https://www.tesco.com/groceries/en-GB/products/325333823",
    "https://woodbridgekitchencompany.co.uk/product/last-one-drunk-game/",
  ],
} as const;
