// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug salem-1692
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Hidden-role party card game where players draw accusation cards, pile them on suspects, and expose Tryal cards to find witches.",
  default:
    "Hidden-role social deduction game where townsfolk hunt secret witches with accusation cards. On a turn, draw two cards or play accusation and effect cards onto other players; seven accusations flip one Tryal card. Town wins by revealing every Witch Tryal card, while witches win once every living player has held a Witch card.",
  loose:
    "Hidden-role party card game where townsfolk argue over face-down Tryal cards while secret witches hide. On a turn, a player either draws two cards or plays accusation and effect cards onto other players; seven accusations flip one Tryal card. The town wins by revealing every Witch Tryal card, while witches win once every living player has held a Witch card. The Conspiracy card passes Tryal cards around, so a trusted neighbor can quietly join the witches midgame.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:28.995Z",
  model: "gpt-5.5",
  durationMs: 23853,
  sources: [
    "https://facadegames.com/collections/the-dark-cities-series/products/salem-1692",
    "https://www.ultraboardgames.com/salem/game-rules.php",
    "https://www.board-game.co.uk/salem-1692-review/",
    "https://www.boardseyeview.net/post/2017/10/01/salem-1692",
  ],
} as const;
