// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug salem-1692
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A witch hunt turns neighbors into liabilities, using hidden roles and accusation cards to make every face-down Tryal card suspect.",
  default:
    "A Salem witch hunt turns table talk brittle because guilt can hide under any face-down Tryal card. Hidden roles drive the game as accusation cards expose players and Night lets witches strike. Townsfolk win by revealing every Witch card, but Conspiracy can create new witches.",
  loose:
    "A witch hunt turns table talk brittle because any unrevealed Tryal card can hide guilt. Hidden roles drive the game, with accusation cards forcing players to expose one another while Night lets witches strike in secret. Townsfolk win by revealing every Witch card, but Conspiracy can pass a Witch card to a new player and convert them. The faux book box is more than shelf dressing; Facade built the series around that disguised volume.",
};

export const meta = {
  generatedAt: "2026-05-13T16:38:59.262Z",
  model: "gpt-5.5",
  durationMs: 28460,
  sources: [
    "https://facadegames.com/collections/the-dark-cities-series/products/salem-1692",
    "https://www.ultraboardgames.com/salem/game-rules.php",
    "https://www.reddit.com/r/boardgames/comments/112zxeu/im_the_founder_of_facade_games_and_the_inventor/",
  ],
} as const;
