// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug jaipur
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Head-to-head trading card game where players draft goods and camels from a market, then sell sets for rupee tokens.",
  default:
    "Light head-to-head trading card game about timing market grabs and set sales for rupees. On a turn, take one goods card, take all camels, swap several cards with the market, or sell one goods type. Highest rupee total takes a seal each round, and two seals win.",
  loose:
    "Light head-to-head trading card game about timing market grabs and set sales for rupees. On a turn, take one goods card, scoop all camels, exchange several cards with the five-card market, or sell one goods type for tokens. A round ends when token piles run out or the deck cannot refill the market; highest rupee total takes a seal, and two seals win. The signature squeeze is selling early for high-value tokens or waiting for a larger sale bonus.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:51.319Z",
  model: "gpt-5.5",
  durationMs: 14444,
  sources: [
    "https://hobbygames.ru/download/rules/jaipur-rules.pdf",
    "https://www.wargamer.com/jaipur/board-game-review",
    "https://www.gamesradar.com/tabletop-gaming/jaipur-review/",
  ],
} as const;
