// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug jaipur
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A five-card market makes every camel grab a gamble, and hand management drives brisk trades of leather, spice, silver, gold, and gems.",
  default:
    "The five-card market turns Jaipur into a duel of timing, with early sales racing against richer set bonuses. Hand management drives each turn through taking, swapping, herding camels, or selling one good type. Two Seals of Excellence win the Maharaja’s favor.",
  loose:
    "The five-card market makes timing sharp, as early sales pay rupees while bigger sets tempt a delay. Hand management drives each turn: take one good, swap cards with camels, gather all camels, or sell one type. The richer trader wins the round, and two Seals of Excellence earn the Maharaja’s court. A camel sweep fuels later trades but may flip fresh diamonds or gold for the rival.",
};

export const meta = {
  generatedAt: "2026-05-13T16:36:10.539Z",
  model: "gpt-5.5",
  durationMs: 36526,
  sources: [
    "https://www.spacecowboys-games.com/game/jaipur/",
    "https://cdn.1j1ju.com/medias/04/3f/df-jaipur-rulebook.pdf",
    "https://www.wargamer.com/jaipur/board-game-review",
    "https://www.gamesradar.com/tabletop-gaming/jaipur-review/",
  ],
} as const;
