// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug jaipur
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Head-to-head set-collection card game: draft goods from a shared market, trade with camels, then sell sets before values drop.",
  default:
    "Competitive hand-management card game about timing set sales from a shared five-card market. On a turn, either take one goods card, take all camels, or swap 2+ cards with the market; or sell one goods type for coin tokens and possible bonuses. Win rounds by having the most money, and first to earn two Seals wins.",
  loose:
    "Competitive hand-management card game about timing set sales from a shared five-card market. On a turn, either take one goods card, take all camels, or swap 2+ cards with the market; or sell one goods type for coin tokens and possible bonuses. A round ends when the deck runs out or three token stacks empty; the richer trader takes a Seal, and first to two Seals wins. Bonus tokens stay face-down until taken, so a big sale can flip a surprise payout.",
};

export const meta = {
  generatedAt: "2026-09-02T21:50:24.577Z",
  model: "openai/gpt-5.2",
  durationMs: 49503,
  sources: [
    "https://www.goblins.net/files/downloads/JAIPUR.pdf",
    "https://www.meeplemountain.com/reviews/jaipur/",
    "https://www.tombell.net/board-game-review-jaipur/",
    "https://shelfgamer.com/reviews/jaipur/",
    "https://en.wikipedia.org/wiki/Jaipur_(card_game)",
  ],
} as const;
