// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug parks-europe
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Strategic hiking worker-placement game where hikers move down trail sites, collect resources and fatigue, then buy park cards for points.",
  default:
    "Gateway-plus strategy game about planning hikes through European national parks. On a turn, one hiker advances along a one-way trail to gather resources, take photos, use Via Ferrata, rest at the Chalet, or visit a park. After the third season, most points from parks, photos, projects, awards, and card sets wins.",
  loose:
    "Gateway-plus strategy game about planning hikes through European national parks. On a turn, one hiker advances along a one-way trail to gather resources, take photos, use Via Ferrata, rest at the Chalet, or visit a park. After the third season, most points from parks, photos, conservation projects, awards, and card sets wins. The deluxe box adds screen-printed wooden wildlife, double-layer player mats, a cloth Trail Site Bag, and 48 oversized park cards from eight European artists.",
};

export const meta = {
  generatedAt: "2026-08-04T10:22:33.964Z",
  model: "gpt-5.5",
  durationMs: 30114,
  sources: [
    "https://www.backerkit.com/c/projects/keymaster/parks-europe-chalet-edition-free-expansion",
    "https://icv2.com/articles/news/view/62765/venture-parks-europe",
    "https://frogames.it/en/products/parks-europe",
    "https://dragonslair.se/en/products/parks-europe",
    "https://www.reddit.com/r/boardgames/comments/1v3qe6e/parks_europe/",
  ],
} as const;
