// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug rummikub
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light tile-rummy game where players empty racks by laying numbered tiles into same-color runs and same-number groups.",
  default:
    "Light tile-rummy game where players race to empty a rack of numbered tiles. On a turn, a player lays a 30-point opening meld, adds tiles to table sets, rearranges runs and groups, or draws one tile. The first empty rack wins, and leftover tiles count against everyone else.",
  loose:
    "Light tile-rummy game where players try to empty a rack of numbered tiles by making same-color runs and same-number groups. On a turn, a player lays an opening meld, adds tiles to existing sets, rearranges the whole table into legal sets, or draws one tile. The first empty rack wins the round, while leftover tiles on other racks count as penalties. Jokers are wild, but rescuing one usually forces an immediate new play.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:16.821Z",
  model: "gpt-5.5",
  durationMs: 26184,
  sources: [
    "https://www.rummikub.org/rules",
    "https://www.pagat.com/rummy/rummikub.html",
    "https://familygameshelf.com/2021/05/11/rummikub/",
  ],
} as const;
