// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug rummikub
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A calm rack of numbers turns volatile as tile-rummy set collection lets every legal run and group on the table be rebuilt.",
  default:
    "Every meld can unlock the whole table, turning a quiet rack of numbered tiles into a shared puzzle. Set collection drives each turn through colored runs and matching-number groups. The round ends when one player empties a rack, while leftovers become penalties.",
  loose:
    "Every new meld can unlock the whole table, turning a quiet rack of numbered tiles into a shared puzzle. Set collection drives each turn: make runs of one color or groups of matching numbers. The round ends when one player empties a rack, while leftovers become penalties. A 30-point initial meld gates entry, then later turns can split runs, move tiles, and free jokers if every tile finishes in a legal set.",
};

export const meta = {
  generatedAt: "2026-05-13T16:38:39.894Z",
  model: "gpt-5.5",
  durationMs: 42347,
  sources: [
    "https://www.rummikub.org/gameplay",
    "https://www.rummikub.org/history",
    "https://www.rummikub.org/rules",
  ],
} as const;
