// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug not-enough-mana
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Spell duels turn liquid courage into spell fuel, with hand management deciding when to blast, curse, equip, or drink for mana.",
  default:
    "Mana comes from potions in a wizard duel where every spell risks another gulp. Hand management drives turns of casting, cursing, equipping, and exchanging cards. The last wizard standing wins after rivals lose health or hit Too Much Mana.",
  loose:
    "Wizard duels become a drinking-risk brawl, because mana comes from potions rather than a tidy resource track. Hand management drives each turn: draw to a limit, cast spells, lay curses, equip artifacts, or exchange cards. The last wizard standing wins after rivals lose health or hit Too Much Mana. The rules even suggest swapping potions for sausages or press-ups.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:32.849Z",
  model: "gpt-5.5",
  durationMs: 28893,
  sources: [
    "https://notenoughmana.com/",
    "https://buy.notenoughmana.com/wp-content/uploads/2023/10/Not-Enough-Mana-Maleficus-Praecepta-WEB-EN.pdf",
  ],
} as const;
