// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug keltis
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light family hand-management game where players play numbered color cards in order to push pawns along scoring paths.",
  default:
    "Light family hand-management game about committing cards to colored stone paths. Each turn, a player plays or discards one card, moves a matching pawn if played, then draws from the deck or a discard pile. Highest score wins after the deck empties or enough pawns reach the goal area.",
  loose:
    "Light family hand-management game about committing numbered cards to colored stone paths. Each turn, a player plays or discards one card, moves a matching pawn if played, resolves any bonus tile reached, then draws from the deck or a discard pile. When the deck empties or enough pawns reach the goal area, pawns score by distance traveled and the highest total wins. Wishing stones matter because too few cost points at final scoring.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:56.368Z",
  model: "gpt-5.5",
  durationMs: 13477,
  sources: [
    "https://www.ultraboardgames.com/keltis/game-rules.php",
    "https://www.meeplemountain.com/reviews/keltis/",
  ],
} as const;
