// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug uno-flip
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A familiar race to empty hands turns mean when Flip cards expose the harsher backs of every card; hand management drives each turn.",
  default:
    "A familiar race to empty hands turns mean when Flip cards expose the harsher backs of every card. Hand management drives each turn through color, number, and symbol matches. Rounds end when one player sheds the last card and scores the cards left in others’ hands.",
  loose:
    "A familiar race to empty hands turns mean when Flip cards expose the harsher backs of every card. Hand management drives play as each card must match the current color, number, or symbol. Rounds end when one player sheds the last card, and scores come from cards trapped in rivals’ hands. A single Flip turns hands, draw pile, and discard pile over, bringing Draw Five, Skip Everyone, and Wild Draw Color into view.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:11.647Z",
  model: "gpt-5.5",
  durationMs: 21806,
  sources: [
    "https://unogamerules.com/wp-content/uploads/2022/02/Uno-Flip-Rules.pdf",
    "https://www.geekyhobbies.com/uno-flip-2019-card-game-review-and-rules/",
    "https://www.unorules.com/uno-flip-rules/",
  ],
} as const;
