// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug uno-flip
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light family shedding card game where turns match a hand card by color, number, or symbol, with Flip cards swapping the whole deck side.",
  default:
    "Light family shedding card game about emptying a hand by matching the discard pile’s color, number, or symbol. On a turn, play one matching card or draw; action cards reverse order, skip turns, force draws, or set a new color. First out scores the cards left in other hands, and the first to 500 points wins.",
  loose:
    "Light family shedding card game about emptying a hand by matching the discard pile’s color, number, or symbol. On a turn, play one matching card or draw; action cards reverse order, skip turns, force draws, or set a new color. Playing a Flip card makes every hand, draw pile, and discard pile use the opposite side, and the first to 500 points wins. The dark side hits harder with Draw Five, Skip Everyone, and Wild Draw Color cards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:16.663Z",
  model: "gpt-5.5",
  durationMs: 17301,
  sources: [
    "https://service.mattel.com/instruction_sheets/GDR44-English.pdf",
    "https://www.geekyhobbies.com/uno-flip-2019-card-game-review-and-rules/",
    "https://www.manuals.co.uk/mattel/uno-flip/manual",
  ],
} as const;
