// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wingspan
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight: "Euro-style tableau engine game where players play birds, run habitat actions to trigger row powers, and win on total points after four rounds.",
  default: "Engine-building tableau game where each player builds three habitat rows of bird cards, mostly on their own board. On a turn, place a cube to gain food from dice, lay eggs, draw from the face-up birds, or pay food plus eggs to play a bird.",
  loose: "Engine-building tableau game where each player builds three habitat rows of bird cards, mostly on their own board. On a turn, place a cube to gain food from dice, lay eggs, draw from the face-up birds, or pay food plus eggs to play a bird. Row actions trigger bird powers in order, and after four rounds the high score wins from birds, goals, bonus cards, eggs, cached food, and tucked cards. A birdhouse dice tower and pastel egg tokens are the signature table pieces.",
};

export const meta = {
  generatedAt: "2026-09-03T02:39:02.327Z",
  model: "openai/gpt-5.2",
  durationMs: 82053,
  sources: [
    "https://store.stonemaiergames.com/products/wingspan",
    "https://arstechnica.com/gaming/2019/03/wingspan-review-a-gorgeous-birding-board-game-takes-flight/",
    "https://wingspan.rulepop.com/",
    "https://www.wargamer.com/wingspan/review",
    "https://boardgamegeek.com/wiki/page/thing:266192"
  ],
} as const;
