// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug bandit
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light bluff-and-memory card game where players manage hidden grids, draw cards, swap unknowns, and race to dump matches.",
  default:
    "Light party-style bluff-and-memory card game about driving a hidden card grid to the lowest total. On a turn, draw from the deck or discard pile, use a power, swap it into a face-down slot, or throw it away. A round ends when someone calls out and everyone takes one last turn; at 100 points, low score wins.",
  loose:
    "Light party-style bluff-and-memory card game about driving a hidden card grid to the lowest total. On a turn, draw from the deck or discard pile, use a power, swap it into a face-down slot, or throw it away while tracking which numbers sit where. A round ends when someone calls out, everyone gets one last turn, and at 100 points the lowest score wins. Matching the top discard lets any player slap a card down, with misses adding penalty cards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:28.736Z",
  model: "gpt-5.5",
  durationMs: 19214,
  sources: [
    "https://www.bandit.cards/de",
    "https://www.analog.games/games/70a3e645-64a8-4c31-9af1-a63fb1cf77bd/bandit?lang=en",
    "https://boardgamegeek.com/wiki/page/weblink%3A367518",
  ],
} as const;
