// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug bandit
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Four hidden cards turn every swap into a bluff, and memory drives each draw, steal, and risky table slap.",
  default:
    "Four hidden cards make every steal and swap feel like a small heist. Memory drives the game through draws, peeks, powers, and scrambled grids. The lowest total wins, but a bad Bandit call adds a penalty.",
  loose:
    "Four hidden cards make every steal and swap feel like a heist, because only part of each grid is known. Memory drives the game: draw, replace, peek, or trigger a card power while rivals scramble the layout. Rounds end when someone calls Bandit, and the lowest total wins unless the call was reckless. A matching discard can be slapped from the table at any time, turning a quiet count into a race.",
};

export const meta = {
  generatedAt: "2026-05-13T16:32:48.248Z",
  model: "gpt-5.5",
  durationMs: 34779,
  sources: [
    "https://bandit.cards/?lang=en",
    "https://www.bandit.cards/rules",
    "https://bandit.cards/play",
    "https://bandit.cards/video",
    "https://boardgamegeek.com/wiki/page/thing%3A450261",
  ],
} as const;
