export const qk = {
  inventory: (userId: string | null | undefined) => ["inventory", userId] as const,
  adminUsers: () => ["admin", "users"] as const,
  adminUserInventory: (targetUserId: string) => ["admin", "user-inventory", targetUserId] as const,
  adminUserNewSlugs: (targetUserId: string) => ["admin", "user-new-slugs", targetUserId] as const,
  adminPendingInventory: () => ["admin", "pending-inventory"] as const,
  availability: (userId: string | null | undefined) => ["availability", userId] as const,
  availabilityCounts: () => ["availability", "counts"] as const,
  calendarLocks: () => ["calendar", "locks"] as const,
  hostStats: () => ["calendar", "host-stats"] as const,
  availableGames: (date: string | null) => ["calendar", "games", date] as const,
  /** Prefix of every night's picker payload — for invalidating them all. */
  availableGamesAll: () => ["calendar", "games"] as const,
  exitNight: (date: string | null) => ["calendar", "exit", date] as const,
  adminUserAvailability: (targetUserId: string) =>
    ["admin", "user-availability", targetUserId] as const,
  adminUserActivity: (targetUserId: string) => ["admin", "user-activity", targetUserId] as const,
  adminUserDevices: (targetUserId: string) => ["admin", "user-devices", targetUserId] as const,
  adminUnseenActivity: () => ["admin", "unseen-activity"] as const,
  adminAggregateAvailability: () => ["admin", "availability", "all"] as const,
  /** Every member's admin-noted away days (userId → date keys), today on. */
  adminAwayDays: () => ["admin", "away-days"] as const,
  history: () => ["history"] as const,
  historyByNight: (dateKey: string) => ["history", "by-night", dateKey] as const,
  dndOpenCampaigns: () => ["history", "dnd-campaigns"] as const,
  gameReplays: (gameSlug: string) => ["game-replays", gameSlug] as const,
  tournamentGames: (tournamentId: string) => ["tournament-games", tournamentId] as const,
  calendarFeed: () => ["calendar", "feed"] as const,
  players: () => ["players"] as const,
  profile: (userId: string | null | undefined) => ["profile", userId] as const,
  profileMatches: (userId: string) => ["profile", userId, "matches"] as const,
  profileMatchSummary: (userId: string) => ["profile", userId, "match-summary"] as const,
  profileNights: (userId: string) => ["profile", userId, "nights"] as const,
  skillPlayer: (userId: string) => ["skills", "player", userId] as const,
  skillLeaderboards: () => ["skills", "leaderboards"] as const,
  // App-wide greeting queue. Root key "greetings" is matched by name in the
  // persister exclusion (App.tsx) — a nag must re-evaluate every app open,
  // never hydrate from disk.
  greetings: () => ["greetings"] as const,
  purchaseVote: () => ["purchase-vote"] as const,
  adminPurchaseVote: () => ["admin", "purchase-vote"] as const,
  adminArrivals: () => ["admin", "arrivals"] as const,
  collection: (userId: string) => ["collection", userId] as const,
  purchases: (userId: string) => ["purchases", userId] as const,
  adminAnnouncements: () => ["admin", "announcements"] as const,
  adminSkills: () => ["admin", "skills"] as const,
  adminLastAttended: () => ["admin", "last-attended"] as const,
  dndCampaigns: () => ["dnd", "campaigns"] as const,
  dndCharacters: (partyId: string) => ["dnd", "characters", partyId] as const,
  dndParties: (campaignId: string) => ["dnd", "parties", campaignId] as const,
  dndNodes: (partyId: string) => ["dnd", "nodes", partyId] as const,
  dndHistory: (partyId: string) => ["dnd", "history", partyId] as const,
  dndCombat: (partyId: string) => ["dnd", "combat", partyId] as const,
  dndActions: (characterId: string) => ["dnd", "actions", characterId] as const,
  dndNpcs: (campaignId: string) => ["dnd", "npcs", campaignId] as const,
  dndFiles: () => ["dnd", "files"] as const,
  dndActiveSession: () => ["dnd", "session", "active"] as const,
  // Quiztopia trainer + wiki. Root key "quiztopia" is excluded from the
  // persister (App.tsx): queues are date-bound and content chunks are big.
  quiztopiaOverview: (today: string) => ["quiztopia", "overview", today] as const,
  quiztopiaQueue: (category: number | null, today: string) =>
    ["quiztopia", "queue", category, today] as const,
  quiztopiaStates: (ids: readonly string[]) => ["quiztopia", "states", ids.join(",")] as const,
  quiztopiaHistory: (days: number, today: string) => ["quiztopia", "history", days, today] as const,
  quiztopiaSettings: () => ["quiztopia", "settings"] as const,
  quiztopiaPins: () => ["quiztopia", "pins"] as const,
  quiztopiaSearch: (q: string, lang: string, category: number | null) =>
    ["quiztopia", "search", q, lang, category] as const,
  quiztopiaWikiReads: () => ["quiztopia", "wiki-reads"] as const,
  quiztopiaRecentMisses: () => ["quiztopia", "recent-misses"] as const,
  quiztopiaContent: (kind: "questions" | "articles" | "titles" | "timeline", cardId: string) =>
    ["quiztopia", "content", kind, cardId] as const,
} as const;
