export const qk = {
  inventory: (userId: string | null | undefined) => ["inventory", userId] as const,
  adminUsers: () => ["admin", "users"] as const,
  adminUserInventory: (targetUserId: string) => ["admin", "user-inventory", targetUserId] as const,
  adminPendingInventory: () => ["admin", "pending-inventory"] as const,
  availability: (userId: string | null | undefined) => ["availability", userId] as const,
  availabilityCounts: () => ["availability", "counts"] as const,
  calendarLocks: () => ["calendar", "locks"] as const,
  hostStats: () => ["calendar", "host-stats"] as const,
  availableGames: (date: string | null) => ["calendar", "games", date] as const,
  adminUserAvailability: (targetUserId: string) =>
    ["admin", "user-availability", targetUserId] as const,
  adminAggregateAvailability: () => ["admin", "availability", "all"] as const,
  history: () => ["history"] as const,
  historyByNight: (dateKey: string) => ["history", "by-night", dateKey] as const,
  gameReplays: (gameSlug: string) => ["game-replays", gameSlug] as const,
  tournamentGames: (tournamentId: string) => ["tournament-games", tournamentId] as const,
  calendarFeed: () => ["calendar", "feed"] as const,
  players: () => ["players"] as const,
  profile: (userId: string | null | undefined) => ["profile", userId] as const,
  profileMatches: (userId: string) => ["profile", userId, "matches"] as const,
} as const;
