// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wizard
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Exact-bid trick-taker where each hand grows by one card, then players call their trick count before playing trump, Wizards, and Jesters.",
  default:
    "Exact-bid trick-taking card game about calling exactly how many tricks a hand will take. Each hand grows by one card, trump is revealed, everyone bids a number, then plays tricks while following suit when possible. Correct bids score bonuses, missed bids lose points, and the highest final score wins.",
  loose:
    "Exact-bid trick-taking card game about predicting your own haul before the cards hit the table. Each hand grows by one card, trump is revealed, everyone bids a trick total, then plays cards while following suit when possible. Hit the bid exactly to score bonuses; miss high or low and lose points, with the highest final score winning. The custom deck adds four always-winning Wizards and four usually-losing Jesters.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:45.000Z",
  model: "gpt-5.5",
  durationMs: 13442,
  sources: [
    "https://www.usgamesinc.com/files/attachments/850/2025_FAQ_wizard.pdf",
    "https://officialgamerules.org/game-rules/wizard-card-game-rules/",
  ],
} as const;
