// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug thurn-and-taxis
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light route-building Euro where players draft city cards, extend postal routes, then place houses on a map for bonuses.",
  default:
    "Light route-building Euro about building postal networks across a map of Central Europe. Each turn, a player drafts a city card, adds one card to either end of their current route, and may score a route of at least three linked cities. Most points wins after someone claims the top carriage or places their last house.",
  loose:
    "Light route-building Euro about building postal networks across a map of Central Europe. Each turn, a player drafts a city card, adds one card to either end of their current route, and may score a route of at least three linked cities. Most points wins after someone claims the top carriage or places their last house, counting carriage cards, region bonuses, route bonuses, and unplaced-house penalties. The key placement choice is either one house in each province on the route or every routed city in one province.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:44.711Z",
  model: "gpt-5.5",
  durationMs: 12484,
  sources: [
    "https://fgbradleys.com/wp-content/uploads/rules/Thurn%20and%20Taxis%20-%20rules.pdf?srsltid=AfmBOoobnLuhoAY3nKUfdR4qlL2SyEE3GKxH7t2BEdYOOXAHK8-eo_uQ",
    "https://mikkosgameblog.com/2006/04/thurn-und-taxis/",
    "https://www.pevans.co.uk/Reviews/ThurnTaxis.pdf",
  ],
} as const;
