// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug thurn-and-taxis
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A fragile postal route can collapse on one missing city card in this lean route-building game across southern Germany.",
  default:
    "Each postal line feels provisional, since one missing city can dump a whole route into the discard. Route-building drives each turn. Win by upgrading carriages, completing regions, and wasting fewer houses.",
  loose:
    "Each postal line feels provisional, since one missing city can dump a whole route into the discard. Route-building drives each turn: draw a city card, add one adjacent city to the line, then choose when to score. Points come from carriage upgrades, region bonuses, and penalties for houses left in hand. Four postal officials bend one rule per turn, including a cartwright who can grant a carriage from a short route.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:18.531Z",
  model: "gpt-5.5",
  durationMs: 54178,
  sources: [
    "https://paperzz.com/doc/7320284/thurn-and-taxis---rio-grande-games",
    "https://gamesnightguru.com/game/thurn-taxis/",
    "https://www.hans-im-glueck.de/en/our-story/",
    "https://www.reddit.com/r/boardgames/comments/1fm6tbb/whats_wrong_with_thurn_and_taxis/",
  ],
} as const;
