// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug challengers-beach-cup
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Tournament deck-builder where decks of oddball characters auto-battle for a flag by flipping cards, against a new rival every round.",
  default:
    "Light deck-building card game played as a tournament of head-to-head matches. Players draft wizards, cats and krakens into their decks, then flip cards until their power beats the flag holder's card. After seven rounds, the two most popular players meet in a final for the cup.",
  loose:
    "Light deck-building card game played as a tournament, with a new head-to-head rival every round. Each round players draft wizards, cats, aliens and krakens into their decks, then take turns flipping cards until their total power beats the card holding the flag, sending beaten cards to the bench. A full bench or empty deck loses the match, and the two players with the most fans after seven rounds meet in a final. Reviewers call it War for gamers.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.334Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 37812,
  sources: [
    "https://www.meeplemountain.com/reviews/challengers-beach-cup/",
    "https://en.doc.boardgamearena.com/Gamehelpchallengersbeachcup",
  ],
} as const;
