import { bggSnapshot } from "@boardgames/core/bgg";
import placeholderThumbnail from "./_placeholder-thumbnail.svg?url";
import type { GameDefinition, GameDescriptions, GameModule } from "./types";

const modules = import.meta.glob<{ default: GameModule }>("./*/index.ts", {
  eager: true,
});

// Per-game generated descriptions. Emitted by
// `pnpm -F @boardgames/server gen-descriptions`. Absent for homebrew games
// (bggId: 0) and any game that hasn't been run through the pipeline yet —
// those fall back to `bgg.description` repeated across all three slots.
const descriptionModules = import.meta.glob<{ descriptions: GameDescriptions }>(
  "./*/descriptions.generated.ts",
  { eager: true },
);

const descriptionsBySlug: Record<string, GameDescriptions> = {};
for (const [path, mod] of Object.entries(descriptionModules)) {
  const m = path.match(/^\.\/([^/]+)\/descriptions\.generated\.ts$/);
  if (m) descriptionsBySlug[m[1]] = mod.descriptions;
}

// Collect every game's thumbnail URL. Generated by `pnpm thumbnails`
// (scripts/optimize-thumbnails.mjs) from the original full-resolution PNGs;
// the script cuts each image from ~2.7 MB to ~40 KB. Pandemic ships at
// `assets/img/thumbnail.webp`; everyone else uses `assets/thumbnail.webp`.
const thumbnailModules = import.meta.glob<string>(
  ["./*/assets/thumbnail.webp", "./*/assets/img/thumbnail.webp"],
  { eager: true, query: "?url", import: "default" },
);

const thumbnailBySlug: Record<string, string> = {};
for (const [path, url] of Object.entries(thumbnailModules)) {
  const m = path.match(/^\.\/([^/]+)\/assets\//);
  if (m) thumbnailBySlug[m[1]] = url;
}

export const games: GameDefinition[] = Object.values(modules)
  .map((m): GameDefinition => {
    const slug = m.default.slug;
    const snapshotEntry = bggSnapshot[slug];
    if (!snapshotEntry) {
      throw new Error(
        `[registry] No BGG snapshot entry for slug "${slug}". ` +
          `Run \`pnpm bgg-sync\` to refresh packages/core/src/bgg/snapshot.json.`,
      );
    }
    // Shallow-merge per-game overrides on top of the BGG snapshot. This is
    // how each game patches BGG inaccuracies (wrong player count, missing
    // suggested age, etc.) without re-fetching from BGG. `bggOverrides.description`
    // is honored downstream too — it short-circuits the three-length
    // descriptions block below.
    const bgg = {
      ...snapshotEntry,
      ...(m.default.bggOverrides ?? {}),
    };
    // Three-length description resolution. Precedence (highest wins):
    //   1. `bggOverrides.description` — per-game manual escape hatch. Applies
    //      to all three variants uniformly (the human edit is authoritative).
    //   2. Generated `descriptions.generated.ts` — from the gen-descriptions
    //      pipeline; each variant char-budgeted to its target surface.
    //   3. `bgg.description` — raw BGG fallback, repeated. Ensures every game
    //      ships *something* even without a generated file.
    const manualOverride = m.default.bggOverrides?.description;
    const descriptions: GameDescriptions = manualOverride
      ? { tight: manualOverride, default: manualOverride, loose: manualOverride }
      : (descriptionsBySlug[slug] ?? {
          tight: bgg.description,
          default: bgg.description,
          loose: bgg.description,
        });
    return {
      ...m.default,
      bgg,
      descriptions,
      title: m.default.displayTitle ?? bgg.name,
      thumbnail: thumbnailBySlug[slug] ?? placeholderThumbnail,
    };
  })
  .sort((a, b) => a.title.localeCompare(b.title));

/**
 * Min/max `averageWeight` across the registry — used by `BggInline` to
 * normalize the complexity bar so the lightest game in the catalog reads as
 * empty and the heaviest reads as full. Recomputed once at module load.
 */
export const weightStats: { min: number; max: number } = (() => {
  const weights = games
    .map((g) => g.bgg.averageWeight)
    .filter((w): w is number => w !== null && w > 0);
  if (weights.length === 0) return { min: 1, max: 5 };
  return { min: Math.min(...weights), max: Math.max(...weights) };
})();
