import type { BggGame } from "@boardgames/core/bgg";
import type { ComponentType, LazyExoticComponent } from "react";

export type { BggGame };

/**
 * Which side of the shared shell session a game's playable component
 * is currently rendering for. The same component renders both routes —
 * `<MyGame source="solo" />` for `/play/:slug/solo` and
 * `<MyGame source="mp" />` for `/play/:slug/mp/play/:roomCode` — and
 * the component dispatches internally to pick the right setup / board
 * / game-over surface. Keeping it in one file per game keeps the
 * shared action handlers and view→state helpers in one place.
 */
export type GameSource = "solo" | "mp";

/** Props every playable game component receives from the shell routes. */
export type GameComponentProps = { source: GameSource };

/**
 * Game-specific lobby-config component. Mounted inside `<LobbyRoute>`
 * when the game declares a `lobbyConfigComponent`. The component owns
 * its own UI state and reports the current config via `onChange`; the
 * lobby route holds that value and passes it to `mp.startRoom(config)`
 * when the host hits Start. Initial value comes from `defaultMpConfig`
 * on the same `GameDefinition`.
 *
 * Example — Pandemic's difficulty picker is a `LobbyConfigProps`
 * component that renders three Chip buttons and calls
 * `onChange({ difficulty })` when one is clicked.
 */
export type LobbyConfigProps = {
  value: unknown;
  onChange: (config: unknown) => void;
};

/**
 * Replay viewer component shared by the match-history and tournament
 * routes. Each game's log shape is distinct (TournamentGameLog,
 * EKGameReplayLog, …) so we type-erase to `unknown` at the boundary
 * and let the component cast internally to its concrete type.
 *
 * `onBack` is the route-supplied "exit replay" hook — used by games
 * that want an in-component "back" affordance. Replays opened via the
 * Layout's top-nav back button work without it (they navigate out of
 * the route entirely), so it stays optional.
 */
export type ReplayProps = {
  game: unknown;
  onBack?: () => void;
};

/**
 * Three length variants of a game's description, generated by the
 * `gen-descriptions` pipeline and committed per-game as
 * `descriptions.generated.ts`. Each surface picks the variant that fits its
 * truncation budget:
 *   - `tight`  → reserved for future compact / small-card surfaces (~140 chars).
 *   - `default` → carousel card (~240 chars, fits `line-clamp-7` even at the
 *      smallest non-compact card width).
 *   - `loose`  → catalog grid card with `line-clamp-6 text-sm` (~360 chars).
 *
 * If a game has `bggOverrides.description` set in its `index.ts`, that string
 * replaces all three variants — manual edit wins over generated content.
 * Games without a generated file fall back to repeating `bgg.description`
 * across all three slots.
 */
export type GameDescriptions = {
  tight: string;
  default: string;
  loose: string;
};

/**
 * Membership in a "family" of related games — different editions, reskins,
 * or close-cousin sequels (UNO Classic / Flip / Show 'Em No Mercy; Brass:
 * Birmingham / Lancashire / Pittsburgh; Gloomhaven / Frosthaven / JotL).
 *
 * Grouping is purely a presentation concern: the gallery, inventory grid, and
 * RSVP carousel collapse families into one tile to reduce visual clutter,
 * while every server-bound payload (votes, RSVPs, bringing assignments,
 * top-5) remains keyed by individual slug.
 */
export type GameFamily = {
  /** Shared id — same string for every member of one family. */
  id: string;
  /** Marks the canonical (representative) member. Exactly one per family
   * should set this; if none does, the first member by registry order wins. */
  canonical?: boolean;
  /** Optional family display name. Set on the canonical member when the
   * family's name should differ from the canonical's title (e.g. canonical
   * "Brass: Birmingham" → family "Brass"). When omitted, the family is
   * displayed as the canonical's title. */
  name?: string;
  /** Human-readable variant label, e.g. "Classic", "Flip", "Jaws of the Lion".
   * Used for chip labels in the carousel and inventory headers. */
  variant: string;
};

export interface GameDefinition {
  slug: string;
  /**
   * Resolved display name. Comes from the game's `displayTitle` override if
   * set, otherwise from `bgg.name`. Hydrated by the registry — never declared
   * by individual games.
   */
  title: string;
  /** BoardGameGeek XML API2 ID — the catalog primary key. `0` for homebrew. */
  bggId: number;
  /**
   * BGG metadata. Hydrated by the registry from
   * `@boardgames/core/bgg`'s bundled snapshot — never imported per game.
   */
  bgg: BggGame;
  /**
   * Three-length description set. Hydrated by the registry from the per-game
   * `descriptions.generated.ts` file when present, otherwise filled with
   * `bgg.description` repeated across all three slots, or `bggOverrides.description`
   * applied uniformly if the per-game escape hatch is set. Never declared by
   * individual games directly.
   */
  descriptions: GameDescriptions;
  /**
   * Imported thumbnail asset URL. Attached by the registry from the game's
   * `assets/thumbnail.png` when present, or a shared placeholder when absent —
   * never imported directly from a game's `index.ts`.
   */
  thumbnail: string;
  /** Dominant accent color extracted at build time from the thumbnail. */
  accentHex: string;
  /** Optional full-page backdrop for the game's own screens. */
  backgroundImage?: string;
  /** Online-playable component. Omit for catalog-only games. */
  component?: LazyExoticComponent<ComponentType<GameComponentProps>>;
  /** Multiplayer architecture for the playable component. */
  mode?: "remote" | "local";
  /** Label for the solo/AI button on the mode-picker (e.g. "Play vs AI", "Trainer"). */
  soloLabel?: string;
  /** Whether the game has a match history screen accessible from the mode-picker. */
  hasMatchHistory?: boolean;
  /** Whether the game has a tournament screen accessible from the mode-picker. */
  hasTournament?: boolean;
  /** AI strategies for the tournament grid. Required when `hasTournament` is true. */
  tournamentStrategies?: { id: string; label: string }[];
  /** Whether to show average score diff in tournament grid cells (default true). */
  tournamentShowScoreDiff?: boolean;
  /** URL to a PDF file with the game rules, shown from the mode-picker. */
  rulesUrl?: string;
  /** Optional family membership for visual grouping in browse views. */
  family?: GameFamily;
  /**
   * Optional game-specific replay component, used by the match-history
   * and tournament-detail routes to render a single game log inline.
   * The log shape is typed `unknown` at the boundary; each game's
   * component casts to its concrete log type internally.
   */
  replayComponent?: LazyExoticComponent<ComponentType<ReplayProps>>;
  /**
   * Maps an AI strategy / engine id (the strings recorded in match logs)
   * to a human label for the match-history table. Defaults to the
   * identity function when omitted.
   */
  matchHistoryLabelResolver?: (engineId: string) => string;
  /**
   * Game-specific lobby-config UI rendered inside the lobby route.
   * Pandemic's difficulty picker is the canonical example. Omit for
   * games whose mp lobby has no extra controls.
   */
  lobbyConfigComponent?: LazyExoticComponent<ComponentType<LobbyConfigProps>>;
  /**
   * Initial mp config sent to `mp.startRoom` when the host starts the
   * game. Set when the game has constant config (Sky Team's scenarioId)
   * or when `lobbyConfigComponent` needs an initial value.
   */
  defaultMpConfig?: unknown;
  /**
   * Convert a single tournament game log into its human-readable form
   * for the "Download all logs (ZIP)" button on `<TournamentMatchHistory>`.
   * Most games leave this undefined; Lost Cities supplies one because
   * the raw protocol log is unreadable to humans.
   */
  tournamentExportLogFn?: (game: unknown) => unknown;
  /**
   * Optional override for the `/play/:slug/match-history` route. Set
   * games with non-standard history surfaces — e.g. Set has both a
   * client-side trainer history AND a server PvP history and renders
   * them as tabs. Receives an `onBack` callback wired to the parent
   * route navigation. When omitted, the route renders the generic
   * `<MatchHistory>` component plus the game's `matchHistoryLabelResolver`.
   */
  matchHistoryComponent?: LazyExoticComponent<ComponentType<{ onBack: () => void }>>;
}

/**
 * Shape exported by each game's `index.ts`. The registry attaches:
 *   - `thumbnail`: from `assets/thumbnail.webp` (so a missing image can't
 *     break the build).
 *   - `bgg`: from the bundled BGG snapshot (`@boardgames/core/bgg`), keyed
 *     by slug.
 *   - `title`: resolved as `displayTitle ?? bgg.name`.
 *
 * Per-game files therefore declare only `slug`, `bggId`, `accentHex`, and
 * the optional override / behavior fields below.
 */
export type GameModule = Omit<GameDefinition, "thumbnail" | "bgg" | "title" | "descriptions"> & {
  /**
   * Optional title override. Set this when BGG's name is wrong, awkward, or
   * too verbose for the UI (e.g. "7 Wonders" instead of
   * "7 Wonders (Second Edition)"). Otherwise the registry uses `bgg.name`.
   */
  displayTitle?: string;
  /**
   * Per-field overrides on top of the BGG snapshot. Use this to fix BGG
   * inaccuracies or fill in missing data. The registry shallow-merges these
   * over `bggSnapshot[slug]` at build time, so consumers always see the
   * patched values via `game.bgg.*`.
   *
   * Example — BGG says "Best with 4" but our group always plays 5-player
   * variant rules well: `bggOverrides: { bestPlayerCount: 5 }`.
   *
   * Nested objects are replaced wholesale, not deep-merged.
   */
  bggOverrides?: Partial<BggGame>;
};
