import type { BggGame } from "@boardgames/core/bgg";
import type { ComponentType, LazyExoticComponent } from "react";

export type { BggGame };

/**
 * Which side of the shared shell session a game's playable component
 * is currently rendering for. The same component renders both routes —
 * `<MyGame source="solo" />` for `/play/:slug/solo` and
 * `<MyGame source="mp" />` for `/play/:slug/mp/play/:roomCode` — and
 * the component dispatches internally to pick the right setup / board
 * / game-over surface. Keeping it in one file per game keeps the
 * shared action handlers and view→state helpers in one place.
 */
export type GameSource = "solo" | "mp";

/** Props every playable game component receives from the shell routes. */
export type GameComponentProps = { source: GameSource };

/**
 * Game-specific lobby-config component. Mounted inside `<LobbyRoute>`
 * when the game declares a `lobbyConfigComponent`. The component owns
 * its own UI state and reports the current config via `onChange`; the
 * lobby route holds that value and passes it to `mp.startRoom(config)`
 * when the host hits Start. Initial value comes from `defaultMpConfig`
 * on the same `PlayableGame`.
 *
 * Example — Pandemic's difficulty picker is a `LobbyConfigProps`
 * component that renders three Chip buttons and calls
 * `onChange({ difficulty })` when one is clicked.
 */
export type LobbyConfigProps = {
  value: unknown;
  onChange: (config: unknown) => void;
  /**
   * Whether the local viewer is the room host. Most config components
   * don't care — the lobby route only sends the host's `config` to the
   * server on Start — but games whose config is large or interactive
   * (Sky Team's scenario picker) want to render an editable surface for
   * the host and a passive "host is choosing" placeholder for everyone
   * else, since the value never syncs across seats.
   */
  isHost?: boolean;
};

/**
 * Replay viewer component shared by the match-history and tournament
 * routes. Each game's log shape is distinct (TournamentGameLog,
 * EKGameReplayLog, …) so we type-erase to `unknown` at the boundary
 * and let the component cast internally to its concrete type.
 *
 * `onBack` is the route-supplied "exit replay" hook — used by games
 * that want an in-component "back" affordance. Replays opened via the
 * Layout's top-nav back button work without it (they navigate out of
 * the route entirely), so it stays optional.
 */
export type ReplayProps = {
  game: unknown;
  onBack?: () => void;
};

/**
 * Three length variants of a game's description, generated by the
 * `gen-descriptions` pipeline and committed per-game as
 * `descriptions.generated.ts`. Each surface picks the variant that fits its
 * truncation budget:
 *   - `tight`  → reserved for future compact / small-card surfaces (~140 chars).
 *   - `default` → carousel card (~240 chars, fits `line-clamp-7` even at the
 *      smallest non-compact card width).
 *   - `loose`  → catalog grid card with `line-clamp-6 text-sm` (~360 chars).
 *
 * If a catalog entry has `bggOverrides.description` set, that string replaces
 * all three variants — manual edit wins over generated content. Games without
 * a generated file fall back to repeating `bgg.description` across all three
 * slots.
 */
export type GameDescriptions = {
  tight: string;
  default: string;
  loose: string;
};

/**
 * Membership in a "family" of related games — different editions, reskins,
 * or close-cousin sequels (UNO Classic / Flip / Show 'Em No Mercy; Brass:
 * Birmingham / Lancashire / Pittsburgh; Gloomhaven / Frosthaven / JotL).
 *
 * Grouping is purely a presentation concern: the gallery, inventory grid, and
 * RSVP carousel collapse families into one tile to reduce visual clutter,
 * while every server-bound payload (votes, RSVPs, bringing assignments,
 * top-5) remains keyed by individual slug.
 */
export type GameFamily = {
  /** Shared id — same string for every member of one family. */
  id: string;
  /** Marks the canonical (representative) member. Exactly one per family
   * should set this; if none does, the first member by registry order wins. */
  canonical?: boolean;
  /** Optional family display name. Set on the canonical member when the
   * family's name should differ from the canonical's title (e.g. canonical
   * "Brass: Birmingham" → family "Brass"). When omitted, the family is
   * displayed as the canonical's title. */
  name?: string;
  /** Human-readable variant label, e.g. "Classic", "Flip", "Jaws of the Lion".
   * Used for chip labels in the carousel and inventory headers. */
  variant: string;
};

// ── Resolved (registry-output) shape ──────────────────────────────────
//
// `GameDefinition` is a discriminated union on `kind`:
//   - `"catalog"`  — entry exists only in `catalog.json`. Browse-only;
//                    no playable component. UI surfaces a "coming soon"
//                    affordance and the `/play/:slug` route 404s.
//   - `"playable"` — entry in `catalog.json` *and* a matching
//                    `<slug>/index.ts` exporting a `PlayableModule`.
//                    Component is guaranteed non-null once narrowed.
//
// All resolved fields below are hydrated by `registry.ts` — never
// declared per-game. The registry merges:
//   1. Per-slug catalog entry (slug, bggId, accentHex, family,
//      displayTitle, bggOverrides)
//   2. BGG snapshot bundled in `@boardgames/core/bgg`
//   3. Per-slug `descriptions.generated.ts` when present
//   4. Per-slug `assets/thumbnail.webp` (or placeholder)
//   5. For playable slugs: the `<slug>/index.ts` module

/** Fields shared by every entry, regardless of kind. */
interface GameBase {
  slug: string;
  /**
   * Resolved display name. Comes from the catalog entry's `displayTitle`
   * override if set, otherwise from `bgg.name`. Hydrated by the registry.
   */
  title: string;
  /** BoardGameGeek XML API2 ID — the catalog primary key. `0` for homebrew. */
  bggId: number;
  /**
   * BGG metadata. Hydrated by the registry from `@boardgames/core/bgg`'s
   * bundled snapshot and shallow-merged with the catalog's `bggOverrides`.
   */
  bgg: BggGame;
  /** Three-length description set. Hydrated by the registry. */
  descriptions: GameDescriptions;
  /**
   * Imported thumbnail asset URL. Attached by the registry from the game's
   * `assets/thumbnail.webp` when present, or a shared placeholder when absent.
   */
  thumbnail: string;
  /** Dominant accent color extracted at build time from the thumbnail. */
  accentHex: string;
  /** Optional family membership for visual grouping in browse views. */
  family?: GameFamily;
  /**
   * Recently-added flag. Drives the "New" highlighter (cyan-fiery-blue
   * border + badge) on the game-night carousel, which takes precedence
   * over the "Best at N" headcount treatment. Set per-entry in
   * `catalog.json`; clear it once the game stops being a fresh arrival.
   */
  isNew?: boolean;
}

/** A browse-only catalog entry — no playable surface. */
export interface CatalogGame extends GameBase {
  kind: "catalog";
}

/**
 * A playable game — `kind === "playable"` narrows TypeScript so that
 * `component`, `mode`, and the playable extras are all reachable without
 * optional chaining or non-null assertions.
 */
export interface PlayableGame extends GameBase {
  kind: "playable";
  /** Online-playable component. */
  component: LazyExoticComponent<ComponentType<GameComponentProps>>;
  /**
   * Vestigial. Every game is server-authoritative today, so this is `"remote"`
   * for all of them and nothing branches on it at runtime. Kept only for a
   * hypothetical future client-only game — do NOT infer client-side execution
   * from `"local"`. (Game machines + AI always run on the server; see
   * `useGameShell` / `packages/server/src/sessions/manager.ts`.)
   */
  mode: "remote" | "local";
  /**
   * Companion-device screen (e.g. the D&D beamer/TTS display). When set, the
   * mode picker shows this instead of the Multiplayer card and routes to
   * `/play/:slug/companion`, which renders the component full-screen. The
   * component attaches to the primary device's session on its own.
   */
  companion?: {
    label: string;
    description: string;
    component: LazyExoticComponent<ComponentType>;
  };
  /** Optional full-page backdrop for the game's own screens. */
  backgroundImage?: string;
  /** Label for the solo/AI button on the mode-picker (e.g. "Play vs AI", "Trainer"). */
  soloLabel?: string;
  /** Whether the game has a match history screen accessible from the mode-picker. */
  hasMatchHistory?: boolean;
  /** Whether the game has a tournament screen accessible from the mode-picker. */
  hasTournament?: boolean;
  /** AI strategies for the tournament grid. Required when `hasTournament` is true. */
  tournamentStrategies?: { id: string; label: string }[];
  /** Whether to show average score diff in tournament grid cells (default true). */
  tournamentShowScoreDiff?: boolean;
  /**
   * Rules document(s) shown from the mode-picker. A plain string is a single
   * PDF; an array opens the viewer with a tab bar (one tab per booklet). Used
   * by the rare games that ship more than one rulebook — e.g. Sky Team's
   * separate Rules and Flight Log.
   */
  rulesUrl?: string | { label: string; url: string }[];
  /**
   * Optional game-specific replay component, used by the match-history
   * and tournament-detail routes to render a single game log inline.
   * The log shape is typed `unknown` at the boundary; each game's
   * component casts to its concrete log type internally.
   */
  replayComponent?: LazyExoticComponent<ComponentType<ReplayProps>>;
  /**
   * Maps an AI strategy / engine id (the strings recorded in match logs)
   * to a human label for the match-history table. Defaults to the
   * identity function when omitted.
   */
  matchHistoryLabelResolver?: (engineId: string) => string;
  /**
   * Column header used in the match-history table for the AI-engine /
   * second-seat column. Defaults to "Opponent". Co-op games override
   * this to something accurate — Sky Team uses "AI Co-pilot" because
   * "Opponent" implies a versus dynamic that doesn't exist when the
   * team wins or loses together.
   */
  matchHistoryOpponentLabel?: string;
  /**
   * Game-specific lobby-config UI rendered inside the lobby route.
   * Pandemic's difficulty picker is the canonical example. Omit for
   * games whose mp lobby has no extra controls.
   */
  lobbyConfigComponent?: LazyExoticComponent<ComponentType<LobbyConfigProps>>;
  /**
   * Lobby layout variant. `"wide"` swaps the centered scrolling column
   * for a full-viewport, non-scrolling screen that mirrors the game's
   * solo setup screen: a compact room/crew/launch strip on top with the
   * `lobbyConfigComponent` filling all remaining height. Opt in when the
   * lobby config is a large surface (Sky Team's destination gallery);
   * omit for small configs like Pandemic's difficulty chips.
   */
  lobbyLayout?: "wide";
  /**
   * Initial mp config sent to `mp.startRoom` when the host starts the
   * game. Set when the game has constant config (Sky Team's scenarioId)
   * or when `lobbyConfigComponent` needs an initial value.
   */
  defaultMpConfig?: unknown;
  /**
   * Convert a single tournament game log into its human-readable form
   * for the "Download all logs (ZIP)" button on `<TournamentMatchHistory>`.
   * Most games leave this undefined; Lost Cities supplies one because
   * the raw protocol log is unreadable to humans.
   */
  tournamentExportLogFn?: (game: unknown) => unknown;
  /**
   * Optional override for the `/play/:slug/match-history` route. Set
   * games with non-standard history surfaces — e.g. Set has both a
   * client-side trainer history AND a server PvP history and renders
   * them as tabs. Receives an `onBack` callback wired to the parent
   * route navigation. When omitted, the route renders the generic
   * `<MatchHistory>` component plus the game's `matchHistoryLabelResolver`.
   */
  matchHistoryComponent?: LazyExoticComponent<ComponentType<{ onBack: () => void }>>;
}

export type GameDefinition = CatalogGame | PlayableGame;

/**
 * Convenience predicate — narrows a `GameDefinition` to `PlayableGame`.
 * Most call sites can compare `def.kind === "playable"` inline (which
 * TypeScript narrows for free), but using the predicate inside `.filter`
 * gives correctly typed results without a second pass.
 *
 * @example
 * const playable: PlayableGame[] = games.filter(isPlayable);
 */
export function isPlayable(def: GameDefinition): def is PlayableGame {
  return def.kind === "playable";
}

// ── Source shapes (what lives on disk) ───────────────────────────────

/**
 * Raw shape of a single entry in `catalog.json`. The catalog is the
 * single source of truth for browse-only metadata: every game in the
 * registry (catalog AND playable) has an entry here. Playable games
 * additionally export a `PlayableModule` from `<slug>/index.ts`.
 *
 * The catalog is loaded eagerly at registry bootstrap. To keep the file
 * diff-friendly, entries are sorted alphabetically by slug.
 */
export type CatalogEntry = {
  /** Folder name under `packages/web/src/games/`. Lowercase-kebab. */
  slug: string;
  /** BoardGameGeek XML API2 ID — the catalog primary key. `0` for homebrew. */
  bggId: number;
  /** Dominant accent color extracted by `pnpm extract-accents`. */
  accentHex: string;
  /** Optional family membership for visual grouping in browse views. */
  family?: GameFamily;
  /**
   * Recently-added flag. When true the game-night carousel renders the
   * "New" highlighter (cyan-fiery-blue border + badge) and it takes
   * precedence over the "Best at N" headcount treatment.
   */
  isNew?: boolean;
  /**
   * Optional title override. Set this when BGG's name is wrong, awkward, or
   * too verbose for the UI (e.g. "7 Wonders" instead of
   * "7 Wonders (Second Edition)"). Otherwise the registry uses `bgg.name`.
   */
  displayTitle?: string;
  /**
   * Per-field overrides on top of the BGG snapshot. Use this to fix BGG
   * inaccuracies or fill in missing data. The registry shallow-merges these
   * over `bggSnapshot[slug]` at registry-build time so consumers always see
   * the patched values via `game.bgg.*`.
   *
   * `bggOverrides.description` is special-cased downstream: when set, it
   * replaces all three `GameDescriptions` variants uniformly.
   *
   * Nested objects are replaced wholesale, not deep-merged.
   */
  bggOverrides?: Partial<BggGame>;
};

/**
 * Shape exported by a playable game's `<slug>/index.ts`. Only the
 * playable-specific extras — base catalog fields live in `catalog.json`.
 *
 * The folder name *is* the slug; no need to repeat it here. Registry
 * looks up the matching catalog entry by folder path.
 */
export type PlayableModule = Omit<PlayableGame, "kind" | keyof GameBase>;
