// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug stadt-land-vollpfosten-christmas
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Christmas prompts turn family word recall into a speed duel, using hand management as letter cards hit the table before better answers arrive.",
  default:
    "Christmas categories turn Stadt-Land-Fluss recall into a noisy race where fast answers beat perfect ones. Hand management drives each round as players shed letter cards by naming matching words. Emptying a hand wins, but action cards and counters can refill it.",
  loose:
    "Christmas categories turn Stadt-Land-Fluss recall into a noisy race where a perfect answer matters less than saying it first. Hand management drives each round, as players shed letter cards by naming words that match the revealed prompt. A round ends when one hand is empty, unless counters and penalties refill it. The Vollpfosten card works as both joker and ambush, punishing a rival who thought “Affe” was safe.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:47.952Z",
  model: "gpt-5.5",
  durationMs: 44374,
  sources: [
    "https://www.denkriesen.com/products/stadt-land-vollpfosten-das-kartenspiel-christmas-edition",
    "https://www.brettspielversand.de/mediafiles/spieleanleitungen/denkriesen/254-0015_StadtLandVollpfosten_Classic_Anleitung.pdf",
  ],
} as const;
