// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug stadt-land-vollpfosten-christmas
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Fast party word game where players race to play starting-letter cards for Christmas-flavored categories.",
  default:
    "Fast party word card game in the Stadt-Land-Fluss mold. Each round, a category is read, everyone races to play a matching starting-letter card and say a valid word. The fastest correct answer discards; empty a hand first to win the round, usually racing to three round wins.",
  loose:
    "Fast party word card game in the Stadt-Land-Fluss mold, with Christmas categories and a race to shed letter cards. Each round, a category card is read, everyone slaps down a matching starting-letter card and says a valid word, and the fastest correct answer discards. A wrong word draws a penalty card, and the first hand emptied wins the round. Wild cards can stand in for any letter or counter another answer, while action cards pass hands around the table.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:13.404Z",
  model: "gpt-5.5",
  durationMs: 22475,
  sources: [
    "https://www.denkriesen.com/products/stadt-land-vollpfosten-das-kartenspiel-christmas-edition",
    "https://www.brettspielversand.de/mediafiles/spieleanleitungen/denkriesen/254-0015_StadtLandVollpfosten_Classic_Anleitung.pdf",
    "https://www.roterdorn.de/spiel/stadt-land-vollpfosten-das-kartenspiel-rotlicht-edition/",
  ],
} as const;
