// Cyberpunk — indigo-violet surfaces, hot-pink accent, circuit pattern,
// zero radii, monospace type, scanline ambient.
export default {
  key: "cyberpunk",
  label: "Cyberpunk",
  order: 7,
  config: {
    preset: "cyberpunk",
    surface950: "#0a0a0f",
    surface900: "#10101a",
    surface800: "#1a1a2e",
    surface700: "#24243e",
    surface600: "#2a2a48",
    fgPrimary: "#f0e6ff",
    fgSecondary: "#9985b5",
    fgMuted: "#756191",
    fgDisabled: "#4b3d5e",
    accent: "#ff2d95",
    neonCyan: "#00e5ff",
    neonPurple: "#b366ff",
    neonPink: "#ff5aaf",
    pattern: "circuit",
    patternColor: "#ff2d95",
    patternOpacity: 0.12,
    wallpaper: false,
    radiusCard: 0,
    radiusUi: 0,
    selectionStyle: "glow",
    fontFamily: "jetbrains",
    baseFontSize: 16,
    ambientMode: "auto",
    ambientEffect: "scanlines",
    accentMode: "custom",
  },
} as const;
