// Dawn — the lightest-viable dark preset: warm-tinted surfaces around Nord
// brightness, high-contrast warm foregrounds, WhatsApp-green accent family.
export default {
  key: "dawn",
  label: "Dawn",
  order: 3,
  config: {
    preset: "dawn",
    surface950: "#33302c",
    surface900: "#3c3833",
    surface800: "#46413b",
    surface700: "#514b44",
    surface600: "#5d564e",
    fgPrimary: "#f2ede4",
    fgSecondary: "#bdb5a8",
    fgMuted: "#948c7f",
    fgDisabled: "#6e675c",
    accent: "#00a884",
    neonCyan: "#53bdeb",
    neonPurple: "#06cf9c",
    neonPink: "#e6a05c",
    pattern: "doodles",
    patternColor: "#c8b89a",
    patternOpacity: 0.12,
    wallpaper: false,
    radiusCard: 8,
    radiusUi: 8,
    avatarShape: "circle",
    selectionStyle: "bar",
    fontFamily: "inter",
    baseFontSize: 16,
    ambientMode: "auto",
    ambientEffect: null,
    accentMode: "custom",
  },
} as const;
