// Ember — warm charcoal surfaces, amber-gold accent, crosshatch pattern.
// fontFamily stays "inter" for now; a serif option may come later.
export default {
  key: "ember",
  label: "Ember",
  order: 5,
  config: {
    preset: "ember",
    surface950: "#1a1816",
    surface900: "#211f1c",
    surface800: "#2e2b27",
    surface700: "#3a3632",
    surface600: "#46423d",
    fgPrimary: "#ede8e0",
    fgSecondary: "#9e958a",
    fgMuted: "#77716a",
    fgDisabled: "#524d47",
    accent: "#c89b5e",
    neonCyan: "#8ab4d6",
    neonPurple: "#dab478",
    neonPink: "#e0a17a",
    pattern: "crosshatch",
    patternColor: "#5a4a35",
    patternOpacity: 0.25,
    wallpaper: false,
    radiusCard: 6,
    radiusUi: 6,
    selectionStyle: "underline",
    fontFamily: "inter",
    baseFontSize: 16,
    ambientMode: "auto",
    ambientEffect: "embers",
    accentMode: "custom",
  },
} as const;
