// Nord — the classic arctic palette: polar-night surfaces, frost accent,
// aurora highlight trio, diamonds pattern.
export default {
  key: "nord",
  label: "Nord",
  order: 9,
  config: {
    preset: "nord",
    surface950: "#2e3440",
    surface900: "#3b4252",
    surface800: "#434c5e",
    surface700: "#4c566a",
    surface600: "#556076",
    fgPrimary: "#eceff4",
    fgSecondary: "#d8dee9",
    fgMuted: "#a0a8b8",
    fgDisabled: "#6f7889",
    accent: "#88c0d0",
    neonCyan: "#8fbcbb",
    neonPurple: "#b48ead",
    neonPink: "#81a1c1",
    pattern: "diamonds",
    patternColor: "#88c0d0",
    patternOpacity: 0.08,
    wallpaper: false,
    radiusCard: 10,
    radiusUi: 8,
    selectionStyle: "bar",
    fontFamily: "inter",
    baseFontSize: 16,
    ambientMode: "auto",
    ambientEffect: "aurora",
    accentMode: "custom",
  },
} as const;
