// Ocean — deep teal surfaces with a cyan accent family and a waves ambient.
export default {
  key: "ocean",
  label: "Ocean",
  order: 4,
  config: {
    preset: "ocean",
    surface950: "#071318",
    surface900: "#0c1e27",
    surface800: "#153040",
    surface700: "#1e3d50",
    surface600: "#2a4d63",
    fgPrimary: "#e2ecf0",
    fgSecondary: "#9ab3bd",
    fgMuted: "#6b8791",
    fgDisabled: "#49616c",
    accent: "#00bcd4",
    neonCyan: "#4dd0e1",
    neonPurple: "#26a69a",
    neonPink: "#80deea",
    pattern: "waves",
    patternColor: "#1a6070",
    patternOpacity: 0.35,
    wallpaper: false,
    radiusCard: 14,
    radiusUi: 12,
    avatarShape: "circle",
    selectionStyle: "fill",
    fontFamily: "inter",
    baseFontSize: 16,
    ambientMode: "auto",
    ambientEffect: "waves",
    accentMode: "custom",
  },
} as const;
