// Sakura — plum-dark surfaces, blossom-pink accent, petal pattern and ambient.
export default {
  key: "sakura",
  label: "Sakura",
  order: 8,
  config: {
    preset: "sakura",
    surface950: "#1a0a10",
    surface900: "#221018",
    surface800: "#301a24",
    surface700: "#3e2430",
    surface600: "#4c2e3c",
    fgPrimary: "#f5e0ea",
    fgSecondary: "#b08a9e",
    fgMuted: "#84627a",
    fgDisabled: "#543e4c",
    accent: "#e91e7a",
    neonCyan: "#f48fb1",
    neonPurple: "#ce93d8",
    neonPink: "#f54a96",
    pattern: "petals",
    patternColor: "#e91e7a",
    patternOpacity: 0.08,
    wallpaper: false,
    radiusCard: 16,
    radiusUi: 14,
    avatarShape: "circle",
    selectionStyle: "fill",
    fontFamily: "inter",
    baseFontSize: 16,
    ambientMode: "auto",
    ambientEffect: "petals",
    accentMode: "custom",
  },
} as const;
