// Terminal — pure black phosphor look: green accent, square corners, monospace.
export default {
  key: "terminal",
  label: "Terminal",
  order: 6,
  config: {
    preset: "terminal",
    surface950: "#000000",
    surface900: "#0a0a0a",
    surface800: "#1a1a1a",
    surface700: "#2a2a2a",
    surface600: "#3a3a3a",
    fgPrimary: "#ffffff",
    fgSecondary: "#cccccc",
    fgMuted: "#8d8d8d",
    fgDisabled: "#606060",
    accent: "#00ff88",
    neonCyan: "#66ccff",
    neonPurple: "#33ffaa",
    neonPink: "#99ffcc",
    pattern: "dotgrid",
    patternColor: "#00ff88",
    patternOpacity: 0.15,
    wallpaper: false,
    radiusCard: 2,
    radiusUi: 2,
    selectionStyle: "border",
    fontFamily: "jetbrains",
    baseFontSize: 15,
    ambientMode: "auto",
    ambientEffect: "matrix",
    accentMode: "custom",
  },
} as const;
