// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug bananagrams
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time word game where everyone races to rearrange letter tiles into their own crossword grid.",
  default:
    "Real-time word game where everyone races at once to build a private crossword from letter tiles. Use all your loose tiles, call “peel,” and everyone draws another; dump a bad tile to draw three. When the pool is nearly gone, the first valid full grid wins.",
  loose:
    "Real-time word game where everyone races at once to build a private crossword from letter tiles. Use all your loose tiles, call “peel,” and everyone draws another tile from the middle; dump a bad tile to draw three instead. When the shared pool runs low, the first player with a complete valid grid calls “bananas” and wins. The whole set fits in a banana-shaped cloth pouch, so the table is just loose tiles and scrambling hands.",
};

export const meta = {
  generatedAt: "2026-08-17T00:31:32.304Z",
  model: "gpt-5.5",
  durationMs: 8198,
  sources: [
    "https://bananagrams.com/blogs/news/how-to-play-bananagrams-instructions-for-getting-started",
    "https://bananagrams.com/pages/instructions",
    "https://zatu.com/bananagrams-review/",
  ],
} as const;
