// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug magic-the-gathering
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Collectible dueling card game where players play lands for mana, cast creatures and spells, and attack life totals.",
  default:
    "Collectible dueling card game where custom decks fight through lands, creatures, artifacts, and spells. On a turn you untap, draw, play a land, spend mana on cards from hand, and attack with creatures while opponents block or respond. Reduce every opponent to zero life, make them unable to draw, or satisfy a card’s win condition to win.",
  loose:
    "Collectible dueling card game where custom decks fight through lands, creatures, artifacts, and spells. On a turn you untap, draw, play a land, spend mana on cards from hand, and attack with creatures while opponents block or respond. Reduce every opponent to zero life, make them unable to draw, or satisfy a card’s win condition to win. The five mana colors give decks distinct table personalities, from blue counterspells to red burn.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:10.739Z",
  model: "gpt-5.5",
  durationMs: 14370,
  sources: [
    "https://magic.wizards.com/en/how-to-play",
    "https://magic.wizards.com/en/news/feature/original-magic-rulebook-2004-12-25",
  ],
} as const;
