// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug lovecraft-letter
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light deduction card game where players draw one, play one, and risk insanity checks for stronger card effects.",
  default:
    "Light deduction and push-your-luck card game using the Love Letter draw-one, play-one engine. On a turn, a player may check sanity, then draws a card and plays one for a guess, comparison, protection, swap, or knockout. Two sane tokens or three insane tokens win, unless Cthulhu triggers an instant win.",
  loose:
    "Light deduction and push-your-luck card game using the Love Letter draw-one, play-one engine. On a turn, a player with insane cards first flips cards for a sanity check, then draws a card and plays one for a guess, comparison, protection, swap, or knockout. Two sane round tokens or three insane round tokens win the game, unless Cthulhu triggers an instant win. The deluxe set uses tarot-sized sleeved cards, chunky sanity poker chips, and a magnetic book-style box.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:17.133Z",
  model: "gpt-5.5",
  durationMs: 23245,
  sources: [
    "https://www.tabletopgaming.co.uk/Reviews/lovecraft-letter-review/",
    "https://geekdad.com/2017/06/going-crazy-for-lovecraft-letter/",
    "https://www.boardseyeview.net/post/2017/11/03/lovecraft-letter",
  ],
} as const;
