// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug lovecraft-letter
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Forbidden powers tempt every draw-one, play-one decision, turning Love Letter’s hand management into a sanity check with teeth.",
  default:
    "Forbidden powers make every Love Letter decision a bargain with collapse. Hand management drives each round: draw one card, play one card, and risk insanity effects for stronger plays. Two sane tokens, three insane tokens, or Cthulhu’s insane effect can end the game.",
  loose:
    "Cosmic powers make every familiar Love Letter choice a bargain with collapse. Hand management drives each round: draw one card, play one card, and decide whether an insanity effect is worth the sanity check it triggers later. Two sane tokens, three insane tokens, or Cthulhu’s insane effect can end the game. The 25-card deck keeps eliminations sharp while tarot cards, sleeves, and heavy poker chips give the tiny system weight.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:03.956Z",
  model: "gpt-5.5",
  durationMs: 39497,
  sources: [
    "https://www.arkhamhorror.com/games/lovecraft-letter/",
    "https://www.ultraboardgames.com/lovecraft-letter/game-rules.php",
    "https://www.tabletopgaming.co.uk/reviews/lovecraft-letter-review/",
    "https://rolltoreview.com/lovecraft-letter-review/",
  ],
} as const;
