// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug lost-cities
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Every expedition starts in debt, and hand management turns each discard into a gift, a threat, or a delay tactic.",
  default:
    "Every expedition begins as a liability, so ambition feels dangerous from the first card. Hand management drives play through rising color columns and shared discard piles. The highest total after three rounds wins, unless wagers multiply a bad dig into a crater.",
  loose:
    "Every expedition begins as a liability, so ambition feels dangerous from the first card. Hand management drives play as players build rising color columns, discard to shared piles, and decide when a card is too useful to release. The highest total after three rounds wins, but wager cards can multiply a triumph or deepen a failed dig. A bare wager with no follow-up scores -40, a tiny warning sign in Knizia’s math.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:08.994Z",
  model: "gpt-5.5",
  durationMs: 58455,
  sources: [
    "https://www.thamesandkosmos.com/manuals/full/691821_LC_Card_Game.pdf",
    "https://www.gamespot.com/reviews/lost-cities-review/1900-6190397/",
  ],
} as const;
