// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug lost-cities
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Head-to-head hand-management card game where players start risky expeditions, lay rising-number cards, and manage discard piles.",
  default:
    "Head-to-head hand-management card game about funding expeditions in colored suits. On a turn, play one card to a rising-number expedition or discard it, then draw from the deck or a visible discard. Highest total after expedition costs and wagers wins.",
  loose:
    "Head-to-head hand-management card game about funding archaeological expeditions in colored suits. On a turn, play one card to an expedition in rising order or discard it to that color’s pile, then draw from the deck or a visible discard. Started expeditions cost 20 points before card values, wager cards multiply gains or losses, and the highest total after the final round wins. Much of the sting comes from discarding a card your rival can immediately grab.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:30.868Z",
  model: "gpt-5.5",
  durationMs: 37571,
  sources: [
    "https://www.thamesandkosmos.com/manuals/full/691820_lostcities2p_manual.pdf",
    "https://www.miniaturemarket.com/blog/lost-cities-the-original-card-game-review",
    "https://www.kosmos.de/de/lost-cities-das-duell_1694135_4002051694135",
  ],
} as const;
