"""numpy MLP (ReLU hidden layers, linear output) with Adam — the trainer core
for the Sensō value nets, and the exporter to the TS runtime format
(packages/core/src/games/senso-battle-for-japan/mcts/mlp.ts): int8 weights with
one scale per output row, base64-encoded, plus a fixture of (input, output)
pairs computed from the DEQUANTISED weights so the TS forward pass can be
pinned to it exactly.
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

import numpy as np


class Mlp:
    def __init__(self, sizes: list[int], seed: int = 1):
        rng = np.random.default_rng(seed)
        self.sizes = list(sizes)
        self.W = [rng.normal(0, np.sqrt(2 / sizes[i]), (sizes[i + 1], sizes[i])).astype(np.float64) for i in range(len(sizes) - 1)]
        self.b = [np.zeros(sizes[i + 1]) for i in range(len(sizes) - 1)]
        self._m = [np.zeros_like(w) for w in self.W] + [np.zeros_like(b) for b in self.b]
        self._v = [np.zeros_like(w) for w in self.W] + [np.zeros_like(b) for b in self.b]
        self._t = 0

    def zero_last(self) -> None:
        """Start as the identity on a skip connection: the output layer at zero."""
        self.W[-1][:] = 0
        self.b[-1][:] = 0

    def forward(self, X: np.ndarray, keep: bool = False):
        acts = [X]
        h = X
        L = len(self.W)
        for i in range(L):
            z = h @ self.W[i].T + self.b[i]
            h = z if i == L - 1 else np.maximum(z, 0)
            acts.append(h)
        if keep:
            self._acts = acts
        return h

    def backward(self, dout: np.ndarray):
        """dout: gradient of the loss w.r.t. the output (N, out). Returns grads (list W, list b)."""
        acts = self._acts
        gW = [None] * len(self.W)
        gb = [None] * len(self.b)
        d = dout
        for i in range(len(self.W) - 1, -1, -1):
            gW[i] = d.T @ acts[i]
            gb[i] = d.sum(axis=0)
            if i > 0:
                d = (d @ self.W[i]) * (acts[i] > 0)
        return gW, gb

    def adam(self, gW, gb, lr: float, l2: float = 0.0, b1: float = 0.9, b2: float = 0.999, eps: float = 1e-8):
        self._t += 1
        params = self.W + self.b
        grads = list(gW) + list(gb)
        for k, (p, g) in enumerate(zip(params, grads)):
            if k < len(self.W) and l2 > 0:
                g = g + l2 * p
            self._m[k] = b1 * self._m[k] + (1 - b1) * g
            self._v[k] = b2 * self._v[k] + (1 - b2) * g * g
            mh = self._m[k] / (1 - b1**self._t)
            vh = self._v[k] / (1 - b2**self._t)
            p -= lr * mh / (np.sqrt(vh) + eps)

    # ---- export -----------------------------------------------------------
    def quantize(self) -> dict:
        layers = []
        for W, b in zip(self.W, self.b):
            scale = np.maximum(np.abs(W).max(axis=1), 1e-12) / 127.0
            q = np.clip(np.round(W / scale[:, None]), -127, 127).astype(np.int8)
            layers.append({"w": base64.b64encode(q.tobytes()).decode("ascii"), "scale": [float(s) for s in scale], "b": [float(x) for x in b]})
        return {"sizes": self.sizes, "layers": layers}

    def dequantized(self) -> "Mlp":
        m = Mlp(self.sizes)
        for i, layer in enumerate(self.quantize()["layers"]):
            q = np.frombuffer(base64.b64decode(layer["w"]), dtype=np.int8).reshape(self.W[i].shape).astype(np.float64)
            m.W[i] = q * np.array(layer["scale"])[:, None]
            m.b[i] = np.array(layer["b"])
        return m

    def export_ts(self, path: str | Path, name: str, note: str, fixture_inputs: np.ndarray | None = None, fixture_path: str | Path | None = None) -> None:
        q = self.quantize()
        body = (
            f"// {note}\n"
            "// Generated by scripts/senso-train (int8 weights, one scale per output row). Do not edit by hand.\n"
            'import { decodeMlp, type MlpModel } from "./mlp";\n\n'
            f"export const {name}: MlpModel = decodeMlp({json.dumps(q, separators=(',', ':'))});\n"
        )
        Path(path).write_text(body)
        if fixture_inputs is not None and fixture_path is not None:
            deq = self.dequantized()
            outs = deq.forward(fixture_inputs)
            Path(fixture_path).write_text(json.dumps({"model": q, "inputs": fixture_inputs.tolist(), "outputs": outs.tolist()}))
