// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug unstable-unicorns
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Take-that party card game where players race to fill a Stable with seven unicorns while Neighs and Downgrades wreck the competition.",
  default:
    "Take-that party card game about filling a Stable with unicorns while sabotaging everyone else's. On a turn, fire any Stable powers, draw one, play a card or draw again, then discard to seven. Anyone can Neigh a play as it happens, and the first Stable with seven unicorns wins.",
  loose:
    "Take-that party card game about filling a Stable with unicorns while sabotaging everyone else's. On a turn, fire any Stable powers, draw one, play a card or draw again, then discard to seven. Magical Unicorns carry powers, Upgrades and Downgrades buff or curse a Stable, and the first Stable with seven unicorns wins. Anyone can Neigh a play as it happens, a Neigh can be Neighed right back, and only a Super Neigh ends the war.",
};

export const meta = {
  generatedAt: "2026-09-14T12:36:39.000Z",
  model: "claude-opus-5 (simulated run — gateway throttled)",
  durationMs: 160204,
  sources: [
    "http://boardgame.bg/unstable%20unicorns%20rules.pdf",
    "https://www.ultraboardgames.com/unstable-unicorns/game-rules.php",
    "https://en.wikipedia.org/wiki/Unstable_Unicorns",
    "https://everythingboardgames.com/2024/10/unstable-unicorns-review.html",
    "https://theboardgamecollection.com/unstable-unicorns-board-game-review/",
  ],
} as const;
