// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug war-with-the-evil-power-master
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative narrative card adventure where the table reads story cards, picks paths, and assigns crew to die-roll challenges.",
  default:
    "Cooperative narrative card adventure, closer to a sci-fi gamebook than a strategy game. Read a story card, choose a branch, then assign an active crew member to required or optional die-roll challenges. Wins boost the Signal Tracker toward the villain’s location; failures raise the EPM Meter, and the crew loses if it fills first.",
  loose:
    "Cooperative narrative card adventure, basically a sci-fi gamebook played from decks. Read a numbered story card, debate the branch, then pick an active crew member for any required or optional die-roll challenge. Wins raise the Signal Tracker or award DATA items; failures raise the EPM Meter as the ship jumps between planets. The 154 Story Cards and 158 DATA Cards drive the routes, and the crew wins by reaching the final showdown before the EPM Meter hits 25.",
};

export const meta = {
  generatedAt: "2026-08-17T00:32:05.848Z",
  model: "gpt-5.5",
  durationMs: 20658,
  sources: [
    "https://www.zmangames.com/game/choose-your-own-adventure-war-with-the-evil-power-master/",
    "https://cdn.svc.asmodee.net/production-zman/uploads/2024/10/cyoa2_rulebook_web.pdf",
    "https://www.rpg.net/reviews/archive/18/18287.phtml",
  ],
} as const;
