// GENERATED by scripts/gen-cpp-hunger.ts — DO NOT EDIT. Run `pnpm gen-cpp-hunger`.
#include "hg/data.hpp"

namespace hg {

// Physical Bonus tokens, in JavaScript default sort order of their ids.
const BonusDef BONUS_DEFS[NUM_BONUS] = {
  {"discard-draw#0", 4, -1, 0},
  {"discard-draw#1", 4, -1, 0},
  {"draw#0", 5, -1, 0},
  {"draw#1", 5, -1, 0},
  {"extra-hunt#0", 3, -1, 0},
  {"extra-hunt#1", 3, -1, 0},
  {"human-choice#0", 1, -1, 0},
  {"military#0", 0, 2, 0},
  {"mission#0", 6, -1, 0},
  {"mission#1", 6, -1, 0},
  {"noble#0", 0, 3, 0},
  {"parasol#0", 7, -1, 0},
  {"parasol#1", 7, -1, 0},
  {"parasol#2", 7, -1, 0},
  {"religious#0", 0, 1, 0},
  {"speed-1#0", 2, -1, 1},
  {"speed-1#1", 2, -1, 1},
  {"speed-2#0", 2, -1, 2},
  {"speed-2#1", 2, -1, 2},
  {"velvet#0", 8, -1, 0},
  {"velvet#1", 8, -1, 0},
  {"velvet#2", 8, -1, 0},
  {"velvet#3", 8, -1, 0},
  {"velvet#4", 8, -1, 0},
  {"velvet#5", 8, -1, 0},
  {"villager#0", 0, 0, 0},
};

// expand(BONUS_TOKENS)
const uint8_t BONUS_EXPAND[NUM_BONUS] = {
  8, 9, 11, 12, 13, 25, 14, 7, 10, 6, 19, 20, 21, 22, 23, 24,
  4, 5, 0, 1, 2, 3, 15, 16, 17, 18,
};

}  // namespace hg
