// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug upwords
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Familiar crossword play turns vertical through tile placement, as old words become new words under rising stacks.",
  default:
    "Familiar crossword play turns vertical as letters climb over earlier words. Tile placement drives each turn: letters go across, down, or onto existing tiles to change a word. Highest score wins, and stacked words count every tile in the column.",
  loose:
    "Familiar crossword play turns vertical as letters climb over earlier words and turn MOOD into WOOD, then WOOL. Tile placement drives each turn: letters go across, down, or onto existing tiles to change a word. Highest score wins, with flat words paying double while stacked words count every tile in the column. Stacks cap at five tiles, and at least one old letter must remain uncovered.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:32.894Z",
  model: "gpt-5.5",
  durationMs: 23957,
  sources: [
    "https://instructions.hasbro.com/en-us/instruction/upwords-game",
    "https://winning-moves.com/images/UPWORDS_rulesv2.pdf",
    "https://www.ultraboardgames.com/upwords/game-rules.php",
  ],
} as const;
