// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug parks
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A narrowing national-park trail turns each stop into a small denial puzzle, with worker placement sending two hikers down one-way paths.",
  default:
    "Serene park art hides a tight race down a one-way trail. Worker placement sends two hikers to gather resources, photos, wildlife, gear, and canteens across three seasons. The final score rewards visited parks, photos, and personal goals.",
  loose:
    "Serene park art hides a tight race along a one-way trail, where each hiker can block a coveted stop. Worker placement sends two hikers to collect resources, photos, wildlife, gear, canteens, campsites, and passion bonuses across three seasons. The final score rewards visited parks, photos, and personal goals, not distance traveled. This edition adds all 63 parks with new art by Josh Emrich and Lisk Feng.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:49.532Z",
  model: "gpt-5.5",
  durationMs: 33904,
  sources: [
    "https://keymaster.fun/products/parks-2nd-edition",
    "https://dicetower.com/board-game/437306",
    "https://hanhangames.com/products/parks-second-edition",
    "https://www.boardgamevideo.com/videos/parks-2nd-edition-playthru-wOObTj08Dv4",
  ],
} as const;
