// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug parks
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Gentle worker-placement game where hikers move one way along a trail, gather tokens, take photos, and spend supplies to visit parks.",
  default:
    "Family-weight worker-placement game about hiking U.S. national parks and collecting supplies from a one-way trail. On a turn, move one of your two hikers forward to a site, take its action, and use a campfire if the site is occupied. After the fourth season, most points from visited parks, photos, year bonus, and first-hiker marker wins.",
  loose:
    "Family-weight worker-placement and resource collection game about hiking U.S. national parks and choosing scarce trail sites before other hikers block them. On a turn, move one of your two hikers only forward to a site, then gain forest, mountain, sun, water, photos, canteen actions, campsites, or gear. At trail end, reserve a park, buy gear, or pay the shown tokens to visit a park; after the fourth season, most points wins. This edition folds in camping and wildlife ideas, includes all 63 park cards, and uses new Josh Emrich and Lisk Feng art.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:56.370Z",
  model: "gpt-5.5",
  durationMs: 25502,
  sources: [
    "https://keymaster.fun/products/parks-2nd-edition",
    "https://board-game-rules.com/wp-content/uploads/2025/01/parks_Official-Rules.pdf",
    "https://www.gamenerdz.com/parks-2nd-edition-standard-edition",
  ],
} as const;
