// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug hell-of-a-deal
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A rigged infernal casino turns Texas Hold’em into cooperative poker, with Favor cards buying illegal outs at a rising cost.",
  default:
    "The house cheats first, so every hand at the Last Resort Casino feels like poker on a trapdoor. Betting drives the game as players build hands against bosses while guarding shared Souls and Temptation. Beat four bosses to reach the Devil, then win the final hand before the contract closes.",
  loose:
    "The house cheats first, so every hand at the Last Resort Casino feels like poker on a trapdoor. Betting drives the game as players build hands against bosses while guarding shared Souls and Temptation. Beat four bosses to reach the Devil, then win the final hand before Temptation or empty coffers seal the contract. Everyone gets a third Hold’em card up the sleeve, and the central neoprene mat sprawls 28 by 20 inches.",
};

export const meta = {
  generatedAt: "2026-05-13T16:35:35.844Z",
  model: "gpt-5.5",
  durationMs: 41707,
  sources: [
    "https://gamingtrend.com/cashless-co-operative-poker/",
    "https://frogames.it/en/products/hell-of-a-deal",
    "https://www.reddit.com/r/boardgames/comments/1s3lolt/hell_of_a_deal_a_cooperative_poker_experience/",
    "https://www.kicktraq.com/projects/smirkanddagger/hell-of-a-deal/",
    "https://www.cardhaus.com/hell-of-a-deal/",
  ],
} as const;
