// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug hell-of-a-deal
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative Texas Hold’em card game where everyone builds a poker hand, spends chips to cheat, and tries to beat hellish bosses.",
  default:
    "Cooperative poker survival game where each player builds a Texas Hold’em hand against a cheating boss. Each hand deals three private cards, reveals flop-turn-river cards, then players bet chips, earn Souls, and use Favor cards to cheat. Beat the Devil at the Big Table before Souls run out or Temptation claims the team.",
  loose:
    "Cooperative poker survival game where each player builds a Texas Hold’em hand against a cheating boss. Each hand deals three private cards, reveals flop-turn-river community cards, then players bet chips, earn Souls, and use Favor cards to cheat. Clear the boss run and beat the Devil at the Big Table before Souls run out or Temptation claims the team. The box includes a large neoprene casino mat, custom poker chips, Boss cards, and rule-breaking Favor cards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:08.877Z",
  model: "gpt-5.5",
  durationMs: 53108,
  sources: [
    "https://www.gamenerdz.com/hell-of-a-deal-preorder",
    "https://gamingtrend.com/six-ways-hell-of-a-deal-is-actually-like-poker/",
    "https://gamingtrend.com/cashless-co-operative-poker/",
    "https://hell-of-a-deal.backerkit.com/faq",
  ],
} as const;
