// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug heroquest
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A dungeon appears room by room as Zargon follows a hidden map against four fragile heroes, with grid movement driving every risky door.",
  default:
    "One player knows the dungeon first, turning each opened door into a reveal of monsters, furniture, and traps. Grid movement carries the heroes through corridors as Zargon consults a hidden quest map. The heroes win by completing the scenario and escaping before Zargon breaks the party.",
  loose:
    'One player knows the dungeon first, so each opened door becomes a reveal of monsters, furniture, and traps. Grid movement carries heroes through corridors while Zargon reads a hidden quest map and rolls combat dice. The heroes win by finishing the scenario and escaping, while Zargon wins by stopping the objective. Stephen Baker called the design "roleplaying in a box," with fantasy laid out in 3D.',
};

export const meta = {
  generatedAt: "2026-05-13T16:36:42.983Z",
  model: "gpt-5.5",
  durationMs: 108797,
  sources: [
    "https://boardgamegeek.com/boardgame/699/heroquest",
    "https://instructions.hasbro.com/en-us/instruction/heroquest-game-instructions-rulebook",
    "https://elvyler.com/2022/08/interview-with-the-designers-of-heroquest/",
    "https://www.meeplemountain.com/reviews/heroquest/",
  ],
} as const;
