// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug heroquest
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Gateway dungeon-crawl adventure where heroes explore a gridded maze, roll dice, fight monsters, and loot rooms.",
  default:
    "Fantasy dungeon-crawl adventure with an overlord reading a quest map while the hero team explores a room-by-room maze. On a hero turn, roll movement dice, move, then attack, cast a spell, or search for traps, secret doors, or treasure. Heroes win by finishing the quest goal and escaping; the overlord wins if they fail.",
  loose:
    "Fantasy dungeon-crawl adventure with an overlord reading a hidden quest map while the hero team explores a room-by-room maze. On a hero turn, roll movement dice, move, then attack with combat dice, cast a spell, or search for traps, secret doors, or treasure. Heroes win by completing the quest objective and getting out alive; the overlord wins if the party dies or misses the goal. Plastic doors, furniture, and monster miniatures appear on the board only when heroes open rooms.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:42.890Z",
  model: "gpt-5.5",
  durationMs: 16220,
  sources: [
    "https://www.boardgamequest.com/heroquest-review/",
    "https://boardgamegeek.com/boardgame/699/heroquest",
    "https://heroquest.fandom.com/wiki/Guide%3ARules",
    "https://merchantsofplay.com/howtoplay/heroquest/",
  ],
} as const;
