// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug scotland-yard
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A fugitive vanishes into London’s transit web while detectives read ticket trails in a lean hidden movement chase.",
  default:
    "London becomes a logic trap as one fugitive leaves only ticket colors behind. Hidden movement drives the chase across taxi, bus, and Underground lines. Detectives win by landing on Mr. X’s station before he survives the dragnet.",
  loose:
    "London becomes a logic trap as one fugitive leaves only the color of each taxi, bus, or Underground ticket behind. The core is hidden movement: Mr. X records secret stations while the detectives coordinate visible moves across the map. The detectives win by landing on his station, while Mr. X wins by surviving the chase. The visor is not just theater; it keeps Mr. X’s eyes from giving away which corner of London matters.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:34.238Z",
  model: "gpt-5.5",
  durationMs: 114344,
  sources: [
    "https://www.ravensburger.us/en-US/products/games/board-games/scotland-yard-27514",
    "https://www.ultraboardgames.com/scotland-yard/game-rules.php",
    "https://www.reddit.com/r/boardgames/comments/1ibkys/review_scotland_yard/",
    "https://scotland-yard.sourceforge.net/rules/help5.html",
  ],
} as const;
