// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug scotland-yard
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Asymmetric chase game where detectives spend transit tickets around London while hidden Mr. X logs secret taxi, bus, and tube moves.",
  default:
    "Asymmetric chase-and-deduction game where one hidden fugitive crosses London while detectives try to box him in. Each round, Mr. X logs a secret move and shows only the ticket used; detectives spend matching tickets to move visible pawns. Detectives win by landing on Mr. X or trapping him, while Mr. X wins by lasting through the chase.",
  loose:
    "Asymmetric chase-and-deduction game where one hidden fugitive crosses London while detectives try to box him in. Each round, Mr. X logs a secret station and covers it with a taxi, bus, underground, or black ticket; detectives spend matching tickets to move visible pawns. Detectives win by landing on Mr. X or leaving him no legal move; Mr. X wins by lasting through the chase. The travel log gives transport clues every turn, with location reveals only at marked turns.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:06.142Z",
  model: "gpt-5.5",
  durationMs: 55352,
  sources: [
    "https://en.wikipedia.org/wiki/Scotland_Yard_%28board_game%29",
    "https://www.hasbro.com/common/instruct/ScotlandYard.PDF",
    "https://boingboing.net/2015/08/18/game-review-detectives-hunt-f.html",
  ],
} as const;
