// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug kings-in-the-corner
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light family card game where players shed cards onto shared solitaire piles, move stacks, and race to empty their hand.",
  default:
    "Light family card game with a shared solitaire layout. On a turn, a player plays legal cards to descending red-black piles, moves whole stacks, drops kings in corner slots, then draws. Empty a hand first to win the pot; first to 100 points wins.",
  loose:
    "Light family card game with a shared solitaire layout, where players shed cards onto descending red-black piles. On a turn, a player plays legal cards, drops kings into corner slots, moves whole piles to open spaces, then draws or pays a chip for no play. A hand ends when someone empties their hand; that player takes the pot and scores its chips, and first to 100 points wins. The boxed version uses a plastic tray with four king corners and four regular stalls.",
};

export const meta = {
  generatedAt: "2026-08-14T22:19:52.562Z",
  model: "gpt-5.5",
  durationMs: 17953,
  sources: [
    "https://www.ultraboardgames.com/kings-in-the-corner/index.php",
    "https://www.pagat.com/layout/kingscorners.html",
    "https://www.geekyhobbies.com/kings-in-the-corner-rules/",
  ],
} as const;
