// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug mysterium
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A silent ghost feeds surreal vision cards to arguing mediums, turning deduction into a séance of misread colors and symbols.",
  default:
    "A murder case becomes a séance because the only witness is a mute ghost holding dreamlike art. Deduction drives play as mediums interpret vision cards for suspects, locations, and objects. The group wins by naming the true culprit before dawn.",
  loose:
    "A murder case becomes a séance because the only witness is a mute ghost holding dreamlike art. Deduction drives play as the ghost assigns each medium a private suspect, location, and object, then hints with vision cards. The group wins only if every medium clears a personal set before dawn and the table names the true culprit. The ghost's tall screen hides the answers while every wrong theory must be endured in silence.",
};

export const meta = {
  generatedAt: "2026-05-13T16:37:15.627Z",
  model: "gpt-5.5",
  durationMs: 29907,
  sources: [
    "https://www.libellud.com/en/our-games/mysterium/",
    "https://www.libellud.com/en/resources/mysterium/",
    "https://www.gamesradar.com/games/board-games/mysterium-review/",
  ],
} as const;
