// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug mysterium
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative deduction party game where a silent ghost gives surreal image cards and mediums debate suspect, place, and object clues.",
  default:
    "Cooperative image-clue deduction game about solving a murder with one silent ghost and a table of debating mediums. Each round, the ghost gives surreal vision cards, and mediums choose suspect, location, or object cards. Find every set, then vote on the final killer’s set to win together.",
  loose:
    "Cooperative image-clue deduction game about solving a murder with one silent ghost and a table of debating mediums. Each round, the ghost gives surreal vision cards, and mediums choose suspect, location, or object cards. Find every personal set before dawn, then vote on the final killer’s set to win together. The huge ghost screen hides the answer grid like a séance prop.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:31.749Z",
  model: "gpt-5.5",
  durationMs: 22871,
  sources: [
    "https://www.libellud.com/en/our-games/mysterium/",
    "https://cdn.svc.asmodee.net/production-libellud/uploads/2025/11/MYST_REFRESH_RULES_EN-1.pdf",
    "https://www.gamesradar.com/games/board-games/mysterium-review/",
    "https://www.theboardgamefamily.com/2017/03/mysterium-board-game-review/",
  ],
} as const;
