// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug calico
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Thinky tile-laying puzzle where players draft patch tiles, fill quilt boards, and score cats, buttons, and design goals.",
  default:
    "Thinky tile-laying puzzle about filling a personal quilt board. Each turn, a player places one patch tile, checks for cat patterns or button groups, then drafts a replacement from the market. Highest score wins from cats, buttons, and design goals.",
  loose:
    "Thinky tile-laying puzzle where each player fills a personal quilt board with hex patch tiles in colors and patterns. On a turn, a player places one tile from hand, checks for matching cat patterns or same-color button groups, then drafts a replacement from the three-tile market. When every quilt is full, highest score wins from cats, buttons, and design goal tiles. The cute cat tokens sit on top of a surprisingly tight spatial puzzle.",
};

export const meta = {
  generatedAt: "2026-08-17T00:31:42.887Z",
  model: "gpt-5.5",
  durationMs: 18779,
  sources: [
    "https://www.alderac.com/calico/",
    "https://www.alderac.com/wp-content/uploads/2025/04/Calico_BaseGame_Rulebook_Optimized.pdf",
    "https://www.nerdly.co.uk/2021/03/18/calico-board-game-review/",
  ],
} as const;
