// Per-slug description overrides applied on top of the BGG snapshot's
// `description` field. Single source of truth for the prose shown in the
// RSVP game-carousel card body.
//
// Why this file exists: BGG descriptions are inconsistent (some run 6
// paragraphs with shipping-content lists, others read like marketing
// blurbs, others are missing entirely). The carousel card has a fixed
// description region per device. To unify the visual rhythm across the
// catalog, every game gets a hand-written ~75–85 word description with a
// shared structure:
//
//   1. One sentence of premise / theme (who you are, what's at stake).
//   2. One or two sentences on the core mechanic and per-turn loop.
//   3. One sentence on the twist / strategic decision space.
//   4. One sentence on the winning condition.
//
// New games default to the BGG snapshot until they're written up here.
// Per-game `bggOverrides.description` (in each game's `index.ts`) wins
// over this map — that's the per-game escape hatch.

export const descriptionOverrides: Record<string, string> = {
  "7-wonders":
    "You lead an ancient civilization racing to complete one of the seven wonders of the world. Across three ages you draft cards by passing your hand left, then right, then left again, building resource producers, military, science, and commercial structures. Every card you keep is a card your neighbor cannot take, so timing and denial matter as much as efficiency. Brief border wars at the end of each age decide who picks up bonus victory points. Highest total after the third age wins.",
  "aeons-end":
    "The last survivors of humanity hide in the underground city of Gravehold while a Nameless horror gathers strength to break through the breaches. You play a breach mage with a personal deck of gems, relics, and spells, opening breaches in front of you so you can prep spells now and detonate them on later turns. Turn order is shuffled each round, simulating an attack you cannot fully predict. Slay the nemesis before Gravehold or any mage falls and you all win together.",
  "a-game-of-thrones-the-card-game":
    "You take command of one of the great houses of Westeros — Stark, Lannister, Baratheon, Targaryen, or Greyjoy — and fight for the Iron Throne with a deck built from characters, locations, and events. Every round you challenge opponents for military, intrigue, and power, winning the round you can convert into the points that decide the game. Plot cards seed each turn with new income, initiative, and reserve numbers, forcing you to read what your rivals are about to do. First house to fifteen power claims the throne.",
  "ark-nova":
    "You manage a modern, scientifically run zoo competing for international conservation prestige. Five action cards rotate through priority slots — the longer an action sits unused, the more powerful it becomes when you finally trigger it. Cards bring in animals, sponsors, special buildings, and association workers, while conservation projects funnel money out toward the planet. Two scoring tracks run in opposite directions and you win the moment they cross, so balancing appeal against scientific reputation is the whole puzzle.",
  azul: "You play a tile-laying artisan decorating the royal palace at Évora with glittering Portuguese azulejos. On your turn you take all the tiles of one color from a single factory display, sending the rest into the table's center pool. Tiles you grab fill a row in your workshop; if they overflow the row, every extra crashes onto a penalty track. At the end of each round only the rightmost tile in each row promotes to the wall, scoring on adjacency. Highest score after a wall row finishes wins.",
  bandit:
    "You're a desperate outlaw riding hard out of a frontier boomtown with the marshal's posse closing in. Each round you push your luck through dice and card draws — rope a richer haul or fold early and bank what you've got before the law catches up. Other bandits at the table can bid for your stolen goods, fence them through shady deals, or sell you out for a cut of the bounty. Survive the chases, count your gold at dawn, and the richest fugitive walks away the legend.",
  "betrayal-at-house-on-the-hill":
    "Your group walks into a haunted mansion that builds itself one randomly drawn tile at a time. As you explore you collect omens, items, and events — until one omen roll fails and the haunt begins. A scenario book splits the table: one player flips to the betrayer's script while everyone else reads the survivors' page, each with secret objectives and rules the other side cannot see. The map you built moments ago is now the board you fight across. Whichever side completes its scenario goal first wins.",
  "blood-on-the-clocktower":
    "It is dawn in the village of Ravenswood Bluff and a body has been found in the square. A storyteller hands out hidden character roles — townsfolk, outsiders, minions, and a lurking demon — and runs the night phase in secret while the table debates by day. Information leaks through ability prompts, but some of those prompts are bluffs and the demon knows almost everything. Dead players keep talking and keep voting, so a clever ghost can still tip the scales. The good team wins by executing the demon; the evil team wins by surviving.",
  "brass-birmingham":
    "You are an industrialist in the West Midlands during the late 1700s and 1800s, racing rival barons to dominate beer, coal, iron, pottery, and cotton. Two eras of play — canals first, then rails — reset the map and the connections you can build between cities. Each round you take two actions chosen from build, network, develop, sell, loan, and scout, paying close attention to which goods are in surplus on the board. Selling industries flips them and scores them at the era's end. Most points after the rail era wins.",
  "brass-lancashire":
    "You play a Lancashire cotton magnate during the Industrial Revolution, leveraging shipping ports, coal pits, ironworks, and cotton mills to feed an expanding empire. Two eras — canals then rails — wipe the map between them, demoting low-tier industries and forcing you to specialize for each phase. A hand of city/industry cards constrains where you can build, so reading the deck and remembering what others have played matters. Sold industries flip and bank their points immediately. Highest total after the rail era ends wins the game.",
  "brass-pittsburgh":
    "You're an industrialist in 1870s Pittsburgh, the new American gateway between Appalachian coal and the steel mills downriver. Two eras of build, network, develop, sell, loan, and scout actions stack on a Pennsylvania map that demands aggressive expansion along the river. Coal and iron behave like a shared market — your decisions raise and lower prices for everyone — and breweries gate which industries you can flip into scoring. Era transitions wipe low-tier builds and reward whoever invested in higher levels. Most points after the final era wins.",
  "bristol-1350":
    "It's 1350 in plague-ridden Bristol and your wagon is the last cart leaving the city before dawn. Each turn you roll movement dice and choose which to keep, betting that other carts ahead of you hit pothole spaces and slow down. Hidden role cards split the table between people who are clean, infected, or witches whose victory conditions are different from everyone else's. Item cards let you sabotage neighbors, steal turns, and protect yourself from the cough. First clean cart over the line wins outright; otherwise role objectives settle it.",
  "captain-sonar":
    "Two submarine crews battle in real time across opposite sides of a screen, each running four shared roles: captain, first mate, engineer, and radio operator. The captain plots a route in marker on a paper map and shouts the heading; the radio operator listens to the enemy captain and tries to triangulate their position; the engineer manages breakdowns; the first mate charges weapons one click at a time. Surface to repair and your team is exposed for a full minute. First crew to score four direct torpedo hits wins.",
  cascadia:
    "You build a Pacific Northwest wildlife corridor by drafting paired habitat tiles and animal tokens from a shared market. Each turn you pick one tile-and-token pair, place the hexagonal tile next to your tableau, then set the animal on a matching habitat space. Five animals — bear, elk, salmon, hawk, fox — each score by their own pattern card, so the same animal scores differently from game to game. Connecting habitats of the same type chains a separate scoring track. Most combined points across habitats and wildlife wins.",
  catan:
    "You're a settler claiming roads, villages, and cities on the resource-rich island of Catan. Each turn a dice roll triggers production on hex tiles, paying out wood, brick, sheep, wheat, and ore to whoever borders the rolled number. You spend those resources to build, trade with neighbors at the table, or buy development cards that hide knights and victory points. A roving robber blocks production on a chosen hex whenever a seven comes up, so where you settle is a question of geography and risk. First to ten victory points wins.",
  chess:
    "You command sixteen pieces — pawns, knights, bishops, rooks, a queen, and a king — on a checkered eight-by-eight board across from one opponent. Each piece moves on its own pattern, and capturing reduces your opponent's army one square at a time. Pawns transform when they reach the far rank, knights jump over the line, and castling lets your king tuck away behind a rook in a single move. The game ends when one player's king has no legal move that escapes capture. Checkmate the king and you win.",
  "chess-bughouse":
    "Two chess boards sit side by side, two players to a board, four players to the room. You and your partner play opposite colors on opposite boards, and every piece your partner captures gets handed to you to drop back onto your board as a reinforcement on any empty square. Clocks tick in parallel and you can shout strategy across the table — when to stall, when to trade, when to deliver mate. The match ends the instant either board reaches checkmate or a flag falls. Winning team takes both boards.",
  "chess-for-three":
    "Three players take three colors on a hexagonal chess board whose pieces, ranks, and starting setup all stretch to fit a triangular battlefield. Standard piece movement carries over but adapts to the hex grid, so bishops still glide on diagonals and knights still jump in their two-then-one pattern across the new geometry. Coalitions form and collapse mid-game because any check forces the other two to decide who absorbs it. The board is won when a player delivers mate against either rival, no matter who actually pinned them in.",
  codenames:
    "Two rival spymasters know the secret identities of twenty-five agents laid out as a five-by-five grid of code words. Their teammates only see the words. Each turn the spymaster says one word plus a number, hoping their team picks every agent they meant — without touching the rival team's spies or the lone assassin that ends the game on contact. Bigger numbers cover more cards faster, but a single wrong tap can hand the win to the opposing team. First team to reveal all of its agents wins.",
  "codenames-duet":
    "The cooperative twin of Codenames: you and a partner each see your own five-by-five key card with fifteen agents marked, nine of which only your partner can see. You take turns giving one-word clues plus numbers, trying to identify every agent on both grids together within a fixed time budget. Assassins are sprinkled across the same grid, so a clue that looks safe on your card can be lethal on the other side. Coordinate, sandbag the easy clues, and find every agent before time runs out to win as a team.",
  "codenames-pictures":
    "Codenames played with twenty surreal illustrations instead of words — a clock-bear-rocket-hat composite is one square; a ship-spider-pyramid-egg is another. Spymasters give a one-word clue and a number, gesturing toward the symbols hidden inside the artwork. Teams tap the pictures they believe match, dodging the rival team's agents and the single assassin in the grid. Visual clues open up entirely new linking ideas (color, composition, mood, motion) that text-only Codenames does not allow. First team to reveal all of its agents wins.",
  "connect-4":
    "You and one opponent take turns dropping colored discs into a vertical seven-by-six grid. Gravity decides which row each disc lands in — you only choose the column. The objective is to line up four of your own discs in a horizontal, vertical, or diagonal row before your opponent does. Despite the simple rules the game has a solved opening theory: the first player wins with perfect play by starting in the center column. Form four in a row, in any straight line, and you take the round.",
  "deadwood-1876":
    "You're a prospector, gunslinger, or saloon owner in 1876 Deadwood, scrabbling for gold dust and reputation in a town with no real law. Each round you take actions on a grid that mixes panning, drinking, gambling, and shootouts, with cards triggering historical events that reshape the camp. Hidden agendas split the table between citizens, outlaws, and lawmen with different victory conditions and bluffing room. Resources convert messily — chips become bullets become bargaining power — and a wrong call can earn you a pine box. Most influence when the mining season closes wins.",
  decrypto:
    "Two teams of code-makers and -guessers each guard their own set of four secret words numbered 1 through 4. Each round one teammate looks at a three-digit code and gives three one-word clues hinting at the corresponding secret words, hoping their own team can decode it while the rival team — listening to every clue — cannot. Each round you record clues for both teams, building a corpus you can use to intercept. Two intercepts and you win; two miscommunications by your own team and you lose.",
  dorfromantik:
    "You build a pastoral landscape one hex tile at a time, drawing from a shared stack and placing the next tile anywhere along the growing border. Tiles split into combinations of forests, fields, villages, rivers, and rail lines; matching edges chain features together and unlock objective tokens that demand specific group sizes. The deck is finite, so every tile is also a decision about which incomplete cluster gets closed. Cooperative play across multiple sessions also unlocks new tiles and quests. Score the most points before the stack runs out to win.",
  "dungeon-mayhem":
    "Four iconic D&D characters — barbarian, paladin, wizard, rogue — face off across a knockabout combat-card brawl. Each character has its own asymmetric thirty-card deck full of attacks, shields, healing, and ability chains. On your turn you play cards in any order, stacking shields against incoming hits and zapping rivals down to zero hit points. Targeting is open, so deals form and dissolve as soon as one player pulls ahead. Be the last hero standing with at least one hit point to win the round.",
  "dungeons-and-dragons":
    "A dungeon master narrates a fantasy world and the rest of the table plays adventurers exploring it: choose a race, a class, a backstory, and step into a campaign that can run for one evening or a decade. Combat resolves on a twenty-sided die plus your character's bonuses against a target number, but most of the game is conversation, problem-solving, and rolls of charisma, perception, and stealth. The DM adjudicates outcomes, designs encounters, and keeps the world consistent. There's no winner — the goal is a story you keep telling later.",
  durak:
    'A Russian card game whose name literally means "fool": you and the rest of the table fight to discard your hand into the middle while one player at a time is the defender. The attacker plays a card; the defender must beat it with a higher card of the same suit or a trump card revealed at the deal. Cards stack and beat in waves; if the defender can\'t keep up they pick the pile up. After each round, hands refill from the deck. The last player still holding cards is the "durak" — and loses.',
  "elements-of-truth":
    'A homebrew social-deduction round inspired by Codenames and Two Rooms and a Boom. The table is split into elemental factions with different win conditions known only to themselves; one faction holds a secret "truth" the others must reconstruct from leaked clues. Round timers force quick alliances and quicker betrayals, with hidden votes settling who you believe and who you\'ll throw under the bus. Information leaks every turn but you only see your own slice of it. Your faction wins the moment its specific victory condition is met.',
  "escape-tales-the-awakening":
    "A cooperative narrative escape-room game played at the kitchen table over three evenings. You take the role of a father whose daughter has fallen into a coma, and you walk into her dreams to find her. A deck of room cards represents the spaces you can explore; each card opens new objects, hides puzzles, and slowly bleeds your sanity stones. There's no timer — just an evolving story whose endings branch on the choices you make. Solve the final dream room and choose her fate; the table wins or loses based on which ending you reached.",
  "exploding-kittens":
    "A card-game built around one mechanic: you shuffle a deck full of action cards and a handful of exploding kittens, and players draw one card per turn until somebody pulls a kitten and explodes. Hand cards let you skip your turn, peek at upcoming draws, force a draw on another player, or defuse a kitten with the matching defuse card. The deck shrinks every turn and the surviving kittens loom closer with every shuffle. Last player who hasn't exploded wins the round.",
  frosthaven:
    "A campaign-length cooperative dungeon crawler set in the bitter north of the Gloomhaven world, where you've inherited a frontier outpost on the edge of a haunted forest. Six new mercenary classes use the simultaneous-action card system: every round you pick two cards and choose which half of each to play, optimizing initiative, attacks, and movement. Persistent town development, crafting, seasonal events, and a branching story arc carry between sessions. The campaign ends when its branching map runs out of unlocked scenarios — your party's choices write the legacy.",
  gloomhaven:
    "A massive legacy-style dungeon crawler set in the city of Gloomhaven, where mercenary parties take contracts in dungeons riddled with monsters, traps, and looted treasure. Six starting classes drive a card-based combat system in which each card has top and bottom abilities, and you commit to one half from each of two played cards every round. Cards you burn don't come back, slowly grinding your stamina down to a forced retreat. A persistent map and a sealed-envelope campaign unlock new classes and scenarios; the campaign ends when its branching story does.",
  "gloomhaven-jaws-of-the-lion":
    "The standalone tutorial campaign for Gloomhaven, designed to onboard new mercenaries into the same simultaneous-action card system without the seventeen-pound box. Four pre-built classes — Hatchet, Voidwarden, Demolitionist, Red Guard — sweep through twenty-five linked scenarios laid out in a tutorial book whose pages double as the map terrain. Every scenario teaches one new wrinkle of the rule set; gear unlocks and ability cards roll forward between sessions like the main campaign. Finish the final scenario to close the storyline as your party of four.",
  "hell-of-a-deal":
    "You're an underworld broker spinning bargains between desperate mortals and the gods of the dead. Across rounds you bid on petitioner cards, choose which deity to please, and stack combo-effects from your trading post. Action cards stay in front of you, building a tableau where every new card argues with the last, and rival brokers can intercept your richest deals by sliding tokens in at the wrong moment. End-game scoring counts vows kept and souls collected. Most points wins — though anyone who broke a vow loses them first.",
  heroquest:
    "The classic dungeon crawler reissued: one player runs the dungeon master from a quest book while the rest of the table plays a barbarian, dwarf, elf, or wizard. The board is a modular grid of corridors and rooms revealed as you open doors. Combat uses big custom dice — attack skulls against shield faces — and spell decks for the wizard. The dungeon master places monsters, traps, and treasure chests in secret and triggers them as the heroes blunder past. The heroes win the scenario by completing its objective; otherwise the dungeon master wins.",
  hitster:
    "A party music game built around a stack of song cards, each printed with a song's release year on the back. Speakers pump out a track and the active player has to slot it correctly into a personal timeline of previously placed cards — was it before Wonderwall? After Thriller? Tokens let you challenge other players' placements between turns, betting your own score that they got it wrong. Build a timeline of ten correctly placed songs and the round is yours.",
  "hollywood-1947":
    "You're a movie-studio survivor in 1947 Los Angeles, the year the House Un-American Activities Committee dragged Hollywood into a witch hunt. Action cards on a noir grid let you stage screenings, leak rumors, name names, or quietly fund blacklisted writers. Hidden allegiance cards split the table into committee allies, communists, and opportunists, each with their own victory condition. Reputation, money, and suspicion swing every round; one bad subpoena can end your career. The winning side is whichever faction completes its scenario goal when the final reel rolls.",
  jaipur:
    "A two-player trading game set in the Indian city of Jaipur, where you and your rival each angle to become the maharaja's personal merchant. On your turn you take cards from the central market or sell groups of the same good for rupees from the corresponding bonus stacks. Bigger sets pay better, so timing your sells against the market's restocks is the whole tension. Camels never sell directly but unlock huge trades. Win two of three rounds — each round ending when three goods stacks empty — and you take the title.",
  "just-one":
    "A cooperative party game built around a deceptively simple rule. One player draws a mystery word and the rest of the table secretly writes a single one-word clue toward it. Then every clue is compared: any duplicates are crossed out before the guesser sees them, leaving only the unique clues to inspire a single guess. Right answers earn a point; wrong answers cost two; passes cost one. The whole deck is thirteen cards. Score eleven or higher together to win as a table.",
  keltis:
    "The German bestseller renamed Lost Cities: To the Lost Temples for export. Two to four players move pawns up five colored garden paths by playing matching cards in ascending order. Each card you play commits the path you started, but stopping the wrong path early sinks you into negative points. Wishstones along the way collect bonuses and milestones reward whichever pawn reaches the top of a path first. The deck runs out, hands empty, and whoever has the highest combined garden score takes the win.",
  "liars-uno":
    "A house-rules twist on UNO where lying is part of the rules. On your turn you place a card face-down and announce what it is — color and number — and any opponent can call your bluff before the next player plays. If they call truthfully you pick up the discard pile; if they call wrong they pick it up themselves. Skip, Reverse, and Wild Draw cards still fire but only if you actually played them. First to empty your hand wins; the rest of the table tallies what you've held against you.",
  "lost-cities":
    "A two-player tableau game about funding rival archaeological expeditions through five colored regions. Cards are numbered two through ten and each region also holds investment cards that multiply both your gains and your losses. On your turn you either play a card to one of your color columns or discard it, then draw from the deck or a discard pile. Starting an expedition costs twenty points before you score anything, so committing too thinly is a punished mistake. Highest total score after the deck runs out wins.",
  "lovecraft-letter":
    "A horror-flavored riff on Love Letter where each round you and a small circle of rivals fight to be the last sane investigator standing. The deck holds sixteen cards numbered with abilities — guess, see, compare, protect, knock out — plus a layer of insanity cards whose powerful effects come at the cost of accumulating madness. Too many sanity tokens and you're out for the rest of the round. Round-winners take a favor token; first investigator to a fixed number of tokens wins the night.",
  "magic-the-gathering":
    "The original collectible card game: you build a deck out of a card pool that now spans thirty-plus years and tens of thousands of unique cards. Each game you start at twenty life, draw seven cards, and tap lands of five colors to play creatures, spells, artifacts, and enchantments at your opponent. Turns split into phases that gate when each effect can fire. The game ends when an opponent's life hits zero, their deck runs out, or a card with an alternate-win condition triggers. Reduce them to zero life and you win.",
  monopoly:
    "You roll two dice and move around a square board buying real estate, charging rent, and building houses and hotels on color-matched property groups. Landing on opponent property pays them; landing on your own is fine; landing in jail freezes you for up to three turns. Chance and Community Chest cards inject random fortunes and disasters into every lap. Bankrupt all of your rivals — driving every other player's cash and assets below the rent they owe — and you take the deeds, the cash, the board, and the night.",
  mysterium:
    "A cooperative deduction game in which one player plays a silent ghost trying to remember who murdered them, and the rest play psychics. The ghost gives surreal vision cards full of dream imagery; each psychic uses the cards to narrow down their personal suspect, location, and weapon trio. Once every psychic has solved their personal mystery the ghost reveals the real culprit through a final shared vision. Solve the case before seven rounds run out and you win as a séance; otherwise the murderer escapes.",
  "not-enough-mana":
    "A magic-school dueling game built around the constant problem of running out of mana at the worst moment. Each turn you choose to draw a spell, tap your reserves to cast one, or scrounge an emergency mana source from the discard pile. Spells stack effects into combos that can chain across turns if you stage them right — but every chain ends the moment a single component goes missing. Opponents target your mana more often than your health. Last mage with both a hand and the energy to cast wins.",
  "one-night-ultimate-werewolf":
    "A ten-minute social deduction game where every player draws a role card, peeks at it once, then a phone or recorded soundtrack walks the table through a single night phase of role-specific actions in the dark. After night, the table debates for five minutes and votes who to lynch. With seers, robbers, troublemakers, and drunks rearranging cards mid-night, almost nobody knows what their card says when the vote opens. If at least one werewolf is lynched the village wins; otherwise the wolves win.",
  pandemic:
    "Four diseases are erupting across the planet and your team of specialists is the only thing in their way. Each player has a specialist role — medic, scientist, dispatcher, researcher, operations expert — with a unique action and movement rule. On your turn you spend four actions moving, treating cities, building research stations, sharing knowledge, or curing a disease at a station. Player and infection decks tick down between turns, and outbreaks chain across the map. Cure all four diseases together as a team to win.",
  parks:
    "You play two hikers walking through one of America's national parks, taking in scenery, photos, and animal sightings. The board is a one-way trail; each turn you move one of your two hikers forward and trigger that space's action — collect canteen water, exposure, photographs, or animal tokens — before the trail leads you back to camp. Park cards demand specific sets of resources to score, and you can only enter parks when the season cards permit. Most points across photo books, animals, and visited parks wins.",
  "phase-10":
    "A card game where you play through ten specific phases over ten hands — three of a kind plus a run of four, two sets of three, seven of one color, and so on. Each hand you draw and discard from a Rummy-like flow until somebody completes their current phase, lays it down, and starts dumping the rest of their hand. Players who didn't complete their phase have to retry it next hand. The first player to clear all ten phases wins.",
  poker:
    'A family of betting card games — Texas Hold\'em is the most famous variant — built around making the best five-card hand using a mix of hidden "hole" cards and shared "community" cards. Across four betting rounds you call, raise, fold, or go all-in, reading both the math of your hand and the behavior of every other player at the table. Bluffing is part of the rules, not a workaround. The pot goes to the last player standing or the best hand at the showdown.',
  quiztopia:
    "A cooperative trivia game where the whole table works together on one big knowledge map. Question cards span science, history, geography, pop culture, and language, and answering correctly lets your shared explorer move forward across a fantastical board. Some questions are individual; others are wagered as a group, with stakes that swing the team forward or backward. There's no rival team — just the clock, the deck, and whether your collective knowledge is enough. Reach the destination before the deck runs out and you win as a team.",
  "roma-xli":
    "An asymmetric political-intrigue game set in 41 AD as the Roman Senate, the Praetorian Guard, and the people choose what to do with the corpse of Caligula and the question of his successor. Each faction has its own action deck, victory conditions, and hidden agendas. Cards stage senate votes, street rebellions, assassinations, and bribes, often resolved in secret. The map shifts as quarters of Rome change loyalty between turns. Whichever faction's hidden agenda is met first installs an emperor — or topples the whole republic — and wins.",
  rummikub:
    "A tile-laying game whose joy is in restructuring everything on the table at once. You hold a rack of numbered tiles in four colors and lay groups (same number, different colors) and runs (sequential numbers, same color) into a shared play area. The twist: on later turns you can pull tiles already on the table apart and rebuild them into different valid combinations as long as the table is legal again at the end of your turn. First player to empty their rack wins.",
  rummy:
    "The card-game family that gave a hundred others their grammar: you draw and discard one card per turn, building melds of three-of-a-kind or runs of three or more in the same suit in front of you. Some variants let you lay off a single card onto an opponent's meld; some don't. The hand ends when someone empties their hand (\"goes out\") and the rest of the table tallies penalty points for the cards left in their hands. Lowest cumulative penalty across hands wins the game.",
  "salem-1692":
    "A social deduction game set in colonial Massachusetts during the witch trials. Each round you privately mark a card as either accuser or accused, then debate at the table whose evidence rings true. Tryal cards stack against players over multiple rounds; reach the threshold and you swing from the gallows. Hidden conspiracy cards add personal goals — escape town, frame the constable, marry the magistrate — that warp the public vote. The town wins by surviving without losing too many innocents; the witches win by claiming enough of the village in turn.",
  schafkopf:
    'A Bavarian trick-taking card game for four players using a thirty-two-card pack stripped of the lower numbers. Each hand opens with bidding — a soloist may declare a "Sauspiel," a "Wenz," or a full "Solo" — which fixes trump and partnership for that hand. The remaining trio plays cooperatively against the soloist\'s team. Trick play follows strict suit-rank rules; the dance is figuring out which other player is your unknown partner before the round resolves. Whichever team takes more than half of the card points wins the hand.',
  "scotland-yard":
    "One player is Mister X, hiding inside the London transport network; the rest play Scotland Yard detectives trying to corner him. Each round every detective and X spends a transport token — taxi, bus, or underground — and moves along a public map. Mister X moves in secret, but has to reveal his position on specific turns and is fully visible on the final turn. Detectives have limited tokens and no way to share them. Surround Mister X on his last reveal and the detectives win; otherwise Mister X escapes London.",
  "secret-hitler":
    "A 1930s-flavored social deduction game in which the German Reichstag is electing chancellors that pass either Liberal or Fascist policies — and one of the Fascists is secretly Hitler. Each round the elected president and chancellor draw three policy cards in secret and enact one of them. Lies pile up about who saw what; powers unlock as Fascist policies stack. Liberals win by enacting five Liberal policies or assassinating Hitler; Fascists win by enacting six Fascist policies or electing Hitler chancellor after a certain point. The room never knows for sure.",
  "senso-battle-for-japan":
    "A two-player asymmetric wargame about the late-Sengoku unification of Japan. One side plays the western Toyotomi coalition pressing eastward; the other side plays the Tokugawa eastern league bracing for the campaign that will become Sekigahara. Card-driven activations fire armies across a regional map of clans, castles, and supply lines. Diplomatic cards swap clan loyalty mid-campaign and weather cards delay marches by an entire season. Whoever takes Kyoto or eliminates the rival's primary daimyo at game end wins.",
  set: 'A pattern-spotting card game played simultaneously rather than in turns. Twelve cards are laid out and every player races to spot a "set" — three cards in which each of four properties (color, shape, shading, count) is either all the same or all different across the trio. Call a set, grab the three cards, and the dealer fills the gap. False calls cost a card. Whoever has the most sets when the deck runs out wins, though some house rules let one player end the round early on a sudden pile.',
  "skip-bo":
    "A sequential card game in which each player gets a personal stockpile and races to be the first to empty it. Each turn you draw five cards into your hand, then play any of them — plus the top of your stockpile — onto four shared building piles that start at 1 and have to be filled in strict ascending order up to 12. Skip-Bo wild cards substitute for any number you need. You can also stash cards on personal discard piles. Empty your stockpile and you win.",
  "sky-team":
    "A two-player cooperative game where one of you plays the pilot and the other plays the co-pilot, landing a commercial jet that's been programmed by an aggressively distracted air traffic computer. Each round you both roll dice in secret and silently slot them into the cockpit panel's tracks — flaps, gear, engines, communications, axis tilt — without talking about which dice you took. Misalignments slam the plane out of the sky. Communicate through the panel slots only, finish all the approach phases of the chosen airport, and you land safely as a team.",
  "slay-the-spire":
    "A solo deckbuilding adventure adapted from the video game. You pick one of four characters and climb a procedurally generated spire, picking your route along a node map of combats, elites, shops, treasures, and unknown events. Combats play out by spending energy to drop cards from a hand drawn each turn — attack, defend, power, debuff — and grow your deck with new cards harvested from each fight. A losing run resets the spire and unlocks new cards; reach the boss of the third floor and you win the run.",
  "stadt-land-vollpfosten-christmas":
    "A holiday edition of the rapid-fire German party game. A letter is drawn from the deck and a kitchen timer starts; every player frantically fills in their personal sheet with words starting with that letter across themed columns (Christmas tree decorations, holiday songs, gift ideas, etc.). When the timer rings, you score points based on whether your answers are unique or shared by other players. The booklet is funny on purpose. Highest score after ten rounds takes the Stollen.",
  "sushi-go":
    "A drafting game played with hand-illustrated sushi cards. Each player is dealt a hand and picks one card to keep before passing the rest to the left; the round ends when every hand is exhausted. Cards score in different ways — make-a-set, scoring-by-count, simple points, dessert-buffer for later rounds — so each pass forces a trade-off between greed and denial. The deal-and-pass cycle repeats three times and dessert cards score across the whole game. Highest total after three rounds plus dessert wins.",
  targi:
    'A two-player game set among the Tuareg of the Sahara, where you move three meeple around the outer edge of a five-by-five grid representing market days. Each round you place your three workers along the rows and columns — the spaces where your row and column meet become "cross-points" that you can also collect, opening up a slightly bigger action menu. Goods, gold, and tribe cards fund the prestige track. First player to twelve victory points wins.',
  "tellstones-kings-gambit":
    "A two-player abstract from the League of Legends universe, played with five rune-marked tokens and a wooden tray. Each round you set out tokens face-up and face-down, then take turns swapping, peeking, and bluffing about their order. The active player can challenge the rival's claim — be wrong about what's on the table and you give up the round. Three rounds per match, best-of-three takes it. Read your opponent, remember the placements, and call them out at the right moment.",
  "the-crew-mission-deep-sea":
    "The follow-up to the Quest for Planet Nine. Three to five astronauts run a cooperative trick-taking deck across themed missions in a campaign-style mission book. Each mission hands out task cards that one player has to specifically win — a specific card, a specific trick number, an ordering between players — while every other trick still has to be claimed by somebody. Communication is sharply limited: each player gets a single token they can use once per round to telegraph one card's role in their hand. Complete every task in the mission to win as a crew.",
  "the-crew-quest-for-planet-nine":
    "A cooperative trick-taking campaign in which you and your crew fly toward a hypothetical ninth planet. Each round deals task cards that specific players have to win — the captain might need a trick that contains the red 5, while another teammate must take the very first trick. You play trick-taking exactly like a hearts variant, except the deal-out of tasks and a single per-round communication token are the only legal channels between crewmates. Clear every task in the mission and the team progresses; miss one and you retry.",
  "the-fox-in-the-forest":
    "A two-player trick-taking card game with a fairy-tale wrapper. You and one opponent play a thirty-three-card deck with three suits, taking tricks like a tiny version of Spades. Eleven of the cards are decree cards whose powers fire when played — change trump for the rest of the hand, swap with a leading card, redraw, etc. The twist of the scoring: take too many tricks and you score zero; take too few and you score zero. Aim for the sweet spot and beat your opponent across rounds.",
  "the-old-kings-crown":
    "A two-to-four-player kingdom-builder set in a dying fairy realm. Each round you bid hidden cards for a slate of court characters and resource tracks — knights, witches, beggars, bards — that join your court or seed your opponent's. Court members trigger abilities in turn order, and the resources you collect feed a tableau-building phase where you turn cards into towers, kingdoms, and crowns. End-game scoring counts crowns plus the asymmetric combos your court enabled. Most prestige when the king's mourning ends takes the throne.",
  "the-resistance":
    "A social deduction game where every player draws a hidden role — resistance fighter or imperial spy — and the resistance has to pass enough sabotage-able missions to win. Each round the leader picks a team for a mission and the table votes whether to send that team; once a team is approved, the team members secretly pass success or fail cards into the mission. A single fail on most missions ruins it. The resistance wins by passing three missions; the spies win by sabotaging three or by forcing five vetoed teams in a row.",
  "thurn-and-taxis":
    "You and the rest of the table build postal routes across early-modern central Europe, taking cards of city names from a shared market and laying them into your in-progress route. Cities have to chain by adjacency, so the cards you pick aren't free choices — they're constrained by which city last joined your road. Completed routes unlock postal-office tokens, carriages, and bonus cards. End-game scoring blends route length, region coverage, and carriage value. Most postal points wins.",
  "tortuga-1667":
    "A short pirate social-deduction game where two crews share one ship until the captain dies, treasure goes missing, and the table devolves into a mutiny. Hidden role cards split everyone into two crews with their own win conditions; action cards let you peek, swap, slap, or stab between turns. The map is a single deck of seven cards representing the ship and the surrounding sea, and any card flip can shift who's loyal to whom. Whichever crew completes its win condition first takes the gold.",
  "trivial-pursuit":
    'The classic six-category trivia race. You roll a die and move around a wheel-shaped board, landing on geography, entertainment, history, literature, science, or sports squares, answering trivia cards drawn from a central deck. Land on a colored "pie" space and a correct answer earns you a pie wedge in that category. Once you\'ve collected all six wedges you race for the center of the board and try to answer one final card chosen by an opponent. Get it right and you win.',
  uno: 'A shedding card game where you race to empty your hand. The deck holds numbered cards in four colors plus action cards — skip, reverse, draw two, wild, wild draw four — and you have to match either color or number to the top of the discard pile. If you can\'t play, you draw. Calling "Uno" when you reach a single card is the rule everyone forgets; forget it and the table forces you to pick up a couple more. First to zero cards wins the hand.',
  "uno-flip":
    'The double-sided variant of UNO. Cards have a light side (numbers 1–9 in four colors plus the usual actions) and a dark side (numbers 1–9 plus harsher draw-five, skip-everyone, and wild-draw-color penalties). A Flip card on the table flips every player\'s hand and the discard pile to its other side at once. Shedding rules carry across both sides; somebody calls "Uno" with one card left or pays the table for forgetting. First to empty their hand wins.',
  "uno-show-em-no-mercy":
    "The high-pain UNO variant featuring stack-able draw cards, draw-tens, all-color wilds, skip-everyone fans, and a brutal mercy rule that resets a player back to a starting hand if they hit twenty-five cards. Discard your way to zero cards through a thicker deck than classic UNO; the action cards are bigger, the wilds nastier, and the room-table contracts harsher. Same matching rule as classic UNO: color or number, with action cards firing as written. First to empty their hand wins the hand.",
  upwords:
    "A Scrabble-style word game where you can build words by stacking lettered tiles on top of existing tiles. Each tile is one letter and one stack-level high; words score on stack-height plus tile count, so taller stacks pay more per tile. You cannot stack a letter on top of the same letter, so every new layer is also a real word in itself. The board is a ten-by-ten grid. Most points after the bag empties and the racks clear wins.",
  villainous:
    "An asymmetric Disney game where every player picks a different Disney villain — Ursula, Maleficent, Captain Hook, Jafar, the Queen of Hearts — and works toward that villain's specific scenario goal. Each villain has a dedicated location track and two custom decks of action/event cards. On your turn you move along your track, take location actions, and play villainous cards from your hand to attack rivals through their own Fate decks. There's no shared win condition: whoever completes their villain's personal objective first wins.",
  wavelength:
    'A psychic team-versus-team game built around a hidden dial. The active psychic looks at a spectrum card with two opposing concepts on it ("hot and cold", "weird and normal", "useful and useless") and a randomly chosen target sweet-spot under a screen. They give a single-phrase clue that lands somewhere on that spectrum, then their team rotates a public dial trying to match the hidden target. Score points by hitting the bullseye; the other team gets one chance to bet left or right of your team\'s guess. First team to ten points wins.',
  "wer-wars":
    'A homebrew deduction round inspired by Werewolf and Mafia, themed around the question "Who Was It?" Roles are dealt face down at the start: most of the room are villagers trying to find a hidden killer, but a handful of secondary roles tilt information in confusing directions. Day phases are loose group debate; night phases are silent role activations. The killer wins by reducing the village to parity; the village wins by lynching the killer before that happens.',
  wizard:
    "A trick-taking card game built around a single brutal twist: at the start of each hand every player privately bids exactly how many tricks they will take, and you only score points if you hit your bid exactly. Wizards and Jesters cards always win or always lose tricks respectively, regardless of suit or rank. Hands grow by one card per round, peaking at the deck size and ratcheting up the bid math accordingly. After all rounds you tally cumulative score and the highest total takes the wizard hat.",
  "wo-wars":
    'A homebrew counterpart to Who Was It?, themed instead around the question "Where Was It?" Players are dealt scene-location cards face down and the table has to deduce — through indirect questions and partial reveals — where each player\'s character actually is. Hidden roles shift the win conditions: some players need their location guessed, others need it kept hidden, and a small minority win only by misleading everyone. End-game reveals settle who reconstructed the truth and who was bluffing successfully.',
};
