// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug hot-pot-holic
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light trick-taker where played ranks set turn order and how many ingredient cards get plated or eaten for scoring.",
  default:
    "Light trick-taker about timing when to grab ingredient cards and when to eat them. Each round, players play unique ranks, then use their rank position to take cards from the table to a plate or move plate cards to the stomach. After eight rounds, eaten cards score from the revealed scoring cards, and the highest total wins.",
  loose:
    "Family-weight trick-taker about jockeying for turn order around a shared hot pot of ingredient cards. Each round, players play one card with a rank not already used, then act in that rank order: take that many cards from the table to a plate or eat that many from the plate. After eight rounds, only eaten cards score against the revealed scoring cards, and the highest total wins. A 0 and K in the same trick flips the strength card, so first and last can swap at the worst moment.",
};

export const meta = {
  generatedAt: "2026-08-04T10:22:36.589Z",
  model: "gpt-5.5",
  durationMs: 32739,
  sources: [
    "https://www.tbd.com.tw/products/hot-pot-holic",
    "https://www.asianboardgamesfestival.com/product-page/hot-pot-holic",
    "https://www.vindjeu.eu/prd/2024/11/03/hot-pot-holic/",
    "https://punchboardgame.blogspot.com/2025/05/hot-pot-holic-tbd.html",
  ],
} as const;
