// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug villainous-introduction-to-evil
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Asymmetric family strategy card game where each villain moves on a realm board, plays cards, and fires Fate cards at rivals.",
  default:
    "Asymmetric family strategy card game where each villain races toward a different Disney objective. On a turn, move a sculpted villain to a new realm space, take its action icons, play cards, gain power, vanquish heroes, or Fate a rival. First villain to complete their objective wins.",
  loose:
    "Asymmetric family strategy card game where each villain races toward a different Disney objective. On a turn, move a sculpted villain to a new realm space, take its action icons, play cards, gain power, vanquish heroes, or Fate a rival. First villain to complete their objective wins, such as Prince John hoarding power and locking up Robin Hood. This beginner set trims the original box to Maleficent, Captain Hook, Ursula, and Prince John with rebalanced cards.",
};

export const meta = {
  generatedAt: "2026-07-11T20:33:59.553Z",
  model: "gpt-5.5",
  durationMs: 12119,
  sources: [
    "https://lorcana.ravensburger.us/en-US/us/ravensburger-disney-villainous-introduction-to-evil",
    "https://pixelkin.org/2023/07/26/disney-villainous-introduction-to-evil-review/",
    "https://www.meeplemountain.com/reviews/disney-villainous-introduction-to-evil/",
  ],
} as const;
