// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug villainous-introduction-to-evil
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/web/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Asymmetric Disney strategy card game where each villain moves across a personal board, plays schemes, and fires Fate cards at rivals.",
  default:
    "Asymmetric strategy card game where each villain races toward a different evil objective on a personal realm board. On a turn, move to another location, take its action icons, spend power on cards, or use Fate to hinder a rival. The first villain to complete their own objective wins.",
  loose:
    "Asymmetric strategy card game where each villain races toward a different evil objective on a personal realm board. On a turn, move the sculpted mover to another location, take its action icons, spend power to play allies, items, curses, or effects, then refill to four cards. The first villain to complete their own objective wins. Fate actions pull heroes from a rival’s movie deck and drop them over action spaces to slow that player down.",
};

export const meta = {
  generatedAt: "2026-05-23T15:06:29.670Z",
  model: "gpt-5.5",
  durationMs: 35191,
  sources: [
    "https://www.ravensburger.us/en-US/products/games/family-games/disney-villainous-introduction-to-evil-60001998",
    "https://www.cgmagonline.com/review/tabletop/villainous-introduction-to-evil/",
    "https://pixelkin.org/2023/07/26/disney-villainous-introduction-to-evil-review/",
  ],
} as const;
