// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug project-l
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light polyomino engine-builder where turns draft puzzle tiles, upgrade pieces, and fit shapes into recessed boards.",
  default:
    "Light abstract polyomino engine-builder about filling puzzle tiles with acrylic pieces. On a turn, take three actions: draft a puzzle, upgrade a piece, place a piece, recycle a row, or use Master to place across several puzzles. Completed puzzles give points and new pieces; highest score wins after the black deck runs out.",
  loose:
    "Light abstract polyomino engine-builder about filling recessed puzzle tiles with Tetris-like acrylic pieces. Each turn, take three actions: draft a white or black puzzle, upgrade a piece, place a piece, recycle a market row, or use the Master action to place on several puzzles. Completed puzzles return all pieces, add a new piece to your supply, and score points; after the black deck runs out, highest score wins. The table feel is mostly heads-down efficiency, with satisfying chunky pieces and little direct blocking.",
};

export const meta = {
  generatedAt: "2026-08-17T00:32:04.043Z",
  model: "gpt-5.5",
  durationMs: 20346,
  sources: [
    "https://www.boardcubator.com/games/project-l/",
    "https://www.northstreetgames.com/images/Rulebooks/Project-L-Rulebook-v2.5.pdf",
    "https://shelfgamer.com/reviews/project-l/",
  ],
} as const;
