// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug electropolis
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Thinky tile-laying city builder where mayors draft power-plant tiles and permits, then fit them into personal city grids.",
  default:
    "Thinky tile-laying city builder about balancing electricity, pollution, and public support. Each round, mayors pick a turn-order slot, draft adjacent tiles from a face-up ring, and place them in a permitted city zone. Highest score after eight rounds wins.",
  loose:
    "Thinky tile-laying city builder about balancing electricity, pollution, and public support. Each round, mayors choose a turn-order slot that trades early drafting for fewer tiles, then take a contiguous run from a face-up ring. A development card limits where coal, gas, nuclear, green, fuel, waste, and civic tiles may go. After eight rounds, highest score wins from powered plants, card bonuses, support, and pollution penalties.",
};

export const meta = {
  generatedAt: "2026-08-04T10:22:28.535Z",
  model: "gpt-5.5",
  durationMs: 24685,
  sources: [
    "https://opinionatedgamers.com/2019/10/07/dale-yu-review-of-electropolis/",
    "https://tesera.ru/images/items/1890031/Electropolis_-_English_rules.pdf",
    "https://www.tbd.com.tw/products/electropolis",
  ],
} as const;
