// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug publish-or-perish
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Humorous party card game where researchers stack paper ingredients, fire sabotage cards, and chase the most citations.",
  default:
    "Humorous party card game with light take-that, racing to publish fake academic papers for citations. Each turn, players play research cards such as idea, data, references, and writing, or use actions like plagiarism, workshops, audits, and Reviewer 2 on rivals. After defense speeches and award votes, highest citation total wins.",
  loose:
    "Humorous party card game with light take-that, aimed at table jokes more than optimization. On a turn, a player lays research cards like idea, data, references, and writing onto a manuscript, answers trivia, or drops actions such as collaboration, plagiarism, IRB audit, or Reviewer 2 to help or hurt. When someone finishes enough manuscripts, everyone gives defense speeches, votes awards, adds citations, and the highest total wins. Every publication triggers applause and the chant, “Congratulations on your publication!”.",
};

export const meta = {
  generatedAt: "2026-08-04T10:23:03.763Z",
  model: "gpt-5.5",
  durationMs: 59913,
  sources: [
    "https://publishorperish.games/",
    "https://publishorperish.games/products/the-publish-or-perish-game",
    "https://www.hiveinteractive.net/projects/the-publish-or-perish-game-246/posts/w0Oxx80KNhY",
    "https://economistwritingeveryday.com/2024/08/10/publish-or-perish-a-hilarious-card-game-based-on-academia/",
  ],
} as const;
