// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug sky-team
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Final approach becomes a silent cockpit puzzle, with dice placement turning every roll into pitch, speed, radio, gear, and nerve.",
  default:
    "Two pilots share a tense final approach under a no-talking rule after the roll. Dice placement drives the cockpit, from axis and engines to radios, flaps, gear, brakes, and coffee. Landing means reaching the runway with clear traffic, level wings, safe speed, and every system ready.",
  loose:
    "Two pilots face the final minutes of an airliner landing, where silence turns every die into a signal. Dice placement drives the cockpit, assigning rolls to axis, engines, radios, flaps, gear, brakes, and coffee. A landing succeeds only if the runway arrives with clear traffic, level wings, safe speed, and prepared systems. One promo scenario recreates Commander Robert Piché’s 2001 TS-236 glide to Lajes.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:59.483Z",
  model: "gpt-5.5",
  durationMs: 70105,
  sources: [
    "https://www.hachetteboardgames.com/products/sky-team",
    "https://www.scorpionmasque.com/fr/sky-team",
    "https://www.scorpionmasque.com/sites/scorpionmasque.com/files/st_rules01_en_06jun2023.pdf",
    "https://www.philibertnet.com/fr/blog/articles/interview-sky-team-ne-pas-faire-un-simulateur-de-vol-etait-un-gros-defi",
  ],
} as const;
