// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug sky-team
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative limited-communication dice-placement game where pilots silently slot cockpit dice to balance, slow, and land an airliner.",
  default:
    "Cooperative limited-communication dice-placement game about landing an airliner through a shared cockpit board. Each round starts with a plan, then dice go silently onto axis, engines, radio, flaps, gear, brakes, or coffee. Win by touching down level, clear, configured, and slow enough to stop.",
  loose:
    "Cooperative limited-communication dice-placement game about landing an airliner through a shared cockpit board. Each round starts with a brief plan, then both roles roll behind screens and silently place dice on axis, engines, radio, flaps, landing gear, brakes, or coffee. The team wins if the final approach clears traffic, lines up with the runway, deploys gear and flaps, stays level, and stops under brake power. Airport scenarios add wind, fuel, leaks, traffic, ice, and turbulence.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:30.248Z",
  model: "gpt-5.5",
  durationMs: 46160,
  sources: [
    "https://www.scorpionmasque.com/en/sky-team",
    "https://www.scorpionmasque.com/sites/scorpionmasque.com/files/st_rules01_en_06jun2023.pdf",
  ],
} as const;
