// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug tellstones-kings-gambit
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Seven stones turn perfect information into a memory duel, using bluffing to make a known line feel dangerous.",
  default:
    "Seven Demacian stones turn public memory into a staring contest. It is bluffing: players place, hide, swap, peek, challenge, and boast while rattling recall. Three points win, unless a Boast names every hidden stone for an instant finish.",
  loose:
    "Seven Demacian stones turn public memory into a staring contest, since every hidden symbol was once visible. It is bluffing: players place, hide, swap, peek, challenge, and boast while rattling recall. Three points win, but a Boast can end the game instantly if all facedown stones are named, or lose it on one miss. The tin holds seven engraved stones, a cloth mat, score counters, and Cithria's father's letter.",
};

export const meta = {
  generatedAt: "2026-05-13T16:41:37.165Z",
  model: "gpt-5.5",
  durationMs: 45048,
  sources: [
    "https://merch.riotgames.com/en-us/product/tellstones-board-game-english/",
    "https://nastol.io/storage/games/files/tellstones_kings_gambit/662719/tellstones-en.pdf",
    "https://www.shelfside.co/reviews2020/tellstones-review",
    "https://gamingtrend.com/reviews/a-battle-of-minds-tellstones-kings-gambit-review/",
  ],
} as const;
