// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug azul
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A shared market of bright tiles turns every tidy mosaic plan into a trap-laced drafting puzzle.",
  default:
    "A shared market of bright tiles turns an orderly mosaic into a timing puzzle. Drafting drives each round as players take all tiles of one color from a factory or the center. Overflow tiles crash onto the floor for penalties.",
  loose:
    "A shared market of candy-bright tiles turns an orderly mosaic into a knife-edge timing puzzle. Drafting drives each round: take every tile of one color from a factory or the center, then fit them into one pattern row. The highest score comes from linked wall placements and endgame rows, columns, and color sets, while overflow crashes onto the floor for penalties. The resin tiles clack into a cloth bag between rounds.",
};

export const meta = {
  generatedAt: "2026-05-13T16:28:39.632Z",
  model: "gpt-5.5",
  durationMs: 32350,
  sources: [
    "https://www.gamesradar.com/azul-board-game-review/",
    "https://cdn.svc.asmodee.net/production-nextmove/uploads/sites/4/2024/06/EN-Azul-CB-Rules_2024_compressed.pdf",
    "https://boardgamegeek.com/boardgame/230802/azul",
  ],
} as const;
