// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug azul
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Abstract tile-drafting puzzle where players take one color from shared factory discs and fit tiles into rows for mosaic points.",
  default:
    "Abstract tile-drafting strategy game about building a personal mosaic from a shared market. Each turn, take every tile of one color from a factory disc or the center and place them in one pattern row. Completed rows move tiles to the wall for adjacency points; after a horizontal row is complete, highest score wins.",
  loose:
    "Abstract tile-drafting strategy game about building a personal mosaic from a shared market of colored tiles. Each turn, a player takes every tile of one color from a factory disc or the table center, slots them into one pattern row, and sends overflow to a penalty floor. Full rows move one tile onto the wall, scoring adjacent chains; after any horizontal wall row is complete, highest score wins with end bonuses for rows, columns, and colors. The chunky resin tiles and small factory coasters make every draft easy to read across the table.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:18.759Z",
  model: "gpt-5.5",
  durationMs: 18418,
  sources: [
    "https://www.nextmove-games.com/en/azul/azul-game/",
    "https://cdn.svc.asmodee.net/production-nextmove/uploads/sites/4/2024/06/EN-Azul-Rules-Next-Move-web.pdf",
    "https://www.wargamer.com/azul/review",
  ],
} as const;
