// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug aeons-end
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative fantasy deck-builder where mages buy gems and spells, prep them in breaches, and race to kill a boss.",
  default:
    "Cooperative fantasy deck-builder about mages defending a city from one giant nemesis. On a turn, spend aether to buy gems, relics, and spells, open breaches, and prep or cast spells. The team wins by killing the nemesis or surviving its deck; the city falling or all mages collapsing loses.",
  loose:
    "Cooperative fantasy deck-builder about mages defending a city from one giant nemesis. A turn-order card names a mage or the nemesis; mage turns spend aether on gems, relics, and spells, open breaches, then prep or cast spells, while nemesis turns resolve minions and attacks. The team wins by reducing the nemesis to zero life or emptying its deck with no threats in play; Gravehold falling or every mage exhausted loses. Player decks are never shuffled, so the order of each discard pile matters.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:19.032Z",
  model: "gpt-5.5",
  durationMs: 18691,
  sources: [
    "https://indieboardsandcards.com/our-games/aeons-end/",
    "https://coopboardgames.com/cooperative-board-game-reviews/aeons-end-review/",
  ],
} as const;
