// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug aeons-end
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A besieged city turns deck-building into a boss fight, with fixed discard order making every purchased gem and spell a future plan.",
  default:
    "A besieged city turns deck-building into a boss fight against a different nemesis each session. Deck-building drives the action, but decks are flipped rather than shuffled. The mages win by killing the nemesis or outlasting its deck before Gravehold falls.",
  loose:
    "A besieged city turns deck-building into a boss fight where chaos comes from the enemy, not the player deck. Deck-building drives the action, but decks are flipped rather than shuffled, so discard order becomes a weapon. The mages win by killing the nemesis or emptying its deck before Gravehold or every mage falls. The turn deck can hand the nemesis two brutal turns in a row.",
};

export const meta = {
  generatedAt: "2026-05-13T16:32:39.960Z",
  model: "gpt-5.5",
  durationMs: 26491,
  sources: [
    "https://www.handelabra.com/aeonsend",
    "https://coopboardgames.com/cooperative-board-game-reviews/aeons-end-review/",
    "https://aeonsend.fandom.com/wiki/Aeon%27s_End_%28Core_Set%29",
  ],
} as const;
