// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug exploding-kittens
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Each draw turns the deck into a loaded trap, and hand management decides who can dodge, redirect, or delay the kitten.",
  default:
    "A silly cat deck turns every routine draw into tablewide dread as the pile thins. Hand management drives the game through Defuse, Skip, Attack, Shuffle, See the Future, and Nope cards. The last player not blasted by an Exploding Kitten wins.",
  loose:
    "A silly cat deck turns every routine draw into tablewide dread as the pile thins. Hand management drives the game: Defuse, Skip, Attack, Shuffle, See the Future, and Nope cards bend the next draw. The last player not blasted by a kitten wins, often after someone secretly plants danger for the next player. The rules’ signature panic turn is peek, Attack, get Noped, Shuffle, then draw and hope.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:54.185Z",
  model: "gpt-5.5",
  durationMs: 24587,
  sources: [
    "https://www.explodingkittens.com/products/exploding-kittens-original-edition?variant=33359892643979",
    "https://cdn.shopify.com/s/files/1/0345/9180/1483/files/ekoe-instructions-english.pdf?v=1743802429",
    "https://www.chitag.com/single-post/2015/07/15/elan-lee-on-exploding-kittens-and-more",
    "https://gamesbeat.com/exploring-the-lessons-of-the-exploding-kittens-8m-crowdfunding-campaign/",
  ],
} as const;
