// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug exploding-kittens
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light push-your-luck party card game where players play skips, attacks, and peeks before drawing from a danger deck.",
  default:
    "Light push-your-luck party card game about avoiding the knockout cards in the draw pile. On a turn, play any action cards you want, then usually draw one card. Draw an Exploding Kitten without a Defuse, and you are out; the last survivor wins.",
  loose:
    "Light push-your-luck party card game where everyone tries to dodge the knockout cards in the draw pile. On a turn, a player may skip drawing, peek at the top cards, shuffle the deck, steal with Favor, or hit the next player with Attack, then usually draws one card. A Defuse saves a player from an Exploding Kitten and hides it back in the deck; without one, that player is out, and the last survivor wins. The 56-card deck uses Matthew Inman’s Oatmeal art, so the table talk is mostly jokes, accusations, and groans when a Nope cancels a rescue play.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:27.214Z",
  model: "gpt-5.5",
  durationMs: 22498,
  sources: [
    "https://www.explodingkittens.com/products/exploding-kittens-original-edition?variant=33359892643979",
    "https://www.geekyhobbies.com/exploding-kittens-card-game-review-and-rules/",
  ],
} as const;
