// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-resistance
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Secret spies turn every mission roster into an accusation, with social deduction driven by votes, alibis, and one hidden sabotage card.",
  default:
    "Secret spies make every mission roster feel like a public trial. Social deduction drives leader nominations, majority votes, and face-down mission cards. Resistance wins with three clean missions, while spies win by forcing three failures.",
  loose:
    "Secret spies turn each proposed mission team into a public trial, where a yes vote can look as guilty as a no. Social deduction drives the table through leader nominations, majority approval votes, and face-down mission cards. The Resistance needs three clean missions, while spies need three failures or five rejected teams in one round. Don Eskridge has said his love of improv and strange human communication fed the design.",
};

export const meta = {
  generatedAt: "2026-05-13T16:31:49.135Z",
  model: "gpt-5.5",
  durationMs: 44438,
  sources: [
    "https://indieboardsandcards.com/our-games/the-resistance/",
    "https://www.ultraboardgames.com/the-resistance/game-rules.php",
    "https://pocketmags.com/us/tabletop-gaming-magazine/april-2018-17/articles/how-we-made",
  ],
} as const;
