// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-resistance
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Hidden-role party game where a leader proposes mission teams, everyone votes, and spies secretly sabotage approved teams.",
  default:
    "Hidden-role social deduction party game where rebels try to spot spies before missions are sabotaged. Each round, a leader proposes a mission team, the table votes approve or reject, and approved members secretly play success or fail cards. Three successful missions win for the rebels; three failed missions win for the spies.",
  loose:
    "Hidden-role social deduction party game where rebels argue over mission teams while spies lie from inside the group. Each round, the leader assigns team cards, everyone votes approve or reject, and an approved team secretly plays success or fail cards. Three successful missions win for the rebels; three failed missions, or five rejected teams in one round, win for the spies. No one is eliminated, so every accusation, vote pattern, and revealed fail card stays in play.",
};

export const meta = {
  generatedAt: "2026-05-13T20:25:00.656Z",
  model: "gpt-5.5",
  durationMs: 19628,
  sources: [
    "https://boardgamegeek.com/boardgame/41114/the-resistance",
    "https://www.ultraboardgames.com/the-resistance/game-rules.php",
    "https://desktopgames.com.ua/games/642/resistance_rules_en.pdf",
    "https://mechanicsofmagic.com/2022/04/07/critical-play-the-resistance/",
    "https://coopboardgames.com/cooperative-board-game-reviews/the-resistance/",
  ],
} as const;
