// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug targi
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Thinky worker-placement Euro where border meeples claim actions and crossing lines grab resource or tribe cards.",
  default:
    "Thinky worker-placement Euro about collecting goods and buying tribe cards for a personal tableau. Each round, place meeples on border actions, mark the center cards where their rows and columns cross, then take resources or pay to add cards. Highest score wins after a full tableau or the robber’s final raid.",
  loose:
    "Thinky worker-placement Euro about collecting dates, salt, pepper, and gold to buy tribe cards for a personal tableau. Each round, place meeples on border actions, then mark the center cards where their rows and columns cross and resolve those spaces in any order. Highest score wins after a full tableau or the robber’s final raid, counting card points, tokens, and row bonuses. The signature puzzle is blocking a border space while also denying the card opposite it.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:22.966Z",
  model: "gpt-5.5",
  durationMs: 16823,
  sources: [
    "https://www.thamesandkosmos.com/manuals/full/691479_Targi%20Manual.pdf",
    "https://bumblingthroughdungeons.com/targi-review/",
    "https://boardgameguys.com/targi/",
  ],
} as const;
