// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug targi
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A silent duel over a shifting desert grid turns worker placement into a knife fight for rows, columns, and blocked action spaces.",
  default:
    "Every placement gives ground and steals ground, because a border action also claims a crossing in the center grid. Worker placement drives the duel through edge figures, intersections, and denial. The higher-scoring tribe display wins.",
  loose:
    "Every placement gives ground and steals ground, because a border action also claims a crossing in the center grid. Worker placement drives the duel: three Targi figures mark edge spaces, then tribe markers take the cards where those rows and columns meet. Victory comes from a 12-card tribal display, with points for cards and row bonuses. The robber circles the 16-card border as a visible countdown.",
};

export const meta = {
  generatedAt: "2026-05-13T16:41:22.909Z",
  model: "gpt-5.5",
  durationMs: 34957,
  sources: [
    "https://www.kosmos.de/de/targi_1691479_4002051691479",
    "https://thamesandkosmos.com/manuals/full/691479_Targi%20Manual.pdf",
  ],
} as const;
