// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug elements-of-truth
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Science-trivia party game where each answer is also a wager, spending numbered confidence chips on guesses.",
  default:
    "Science-trivia party game about betting on how sure an answer feels. Each round, a reader asks a card and everyone else secretly places one numbered confidence chip on an answer. Correct chips score, wrong chips are lost, and the highest total after ten questions wins.",
  loose:
    "Science-trivia party game about knowing when to bet big and when to admit a guess. Each round, one reader asks a card, everyone else answers at once, and each answer gets one face-down confidence chip numbered 1 to 10. Correct chips go to a scoring pile, wrong chips are discarded, and the highest chip total after ten questions wins. Questions include true/false, multiple choice, higher-or-lower, and number-line answers written on small whiteboards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:14.613Z",
  model: "gpt-5.5",
  durationMs: 19875,
  sources: [
    "https://www.gizmocrowd.com/post/elements-of-truth-game-kickstarter",
    "https://www.wargamer.com/veritasium-elements-of-truth/kickstarter",
    "https://zatu.com/blogs/news/elements-of-truth-launches-on-kickstarter",
  ],
} as const;
