// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug go
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Abstract territory strategy game where opponents place black and white stones on grid intersections to fence off space and trap groups.",
  default:
    "Abstract territory strategy game about building living groups and enclosing empty intersections. On a turn, place one stone on any empty point or pass; surrounded enemy strings lose their last liberty and come off as prisoners. When both sides pass, dead groups are removed and the higher score wins from territory, prisoners, and komi.",
  loose:
    "Abstract territory strategy game about building living groups and enclosing empty intersections. On a turn, place one black or white stone on any empty point or pass; surrounded enemy strings lose their last liberty and come off as prisoners. When both sides pass, dead groups are removed and the higher score wins from territory, prisoners, and komi. The signature table image is a plain wooden grid filling with stone walls, cuts, eyes, and ko threats.",
};

export const meta = {
  generatedAt: "2026-08-14T22:19:53.027Z",
  model: "gpt-5.5",
  durationMs: 18418,
  sources: [
    "https://www.cs.cmu.edu/~wjh/go/rules/AGA.concise.html",
    "https://www.britgo.org/intro/intro2.html",
    "https://www.britgo.org/rules/compare.html",
  ],
} as const;
