// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug codenames-pictures
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Surreal picture cards turn one-word clues into risky leaps of word association across a silent team grid.",
  default:
    "Surreal picture cards make every clue a gamble between clever links and deadly overreach. Word association drives play as spymasters give one word and a number. A team wins by finding all its agents first, unless someone hits the assassin.",
  loose:
    "Surreal picture cards make each clue a gamble, because one image can point to a whale, a moon, or a trapdoor. Word association drives play: a spymaster gives one word and a number, then sits silent while the team chooses cards. A team wins by finding all its agents first, unless a guess hits the assassin. The picture version uses a 5×4 grid, so fewer cards create stranger visual overlaps.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:48.396Z",
  model: "gpt-5.5",
  durationMs: 67893,
  sources: [
    "https://www.czechgames.com/games/codenames-pictures/",
    "https://tabletoptogether.com/2017/08/21/review-codenames-pictures/",
  ],
} as const;
