// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug codenames-pictures
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Team party deduction game where spymasters give one-word, numbered clues so teammates choose the right picture cards.",
  default:
    "Team party deduction game about reading visual associations from a grid of odd picture cards. Each turn, a spymaster says one word and a number, then teammates discuss and touch cards one at a time. First team to cover all its agents wins, but picking the assassin loses instantly.",
  loose:
    "Team party deduction game about reading visual associations from a grid of odd picture cards. Each turn, a spymaster says one word and a number, then teammates argue over which images match and touch cards one at a time. Correct picks get covered with friendly agent tiles, while enemy agents and bystanders end the turn; the first team to find all its agents wins, and the assassin loses instantly. The key card secretly maps the grid into agents, bystanders, and the assassin.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:34.182Z",
  model: "gpt-5.5",
  durationMs: 13142,
  sources: [
    "https://www.codenamesgame.com/boardgames/codenames-pictures",
    "https://www.czechgames.com/files/rules/codenames-pictures-rules-en.pdf",
    "https://www.tabletopgaming.co.uk/features//codenames-pictures-review",
  ],
} as const;
