// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wer-wars
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A talking treasure chest turns a children’s mystery into a ticking castle scramble of deduction and animal bribes.",
  default:
    "The electronic chest makes a children’s whodunit feel like a castle listening to every move. Deduction drives the group through rooms, animal clues, and crossed-off suspects. The team wins by finding the thief before the wizard reaches the gate.",
  loose:
    "A talking treasure chest makes this children’s whodunit feel like a castle listening to every move. Deduction drives the group as pawns search rooms, feed animals, and turn clues into crossed-off suspects. The team wins only by naming the thief and opening the right chest before the wizard reaches the gate. The chest voices the animals, advances the clock toward 6 o’clock, and can send a ghost through the rooms.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:43.365Z",
  model: "gpt-5.5",
  durationMs: 24834,
  sources: [
    "https://www.ravensburger.org/spielanleitungen/ecm/Spielanleitungen/22094%20Whoowasit_GB_72dpi.pdf",
    "https://crowscastle.com/board-games/147-whoowasit.html",
    "https://idleremorse.com/2019/02/24/review-whoowasit/",
    "https://www.meeplemountain.com/articles/the-reiner-knizia-alphabet-the-letter-w/",
  ],
} as const;
