// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wer-wars
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative family deduction game where players roam a castle, question animals, collect food, and narrow down a thief.",
  default:
    "Cooperative family deduction game about searching a castle for the thief who stole the king’s ring. On a turn, roll to move, press the matching room button on the electronic chest, then search, talk, feed an animal, use magic, or try a chest. The team wins by identifying the thief and opening the right chest before time runs out.",
  loose:
    "Cooperative family deduction game about searching a castle for the thief who stole the king’s ring. On a turn, roll to move through rooms, press the matching animal button on the electronic chest, then search, talk, feed an animal, use magic, or try a suspect’s chest. The team wins by ruling out suspects, reaching the right room with a key, and opening the thief’s chest before time runs out. The plastic chest speaks clues and events, while the ghost can shove pawns back to the nursery.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:36.959Z",
  model: "gpt-5.5",
  durationMs: 20296,
  sources: [
    "https://www.ravensburger.org/spielanleitungen/ecm/Spielanleitungen/22094%20Whoowasit_GB_72dpi.pdf",
    "https://idleremorse.com/2019/02/24/review-whoowasit/",
    "https://www.ultraboardgames.com/whoowasit/game-rules.php",
  ],
} as const;
