// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug poker
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight: "Facedown cards make every pot a contest of nerve and probability, driven by betting.",
  default:
    "Facedown cards turn a five-card hand into a test of nerve. Betting drives the game as players call, raise, or fold. The pot goes to the strongest shown hand, unless pressure makes every rival fold first.",
  loose:
    "Facedown cards make every pot a contest between math, nerve, and lies. Betting drives the game as players call, raise, or fold around the table. A hand wins by showing the strongest five-card combination, or by making every rival fold first. Parlett traces the early Mississippi game from 20 cards to 52 as draw poker and larger tables took hold.",
};

export const meta = {
  generatedAt: "2026-05-13T16:38:13.457Z",
  model: "gpt-5.5",
  durationMs: 29335,
  sources: [
    "https://www.pagat.com/poker/rules/",
    "https://www.britannica.com/topic/poker-card-game",
    "https://bicyclecards.com/how-to-play/basics-of-poker",
    "https://www.pagat.com/poker/history.html",
  ],
} as const;
