// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug poker
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Bluffing card game where players bet chips on hidden hands, fold to pressure, or win pots with the best shown cards.",
  default:
    "Classic bluffing card game built around hidden information, chip bets, and ranked five-card hands. On a deal, players check, bet, call, raise, or fold as cards are dealt or exchanged. Each pot goes to the last player left or the best hand at showdown; most chips at the end wins.",
  loose:
    "Classic bluffing card game built around hidden information, chip bets, and ranked five-card hands. On a deal, players receive private cards, then check, bet, call, raise, or fold as cards appear or are exchanged under the chosen variant. Each pot goes to the last player left after folds or to the best shown hand; the session winner has the biggest chip stack when play stops. The signature moment is a quiet raise with bad cards, daring better hands to throw themselves away.",
};

export const meta = {
  generatedAt: "2026-05-13T20:20:50.636Z",
  model: "gpt-5.5",
  durationMs: 18887,
  sources: [
    "https://www.britannica.com/topic/poker-card-game",
    "https://www.britannica.com/topic/poker-card-game/Skillful-play",
  ],
} as const;
