// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug feed-the-kraken
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Three-faction hidden-roles game where sailors, pirates, and a secret cult steer one ship by passing face-down navigation cards.",
  default:
    "Hidden-roles deduction game with three secret factions sharing one ship. Each round the captain and lieutenant each keep one of two course cards, and the navigator plays one. Whoever's destination the ship reaches wins.",
  loose:
    "Hidden-roles deduction game with three secret factions sharing one ship: sailors, pirates, and a cult. Each round the captain picks a lieutenant and navigator, both officers keep one of two course cards, and the navigator plays one blind to who chose it. Sailors win at Bluewater Bay, pirates at Crimson Cove, the cult at the Kraken. Crew can stage a mutiny with hidden gun tokens, and the cult leader recruits converts mid-game.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.335Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 150000,
  sources: [
    "https://officialgamerules.org/game-rules/feed-the-kraken-rules/",
    "https://zatu.com/en-us/blogs/reviews/feed-the-kraken-review",
    "https://en.wikipedia.org/wiki/Feed_the_Kraken",
  ],
} as const;
