// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug one-king-one-crown
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Negotiation and betrayal card game where nobles play cards to steal gold and out-earn the King, then grab the crown the moment they do.",
  default:
    "Negotiation and betrayal card game set in a medieval royal court. Each round the King plays three cards and each noble two, then the table gets two minutes to trade gold, swap cards, and strike non-binding deals. Whoever wears the crown after round four wins.",
  loose:
    "Negotiation and betrayal card game set in a medieval royal court. Each round the King plays three cards and each noble two to gain gold, drain rivals, or lay face-down Knights, followed by two minutes of non-binding trades and deals. Anyone richer than the King takes the crown, and whoever holds it after round four wins. Betrayal cards fizzle unless another player backs them, and a new King physically swaps seats with the old one.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.336Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 150000,
  sources: [
    "https://onecrown.store/",
    "https://cdn.shopify.com/s/files/1/1045/2605/3717/files/Game_Guide_Print.pdf?v=1789294911",
  ],
} as const;
