// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug skip-bo
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Sequencing card game where players draw to five, build shared 1-to-12 piles, and manage discards to empty a stockpile.",
  default:
    "Light sequencing card game about racing through a personal stockpile while feeding shared center piles. Each turn, a player refills to five cards, plays legal numbers from hand, stockpile, or exposed discard tops, then discards one card. First to empty the stockpile wins.",
  loose:
    "Light sequencing card game about racing through a personal stockpile while feeding shared center piles. Each turn, a player refills to five cards, plays legal numbers from hand, stockpile, or exposed discard tops, then parks one card on a personal discard pile. First to empty the stockpile wins, with optional match scoring for cards left in opposing stockpiles. The key table puzzle is four personal discard columns, because only the top card of each can be used later.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:50.167Z",
  model: "gpt-5.5",
  durationMs: 21171,
  sources: [
    "https://m.service.mattel.com/us/Technical/productDetail?prodno=42050&siteid=27",
    "https://service.mattel.com/instruction_sheets/N7808.pdf",
    "https://boardgamegeek.com/wiki/page/thing%3A1269",
  ],
} as const;
