// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug skip-bo
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A race to shed a buried stockpile turns simple counting into tense hand management across four shared ascending piles.",
  default:
    "A race to shed a face-up stockpile turns every useful play into a favor for rivals. Hand management drives five-card hands, personal discards, and shared piles from 1 to 12. The first empty stockpile wins, with Skip-Bo wild cards breaking the sequence.",
  loose:
    "A race to shed a face-up stockpile turns every useful play into a favor that may open the table for rivals. Hand management drives the game, as cards move from a five-card hand, four personal discards, and shared piles climbing from 1 to 12. The first empty stockpile wins, while Skip-Bo wild cards bridge gaps or start piles. Minnie Hazel Skip Bowman boxed her Spite and Malice variant in Texas in 1967.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:52.496Z",
  model: "gpt-5.5",
  durationMs: 68387,
  sources: [
    "https://service.mattel.com/instruction_sheets/42050-Skip-Bo.pdf",
    "https://service.mattel.com/us/productDetail.aspx?prodno=42050&siteid=27",
    "https://boardgameguys.com/skip-bo/",
    "https://www.diabolicalplots.com/tabletop-game-review-skip-bo/",
  ],
} as const;
