// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug uno
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "One matching card can save a hand from a Draw Two pileup in this quick hand management classic of colors, numbers, and wilds.",
  default:
    "Every near-empty hand sits one missed shout from punishment, while Skip, Reverse, and Draw cards wreck the table’s rhythm. Hand management drives each turn. Rounds end when one player sheds the last card, with leftovers feeding the score toward 500.",
  loose:
    "Every near-empty hand sits one missed shout from punishment, while Skip, Reverse, and Draw cards wreck the table’s rhythm. Hand management drives each turn: play a card that matches the discard pile by color, number, or action, or draw. Rounds end when one player sheds the last card, with leftovers feeding the score toward 500. Current decks add color symbols and blank Wild Cards for house rules.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:17.398Z",
  model: "gpt-5.5",
  durationMs: 28504,
  sources: [
    "https://shop.mattel.com/products/uno-card-game-42003",
    "https://service.mattel.com/instruction_sheets/B0001-Eng.pdf",
    "https://mattel.iprsoftware.com/news/unoR-celebrates-50-years-of-bringing-people-together",
  ],
} as const;
