// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug uno
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light hand-shedding card game where players match color or number, fire off action cards, and race to empty their hands.",
  default:
    "Light family hand-shedding card game where players race to dump a hand by matching the top discard’s color, number, or symbol. On a turn, a player lays one matching card or a wild, or draws from the deck if stuck. A round ends when one hand is empty; score cards left in other hands, and first to 500 points wins.",
  loose:
    "Light family hand-shedding card game where players race to dump a hand by matching the top discard’s color, number, or symbol. On a turn, a player lays one matching card or a wild, or draws from the deck if stuck. Emptying a hand ends the round; score cards left in other hands, and first to 500 points wins. The loud table moment is the one-card warning: miss it and get caught, then draw two penalty cards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:16.592Z",
  model: "gpt-5.5",
  durationMs: 28783,
  sources: [
    "https://shop.mattel.com/products/uno-card-game-42003?bvstate=pg%3A2%2Fct%3Ar&psrid=337165450",
    "https://m.service.mattel.com/us/Technical/productDetail?prodno=42003",
    "https://m.service.mattel.com/us/Technical/productDetail?prodno=W2085",
    "https://service.mattel.com//instruction_sheets/W2085-Eng.pdf",
  ],
} as const;
