// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug joking-hazard
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Adult party judging card game where a rotating judge starts a crude comic and everyone submits the funniest final panel.",
  default:
    "Adult party judging card game about building crude three-panel comics. Each round, a judge reveals a panel, adds a setup card, and everyone else submits a face-down ending card. The judge reads the comics aloud and awards the round; first to three wins.",
  loose:
    "Adult party judging card game about making the funniest awful three-panel comic from Cyanide & Happiness-style panel cards. Each round, a judge reveals a starting panel and adds a setup card, then everyone else submits a face-down panel to finish the strip. The judge reads each comic aloud and awards the round to the one they like most; first player with three winning cards wins. Red-bordered cards trigger bonus rounds where players build a two-card setup around a fixed punchline.",
};

export const meta = {
  generatedAt: "2026-08-17T00:31:45.189Z",
  model: "gpt-5.5",
  durationMs: 12883,
  sources: [
    "https://www.jokinghazardgame.com/",
    "https://www.spiele-offensive.de/gfx/cf/joking_hazard/JH_Rules_ENG.pdf",
    "https://skipaturn.com/2017/01/16/asbestos-and-depression-a-joking-hazard-review/",
  ],
} as const;
