// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-crew-quest-for-planet-nine
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Silent astronauts turn every card into a clue in cooperative trick-taking with rockets as trump and table talk rationed to one signal.",
  default:
    "Shared silence makes familiar card play feel like a pressure test for trust and inference. It uses trick-taking with rockets as trump and table talk sharply limited. The crew succeeds only when each player wins the exact task cards assigned for that mission.",
  loose:
    "Shared silence makes familiar card play feel like a pressure test for trust and inference. It uses trick-taking: follow suit when possible, let rockets trump, and read intent from every discard. The crew succeeds only when each player wins the exact task cards assigned for that mission. A radio token can mark one card as highest, lowest, or only in its suit, turning a tiny clue into a table-wide argument conducted in stares.",
};

export const meta = {
  generatedAt: "2026-05-13T16:41:49.840Z",
  model: "gpt-5.5",
  durationMs: 52484,
  sources: [
    "https://store.thamesandkosmos.com/collections/board-games/products/the-crew",
    "https://thamesandkosmos.com/manuals/full/691868_Crew_Manual.pdf",
    "https://www.geeksundergrace.com/tabletop/reviews-tabletop/review-the-crew-the-quest-for-planet-nine/",
    "https://coopboardgames.com/cooperative-board-game-reviews/the-crew-the-quest-for-planet-nine/",
  ],
} as const;
