// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-crew-quest-for-planet-nine
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative trick-taker where players silently steer tricks so assigned task cards land with the right hands.",
  default:
    "Cooperative trick-taking card game where the team clears mission goals under strict table-talk limits. Each trick, a leader plays a suit, others follow if able, and the highest led card or rocket trump wins the pile. A mission succeeds only when every assigned card lands with the right player.",
  loose:
    "Cooperative trick-taker where the team clears mission goals under strict table-talk limits. Each trick, a leader plays a suit, others follow if able, and the highest led card or rocket trump wins the pile. A mission succeeds only when every assigned card lands with the right player, sometimes in order; one wrong capture fails it. One communication token can mark a card as highest, lowest, or only in its suit, and the logbook runs through 50 missions.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:47.809Z",
  model: "gpt-5.5",
  durationMs: 24843,
  sources: [
    "https://www.rulespal.com/the-crew/rulebook",
    "https://whatsericplaying.com/2020/03/16/the-crew/",
    "https://tabletopbellhop.com/game-reviews/the-crew/",
  ],
} as const;
