/**
 * The Hunger's C++ search as WebAssembly, embedded in TS.
 *
 *   pnpm build-hunger-wasm
 *     = make -C cpp/the-hunger wasm   (wasi-sdk; WASI_SDK=… to override the path)
 *       + write packages/core/src/games/the-hunger/search/wasm/hunger-wasm.gen.ts
 *         (the module bytes as base64 — no runtime file path, so it survives
 *          the tsup-bundled server and worker_threads alike)
 *
 *   tsx scripts/gen-hunger-wasm.ts --dump-states <file> [--games N] [--offset K] [--every E]
 *     writes TS self-play states as canonical text, one per line, for the C++
 *     parser round-trip test (cpp/the-hunger/tests/canon_parse_test.cpp):
 *     2–6 seats × Elder / Rookie, random / Nosferatu / mixed seats, every E-th
 *     decision plus every 4th Mission pick, the setup state, a determinized world
 *     now and then, and the finished game (with its result).
 */
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { heuristicPick } from "../packages/core/src/games/the-hunger/ai-heuristic.ts";
import {
  applyUnchecked,
  createInitialState,
} from "../packages/core/src/games/the-hunger/game-engine.ts";
import { getActivePlayer, getLegalActions } from "../packages/core/src/games/the-hunger/rules.ts";
import { canonicalState } from "../packages/core/src/games/the-hunger/search/canon.ts";
import {
  determinize,
  mulberry32,
} from "../packages/core/src/games/the-hunger/search/determinize.ts";
import { seedForGame } from "../packages/core/src/games/the-hunger/tournament-runner.ts";
import type { GameState, Mode } from "../packages/core/src/games/the-hunger/types.ts";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const argv = process.argv.slice(2);
const flag = (name: string, dflt?: string) => {
  const i = argv.indexOf(`--${name}`);
  return i === -1 ? dflt : argv[i + 1];
};

const WASM = resolve(REPO, "cpp/the-hunger/build/hunger.wasm");
const OUT = resolve(REPO, "packages/core/src/games/the-hunger/search/wasm/hunger-wasm.gen.ts");

function build(): void {
  execFileSync("make", ["-C", resolve(REPO, "cpp/the-hunger"), "wasm"], { stdio: "inherit" });
  const bytes = readFileSync(WASM);
  const mod = new WebAssembly.Module(bytes);
  const imports = WebAssembly.Module.imports(mod).map((i) => `${i.module}.${i.name}`);
  const sha = createHash("sha256").update(bytes).digest("hex");
  const src = `// GENERATED by scripts/gen-hunger-wasm.ts — DO NOT EDIT.
// The Hunger's C++ search (cpp/the-hunger: src/*.cpp + wasm/agent.cpp) built
// with wasi-sdk as a WASI reactor, embedded as base64 so no file is read at
// runtime (the server bundle and worker threads load it the same way).
// Source-commit agnostic: rebuilt from whatever C++ is checked out.
// Regenerate after any change under cpp/the-hunger/:  pnpm build-hunger-wasm
//
// ${bytes.length} bytes, sha256 ${sha}
// WASI imports: ${imports.join(", ")}

export const HUNGER_WASM_BASE64 =
  "${bytes.toString("base64")}";
`;
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, src);
  console.log(`wrote ${OUT} (${bytes.length} bytes wasm; imports: ${imports.join(", ")})`);
}

function dumpStates(file: string): void {
  const games = Number(flag("games", "60"));
  const offset = Number(flag("offset", "0"));
  const every = Number(flag("every", "40"));
  const out: string[] = [];
  for (let g = offset; g < offset + games; g++) {
    const n = 2 + (g % 5);
    const mode: Mode = Math.floor(g / 5) % 2 === 1 ? "rookie" : "elder";
    const kind = Math.floor(g / 10) % 3; // 0 random, 1 Nosferatu, 2 mixed
    const seed = seedForGame(g);
    let s: GameState = createInitialState({
      playerCount: n,
      strategies: Array.from({ length: n }, () => null),
      seed,
      options: { mode, beginnerSafeMountains: g % 7 === 3 },
    });
    const pick = mulberry32((seed ^ 0x5bd1e995) >>> 0);
    out.push(canonicalState(s));
    let step = 0;
    let picks = 0;
    while (s.phase !== "game-over") {
      if (++step > 20000) throw new Error(`game ${g}: no end`);
      const seat = getActivePlayer(s);
      const legal = getLegalActions(s, seat);
      // Mission picks are frequent; keep every 4th (they carry missionPick).
      const pickState = s.current?.missionPick != null && picks++ % 4 === 0;
      if (step % every === 0 || pickState) out.push(canonicalState(s));
      if (step % (every * 5) === 0) {
        out.push(canonicalState(determinize(s, seat, mulberry32(step ^ seed))));
      }
      const heuristic = kind === 1 || (kind === 2 && (seat + g) % 2 === 0);
      const a = heuristic
        ? heuristicPick(s, seat, legal)
        : legal[Math.floor(pick() * legal.length)];
      s = applyUnchecked(s, seat, a);
    }
    out.push(canonicalState(s));
  }
  writeFileSync(file, `${out.join("\n")}\n`);
  console.log(`wrote ${out.length} states to ${file}`);
}

const dump = flag("dump-states");
if (dump) dumpStates(resolve(dump));
else build();
