/**
 * Codegen: emit the C++ data tables for The Hunger from the TS content — the
 * single source of truth. Run: `pnpm gen-cpp-hunger` (or
 * `cd packages/core && npx tsx ../../scripts/gen-cpp-hunger.ts`).
 *
 * Outputs cpp/the-hunger/include/hg/data.gen.hpp (counts) and
 * cpp/the-hunger/src/{cards,missions,bonus_tokens,board}.gen.cpp.
 *
 * Load-bearing orders (parity):
 *   - Physical card, Mission and Bonus-token ints are assigned in JavaScript's
 *     default string sort order (UTF-16 code units), so "sort the string pool"
 *     (determinize.ts, rules.missionKeepSets) is "sort the ints" in C++.
 *   - The expand(...) lists are emitted in TS order (they feed the shuffles).
 *   - Spaces keep the board file's order; adjacency lists are emitted exactly
 *     as board.buildGraph sorts them, and each space gets a code-unit rank and
 *     a `localeCompare` rank (walk / Spicy destinations sort by the latter).
 * The output is deterministic: CI can regenerate and diff.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildGraph } from "../packages/core/src/games/the-hunger/board.ts";
import { BONUS_TOKENS } from "../packages/core/src/games/the-hunger/content/bonus-tokens.ts";
import { PATHS, REGIONS, SPACE_EFFECTS } from "../packages/core/src/games/the-hunger/content/board-schema.ts";
import { BOARDS } from "../packages/core/src/games/the-hunger/content/boards.ts";
import {
  CARD_DEFS,
  expand,
  expandByRookie,
  HUNT_CARDS,
  passivesOf,
  ROSES,
  STARTING,
  VAMPIRES,
} from "../packages/core/src/games/the-hunger/content/cards.ts";
import { MISSIONS } from "../packages/core/src/games/the-hunger/content/missions.ts";
import {
  type BoardDef,
  type CardDef,
  HUMAN_CATEGORIES,
  type Keyword,
} from "../packages/core/src/games/the-hunger/types.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../cpp/the-hunger");
const SRC = resolve(ROOT, "src");
const INC = resolve(ROOT, "include/hg");
mkdirSync(SRC, { recursive: true });
mkdirSync(INC, { recursive: true });
const BANNER =
  "// GENERATED by scripts/gen-cpp-hunger.ts — DO NOT EDIT. Run `pnpm gen-cpp-hunger`.\n";

// ---------------------------------------------------------------------------
// Vocabularies (the C++ enums in data.hpp follow these orders)
// ---------------------------------------------------------------------------

const KEYWORDS: Keyword[] = [
  "fast",
  "slow",
  "spicy",
  "confuse",
  "holy-water",
  "gregarious",
  "ready",
  "permanent",
  "unique",
  "inspiring",
];
const CARD_TYPES = ["human", "starting", "power", "familiar", "item"] as const;
const PASSIVE_KINDS = [
  "hunt-vp-per-human",
  "extra-hunt",
  "bat",
  "mist",
  "end-turn-vp",
  "well-speed",
  "human-hunt-vp",
  "stay-extra-hunt",
  "vp-per-mission",
  "speed-per-human-worth",
  "humans-bonus",
  "push-tax",
] as const;
const WHEN = ["always", "hunted", "not-hunted"] as const;
const ACTIVATED = ["discard-for-col1-hunt", "digest-with-card", "redraw-hand", "hypnosis"] as const;
const END_GAME = ["if-has", "if-family", "per-category", "per-family"] as const;
const STD_KINDS = [
  "per-category",
  "majority",
  "fewest-humans",
  "has-rose",
  "host",
  "per-bonus",
  "per-human-worth",
  "none-worth",
  "same-type",
  "per-keyword",
  "per-distinct",
  "least-type",
  "most-type",
  "score-rank",
  "count-humans",
  "missionary",
  "sets",
  "per-digested",
  "first-home",
] as const;
const INSTANT_KINDS = [
  "digest-hand",
  "free-hunt-after-col3",
  "free-hunt-same-column",
  "take-bonus",
  "free-familiar",
  "vp-per-closer",
] as const;
const BONUS_KINDS = [
  "human",
  "human-choice",
  "speed",
  "extra-hunt",
  "discard-draw",
  "draw-to-play",
  "mission",
  "parasol",
  "velvet",
] as const;

const idx = <T extends string>(list: readonly T[], v: string | undefined, what: string): number => {
  if (v === undefined) return -1;
  const i = (list as readonly string[]).indexOf(v);
  if (i < 0) throw new Error(`unknown ${what}: ${v}`);
  return i;
};
const cat = (c: string | undefined) => idx(HUMAN_CATEGORIES, c, "category");
const region = (r: string | undefined) => idx(REGIONS, r, "region");

/** Every string the C++ writes into canonical text must need no JSON escaping. */
function plain(s: string): string {
  if (!/^[A-Za-z0-9#_.,:~+-]+$/.test(s)) throw new Error(`id needs escaping: ${JSON.stringify(s)}`);
  return s;
}
const q = (s: string) => `"${plain(s)}"`;

// ---------------------------------------------------------------------------
// Cards
// ---------------------------------------------------------------------------

const DEFS: CardDef[] = [...HUNT_CARDS, ...ROSES, ...STARTING];
const defIndex = new Map(DEFS.map((d, i) => [d.id, i]));
if (defIndex.size !== DEFS.length) throw new Error("duplicate card def id");
if (CARD_DEFS.size !== DEFS.length) throw new Error("CARD_DEFS differs from the def list");

const huntExpand = expand(HUNT_CARDS);
const rookieSplit = expandByRookie(HUNT_CARDS);
const roseExpand = expand(ROSES);
const startingExpand = VAMPIRES.map((_, p) => expand(STARTING, `${p}-`));
const allPhysical = [...huntExpand, ...roseExpand, ...startingExpand.flat()];
const physicalSorted = [...allPhysical].sort();
if (new Set(physicalSorted).size !== physicalSorted.length) throw new Error("duplicate physical card");
const cardInt = new Map(physicalSorted.map((id, i) => [id, i]));
const ci = (id: string) => {
  const v = cardInt.get(id);
  if (v === undefined) throw new Error(`unknown physical card ${id}`);
  return v;
};
const defOfPhysical = (id: string) => {
  const h = id.indexOf("#");
  const d = defIndex.get(h === -1 ? id : id.slice(0, h));
  if (d === undefined) throw new Error(`no def for ${id}`);
  return d;
};

const families = [...new Set(DEFS.map((d) => d.family).filter((f): f is string => !!f))].sort();
const familyIdx = (f: string | undefined) => (f === undefined ? -1 : families.indexOf(f));

function defRow(d: CardDef): string {
  const kw = d.keywords.reduce((m, k) => m | (1 << idx(KEYWORDS, k, "keyword")), 0);
  const speedVar = typeof d.speed !== "number";
  const speedBase = typeof d.speed === "number" ? d.speed : d.speed.base;
  const speedHuman = typeof d.speed === "number" ? d.speed : d.speed.ifHuman;
  const m = d.manipulation;
  const manip = !m
    ? "{0, 0, -1, false, 1}"
    : m.kind === "draw"
      ? `{1, ${m.n}, ${m.withHuman ?? -1}, ${m.mandatory ? "true" : "false"}, 1}`
      : `{2, 0, -1, false, ${m.times ?? 1}}`;
  const passives = passivesOf(d);
  if (passives.length > 2) throw new Error(`${d.id}: more than 2 passives`);
  const pRow = (i: number) => {
    const p = passives[i];
    if (!p) return "{-1, 0, 0, 0, 0, 0, 0, 0}";
    const f = p as Record<string, unknown>;
    const n = (k: string) => (typeof f[k] === "number" ? (f[k] as number) : 0);
    const when = p.kind === "end-turn-vp" ? idx(WHEN, p.when, "when") : 0;
    return `{${idx(PASSIVE_KINDS, p.kind, "passive")}, ${n("n")}, ${when}, ${n("min")}, ${n("max")}, ${n("atLeast")}, ${n("speed")}, ${n("vp")}}`;
  };
  const a = d.activated;
  const act = !a
    ? "{-1, 0, 0}"
    : `{${idx(ACTIVATED, a.kind, "activated")}, ${"vp" in a ? a.vp : 0}, ${"draw" in a ? a.draw : 0}}`;
  const e = d.endGame;
  let eg = "{-1, -1, -1, -1, 0}";
  if (e) {
    const other =
      e.kind === "if-has"
        ? (defIndex.get(e.other) ??
          (() => {
            throw new Error(`${d.id}: unknown other ${e.other}`);
          })())
        : -1;
    const fam = e.kind === "if-family" || e.kind === "per-family" ? familyIdx(e.family) : -1;
    const c = e.kind === "per-category" ? cat(e.category) : -1;
    eg = `{${idx(END_GAME, e.kind, "endGame")}, ${other}, ${fam}, ${c}, ${e.vp}}`;
  }
  const hb = d.huntBonus ? `${region(d.huntBonus.region)}, ${d.huntBonus.vp}` : "-1, 0";
  return (
    `  {${q(d.id)}, ${idx(CARD_TYPES, d.type, "type")}, ${cat(d.category)}, ${familyIdx(d.family)}, ` +
    `${speedVar}, ${speedBase}, ${speedHuman}, ${d.vp}, ${kw}, ${manip}, ${passives.length}, ` +
    `{${pRow(0)}, ${pRow(1)}}, ${act}, ${hb}, ${d.onHunt?.kind === "digest-any"}, ${eg}, ` +
    `${d.rookie === true}, ${d.rookieCopies ?? -1}, ${d.copies}},`
  );
}

const intList = (xs: readonly number[]) => {
  const lines: string[] = [];
  for (let i = 0; i < xs.length; i += 16) lines.push(`  ${xs.slice(i, i + 16).join(", ")},`);
  return lines.join("\n");
};

const cardsCpp = `${BANNER}#include "hg/data.hpp"

namespace hg {

const char* const FAMILY_NAMES[NUM_FAMILIES] = {${families.map(q).join(", ")}};

const CardDef CARD_DEFS[NUM_DEFS] = {
${DEFS.map(defRow).join("\n")}
};

// Physical cards, in JavaScript default sort order of their string ids.
const char* const CARD_NAMES[NUM_CARDS] = {
${physicalSorted.map((id) => `  ${q(id)},`).join("\n")}
};

const uint8_t CARD_DEF[NUM_CARDS] = {
${intList(physicalSorted.map(defOfPhysical))}
};

// expand(HUNT_CARDS)
const uint8_t HUNT_EXPAND[NUM_HUNT] = {
${intList(huntExpand.map(ci))}
};

// expandByRookie(HUNT_CARDS).a / .rest
const uint8_t ROOKIE_A[NUM_ROOKIE_A] = {
${intList(rookieSplit.a.map(ci))}
};
const uint8_t ROOKIE_REST[NUM_ROOKIE_REST] = {
${intList(rookieSplit.rest.map(ci))}
};

// expand(ROSES)
const uint8_t ROSE_EXPAND[NUM_ROSES] = {${roseExpand.map(ci).join(", ")}};

// expand(STARTING, \`\${p}-\`) for each seat
const uint8_t STARTING_EXPAND[MAX_PLAYERS][NUM_STARTING] = {
${startingExpand.map((l) => `  {${l.map(ci).join(", ")}},`).join("\n")}
};

}  // namespace hg
`;

// ---------------------------------------------------------------------------
// Missions
// ---------------------------------------------------------------------------

const missionSorted = MISSIONS.map((m) => m.id).sort();
if (new Set(missionSorted).size !== missionSorted.length) throw new Error("duplicate mission");
const mi = (id: string) => missionSorted.indexOf(id);

function missionRow(id: string): string {
  const m = MISSIONS.find((x) => x.id === id);
  if (!m) throw new Error(id);
  const s = m.standard as Record<string, unknown> | undefined;
  const n = (k: string, dflt = 0) => (s && typeof s[k] === "number" ? (s[k] as number) : dflt);
  let of = -1;
  if (s && s.kind === "majority") {
    of = s.of === "humans" ? 4 : s.of === "familiars" ? 5 : cat(s.of as string);
  }
  const kwMask =
    s && Array.isArray(s.keywords)
      ? (s.keywords as string[]).reduce((acc, k) => acc | (1 << idx(KEYWORDS, k, "keyword")), 0)
      : 0;
  const distinct = s && s.kind === "per-distinct" ? idx(CARD_TYPES, s.type as string, "type") : -1;
  const rank = s && s.kind === "score-rank" ? (s.rank === "highest" ? 0 : 1) : -1;
  const inst = m.instant;
  const instRegion = inst && inst.kind === "free-hunt-same-column" ? region(inst.region) : -1;
  return (
    `  {${q(m.id)}, ${m.vp}, ${m.fivePlus === true}, ${m.whiteTitle === true}, ` +
    `${s ? idx(STD_KINDS, s.kind as string, "standard") : -1}, ${s && typeof s.category === "string" ? cat(s.category) : -1}, ` +
    `${of}, ${n("vpEach")}, ${n("perBeaten")}, ${n("min")}, ${n("max", -1)}, ${n("atLeast")}, ` +
    `${kwMask}, ${distinct}, ${rank}, ${inst ? idx(INSTANT_KINDS, inst.kind, "instant") : -1}, ${instRegion}},`
  );
}

const missionsCpp = `${BANNER}#include "hg/data.hpp"

namespace hg {

// Missions, in JavaScript default sort order of their ids.
const MissionDef MISSION_DEFS[NUM_MISSIONS] = {
${missionSorted.map(missionRow).join("\n")}
};

// MISSIONS (definition order: the setup pools filter it).
const uint8_t MISSION_ORDER[NUM_MISSIONS] = {
${intList(MISSIONS.map((m) => mi(m.id)))}
};

}  // namespace hg
`;

// ---------------------------------------------------------------------------
// Bonus tokens
// ---------------------------------------------------------------------------

const bonusExpand = expand(BONUS_TOKENS);
const bonusSorted = [...bonusExpand].sort();
const bi = (id: string) => bonusSorted.indexOf(id);
function bonusRow(id: string): string {
  const h = id.indexOf("#");
  const def = BONUS_TOKENS.find((b) => b.id === id.slice(0, h));
  if (!def) throw new Error(id);
  const b = def.bonus;
  const c = b.kind === "human" ? cat(b.category) : -1;
  const n = b.kind === "speed" ? b.n : 0;
  return `  {${q(id)}, ${idx(BONUS_KINDS, b.kind, "bonus")}, ${c}, ${n}},`;
}
const bonusCpp = `${BANNER}#include "hg/data.hpp"

namespace hg {

// Physical Bonus tokens, in JavaScript default sort order of their ids.
const BonusDef BONUS_DEFS[NUM_BONUS] = {
${bonusSorted.map(bonusRow).join("\n")}
};

// expand(BONUS_TOKENS)
const uint8_t BONUS_EXPAND[NUM_BONUS] = {
${intList(bonusExpand.map(bi))}
};

}  // namespace hg
`;

// ---------------------------------------------------------------------------
// Boards
// ---------------------------------------------------------------------------

const BOARD_IDS = ["A", "B", "test"] as const;
let maxSpaces = 0;

function boardBlock(name: (typeof BOARD_IDS)[number]): string {
  const def: BoardDef = BOARDS[name];
  const g = buildGraph(def);
  const ids = def.spaces.map((s) => s.id);
  const si = (id: string) => {
    const i = ids.indexOf(id);
    if (i < 0) throw new Error(`${name}: unknown space ${id}`);
    return i;
  };
  maxSpaces = Math.max(maxSpaces, ids.length);
  const cu = [...ids].sort();
  const loc = [...ids].sort((a, b) => a.localeCompare(b));
  const adjStart: number[] = [];
  const adjList: number[] = [];
  for (const id of ids) {
    adjStart.push(adjList.length);
    for (const n of g.adj.get(id) ?? []) adjList.push(si(n));
  }
  adjStart.push(adjList.length);
  const dist = (m: ReadonlyMap<string, number>) =>
    ids.map((id) => {
      const d = m.get(id);
      if (d === undefined) throw new Error(`${name}: ${id} unreachable`);
      return d;
    });
  const chests = def.spaces.filter((s) => s.effect === "chest" || s.effect === "chest-open");
  const crypts = def.spaces.filter((s) => s.effect === "crypt");
  const p = `B_${name.toUpperCase()}`;
  return `
// ---- Board ${name} ----
static const Space ${p}_SPACES[] = {
${def.spaces
  .map(
    (s) =>
      `  {${q(s.id)}, ${region(s.region)}, ${s.path === null ? -1 : idx(PATHS, s.path, "path")}, ${idx(SPACE_EFFECTS, s.effect, "effect")}, ${s.mountainPenalty ?? -1}},`,
  )
  .join("\n")}
};
static const uint16_t ${p}_ADJ_START[] = {${adjStart.join(", ")}};
static const uint8_t ${p}_ADJ[] = {
${intList(adjList)}
};
static const uint8_t ${p}_CASTLE_DIST[] = {
${intList(dist(g.castleDist))}
};
static const uint8_t ${p}_LABYRINTH_DIST[] = {
${intList(dist(g.labyrinthDist))}
};
static const uint8_t ${p}_CU_RANK[] = {
${intList(ids.map((id) => cu.indexOf(id)))}
};
static const uint8_t ${p}_LOCALE_RANK[] = {
${intList(ids.map((id) => loc.indexOf(id)))}
};
static const uint8_t ${p}_CHESTS[] = {${chests.map((s) => si(s.id)).join(", ")}};
static const uint8_t ${p}_CRYPTS[] = {${crypts.map((s) => si(s.id)).join(", ")}};
`;
}

function boardInit(name: (typeof BOARD_IDS)[number]): string {
  const def = BOARDS[name];
  const g = buildGraph(def);
  const ids = def.spaces.map((s) => s.id);
  const p = `B_${name.toUpperCase()}`;
  const tavern = def.spaces.find((s) => s.effect === "tavern");
  const nChests = def.spaces.filter((s) => s.effect === "chest" || s.effect === "chest-open").length;
  const nCrypts = def.spaces.filter((s) => s.effect === "crypt").length;
  return `  {${q(name)}, ${ids.length}, ${p}_SPACES, ${p}_ADJ_START, ${p}_ADJ, ${ids.indexOf(g.castle)}, ${ids.indexOf(g.labyrinth)}, ${tavern ? ids.indexOf(tavern.id) : -1}, ${p}_CASTLE_DIST, ${p}_LABYRINTH_DIST, ${p}_CU_RANK, ${p}_LOCALE_RANK, ${nChests}, ${p}_CHESTS, ${nCrypts}, ${p}_CRYPTS},`;
}

const boardBlocks = BOARD_IDS.map(boardBlock).join("");
const boardCpp = `${BANNER}#include "hg/data.hpp"

namespace hg {
${boardBlocks}
const BoardData BOARD_DATA[3] = {
${BOARD_IDS.map(boardInit).join("\n")}
};

}  // namespace hg
`;

let maxChests = 0;
let maxCrypts = 0;
for (const b of BOARD_IDS) {
  maxChests = Math.max(
    maxChests,
    BOARDS[b].spaces.filter((s) => s.effect === "chest" || s.effect === "chest-open").length,
  );
  maxCrypts = Math.max(maxCrypts, BOARDS[b].spaces.filter((s) => s.effect === "crypt").length);
}
if (maxSpaces > 64) throw new Error("more than 64 spaces: widen the Well mask");

const header = `${BANNER}#pragma once

namespace hg {

constexpr int MAX_PLAYERS = ${VAMPIRES.length};
constexpr int NUM_DEFS = ${DEFS.length};
constexpr int NUM_CARDS = ${physicalSorted.length};
constexpr int NUM_HUNT = ${huntExpand.length};
constexpr int NUM_ROOKIE_A = ${rookieSplit.a.length};
constexpr int NUM_ROOKIE_REST = ${rookieSplit.rest.length};
constexpr int NUM_ROSES = ${roseExpand.length};
constexpr int NUM_STARTING = ${startingExpand[0].length};
constexpr int NUM_FAMILIES = ${families.length};
constexpr int FAM_ROSE = ${families.indexOf("rose")};
constexpr int NUM_MISSIONS = ${missionSorted.length};
constexpr int NUM_BONUS = ${bonusSorted.length};
constexpr int MAX_SPACES = ${maxSpaces};
constexpr int MAX_CHESTS = ${maxChests};
constexpr int MAX_CRYPTS = ${maxCrypts};

}  // namespace hg
`;

const write = (path: string, text: string) => {
  writeFileSync(path, text);
  console.log(`wrote ${path}`);
};
write(resolve(INC, "data.gen.hpp"), header);
write(resolve(SRC, "cards.gen.cpp"), cardsCpp);
write(resolve(SRC, "missions.gen.cpp"), missionsCpp);
write(resolve(SRC, "bonus_tokens.gen.cpp"), bonusCpp);
write(resolve(SRC, "board.gen.cpp"), boardCpp);
