/**
 * Codegen: emit C++ data tables for the 7 Wonders engine from the TS rules —
 * the single source of truth. Run: `pnpm gen-cpp-7wonders`.
 *
 * Outputs cpp/seven-wonders/src/{cards,wonders,edifice}.gen.cpp. Card ids follow
 * [...CARDS, ...GUILDS] order (load-bearing for deck-shuffle parity); nameIds are
 * first-appearance order (Loom/Glassworks/Press share one across ages).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { CARDS, GUILDS } from "../packages/core/src/games/7-wonders/cards.ts";
import { EDIFICES } from "../packages/core/src/games/7-wonders/edifice.ts";
import type {
  CardDef,
  CardEffect,
  CountScope,
  WonderStage,
  WonderStageEffect,
} from "../packages/core/src/games/7-wonders/types.ts";
import {
  CARD_COLORS,
  RESOURCE_TYPES,
  SCIENCE_SYMBOLS,
  WONDER_IDS,
} from "../packages/core/src/games/7-wonders/types.ts";
import { WONDERS } from "../packages/core/src/games/7-wonders/wonders.ts";
import type {
  EdificeCardDef,
  EdificePenalty,
  EdificeReward,
} from "../packages/core/src/games/7-wonders/edifice.ts";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "../cpp/seven-wonders/src");
const BANNER = "// GENERATED by scripts/gen-cpp-7wonders.ts — DO NOT EDIT. Run `pnpm gen-cpp-7wonders`.\n";

const resIdx = (r: string) => RESOURCE_TYPES.indexOf(r as (typeof RESOURCE_TYPES)[number]);
const colorIdx = (c: string) => CARD_COLORS.indexOf(c as (typeof CARD_COLORS)[number]);
const sciIdx = (s: string) => SCIENCE_SYMBOLS.indexOf(s as (typeof SCIENCE_SYMBOLS)[number]);
const scopeMask = (scopes: readonly CountScope[]) =>
  (scopes.includes("self") ? 1 : 0) |
  (scopes.includes("left") ? 2 : 0) |
  (scopes.includes("right") ? 4 : 0);
const resMask = (rs: readonly string[]) => rs.reduce((m, r) => m | (1 << resIdx(r)), 0);
const resCost = (cost: CardDef["cost"] | WonderStage["cost"]) => {
  const arr = new Array(RESOURCE_TYPES.length).fill(0);
  for (const [r, n] of Object.entries(cost.resources ?? {})) arr[resIdx(r)] = n;
  return `{${arr.join(",")}}`;
};

// ── name id map (first-appearance order over CARDS then GUILDS) ───────────────
const nameId = new Map<string, number>();
const names: string[] = [];
for (const c of [...CARDS, ...GUILDS]) {
  if (!nameId.has(c.name)) {
    nameId.set(c.name, names.length);
    names.push(c.name);
  }
}
const nid = (name: string) => {
  const id = nameId.get(name);
  if (id === undefined) throw new Error(`unknown card name in chain/effect: ${name}`);
  return id;
};

// ── effect emitter (shared by cards + wonder stages) ─────────────────────────
function emitEffect(e: CardEffect | WonderStageEffect): string {
  const f: string[] = [];
  switch (e.kind) {
    case "production": {
      const count = e.resources.length === 1 ? (e.count ?? 1) : 1;
      f.push(`.kind=EffectKind::Production`, `.resMask=${resMask(e.resources)}`, `.count=${count}`);
      break;
    }
    case "points":
      f.push(`.kind=EffectKind::Points`, `.amount=${e.amount}`);
      break;
    case "shields":
      f.push(`.kind=EffectKind::Shields`, `.amount=${e.amount}`);
      break;
    case "science":
      f.push(`.kind=EffectKind::Science`, `.science=${sciIdx(e.symbol)}`);
      break;
    case "coins":
      f.push(`.kind=EffectKind::Coins`, `.amount=${e.amount}`);
      break;
    case "coins-per-card":
      f.push(`.kind=EffectKind::CoinsPerCard`, `.color=${colorIdx(e.color)}`,
        `.scopes=${scopeMask(e.scopes)}`, `.amount=${e.amount}`);
      break;
    case "coins-per-stage":
      f.push(`.kind=EffectKind::CoinsPerStage`, `.scopes=${scopeMask(e.scopes)}`, `.amount=${e.amount}`);
      break;
    case "points-per-card":
      f.push(`.kind=EffectKind::PointsPerCard`, `.color=${colorIdx(e.color)}`,
        `.scopes=${scopeMask(e.scopes)}`, `.amount=${e.amount}`);
      break;
    case "points-per-stage":
      f.push(`.kind=EffectKind::PointsPerStage`, `.scopes=${scopeMask(e.scopes)}`, `.amount=${e.amount}`);
      break;
    case "points-per-defeat":
      f.push(`.kind=EffectKind::PointsPerDefeat`, `.scopes=${scopeMask(e.scopes)}`, `.amount=${e.amount}`);
      break;
    case "trade-discount":
      f.push(`.kind=EffectKind::TradeDiscount`, `.tradeRaw=${e.resources === "raw" ? 1 : 0}`,
        `.neighbors=${(e.neighbors.includes("left") ? 1 : 0) | (e.neighbors.includes("right") ? 2 : 0)}`);
      break;
    case "science-wildcard":
      f.push(`.kind=EffectKind::ScienceWildcard`);
      break;
    case "play-discarded":
      f.push(`.kind=EffectKind::PlayDiscarded`);
      break;
    case "free-build-per-age":
      f.push(`.kind=EffectKind::FreeBuildPerAge`);
      break;
    case "play-seventh-card":
      f.push(`.kind=EffectKind::PlaySeventhCard`);
      break;
    case "copy-guild":
      f.push(`.kind=EffectKind::CopyGuild`);
      break;
    default: {
      const _exhaustive: never = e;
      throw new Error(`unhandled effect ${JSON.stringify(_exhaustive)}`);
    }
  }
  return `Effect{${f.join(", ")}}`;
}

function emitEffects(effects: readonly (CardEffect | WonderStageEffect)[]): string {
  return `{${effects.map(emitEffect).join(", ")}}`;
}

// ── cards.gen.cpp ────────────────────────────────────────────────────────────
function genCards(): string {
  const all = [...CARDS, ...GUILDS];
  const rows = all.map((c: CardDef) => {
    const chain = c.chainFrom ?? [];
    return (
      `  {${nid(c.name)}, ${c.age}, ${colorIdx(c.color)}, ${c.cost.coins ?? 0}, ${resCost(c.cost)}, ` +
      `${c.effects.length}, ${emitEffects(c.effects)}, ` +
      `${chain.length}, {${chain.map(nid).join(",")}}, ` +
      `${c.copies.length}, {${c.copies.join(",")}}}`
    );
  });
  const nameLits = names.map((n) => `  ${JSON.stringify(n)}`);
  return (
    BANNER +
    `#include "sw/cards.hpp"\n\nnamespace sw {\n\n` +
    `const Card CARD_TYPES[] = {\n${rows.join(",\n")},\n};\n` +
    `const int NUM_CARD_TYPES = ${all.length};\n` +
    `const int NUM_NAMES = ${names.length};\n` +
    `const char* const NAME_TABLE[] = {\n${nameLits.join(",\n")},\n};\n\n` +
    `}  // namespace sw\n`
  );
}

// ── wonders.gen.cpp ──────────────────────────────────────────────────────────
function genWonders(): string {
  const byId = [...WONDERS].sort((a, b) => WONDER_IDS.indexOf(a.id) - WONDER_IDS.indexOf(b.id));
  const emitStage = (s: WonderStage) =>
    `{${s.cost.coins ?? 0}, ${resCost(s.cost)}, ${s.effects.length}, ${emitEffects(s.effects)}}`;
  const emitSide = (side: { initialResource: string; stages: readonly WonderStage[] }) =>
    `{${resIdx(side.initialResource)}, ${side.stages.length}, {${side.stages.map(emitStage).join(", ")}}}`;
  const rows = byId.map(
    (w) => `  {${WONDER_IDS.indexOf(w.id)}, {${emitSide(w.sides.A)}, ${emitSide(w.sides.B)}}}`,
  );
  const nameLits = byId.map((w) => `  ${JSON.stringify(w.name)}`);
  return (
    BANNER +
    `#include "sw/wonders.hpp"\n\nnamespace sw {\n\n` +
    `const Wonder WONDERS[] = {\n${rows.join(",\n")},\n};\n` +
    `const char* const WONDER_NAMES[] = {\n${nameLits.join(",\n")},\n};\n\n` +
    `}  // namespace sw\n`
  );
}

// ── edifice.gen.cpp ──────────────────────────────────────────────────────────
function emitReward(r: EdificeReward): string {
  switch (r.kind) {
    case "coins": return `{EdRewardKind::Coins, ${r.amount}}`;
    case "shield": return `{EdRewardKind::Shield, ${r.amount}}`;
    case "victory-token": return `{EdRewardKind::VictoryToken, ${r.value}}`;
    case "remove-defeat-tokens": return `{EdRewardKind::RemoveDefeatTokens}`;
    case "production": return `{EdRewardKind::Production, 0, ${resMask(r.resources)}}`;
    case "points-per-wonder-stage": return `{EdRewardKind::PointsPerWonderStage}`;
    case "points-per-blue": return `{EdRewardKind::PointsPerBlue}`;
    case "points-per-color": return `{EdRewardKind::PointsPerColor}`;
    case "points-per-brown-grey-set": return `{EdRewardKind::PointsPerBrownGreySet, ${r.amount}}`;
    case "duplicate-guild": return `{EdRewardKind::DuplicateGuild}`;
    default: {
      const _e: never = r;
      throw new Error(`unhandled edifice reward ${JSON.stringify(_e)}`);
    }
  }
}
function emitPenalty(p: EdificePenalty): string {
  switch (p.kind) {
    case "discard-color": return `{EdPenaltyKind::DiscardColor, 0, ${colorIdx(p.color)}}`;
    case "coins": return `{EdPenaltyKind::Coins, ${p.amount}}`;
    case "lose-victory-tokens": return `{EdPenaltyKind::LoseVictoryTokens, ${p.amount}}`;
    default: {
      const _e: never = p;
      throw new Error(`unhandled edifice penalty ${JSON.stringify(_e)}`);
    }
  }
}
function genEdifice(): string {
  const rows = EDIFICES.map(
    (e: EdificeCardDef) =>
      `  {${e.age}, ${e.cost}, ${e.reward.length}, {${e.reward.map(emitReward).join(", ")}}, ${emitPenalty(e.penalty)}}`,
  );
  const nameLits = EDIFICES.map((e) => `  ${JSON.stringify(e.name)}`);
  return (
    BANNER +
    `#include "sw/edifice.hpp"\n\nnamespace sw {\n\n` +
    `const Edifice EDIFICES[] = {\n${rows.join(",\n")},\n};\n` +
    `const char* const EDIFICE_NAMES[] = {\n${nameLits.join(",\n")},\n};\n\n` +
    `}  // namespace sw\n`
  );
}

writeFileSync(resolve(OUT, "cards.gen.cpp"), genCards());
writeFileSync(resolve(OUT, "wonders.gen.cpp"), genWonders());
writeFileSync(resolve(OUT, "edifice.gen.cpp"), genEdifice());
console.log(
  `Generated ${CARDS.length + GUILDS.length} cards (${names.length} names), ${WONDERS.length} wonders, ${EDIFICES.length} edifices -> ${OUT}`,
);
