// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-fox-in-the-forest
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Fairy-tale card powers turn a two-player trick-taking duel into a knife-edge contest of timing, trump shifts, and restraint.",
  default:
    "Fairy-tale card powers make every small lead dangerous, because a clean sweep can become a punishment. Its core is trick-taking. Rounds score toward 21 points, but taking too many tricks earns nothing.",
  loose:
    "Fairy-tale card powers make every small lead feel dangerous, because a clean sweep can become a punishment. Its core is trick-taking. Rounds score toward 21 points, but taking ten or more of the thirteen tricks earns nothing while a humble 0–3 tricks pays richly. A Fox can swap the decree card and change trump before the trick resolves; a Swan lets the loser lead next.",
};

export const meta = {
  generatedAt: "2026-05-13T16:41:32.928Z",
  model: "gpt-5.5",
  durationMs: 33444,
  sources: [
    "https://renegadegamestudios.com/content/File%20Storage%20for%20site/Rulebooks/Fox%20in%20the%20Forest/FitFDeluxe%20Rulebook_WEB.pdf",
    "https://opinionatedgamers.com/2017/09/13/the-fox-in-the-forest-game-review-by-chris-wray/",
    "https://renegadegamestudios.com/blog/the-fox-in-the-forest-deluxe-is-available-now/",
    "https://en.boardgamearena.com/gamepanel?game=thefoxintheforest",
  ],
} as const;
