// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug sushi-go
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A sushi conveyor belt becomes a knife-edge race for combos as hands circle the table in brisk card drafting.",
  default:
    "The sushi-train theme turns every passing hand into a gift and a threat. Card drafting drives the game as players keep one card, reveal it, and pass the rest. The best score comes from reading which combos to chase, block, or abandon.",
  loose:
    "The sushi-train theme makes every passing hand feel like a gift and a threat. Card drafting drives the game: each player keeps one card, reveals it, then passes the shrinking hand along. Points come from fragile combos, majorities, and endgame pudding, so a harmless dessert can decide the final score. Walker-Harding said the theme clicked because sushi plates already feel like cards moving around a table.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:52.117Z",
  model: "gpt-5.5",
  durationMs: 17878,
  sources: [
    "https://www.gamewright.com/product/Sushi-Go",
    "https://www.mojo-nation.com/sushi-go-creator-phil-walker-harding-accessibility-creativity-future-sushi-series/",
  ],
} as const;
