// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug sushi-go
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light card-drafting set-collection game where everyone keeps one sushi card, passes the hand, and scores combo plates.",
  default:
    "Light card-drafting and set-collection game about building the best sushi meal from passing hands. Each pick, everyone keeps one card, reveals it, then passes the shrinking hand left. After three rounds, highest score wins, with pudding saved for the final swing.",
  loose:
    "Light card-drafting and set-collection game about building the best sushi meal from passing hands of cards. Each pick, everyone secretly keeps one card, reveals it, then passes the shrinking hand left while chasing tempura pairs, sashimi triples, maki majorities, dumpling runs, and nigiri. After three rounds, highest total score wins, with pudding cards saved for the final bonus or penalty. Wasabi sits empty until the next nigiri lands on it, making squid worth nine points instead of three.",
};

export const meta = {
  generatedAt: "2026-05-13T20:22:25.171Z",
  model: "gpt-5.5",
  durationMs: 22694,
  sources: [
    "https://gamewright.com/product/Sushi-Go",
    "https://fgbradleys.com/wp-content/uploads/rules/SushiGo-rules.pdf",
    "https://gameinformer.com/column/2019/06/26/top-of-the-table-sushi-roll",
    "https://en.wikipedia.org/wiki/Sushi_Go%21",
  ],
} as const;
