// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug hitster
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Music party trivia game where players scan song cards, hear the track, and slot each card into a personal release-year timeline.",
  default:
    "Music party trivia game about building a timeline of hit songs by release year. Each turn, the DJ scans a QR code, a song plays, and the guesser places the card before, after, or between dated cards. First timeline with 10 correctly placed songs wins.",
  loose:
    "Music party trivia game about building a timeline of hit songs by release year. Each turn, the DJ scans a QR code, a song plays, and the guesser places the card before, after, or between dated cards. First timeline with 10 correctly placed songs wins. Tokens let rivals shout a challenge before the reveal and steal the card if they point to the correct slot.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:37.945Z",
  model: "gpt-5.5",
  durationMs: 10731,
  sources: [
    "https://hitstergame.com/en-us/how-to-play/",
    "https://www.whatboardgame.com/post/hitster-party-game-review",
    "https://www.hitster4all.com/rules/",
  ],
} as const;
