// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug hitster
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Half-remembered choruses turn release years into table-wide arguments through set collection with QR-scanned songs.",
  default:
    "Familiar songs become risky bets about what came first. Set collection drives each turn as a scanned QR code plays a track, then the card is placed in a growing timeline. The first timeline with ten correctly ordered songs wins.",
  loose:
    "Familiar songs become risky bets about what came first. Set collection drives each turn as a scanned QR code plays a track, then the card is placed in a growing timeline. The first timeline with ten correctly ordered songs wins. Tokens sharpen the party noise: name the artist and title to earn one, or spend one to challenge a rival’s placement and steal the card.",
};

export const meta = {
  generatedAt: "2026-05-13T16:35:34.013Z",
  model: "gpt-5.5",
  durationMs: 26431,
  sources: [
    "https://hitstergame.com/en-nz/how-to-play-v3/",
    "https://www.whatboardgame.com/post/hitster-party-game-review",
    "https://nordics.hitstergame.com/wp-content/uploads/2021/06/HITSTER-Print-and-Play.pdf",
  ],
} as const;
