import type { BlockName } from "./types.ts";

// Names for the centuries (round-number blocks: `cen:1900` = 1900–1999). See ./index.ts.

export const CENTURIES: Readonly<Record<string, BlockName>> = {
  "cen:9700bc": { en: "End of the Ice Age", de: "Ende der Eiszeit" },
  "cen:9600bc": { en: "The First Wheat Fields", de: "Die ersten Weizenfelder" },
  "cen:9500bc": { en: "Cereal Farming Begins", de: "Beginn des Getreideanbaus" },
  "cen:9400bc": { en: "Pigs Reach Cyprus", de: "Schweine erreichen Zypern" },
  "cen:9000bc": { en: "Herds of Sheep and Goats", de: "Schaf- und Ziegenherden" },
  "cen:8500bc": { en: "Taming the Aurochs", de: "Zähmung des Auerochsen" },
  "cen:8000bc": { en: "Founder Crops of the Crescent", de: "Linsen, Erbsen und Getreide" },
  "cen:7800bc": { en: "Hunter-Gatherers in America", de: "Jäger und Sammler in Amerika" },
  "cen:7500bc": { en: "Old Tjikko Takes Root", de: "Old Tjikko schlägt Wurzeln" },
  "cen:7000bc": { en: "Britain Becomes an Island", de: "Britannien wird zur Insel" },
  "cen:6700bc": { en: "Pistachios on the Menu", de: "Pistazien auf dem Speiseplan" },
  "cen:6600bc": { en: "Soybeans in China", de: "Sojabohnen in China" },
  "cen:6500bc": { en: "Pigs Reach Europe", de: "Schweine erreichen Europa" },
  "cen:6200bc": { en: "China's First Jade", de: "Chinas früheste Jade" },
  "cen:6000bc": { en: "Chickens, Olives and Milk", de: "Huhn, Olive und Milch" },
  "cen:5600bc": { en: "Peanuts in South America", de: "Erdnüsse in Südamerika" },
  "cen:5500bc": { en: "The First Drums", de: "Die ersten Trommeln" },
  "cen:5400bc": { en: "Jade Carvers of Xinglongwa", de: "Jadeschnitzer von Xinglongwa" },
  "cen:5000bc": { en: "Farming Reaches Central Europe", de: "Zeit der Bandkeramiker" },
  "cen:4600bc": { en: "The Gold of Varna", de: "Das Gold von Varna" },
  "cen:4500bc": { en: "Proto-Indo-European Speech", de: "Die indogermanische Ursprache" },
  "cen:4200bc": { en: "Copper Age Balkans", de: "Kupferzeit auf dem Balkan" },
  "cen:4000bc": { en: "Dawn of Sumer", de: "Anfänge Sumers" },
  "cen:3500bc": { en: "The First Cities", de: "Die ersten Städte" },
  "cen:3300bc": { en: "Age of Ötzi", de: "Die Zeit des Ötzi" },
  "cen:3100bc": { en: "Egypt Unified", de: "Die Einigung Ägyptens" },
  "cen:3000bc": { en: "Early Dynastic Egypt", de: "Ägyptens Frühzeit" },
  "cen:2900bc": { en: "Sumerian City-States", de: "Sumerische Stadtstaaten" },
  "cen:2800bc": { en: "Methuselah Pine Sprouts", de: "Die Methusalem-Kiefer keimt" },
  "cen:2700bc": { en: "Age of Gilgamesh", de: "Zeit des Gilgamesch" },
  "cen:2600bc": { en: "The Great Pyramid", de: "Bau der Cheops-Pyramide" },
  "cen:2500bc": { en: "The Sphinx of Giza", de: "Die Sphinx von Gizeh" },
  "cen:2400bc": { en: "The Pyramid Texts", de: "Die Pyramidentexte" },
  "cen:2300bc": { en: "Empire of Akkad", de: "Das Reich von Akkad" },
  "cen:2200bc": { en: "Taming the Horse", de: "Zähmung des Pferdes" },
  "cen:2100bc": { en: "Gudea of Lagash", de: "Gudea von Lagasch" },
  "cen:2000bc": { en: "Ur under King Shulgi", de: "Ur unter König Schulgi" },
  "cen:1900bc": { en: "Palace of Knossos", de: "Der Palast von Knossos" },
  "cen:1800bc": { en: "Babylonian Mathematics", de: "Babylonische Mathematik" },
  "cen:1700bc": { en: "Hammurabi's Code", de: "Der Codex Hammurapi" },
  "cen:1600bc": { en: "Eruption of Thera", de: "Ausbruch von Thera" },
  "cen:1500bc": { en: "Hatshepsut's Egypt", de: "Ägypten unter Hatschepsut" },
  "cen:1400bc": { en: "Bronze Age Trade", de: "Handel der Bronzezeit" },
  "cen:1300bc": { en: "Akhenaten and Tutankhamun", de: "Echnaton und Tutanchamun" },
  "cen:1200bc": { en: "Bronze Age Collapse", de: "Zusammenbruch der Bronzezeit" },
  "cen:1100bc": { en: "The Trojan War", de: "Der Trojanische Krieg" },
  "cen:1000bc": { en: "Age of King David", de: "Zeit König Davids" },
  "cen:900bc": { en: "Solomon's Kingdom", de: "Das Reich Salomos" },
  "cen:800bc": { en: "Age of Homer", de: "Zeitalter Homers" },
  "cen:700bc": { en: "Hesiod and the First Coins", de: "Hesiod und die ersten Münzen" },
  "cen:600bc": { en: "Nebuchadnezzar's Babylon", de: "Babylon unter Nebukadnezar" },
  "cen:500bc": { en: "Philosophers of Ionia", de: "Die ionischen Naturphilosophen" },
  "cen:400bc": { en: "Age of Pericles", de: "Zeitalter des Perikles" },
  "cen:300bc": { en: "Age of Alexander", de: "Zeitalter Alexanders" },
  "cen:200bc": { en: "Rome against Carthage", de: "Rom gegen Karthago" },
  "cen:100bc": { en: "Rome Rules the Mediterranean", de: "Rom beherrscht das Mittelmeer" },
  "cen:0bc": { en: "Fall of the Republic", de: "Untergang der Republik" },
  "cen:0": { en: "Rome and the First Christians", de: "Rom und die ersten Christen" },
  "cen:100": { en: "Rome at Its Height", de: "Blütezeit des Kaiserreichs" },
  "cen:200": { en: "Empire in Crisis", de: "Das Reich in der Krise" },
  "cen:300": { en: "Rome Turns Christian", de: "Rom wird christlich" },
  "cen:400": { en: "Fall of the Western Empire", de: "Untergang Westroms" },
  "cen:500": { en: "Age of Justinian", de: "Zeitalter Justinians" },
  "cen:600": { en: "Rise of Islam", de: "Aufstieg des Islam" },
  "cen:700": { en: "Caliphs and Carolingians", de: "Kalifen und Karolinger" },
  "cen:800": { en: "The Viking Age", de: "Die Wikingerzeit" },
  "cen:900": { en: "Rise of the Ottonians", de: "Aufstieg der Ottonen" },
  "cen:1000": { en: "Romanesque Europe", de: "Das Zeitalter der Romanik" },
  "cen:1100": { en: "Crusades and Cathedrals", de: "Kreuzzüge und Kathedralen" },
  "cen:1200": { en: "High Middle Ages", de: "Hochmittelalter" },
  "cen:1300": { en: "Plague and Hundred Years' War", de: "Pest und Hundertjähriger Krieg" },
  "cen:1400": { en: "Renaissance and Discovery", de: "Renaissance und Entdeckungen" },
  "cen:1500": { en: "Age of Reformation", de: "Zeitalter der Reformation" },
  "cen:1600": { en: "Age of the Baroque", de: "Zeitalter des Barock" },
  "cen:1700": { en: "Age of Enlightenment", de: "Zeitalter der Aufklärung" },
  "cen:1800": { en: "Industry and Empire", de: "Industrie und Imperialismus" },
  "cen:1900": { en: "Age of Extremes", de: "Zeitalter der Extreme" },
  "cen:2000": { en: "The Digital Age", de: "Das digitale Zeitalter" },
  "cen:2100": { en: "Into the Future", de: "Blick in die Zukunft" },
};
