import type { BlockName } from "./types.ts";

// Names for the AD decades before 1500 that hold quiz content. See ./index.ts.

export const DECADES_MEDIEVAL: Readonly<Record<string, BlockName>> = {
  "dec:0": { en: "Varus Loses His Legions", de: "Die Varusschlacht" },
  "dec:10": { en: "Death of Augustus", de: "Tod des Augustus" },
  "dec:20": { en: "Jesus Baptised in the Jordan", de: "Die Taufe Jesu im Jordan" },
  "dec:30": { en: "The Crucifixion", de: "Die Kreuzigung Jesu" },
  "dec:40": { en: "The Pont du Gard", de: "Der Pont du Gard" },
  "dec:50": { en: "Nero Takes the Throne", de: "Nero besteigt den Thron" },
  "dec:60": { en: "Rome Burns Under Nero", de: "Rom brennt unter Nero" },
  "dec:70": { en: "Vesuvius Buries Pompeii", de: "Der Vesuv begräbt Pompeji" },
  "dec:80": { en: "The Colosseum Opens", de: "Das Kolosseum wird eröffnet" },
  "dec:90": { en: "John's Revelation on Patmos", de: "Die Offenbarung des Johannes" },
  "dec:100": { en: "Cai Lun's Paper", de: "Cai Luns Papier" },
  "dec:110": { en: "Trajan's Column", de: "Die Trajanssäule" },
  "dec:120": { en: "Hadrian's Wall & Pantheon", de: "Hadrianswall und Pantheon" },
  "dec:130": { en: "Hadrian's Mausoleum", de: "Das Grabmal Hadrians" },
  "dec:150": { en: "Ptolemy's Almagest", de: "Der Almagest des Ptolemäus" },
  "dec:160": { en: "Marcus Aurelius Reigns", de: "Mark Aurel wird Kaiser" },
  "dec:170": { en: "Meditations of an Emperor", de: "Die Selbstbetrachtungen" },
  "dec:180": { en: "End of the Good Emperors", de: "Ende der Adoptivkaiser" },
  "dec:200": { en: "The Mishnah Compiled", de: "Die Mischna entsteht" },
  "dec:210": { en: "Caracalla Meets the Alemanni", de: "Die Alamannen treten auf" },
  "dec:220": { en: "Fall of the Han Dynasty", de: "Das Ende der Han-Dynastie" },
  "dec:230": { en: "Crisis of the Third Century", de: "Die Reichskrise beginnt" },
  "dec:240": { en: "Rome's Thousandth Birthday", de: "Roms Tausendjahrfeier" },
  "dec:260": { en: "Saint Valentine's Martyrdom", de: "Das Martyrium Valentins" },
  "dec:270": { en: "Aurelian Defeats Zenobia", de: "Aurelian besiegt Zenobia" },
  "dec:280": { en: "Diocletian Takes Power", de: "Diokletian kommt an die Macht" },
  "dec:290": { en: "The Tetrarchy", de: "Die Tetrarchie" },
  "dec:300": { en: "The Great Persecution", de: "Die große Christenverfolgung" },
  "dec:310": { en: "The Edict of Milan", de: "Toleranzedikt von Mailand" },
  "dec:320": { en: "The Council of Nicaea", de: "Das Konzil von Nicäa" },
  "dec:330": { en: "Constantinople Founded", de: "Gründung Konstantinopels" },
  "dec:340": { en: "Saint Nicholas of Myra", de: "Nikolaus von Myra" },
  "dec:350": { en: "Julian at Strasbourg", de: "Die Schlacht bei Straßburg" },
  "dec:360": { en: "The New Testament Canon", de: "Der Kanon des Neuen Testaments" },
  "dec:370": { en: "Disaster at Adrianople", de: "Die Schlacht von Adrianopel" },
  "dec:380": { en: "Jerome's Latin Bible", de: "Die Vulgata entsteht" },
  "dec:390": { en: "Theodosius Bans the Old Gods", de: "Das Ende der alten Kulte" },
  "dec:400": { en: "Alaric Holds Rome to Ransom", de: "Alarich erpresst Rom" },
  "dec:410": { en: "The Sack of Rome", de: "Die Goten plündern Rom" },
  "dec:420": { en: "Augustine's City of God", de: "Augustins Gottesstaat" },
  "dec:430": { en: "Vandals Take Carthage", de: "Die Vandalen in Karthago" },
  "dec:440": { en: "Attila's Hun Empire", de: "Attilas Hunnenreich" },
  "dec:450": { en: "The Vandals Plunder Rome", de: "Die Vandalen plündern Rom" },
  "dec:460": { en: "Saint Patrick's Death", de: "Der Tod des heiligen Patrick" },
  "dec:470": { en: "Fall of the Western Empire", de: "Untergang Westroms" },
  "dec:480": { en: "Clovis, King of the Franks", de: "Chlodwig, König der Franken" },
  "dec:490": { en: "Theodoric Rules Italy", de: "Theoderich in Ravenna" },
  "dec:500": { en: "Chaturanga, Ancestor of Chess", de: "Tschaturanga, das Urschach" },
  "dec:510": { en: "Death of Clovis", de: "Der Tod Chlodwigs" },
  "dec:520": { en: "Benedict at Monte Cassino", de: "Benedikt gründet Montecassino" },
  "dec:530": { en: "Hagia Sophia Consecrated", de: "Die Weihe der Hagia Sophia" },
  "dec:540": { en: "The Plague of Justinian", de: "Die Justinianische Pest" },
  "dec:550": { en: "Silkworms Smuggled West", de: "Seidenraupen für Byzanz" },
  "dec:560": { en: "The Lombards Invade Italy", de: "Die Langobarden in Italien" },
  "dec:570": { en: "Birth of Muhammad", de: "Geburt Mohammeds" },
  "dec:580": { en: "Bilal, the First Muezzin", de: "Bilal, der erste Muezzin" },
  "dec:590": { en: "Pope Gregory the Great", de: "Papst Gregor der Große" },
  "dec:600": { en: "Isidore's Etymologies", de: "Isidors Etymologien" },
  "dec:610": { en: "Muhammad's First Revelation", de: "Mohammeds erste Offenbarung" },
  "dec:620": { en: "The Hijra to Medina", de: "Die Hidschra nach Medina" },
  "dec:630": { en: "Mecca and the First Caliph", de: "Mekka und der erste Kalif" },
  "dec:640": { en: "The Arabs Conquer Egypt", de: "Die Araber erobern Ägypten" },
  "dec:650": { en: "Uthman's Qur'an", de: "Uthmans Koranausgabe" },
  "dec:660": { en: "Ali Slain, Umayyads Rise", de: "Alis Tod und die Umayyaden" },
  "dec:690": { en: "The Dome of the Rock", de: "Der Felsendom" },
  "dec:700": { en: "Umayyad Caliphate at Its Peak", de: "Das Kalifat der Umayyaden" },
  "dec:710": { en: "Tariq Crosses to Spain", de: "Tariq setzt nach Spanien über" },
  "dec:720": { en: "Boniface Fells Donar's Oak", de: "Die Fällung der Donareiche" },
  "dec:730": { en: "Charles Martel at Tours", de: "Die Schlacht bei Poitiers" },
  "dec:740": { en: "Birth of Charlemagne", de: "Karl der Große wird geboren" },
  "dec:750": { en: "The First Carolingian King", de: "Pippin wird König" },
  "dec:760": { en: "Baghdad Founded", de: "Die Gründung Bagdads" },
  "dec:770": { en: "Ambush at Roncevaux", de: "Die Schlacht von Roncesvalles" },
  "dec:780": { en: "Harun al-Rashid's Baghdad", de: "Harun al-Raschids Bagdad" },
  "dec:790": { en: "Vikings Raid Lindisfarne", de: "Überfall auf Lindisfarne" },
  "dec:800": { en: "Charlemagne Crowned", de: "Karls Kaiserkrönung" },
  "dec:810": { en: "Death of Charlemagne", de: "Tod Karls des Großen" },
  "dec:820": { en: "Al-Khwarizmi's Algebra", de: "Al-Chwarizmis Algebra" },
  "dec:830": { en: "The Hildebrandslied", de: "Das Hildebrandslied" },
  "dec:840": { en: "The Treaty of Verdun", de: "Der Vertrag von Verdun" },
  "dec:850": { en: "Prambanan's Shiva Temple", de: "Der Tempel von Prambanan" },
  "dec:870": { en: "Iceland Settled", de: "Die Besiedlung Islands" },
  "dec:880": { en: "Prague Castle Founded", de: "Die Prager Burg entsteht" },
  "dec:890": { en: "Cyrillic Script Created", de: "Die kyrillische Schrift" },
  "dec:900": { en: "The Merseburg Charms", de: "Merseburger Zaubersprüche" },
  "dec:910": { en: "Rollo Receives Normandy", de: "Rollo erhält die Normandie" },
  "dec:930": { en: "Otto I Crowned at Aachen", de: "Ottos Krönung in Aachen" },
  "dec:940": { en: "Bishoprics on the Elbe", de: "Bistümer an der Elbe" },
  "dec:950": { en: "Victory at the Lechfeld", de: "Die Schlacht auf dem Lechfeld" },
  "dec:960": { en: "The Jelling Stone", de: "Der Jelling-Stein" },
  "dec:970": { en: "The Mihrab of Córdoba", de: "Der Mihrab von Córdoba" },
  "dec:980": { en: "Erik the Red's Greenland", de: "Erik der Rote in Grönland" },
  "dec:990": { en: "Guido of Arezzo Is Born", de: "Guido von Arezzo wird geboren" },
  "dec:1000": { en: "Leif Erikson in Vinland", de: "Leif Eriksson in Vinland" },
  "dec:1010": { en: "Thang Long (Hanoi) Founded", de: "Gründung von Thang Long" },
  "dec:1020": { en: "Avicenna's Canon of Medicine", de: "Avicennas Kanon der Medizin" },
  "dec:1030": { en: "Speyer Cathedral Begun", de: "Der Speyerer Dom entsteht" },
  "dec:1050": { en: "The Great Schism", de: "Das Morgenländische Schisma" },
  "dec:1060": { en: "The Norman Conquest", de: "Die Schlacht bei Hastings" },
  "dec:1070": { en: "The Walk to Canossa", de: "Der Gang nach Canossa" },
  "dec:1080": { en: "The Domesday Book", de: "Das Domesday Book" },
  "dec:1090": { en: "The First Crusade", de: "Der Erste Kreuzzug" },
  "dec:1100": { en: "Crusader Jerusalem", de: "Das Königreich Jerusalem" },
  "dec:1110": { en: "Angkor Wat Begun", de: "Baubeginn von Angkor Wat" },
  "dec:1120": { en: "The Concordat of Worms", de: "Das Wormser Konkordat" },
  "dec:1130": { en: "Regensburg's Stone Bridge", de: "Die Steinerne Brücke" },
  "dec:1140": { en: "Birth of Gothic: Saint-Denis", de: "Die Geburt der Gotik" },
  "dec:1150": { en: "Munich First Recorded", de: "Erste Erwähnung Münchens" },
  "dec:1160": { en: "Notre-Dame Begun", de: "Baubeginn von Notre-Dame" },
  "dec:1170": { en: "Becket Murdered at Canterbury", de: "Der Mord an Thomas Becket" },
  "dec:1180": { en: "Saladin Retakes Jerusalem", de: "Saladin erobert Jerusalem" },
  "dec:1190": { en: "Richard the Lionheart", de: "Richard Löwenherz" },
  "dec:1200": { en: "Crusaders Sack Constantinople", de: "Kreuzfahrer plündern Byzanz" },
  "dec:1210": { en: "Magna Carta", de: "Die Magna Carta" },
  "dec:1220": { en: "Death of Francis of Assisi", de: "Der Tod des Franz von Assisi" },
  "dec:1230": { en: "The Alhambra Begun", de: "Baubeginn der Alhambra" },
  "dec:1240": { en: "The Mongols at Legnica", de: "Die Mongolen bei Liegnitz" },
  "dec:1250": { en: "Mongols Sack Baghdad", de: "Die Mongolen zerstören Bagdad" },
  "dec:1260": { en: "Dante Is Born", de: "Dantes Geburt" },
  "dec:1270": { en: "Death of Thomas Aquinas", de: "Der Tod des Thomas von Aquin" },
  "dec:1280": { en: "The Zohar Is Written", de: "Der Sohar entsteht" },
  "dec:1290": { en: "Marco Polo's Travels", de: "Marco Polos Reisebericht" },
  "dec:1300": { en: "Giotto's Scrovegni Chapel", de: "Giottos Scrovegni-Kapelle" },
  "dec:1310": { en: "Victory at Bannockburn", de: "Die Schlacht von Bannockburn" },
  "dec:1320": { en: "Dante's Divine Comedy", de: "Dantes Göttliche Komödie" },
  "dec:1330": { en: "The Hundred Years' War", de: "Der Hundertjährige Krieg" },
  "dec:1340": { en: "The Black Death", de: "Der Schwarze Tod" },
  "dec:1350": { en: "The Golden Bull", de: "Die Goldene Bulle" },
  "dec:1360": { en: "The Court of the Lions", de: "Der Löwenhof der Alhambra" },
  "dec:1370": { en: "The First Quarantine", de: "Die erste Quarantäne" },
  "dec:1380": { en: "Heidelberg University", de: "Die Universität Heidelberg" },
  "dec:1390": { en: "The Kalmar Union", de: "Die Kalmarer Union" },
  "dec:1400": { en: "The Forbidden City Begun", de: "Baubeginn der Verbotenen Stadt" },
  "dec:1410": { en: "Jan Hus Burned at Constance", de: "Jan Hus stirbt in Konstanz" },
  "dec:1420": { en: "Joan of Arc at Orléans", de: "Jeanne d'Arc vor Orléans" },
  "dec:1430": { en: "The Ghent Altarpiece", de: "Der Genter Altar" },
  "dec:1440": { en: "Cosimo de' Medici's Florence", de: "Das Florenz der Medici" },
  "dec:1450": { en: "Fall of Constantinople", de: "Der Fall Konstantinopels" },
  "dec:1460": { en: "Guru Nanak Is Born", de: "Guru Nanak wird geboren" },
  "dec:1470": { en: "Leonardo's Annunciation", de: "Leonardos Verkündigung" },
  "dec:1480": { en: "Botticelli's Birth of Venus", de: "Botticellis Geburt der Venus" },
  "dec:1490": { en: "Columbus Reaches America", de: "Kolumbus erreicht Amerika" },
};
