import type { BlockName } from "./types.ts";

// Names for the BC decades that hold quiz content. See ./index.ts.

export const DECADES_BC: Readonly<Record<string, BlockName>> = {
  "dec:9700bc": { en: "The Ice Age Ends", de: "Ende der letzten Eiszeit" },
  "dec:9600bc": { en: "The First Wheat Fields", de: "Die ersten Weizenfelder" },
  "dec:9500bc": { en: "Dawn of Farming", de: "Beginn des Ackerbaus" },
  "dec:9400bc": { en: "Pigs Reach Cyprus", de: "Schweine erreichen Zypern" },
  "dec:9000bc": { en: "Taming Sheep and Goats", de: "Zähmung von Schaf und Ziege" },
  "dec:8500bc": { en: "The Aurochs Tamed", de: "Der Auerochse wird gezähmt" },
  "dec:8000bc": { en: "The Founder Crops", de: "Die Gründerpflanzen" },
  "dec:7830bc": { en: "Hunters of the Great Basin", de: "Jäger im Großen Becken" },
  "dec:7500bc": { en: "Old Tjikko Takes Root", de: "Old Tjikko schlägt Wurzeln" },
  "dec:7000bc": { en: "Britain Becomes an Island", de: "Britannien wird zur Insel" },
  "dec:6750bc": { en: "Pistachio Gatherers", de: "Die Pistaziensammler" },
  "dec:6600bc": { en: "Soybeans in Ancient China", de: "Sojabohnen im alten China" },
  "dec:6500bc": { en: "Farming Reaches Europe", de: "Der Ackerbau erreicht Europa" },
  "dec:6200bc": { en: "China's First Jade", de: "Chinas erste Jade" },
  "dec:6050bc": { en: "Salt Boilers of Romania", de: "Salzsieder in Rumänien" },
  "dec:6000bc": { en: "Olives, Peaches and Chickens", de: "Olive, Pfirsich und Huhn" },
  "dec:5600bc": { en: "Peanuts in South America", de: "Erdnüsse in Südamerika" },
  "dec:5500bc": { en: "The First Drums", de: "Die ersten Trommeln" },
  "dec:5400bc": { en: "Jade Carvers of Xinglongwa", de: "Jadeschnitzer von Xinglongwa" },
  "dec:5000bc": { en: "Wheat Reaches Central Europe", de: "Weizen erreicht Mitteleuropa" },
  "dec:4600bc": { en: "Gold of Varna", de: "Das Gold von Warna" },
  "dec:4500bc": { en: "The Proto-Indo-Europeans", de: "Die Urindogermanen" },
  "dec:4200bc": { en: "Varna's Golden Necropolis", de: "Die Nekropole von Warna" },
  "dec:4000bc": { en: "Sumer Takes Shape", de: "Sumer nimmt Gestalt an" },
  "dec:3500bc": { en: "The First Cities", de: "Die ersten Städte" },
  "dec:3300bc": { en: "Ötzi and the Bronze Age", de: "Ötzi und die Bronzezeit" },
  "dec:3100bc": { en: "Egypt's First Pharaohs", de: "Ägyptens erste Pharaonen" },
  "dec:3000bc": { en: "Almonds, Geese and Vinegar", de: "Mandeln, Gänse und Essig" },
  "dec:2900bc": { en: "Early Dynastic Egypt", de: "Ägyptische Frühzeit" },
  "dec:2830bc": { en: "The Methuselah Pine Sprouts", de: "Die Kiefer Methusalem keimt" },
  "dec:2700bc": { en: "Gilgamesh of Uruk", de: "Gilgamesch von Uruk" },
  "dec:2650bc": { en: "Djoser's Step Pyramid", de: "Djosers Stufenpyramide" },
  "dec:2600bc": { en: "The Great Pyramid", de: "Die Große Pyramide" },
  "dec:2550bc": { en: "Khafre and the Sphinx", de: "Chephren und die Sphinx" },
  "dec:2500bc": { en: "Menkaure's Pyramid", de: "Die Pyramide des Mykerinos" },
  "dec:2400bc": { en: "The Pyramid Texts", de: "Die Pyramidentexte" },
  "dec:2330bc": { en: "Sargon of Akkad", de: "Sargon von Akkad" },
  "dec:2300bc": { en: "Liangzhu Jade", de: "Die Jade von Liangzhu" },
  "dec:2270bc": { en: "The Akkadian Empire", de: "Das Akkadische Reich" },
  "dec:2200bc": { en: "Taming the Horse", de: "Die Zähmung des Pferdes" },
  "dec:2090bc": { en: "Shulgi of Ur", de: "Schulgi von Ur" },
  "dec:2040bc": { en: "The Third Dynasty of Ur", de: "Die Dritte Dynastie von Ur" },
  "dec:2000bc": { en: "Saffron and Cinnamon", de: "Safran und Zimt" },
  "dec:1930bc": { en: "The Laws of Eshnunna", de: "Die Gesetze von Eschnunna" },
  "dec:1900bc": { en: "First Palace of Knossos", de: "Der erste Palast von Knossos" },
  "dec:1800bc": { en: "Babylonian Mathematics", de: "Babylonische Mathematik" },
  "dec:1790bc": { en: "Hammurabi Takes the Throne", de: "Hammurabi besteigt den Thron" },
  "dec:1750bc": { en: "The Code of Hammurabi", de: "Der Codex Hammurabi" },
  "dec:1650bc": { en: "The Mesoamerican Ballgame", de: "Mesoamerikas Ballspiel" },
  "dec:1600bc": { en: "The Eruption of Thera", de: "Der Ausbruch von Thera" },
  "dec:1570bc": { en: "Tyrian Purple", de: "Der Purpur der Phönizier" },
  "dec:1500bc": { en: "Age of Hatshepsut", de: "Zeitalter der Hatschepsut" },
  "dec:1400bc": { en: "The Uluburun Shipwreck", de: "Das Wrack von Uluburun" },
  "dec:1350bc": { en: "Akhenaten's Sun Disc", de: "Echnatons Sonnenscheibe" },
  "dec:1340bc": { en: "The Bust of Nefertiti", de: "Die Büste der Nofretete" },
  "dec:1330bc": { en: "The Boy Pharaoh", de: "Der Kindpharao" },
  "dec:1320bc": { en: "Tutankhamun's Gold Mask", de: "Tutanchamuns Goldmaske" },
  "dec:1290bc": { en: "Karnak's Hypostyle Hall", de: "Der Säulensaal von Karnak" },
  "dec:1260bc": { en: "Ramesses the Great", de: "Ramses der Große" },
  "dec:1250bc": { en: "Mycenae's Lion Gate", de: "Das Löwentor von Mykene" },
  "dec:1240bc": { en: "The Temples of Abu Simbel", de: "Die Tempel von Abu Simbel" },
  "dec:1220bc": { en: "Ramesses' Long Reign", de: "Ramses' lange Herrschaft" },
  "dec:1200bc": { en: "Bronze Age Collapse", de: "Zusammenbruch der Bronzezeit" },
  "dec:1190bc": { en: "The Fall of Troy", de: "Der Fall Trojas" },
  "dec:1180bc": { en: "The Trojan War", de: "Der Trojanische Krieg" },
  "dec:1100bc": { en: "Babylonian Star Lore", de: "Babylonische Sternkunde" },
  "dec:1050bc": { en: "The Phoenician Alphabet", de: "Das phönizische Alphabet" },
  "dec:1000bc": { en: "David and Goliath", de: "David und Goliath" },
  "dec:970bc": { en: "King Solomon", de: "König Salomo" },
  "dec:950bc": { en: "Solomon's Temple", de: "Der Salomonische Tempel" },
  "dec:930bc": { en: "The Kingdom Divides", de: "Die Reichsteilung" },
  "dec:900bc": { en: "The Geometric Style", de: "Der geometrische Stil" },
  "dec:870bc": { en: "Ahab and Elijah", de: "Ahab und Elija" },
  "dec:850bc": { en: "The Battle of Qarqar", de: "Die Schlacht bei Karkar" },
  "dec:810bc": { en: "The Founding of Carthage", de: "Die Gründung Karthagos" },
  "dec:800bc": { en: "The Age of Homer", de: "Das Zeitalter Homers" },
  "dec:770bc": { en: "The First Olympics", de: "Die ersten Olympischen Spiele" },
  "dec:750bc": { en: "Romulus Founds Rome", de: "Romulus gründet Rom" },
  "dec:730bc": { en: "Hesiod's Theogony", de: "Hesiods Theogonie" },
  "dec:720bc": { en: "The Fall of Israel", de: "Der Untergang Israels" },
  "dec:710bc": { en: "King Numa's Calendar", de: "König Numas Kalender" },
  "dec:700bc": { en: "The First Coins", de: "Die ersten Münzen" },
  "dec:680bc": { en: "Chariots at Olympia", de: "Wagenrennen in Olympia" },
  "dec:670bc": { en: "Ashurbanipal's Assyria", de: "Assurbanipals Assyrien" },
  "dec:640bc": { en: "Riders at Olympia", de: "Reiter in Olympia" },
  "dec:620bc": { en: "Thales of Miletus", de: "Thales von Milet" },
  "dec:610bc": { en: "The Fall of Nineveh", de: "Der Fall Ninives" },
  "dec:600bc": { en: "Greeks Found Marseille", de: "Griechen gründen Massalia" },
  "dec:590bc": { en: "Corinthian Pottery", de: "Korinthische Keramik" },
  "dec:580bc": { en: "The Babylonian Exile", de: "Das Babylonische Exil" },
  "dec:570bc": { en: "Pythagoras of Samos", de: "Pythagoras von Samos" },
  "dec:560bc": { en: "Peisistratos Rules Athens", de: "Peisistratos herrscht in Athen" },
  "dec:550bc": { en: "Birth of Confucius", de: "Die Geburt des Konfuzius" },
  "dec:540bc": { en: "The Fall of Croesus", de: "Der Sturz des Krösus" },
  "dec:530bc": { en: "Thespis and the First Tragedy", de: "Thespis und die erste Tragödie" },
  "dec:520bc": { en: "Darius the Great", de: "Dareios der Große" },
  "dec:500bc": { en: "Birth of Athenian Democracy", de: "Die Reformen des Kleisthenes" },
  "dec:490bc": { en: "The Battle of Marathon", de: "Die Schlacht bei Marathon" },
  "dec:480bc": { en: "Thermopylae and Salamis", de: "Thermopylen und Salamis" },
  "dec:470bc": { en: "The Delian League", de: "Der Attisch-Delische Seebund" },
  "dec:460bc": { en: "The Rise of Pericles", de: "Der Aufstieg des Perikles" },
  "dec:450bc": { en: "Aeschylus' Oresteia", de: "Die Orestie des Aischylos" },
  "dec:440bc": { en: "The Parthenon Rises", de: "Der Parthenon entsteht" },
  "dec:430bc": { en: "The Peloponnesian War", de: "Der Peloponnesische Krieg" },
  "dec:420bc": { en: "The Porch of the Maidens", de: "Die Korenhalle" },
  "dec:410bc": { en: "The Four Hundred", de: "Die Herrschaft der Vierhundert" },
  "dec:400bc": { en: "The Thirty Tyrants", de: "Die Dreißig Tyrannen" },
  "dec:390bc": { en: "The Trial of Socrates", de: "Der Prozess des Sokrates" },
  "dec:380bc": { en: "Plato's Academy", de: "Platons Akademie" },
  "dec:370bc": { en: "Plato's Republic", de: "Platons Politeia" },
  "dec:360bc": { en: "Aristotle at the Academy", de: "Aristoteles an der Akademie" },
  "dec:350bc": { en: "Birth of Alexander", de: "Die Geburt Alexanders" },
  "dec:340bc": { en: "Aristotle Tutors Alexander", de: "Aristoteles lehrt Alexander" },
  "dec:330bc": { en: "Alexander Conquers Persia", de: "Alexander erobert Persien" },
  "dec:320bc": { en: "Death of Alexander", de: "Der Tod Alexanders" },
  "dec:310bc": { en: "Wars of the Successors", de: "Die Diadochenkriege" },
  "dec:300bc": { en: "Euclid's Elements", de: "Euklids Elemente" },
  "dec:290bc": { en: "The Colossus of Rhodes", de: "Der Koloss von Rhodos" },
  "dec:280bc": { en: "Pyrrhus Invades Italy", de: "Pyrrhus landet in Italien" },
  "dec:270bc": { en: "A Pyrrhic Victory", de: "Ein Pyrrhussieg" },
  "dec:260bc": { en: "The First Punic War", de: "Der Erste Punische Krieg" },
  "dec:250bc": { en: "Archimedes and the Circle", de: "Archimedes und der Kreis" },
  "dec:240bc": { en: "Eureka!", de: "Heureka!" },
  "dec:230bc": { en: "Chrysippus and the Stoa", de: "Chrysipp und die Stoa" },
  "dec:220bc": { en: "The Colossus Falls", de: "Der Koloss stürzt" },
  "dec:210bc": { en: "The Terracotta Army", de: "Die Terrakotta-Armee" },
  "dec:200bc": { en: "The Han Dynasty", de: "Die Han-Dynastie" },
  "dec:190bc": { en: "Parchment of Pergamon", de: "Pergament aus Pergamon" },
  "dec:180bc": { en: "The House of the Faun", de: "Das Haus des Fauns" },
  "dec:170bc": { en: "Antiochus Epiphanes", de: "Antiochos Epiphanes" },
  "dec:160bc": { en: "The Maccabean Revolt", de: "Der Makkabäeraufstand" },
  "dec:150bc": { en: "Carneades in Rome", de: "Karneades in Rom" },
  "dec:140bc": { en: "Carthage Destroyed", de: "Die Zerstörung Karthagos" },
  "dec:130bc": { en: "The Gracchi Reforms", de: "Die Reformen der Gracchen" },
  "dec:120bc": { en: "Death of Gaius Gracchus", de: "Der Tod des Gaius Gracchus" },
  "dec:110bc": { en: "The Jugurthine War", de: "Der Jugurthinische Krieg" },
  "dec:100bc": { en: "Marius and the Cimbri", de: "Marius und die Kimbern" },
  "dec:90bc": { en: "The Social War", de: "Der Bundesgenossenkrieg" },
  "dec:80bc": { en: "Sulla Marches on Rome", de: "Sulla marschiert auf Rom" },
  "dec:70bc": { en: "Spartacus's Revolt", de: "Der Spartacus-Aufstand" },
  "dec:60bc": { en: "The First Triumvirate", de: "Das Erste Triumvirat" },
  "dec:50bc": { en: "Caesar's Gallic Wars", de: "Caesars Gallischer Krieg" },
  "dec:40bc": { en: "The Ides of March", de: "Die Iden des März" },
  "dec:30bc": { en: "Egypt Becomes Roman", de: "Ägypten wird römisch" },
  "dec:20bc": { en: "Augustus, First Emperor", de: "Augustus, der erste Kaiser" },
  "dec:10bc": { en: "Virgil's Aeneid", de: "Vergils Aeneis" },
  "dec:0bc": { en: "Birth of Jesus", de: "Die Geburt Jesu" },
};
