import type { BlockName } from "./types.ts";

// Names for the decades from 1500 on. See ./index.ts.

export const DECADES_MODERN: Readonly<Record<string, BlockName>> = {
  "dec:1500": { en: "New World & High Renaissance", de: "Neue Welt und Hochrenaissance" },
  "dec:1510": { en: "Reformation & Conquistadors", de: "Reformation und Konquistadoren" },
  "dec:1520": { en: "Diet of Worms & Peasants' War", de: "Wormser Reichstag, Bauernkrieg" },
  "dec:1530": { en: "Henry VIII & the Inca's Fall", de: "Heinrich VIII. und die Inka" },
  "dec:1540": { en: "The Sun Moves to the Centre", de: "Die Sonne rückt ins Zentrum" },
  "dec:1550": { en: "Peace of Augsburg", de: "Augsburger Religionsfrieden" },
  "dec:1560": { en: "Wars of Religion Begin", de: "Beginn der Hugenottenkriege" },
  "dec:1570": { en: "St Bartholomew's Massacre", de: "Bartholomäusnacht" },
  "dec:1580": { en: "The Armada & Montaigne", de: "Armada und Montaignes Essais" },
  "dec:1590": { en: "Hamlet & Mercator's Atlas", de: "Hamlet und Mercators Atlas" },
  "dec:1600": { en: "Dawn of the Baroque", de: "Aufbruch ins Barock" },
  "dec:1610": { en: "Telescopes & Defenestration", de: "Fernrohr und Fenstersturz" },
  "dec:1620": { en: "Thirty Years' War", de: "Dreißigjähriger Krieg" },
  "dec:1630": { en: "Cogito & the Taj Mahal", de: "Cogito und Taj Mahal" },
  "dec:1640": { en: "Peace of Westphalia", de: "Westfälischer Friede" },
  "dec:1650": { en: "Leviathan & the Sun King", de: "Leviathan und Sonnenkönig" },
  "dec:1660": { en: "Versailles & Molière", de: "Versailles und Molière" },
  "dec:1670": { en: "Leeuwenhoek's Animalcules", de: "Leeuwenhoeks Tierchen" },
  "dec:1680": { en: "Newton's Gravity", de: "Newton und die Schwerkraft" },
  "dec:1690": { en: "Te Deum & Late Baroque", de: "Te Deum und Spätbarock" },
  "dec:1700": { en: "War of the Spanish Succession", de: "Spanischer Erbfolgekrieg" },
  "dec:1710": { en: "Bach, Zwinger & Belvedere", de: "Bach, Zwinger und Belvedere" },
  "dec:1720": { en: "The Well-Tempered Clavier", de: "Das Wohltemperierte Klavier" },
  "dec:1730": { en: "The Age of Rococo", de: "Zeitalter des Rokoko" },
  "dec:1740": { en: "Frederick & Maria Theresa", de: "Friedrich und Maria Theresia" },
  "dec:1750": { en: "Encyclopédie & Linnaeus", de: "Enzyklopädie und Linné" },
  "dec:1760": { en: "Catherine the Great", de: "Katharina die Große" },
  "dec:1770": { en: "Werther & the Tea Party", de: "Sturm und Drang" },
  "dec:1780": { en: "Enlightenment & Bastille", de: "Aufklärung und Bastille" },
  "dec:1790": { en: "Revolution & Guillotine", de: "Revolution und Guillotine" },
  "dec:1800": { en: "Napoleon & the Empire's End", de: "Napoleon und das Reichsende" },
  "dec:1810": { en: "Moscow, Waterloo & Vienna", de: "Die Befreiungskriege" },
  "dec:1820": { en: "Restoration & Romanticism", de: "Biedermeier und Romantik" },
  "dec:1830": { en: "July Revolution & Railways", de: "Vormärz und erste Eisenbahn" },
  "dec:1840": { en: "The Springtime of Peoples", de: "Völkerfrühling und Paulskirche" },
  "dec:1850": { en: "Crimea & Darwin's Origin", de: "Krimkrieg und Darwin" },
  "dec:1860": { en: "Civil War & Blood and Iron", de: "Bismarcks Einigungskriege" },
  "dec:1870": { en: "German Empire & Telephone", de: "Reichsgründung und Gründerzeit" },
  "dec:1880": { en: "Motorcar & Radio Waves", de: "Automobil und Funkwellen" },
  "dec:1890": { en: "Fin de Siècle", de: "Jahrhundertwende" },
  "dec:1900": { en: "Belle Époque & First Flight", de: "Kaiserzeit und Jugendstil" },
  "dec:1910": { en: "The Great War & Revolution", de: "Weltkrieg und Revolution" },
  "dec:1920": { en: "The Roaring Twenties", de: "Die Goldenen Zwanziger" },
  "dec:1930": { en: "Depression & Dictatorship", de: "Weltkrise und NS-Diktatur" },
  "dec:1940": { en: "World War & Holocaust", de: "Weltkrieg und Holocaust" },
  "dec:1950": { en: "Rock 'n' Roll & Cold War", de: "Wirtschaftswunder" },
  "dec:1960": { en: "Space Race & Flower Power", de: "Mondlandung und Blumenkinder" },
  "dec:1970": { en: "Disco, Oil Crisis & Punk", de: "Ölkrise und Deutscher Herbst" },
  "dec:1980": { en: "Synth-Pop & the Wall Falls", de: "NDW, Walkman und Mauerfall" },
  "dec:1990": { en: "Unity, Techno & the Web", de: "Einheit, Loveparade, Internet" },
  "dec:2000": { en: "Terror, the Euro & the iPod", de: "Terror, Euro und Sommermärchen" },
  "dec:2010": { en: "Smartphones & Social Media", de: "Smartphone und soziale Medien" },
  "dec:2020": { en: "Pandemic & Upheaval", de: "Pandemie und Zeitenwende" },
  "dec:2100": { en: "Polaris at the Pole", de: "Polarstern am Himmelspol" },
};
