// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug brass-lancashire
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Heavy economic network game where players spend cards and cash to build industries, sell cotton, and lay canals or rails.",
  default:
    "Heavy economic network strategy about building mills, mines, ports, and links across Lancashire. Each turn, spend cards and cash for two actions: build, develop, sell cotton, take a loan, or lay canal or rail. Most points from flipped industries and owned links after both eras wins.",
  loose:
    "Heavy economic network strategy about building mills, mines, iron works, ports, shipyards, and transport links across Lancashire. Each turn, spend cards and cash for two actions: build, lay canal or rail, develop better tiles, sell cotton, or take a loan. Score after the canal era and again after the rail era; most points from flipped industries and owned links wins. Turn order follows last round’s spending, so a cheap turn can set up a rare back-to-back move.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:50.425Z",
  model: "gpt-5.5",
  durationMs: 21688,
  sources: [
    "https://roxley.com/products/brass-lancashire",
    "https://files.roxley.com/Brass-Lancashire-Rulebook-2018.11.20-highlights.pdf",
    "https://www.board-game.co.uk/brass-lancashire-review/",
  ],
} as const;
