// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug brass-lancashire
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "An industrial map turns other players’ coal and rails into temptation in a hand-management fight over Lancashire’s canal and rail eras.",
  default:
    "Lancashire’s mills, mines, and ports tempt rivals to use the very infrastructure that feeds their scores. Hand management drives each turn as cards constrain builds. Most points after the canal and rail eras wins.",
  loose:
    "Lancashire’s mills, mines, and ports tempt rivals to use the very infrastructure that feeds their scores. Hand management drives each turn, with cards narrowing where industries can appear as canals give way to rails. The winner has the most points after both eras from flipped industries and links. The least spender acts first next round, making thrift a weapon for back-to-back turns.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:16.091Z",
  model: "gpt-5.5",
  durationMs: 27843,
  sources: [
    "https://roxley.com/products/brass-lancashire",
    "https://www.pevans.co.uk/Reviews/Brass.pdf",
    "https://gamesnightguru.com/game/brass/",
  ],
} as const;
