// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug cascadia
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Relaxed tile-and-token drafting puzzle where each turn picks a paired hex and animal token to grow a scoring habitat.",
  default:
    "Light spatial puzzle where players draft paired habitat hexes and animal tokens for private nature maps. A turn takes one display pair, places the hex, then puts the animal on a matching icon. Highest score wins from wildlife patterns, connected habitats, bonuses, and leftover nature tokens.",
  loose:
    "Light spatial puzzle where players draft paired hex tiles and animal tokens to build private Pacific Northwest habitats. A turn picks one display pair, adds the hex to the map, then places the animal on a matching icon if a legal space exists. At the end, highest score wins from wildlife cards, connected habitat regions, majority bonuses, and unused nature tokens. Pine-cone tokens can refresh bad animal draws or split a pair, so the market rarely feels punishing.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:07.091Z",
  model: "gpt-5.5",
  durationMs: 28561,
  sources: [
    "https://www.flatout.games/cascadia",
    "https://merchantsofplay.com/howtoplay/cascadia/",
    "https://www.geekyhobbies.com/cascadia-rules/",
    "https://www.reddit.com/r/boardgames/comments/q2kw7b/cascadia_review_american_animal_npi/",
  ],
} as const;
