// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug codenames
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A single clue can rescue a team or doom it, as word association turns a 5x5 grid into shared logic and dread.",
  default:
    "A one-word clue can save three agents or point straight at the assassin. Word association drives each turn, with teammates debating which cards the spymaster meant. A team wins by finding all its agents first, unless one fatal guess ends the game.",
  loose:
    "Every clue is a gamble, because one word must steer teammates toward the right cards and away from disaster. Word association drives the play. A team wins by finding all its agents first, unless a guess hits the assassin and ends everything at once. Chvátil’s prototype was hand-torn paper in a grid, already close to the finished game.",
};

export const meta = {
  generatedAt: "2026-05-13T16:28:07.028Z",
  model: "gpt-5.5",
  durationMs: 41688,
  sources: [
    "https://www.czechgames.com/games/codenames",
    "https://filemanager.czechgames.com/storage/files/codenames/rules/codenames-rules-en.pdf",
    "https://www.theguardian.com/culture/2024/sep/26/vlaada-chvatil-codenames-board-game-market-czech-phone",
  ],
} as const;
