// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug decrypto
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Team word-deduction party game where clue givers encode three numbered words while rivals build a note sheet to intercept them.",
  default:
    "Team word-deduction party game about sending three-digit codes through clues while the other side listens and takes notes. Each round, an encryptor draws a code card, writes three public clues, and both teams guess the number order. Two interceptions win; two miscommunications lose.",
  loose:
    "Team word-deduction party game about sending three-digit codes through clues while the other side listens and takes notes. Each round, one encryptor draws a code card, writes three public clues for the matching hidden keywords, and both teams guess the number order. Two interception tokens win the game, while two miscommunication tokens lose it. Each team has a numbered screen holding four secret keyword cards, so old clues pile up into a visible trail for opponents.",
};

export const meta = {
  generatedAt: "2026-05-13T20:18:52.042Z",
  model: "gpt-5.5",
  durationMs: 22853,
  sources: [
    "https://shop.scorpionmasque.com/products/decrypto",
    "https://www.scorpionmasque.com/sites/scorpionmasque.com/files/decrypto_en_rules_20sep2019_1.pdf",
    "https://www.play-board-games.com/decrypto-board-game-review/",
    "https://www.meeplemountain.com/reviews/decrypto/",
  ],
} as const;
