// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug decrypto
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Fragile clues must guide allies while feeding rivals a growing pattern in this tense deduction game of numbered secret words.",
  default:
    "A clue that saves a team now can expose its code three rounds later. Deduction drives each round as one encryptor links three public clues to four hidden numbered words. A team wins by intercepting two opposing codes, while two botched home-team decodes lose the game.",
  loose:
    "A clue that saves a team now can expose its code three rounds later. Deduction drives each round as one encryptor links three public clues to four hidden numbered words. A team wins by intercepting two opposing codes, while two botched home-team decodes lose the game. The screens slot 110 keyword cards into numbered windows, turning a party table into a paper trail.",
};

export const meta = {
  generatedAt: "2026-05-13T16:34:26.864Z",
  model: "gpt-5.5",
  durationMs: 26705,
  sources: [
    "https://www.hachetteboardgames.com/products/decrypto",
    "https://shop.scorpionmasque.com/fr/products/decrypto",
    "https://ryanboardgames.com/reviews/decrypto-review",
    "https://www.reddit.com/r/boardgames/comments/txh13f/game_of_the_week_decrypto/",
  ],
} as const;
