// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug gloomhaven
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A dungeon crawl becomes a stamina puzzle through hand management, where every swing, sprint, and spell spends a shrinking hand of cards.",
  default:
    "Every dungeon is a stamina puzzle, because attacks, movement, and rest all drain the same hand of cards. Hand management drives play: each round, a mercenary plays two ability cards and uses the top of one with the bottom of the other. Scenarios end when the party meets its objective or exhausts.",
  loose:
    "Every dungeon is a stamina puzzle, because attacks, movement, and rest all drain the same hand of cards. Hand management drives play: each round, a mercenary plays two ability cards and uses the top of one with the bottom of the other. Scenarios end when the party meets its objective or exhausts, while the campaign unlocks maps, classes, and retirements. Stickers turn the city map into a record of the group's choices.",
};

export const meta = {
  generatedAt: "2026-05-13T16:35:20.194Z",
  model: "gpt-5.5",
  durationMs: 46625,
  sources: [
    "https://cephalofair.com/pages/games",
    "https://cephalofair.com/pages/gloomhaven",
    "https://cephalofair.com/pages/about",
    "https://www.tabletopgaming.co.uk/Reviews/gloomhaven-review/",
    "https://www.gameinformer.com/b/features/archive/2017/12/15/top-of-the-table-gloomhaven.aspx",
  ],
} as const;
