// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug escape-tales-the-awakening
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative escape-room card game where players spend action tokens on map spots, solve code puzzles, and chase a better ending.",
  default:
    "Cooperative, story-heavy escape-room card game with no countdown clock. Each turn, players spend action tokens on map spots, read storybook entries, draw item or puzzle cards, and enter codes in the web app. The game ends in one of several story endings, with the best result tied to finding Lizzy and avoiding too many doom cards.",
  loose:
    "Cooperative, story-heavy escape-room card game built around exploration, puzzles, and moral choices instead of a countdown clock. Each scene lays location cards on a board; players spend action tokens to inspect grid spots, read numbered storybook paragraphs, collect item and puzzle cards, and enter codes in the web app. The game ends at one of several storybook endings, with the best outcome tied to finding Lizzy and avoiding too many doom cards. The table feel is closer to a dark choose-your-path puzzle novel than a timed escape race.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:15.769Z",
  model: "gpt-5.5",
  durationMs: 20894,
  sources: [
    "https://boardanddice.com/product/escape-tales-the-awakening/",
    "https://escape-tales.com/awakening",
    "https://www.meeplemountain.com/reviews/escape-tales-the-awakening/",
    "https://cdn.1j1ju.com/medias/c6/1f/3f-escape-tales-the-awakening-rulebook.pdf",
  ],
} as const;
