// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug escape-tales-the-awakening
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "A father’s occult rescue turns every room search into a moral gamble, with exploration driven by dwindling action tokens.",
  default:
    "A father’s occult rescue turns an escape-room box into a grim tale of memory and grief. Exploration drives play through action-token searches on card-grid rooms. Finding Lizzy is the goal, but choices and Doom cards steer Samuel toward several endings.",
  loose:
    "A father’s occult rescue turns an escape-room box into a grim tale of grief and bad bargains. Exploration drives play: action tokens buy searches on card-grid rooms, and a web app checks puzzle answers. Finding Lizzy is the goal, but choices and Doom cards steer Samuel toward several endings. Each location card is a six-square map, so one wrong corner can burn a vital token.",
};

export const meta = {
  generatedAt: "2026-05-13T16:35:07.582Z",
  model: "gpt-5.5",
  durationMs: 40717,
  sources: [
    "https://boardanddice.com/product/escape-tales-the-awakening/",
    "https://escapethereview.co.uk/escape-tales-the-awakening/",
    "https://www.thegamingreview.com/11808/2019/05/15/board-game-review-escape-tales-the-awakening/",
    "https://cdn.1j1ju.com/medias/c6/1f/3f-escape-tales-the-awakening-rulebook.pdf",
  ],
} as const;
