// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug roma-xli
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Social deduction card game where senators play secret exile votes, public actions, and legion shields while cutting deals.",
  default:
    "Social deduction party-strategy game about surviving secret votes and shifting alliances. On a turn, play one card face down as an exile vote or legion shield, or face up for an action or boost, then roll the die. When the exile track hits red, votes flip; the final un-exiled contender wins.",
  loose:
    "Social deduction party-strategy game about outlasting rival Roman power brokers with secret votes, alliances, and betrayals. On a turn, play one card face down as an exile vote or legion shield, or face up for an action or boost, then refill and roll for track movement or gold. When the exile track hits red, hidden votes flip and the most-voted unprotected character is exiled; the last contender on the map wins. Empty seats run as automated Ghosts, and exiled players can still bargain for a comeback.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:10.790Z",
  model: "gpt-5.5",
  durationMs: 24253,
  sources: [
    "https://www.wargamer.com/board-games/roma-xli",
    "https://www.thegamesteward.com/products/roma-xli-everything-new-pledge-kickstarter-edition-board-game",
    "https://frogames.it/en/products/roma-xli",
  ],
} as const;
