// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug roma-xli
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "After Caesar’s murder, face-down exile votes turn hand management into a Roman knife fight of allies, legions, and betrayals.",
  default:
    "After Caesar’s murder, every alliance points toward the next exile. Hand management drives each turn through hidden votes, protective legions, open actions, and permanent boosts. The last contender left on the map claims Rome.",
  loose:
    "After Caesar’s murder, every ally can become the next name on the exile slate. Hand management drives each turn, with cards hidden as votes or legions, or exposed for actions and lasting boosts. The last contender on the map claims Rome, but exiles can bargain, claw back influence, and re-enter the knife fight. All nine Roman leaders begin in play, and unchosen rivals still take automated turns.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:03.578Z",
  model: "gpt-5.5",
  durationMs: 129332,
  sources: [
    "https://facadegames.com/",
    "https://www.wargamer.com/board-games/roma-xli",
    "https://www.reddit.com/r/boardgames/comments/1s3cf6z/im_the_designer_of_the_dark_cities_series_salem/",
    "https://www.kicktraq.com/projects/facadegames/roma-xli-game/",
  ],
} as const;
