// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug a-game-of-thrones-the-card-game
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Westeros politics turn each round into knives-out hand management, with plots setting income, initiative, and the pain of each challenge.",
  default:
    "Power in Westeros changes hands through military, intrigue, and power challenges. Hand management drives custom House decks and seven-card plot decks. The first House to hold 15 power wins, unless table politics cuts that lead apart.",
  loose:
    "Power in Westeros changes hands through military, intrigue, and power challenges, so every attack threatens bodies, cards, or points. Hand management drives custom House decks and seven-card plot decks. The first House to hold 15 power wins, but multiplayer titles create temporary alliances. The core box included Stark, Lannister, Baratheon, and Targaryen decks.",
};

export const meta = {
  generatedAt: "2026-05-13T16:32:42.687Z",
  model: "gpt-5.5",
  durationMs: 29219,
  sources: [
    "https://www.fantasyflightgames.com/en/products/a-game-of-thrones-lcg/",
    "https://www.fantasyflightgames.com/en/news/2014/11/5/a-new-road-forward/",
    "https://www.scribd.com/document/58682079/AGOT-Coreset-Rules",
  ],
} as const;
