// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug a-game-of-thrones-the-card-game
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Thinky Living Card Game where each round reveals a plot, marshals characters, and attacks through military, intrigue, and power challenges.",
  default:
    "Thinky competitive Living Card Game built around custom House decks and a separate plot deck. Each round, players reveal plots, spend gold on characters and locations, then kneel characters into military, intrigue, and power challenges. First player to collect 15 power wins.",
  loose:
    "Thinky competitive Living Card Game built around custom House decks and a separate plot deck. Each round, players reveal plots, spend gold on characters and locations, then kneel characters into military, intrigue, and power challenges. Military kills characters, intrigue discards cards, power steals tokens, and the first player to collect 15 power wins. The LCG format used fixed card packs instead of random boosters.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:09.522Z",
  model: "gpt-5.5",
  durationMs: 9181,
  sources: [
    "https://www.fantasyflightgames.com/en/products/a-game-of-thrones-lcg/",
    "https://www.polyhedroncollider.com/2014/05/a-game-of-thrones-card-game-review.html",
    "https://en.wikipedia.org/wiki/A_Game_of_Thrones_%28card_game%29",
  ],
} as const;
