// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug quiztopia
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative quiz game where the table picks building-category cards, answers trivia, and uses clue cards to save enough buildings.",
  default:
    "Cooperative quiz game with a party edge, about saving building cards that double as trivia categories. Each turn, one player chooses a building, hears the matching question, and may get table help. Correct answers claim or brighten buildings; wrong answers darken or lose them. Win by claiming the target before the question deck or loss.",
  loose:
    "Cooperative quiz game with a party edge, about saving building cards that double as trivia categories. On a turn, the active player chooses a building, another player reads its matching question, and the table may discuss or spend help for one-word clues, pantomime, humming, or noises. Correct answers claim or brighten buildings; wrong answers darken or lose them, and the team wins by claiming the target before the question deck or loss limit runs out. The card holder hides answers while feeding a fixed deck of question cards.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:05.497Z",
  model: "gpt-5.5",
  durationMs: 30056,
  sources: [
    "https://www.kosmos.de/de/quiztopia_1694296_4002051694296",
    "https://cms.kosmos.de/game-instructions/4002051694296_Quiztopia_Manual_220420_web.pdf",
    "https://www.brettspielabend.net/2019/08/18/quiztopia/",
    "https://www.reich-der-spiele.de/kritiken/Quiztopia",
    "https://www.krimimaster.de/2019/08/03/quiztopia-die-welt-ist-nicht-genug/",
  ],
} as const;
