// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug quiztopia
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Trivia answers tug a city between color and darkness, with cooperative play turning every blank stare into tablewide crisis.",
  default:
    "Each answer pulls one of twelve city buildings toward color or darkness. Cooperative play drives the quiz as the table manages categories, help cards, and risk. The team wins by claiming enough buildings within 24 questions before too many fall.",
  loose:
    "Each answer pulls one of twelve city buildings toward color or darkness, so a missed category can vanish from the table. Cooperative play drives the quiz, with one player choosing a building while the table weighs knowledge, risk, and help cards. The team wins by claiming enough buildings within 24 questions before too many fall. Expert rules ration help into one-word clues, pantomime, humming, and noises.",
};

export const meta = {
  generatedAt: "2026-05-13T16:38:30.802Z",
  model: "gpt-5.5",
  durationMs: 41269,
  sources: [
    "https://quiztopia.de/",
    "https://quiztopia.de/download/quiztopia-spielregeln_2.0.pdf",
    "https://www.kosmos.de/de/quiztopia_1694296_4002051694296",
    "https://www.brettspielabend.net/2019/08/18/quiztopia/",
    "https://www.krimimaster.de/2019/08/03/quiztopia-die-welt-ist-nicht-genug/",
  ],
} as const;
