// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug hollywood-1947
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Hidden-role social deduction game where studio jobs, dice, and secret propaganda cards steer each movie toward a team.",
  default:
    "Hidden-role social deduction game about a film studio split between Patriots, Communists, and maybe a Rising Star. Each round, everyone uses a job power or rerolls dice, then star-side dice add secret propaganda cards to the movie. Four films for one faction wins, unless the Rising Star keeps the score nearly tied.",
  loose:
    "Hidden-role social deduction game about a film studio where Patriots and Communists steer each movie’s message. Each round, everyone uses a job power or rerolls dice, then star-side dice let those players secretly add propaganda cards to the poster. Four Patriot films or four Communist films wins for that team; a Rising Star can steal it if the sides stay nearly tied. The faux book box, filmstrip overlays, genre posters, and custom dice make the table look like a studio archive.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:53.297Z",
  model: "gpt-5.5",
  durationMs: 21340,
  sources: [
    "https://facadegames.com/products/hollywood-1947",
    "https://www.boardseyeview.net/post/hollywood-1947",
    "https://www.tabletopgaming.co.uk/Reviews/hollywood-1947-game-review/",
  ],
} as const;
