// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug take-5
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light simultaneous card game where everyone reveals one number card and tries not to become the sixth card in a row.",
  default:
    "Light simultaneous card game about avoiding penalty cards in four shared rows. Each round, everyone chooses one numbered card face down, reveals together, then slots cards in ascending order. Fewest bullheads wins after a player reaches the score limit.",
  loose:
    "Light simultaneous card game about avoiding penalty cards in four shared rows. Each round, everyone chooses one numbered card face down, reveals together, then the cards slot into rows from lowest to highest by nearest lower end card. If a card would be sixth in a row, its player takes the five previous cards; after someone reaches 66 bullheads, the lowest total wins. The 104-card deck marks penalties with bullheads, making 55 the ugly seven-point trap.",
};

export const meta = {
  generatedAt: "2026-05-23T15:05:38.356Z",
  model: "gpt-5.5",
  durationMs: 17650,
  sources: [
    "https://www.amigo-spiele.de/6-nimmt_4910_1124",
    "https://bozosguide.com/2019/03/21/6-nimmt-1994-wolfgang-kramer/",
    "https://www.ultraboardgames.com/6-nimmt/game-rules.php",
    "https://en.wikipedia.org/wiki/6_nimmt%21",
  ],
} as const;
