// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug dungeons-and-dragons
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Fantasy tabletop RPG where a referee describes dungeons, players choose hero actions, and dice decide risky results.",
  default:
    "Fantasy tabletop role-playing game where a referee presents a dungeon or wilderness and the others speak for adventurers. When a character acts, the referee calls for dice, checks notes, and describes the result. The group succeeds by surviving quests, gaining treasure and experience, and getting home.",
  loose:
    "Fantasy tabletop role-playing game where a referee presents a dungeon or wilderness and the others speak for adventurers. When a character acts, the player says the move, like searching a door, casting a spell, or swinging a sword; the referee calls for dice and describes the result. The group succeeds by surviving quests, gaining treasure and experience, and getting home. The 1974 box used three little booklets, graph-paper maps, and polyhedral dice.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:10.070Z",
  model: "gpt-5.5",
  durationMs: 27658,
  sources: [
    "https://www.britannica.com/topic/Dungeons-and-Dragons",
    "https://artsandculture.google.com/asset/game-dungeons-dragons-rules-for-fantastic-medieval-wargames-campaigns-playable-with-paper-and-pencil-tsr-inc/AwED4llz7_kd0A?hl=en",
    "https://en.wikipedia.org/wiki/Dungeons_%26_Dragons_%281974%29",
  ],
} as const;
