// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug two-rooms-and-a-boom
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time hidden-roles party game where two teams split across two rooms swap hostages while hunting for the President and the Bomber.",
  default:
    "Hidden-roles party game played on foot across two separate rooms. During each timed round, players show cards or team colors to one another, and a leader chosen by pointing picks hostages to swap at the buzzer. Red wins if the Bomber ends in the President's room; Blue wins otherwise.",
  loose:
    "Hidden-roles party game played on foot across two separate rooms, with no moderator. During each timed round, players show cards or team colors to one another, and a leader chosen by pointing picks hostages to swap at the buzzer. Red wins if the Bomber ends in the President's room; Blue wins otherwise. Rounds shrink from three minutes to one, and extra role cards add oddballs like the Gambler, who wins by guessing the winning team.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.336Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 41642,
  sources: [
    "https://www.ultraboardgames.com/two-rooms-and-a-boom/game-rules.php",
    "https://www.tuesdayknightgames.com/products/two-rooms-and-a-boom",
    "https://www.boardgamequest.com/two-rooms-and-a-boom-review/",
  ],
} as const;
