// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug villainous
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Disney villains race across separate storyboards, using hand management to build schemes while rivals unleash movie heroes.",
  default:
    "Six Disney villains work through separate schemes, each with a deck, realm, and objective. Hand management drives the turn as cards fuel plans and Fate cards drop heroes onto rivals. The first villain to finish a private story goal wins.",
  loose:
    "Six classic Disney villains run on separate storyboards, so every scheme feels like a different problem under the same rules. Hand management drives each turn as cards fuel plans, gather power, and trigger Fate against rivals. Victory goes to the first villain to complete a private story goal, from hoarding Prince John’s gold to cursing Maleficent’s realm. The Queen of Hearts turns card guards into wickets, then tries to take the shot.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:40.528Z",
  model: "gpt-5.5",
  durationMs: 28880,
  sources: [
    "https://www.ravensburger.us/en-US/products/games/family-games/disney-villainous-the-worst-takes-it-all-60001739",
    "https://www.ravensburger.org/spielanleitungen/ecm/Spielanleitungen/26295%20anl%202050897.pdf?ossl=pds_text_Spielanleitung",
    "https://www.geeksundergrace.com/tabletop/review-disney-villainous/",
  ],
} as const;
