// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug villainous
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Asymmetric take-that strategy card game where each villain moves on a personal board, plays cards, and fates rivals.",
  default:
    "Asymmetric strategy card game where each villain races toward a different movie objective. Each turn, a player moves to a new board space, takes its action icons, plays cards, and may fate a rival with heroes. First to meet their printed villain goal wins.",
  loose:
    "Asymmetric strategy card game where every villain races toward a different movie-specific objective. On a turn, a player moves a sculpted mover to a new board space, takes its action icons, plays cards, then refills to four cards. First to meet their printed goal wins, such as hoarding power, defeating Peter Pan, or claiming the Trident and Crown. Fate actions let rivals drop heroes onto a board, covering actions with Ariel, Robin Hood, or Aladdin.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:31.558Z",
  model: "gpt-5.5",
  durationMs: 22081,
  sources: [
    "https://www.ravensburger.us/en-US/products/games/family-games/disney-villainous-the-worst-takes-it-all-60001739",
    "https://www.gamesradar.com/disney-villainous-board-game-review/",
    "https://boardgamegeek.com/boardgame/256382/disney-villainous-the-worst-takes-it-all",
  ],
} as const;
