// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug medical-mysteries-miami
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative medical deduction game where the table spends action points to question patients, order tests, read results, and treat.",
  default:
    "Cooperative medical deduction game about saving emergency-room patients by linking symptoms, records, and test results. Each action spends time-points on questions, labs, imaging, procedures, consults, or drugs, then a result code points to a story or status card. The case succeeds if the patient survives and the final report names the/a?",
  loose:
    "Cooperative medical deduction game about saving emergency-room patients by linking symptoms, records, and test results. Each action spends time-points on questions, labs, imaging, procedures, consults, or drugs, then a result code points to a story or status card. The case succeeds if the patient survives and the final report names the diagnosis, cause, treatment, and follow-up. Each patient envelope holds records, story cards, status cards, a report form, and an epilogue.",
};

export const meta = {
  generatedAt: "2026-08-14T22:20:05.394Z",
  model: "gpt-5.5",
  durationMs: 30785,
  sources: [
    "https://identitygames.nl/wp-content/uploads/2024/07/2025_IG_ProductSheet_MM.pdf",
    "https://www.escapetheroomers.com/post/identity-games-medical-mysteries-miami-flatline",
    "https://identitygames.nl/svhj-medical-mysteries/",
    "https://madresdesterradas.es/index.php/2025/07/07/medical-mysteries-miami-flatline/",
  ],
} as const;
