// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug cartographers
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Flip-and-write map-drawing game where everyone inks the same revealed terrain shape onto a personal grid, chasing rotating scoring goals.",
  default:
    "Flip-and-write spatial puzzle about drawing a fantasy map on a square grid. Each turn an explore card shows terrain types and polyomino shapes, and every player picks one to ink onto their own sheet. After four seasons of edict scoring, the most reputation stars wins.",
  loose:
    "Flip-and-write spatial puzzle about drawing a fantasy map on a square grid. Each turn an explore card shows terrain types and polyomino shapes, and every player picks one to ink onto their own sheet. Four edict cards score in overlapping pairs each season, and the most reputation stars after winter wins. Ambush cards pass each sheet to a neighbour, who draws a monster where it hurts most, and every empty square beside it costs a star.",
};

export const meta = {
  generatedAt: "2026-09-25T11:21:20.335Z",
  model: "claude-opus-5.5 (simulated run — research agent)",
  durationMs: 90000,
  sources: [
    "https://thunderworksgames.com/products/cartographers-board-game",
    "https://www.boardgamequest.com/cartographers-a-roll-player-tale-review/",
  ],
} as const;
