// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug tortuga-1667
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Pirate crews raid one prize ship while secret loyalties turn every vote for attacks, mutinies, and brawls into social deduction.",
  default:
    "A Spanish galleon feeds two pirate crews, but every helpful vote can hide sabotage. Social deduction drives face-down loyalties, shared vote cards, and offices like captain or governor. The richest French or British side wins when the Spanish Armada appears, unless the lone Dutch pirate steals a tie",
  loose:
    "One Spanish galleon feeds two pirate crews, and every helpful cannon vote may be sabotage in disguise. Social deduction drives face-down loyalties, shared vote cards, and offices like captain, first mate, and governor. When the Spanish Armada appears, the French or British side with more treasure wins, unless the lone Dutch pirate steals a tie. The faux book box opens onto a rubber map and wood treasure tokens.",
};

export const meta = {
  generatedAt: "2026-05-13T16:42:08.937Z",
  model: "gpt-5.5",
  durationMs: 36009,
  sources: [
    "https://facadegames.com/products/tortuga-1667",
    "https://cdn.shopify.com/s/files/1/0028/2964/7961/files/Tortuga_1667_P_P_Rules.pdf?15163670277584322649=",
    "https://www.geeksundergrace.com/tabletop/reviews-tabletop/review-tortuga-1667/",
    "https://www.reddit.com/r/boardgames/comments/1cru5he/im_travis_hancock_founder_of_facade_games_and/",
  ],
} as const;
