// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug tortuga-1667
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Social-deduction pirate game where secret loyalists move pawns, vote on attacks or mutinies, and stash treasure for their side.",
  default:
    "Social-deduction pirate game where secret British and French loyalists fight over stolen treasure. On a turn, move by rowboat, peek at or reveal an event card, or use a role action to attack, mutiny, or brawl. When the Spanish Armada appears, the side with more treasure wins.",
  loose:
    "Social-deduction pirate game where secret British and French loyalists shift treasure between ship holds while lying about their flag. Each turn, move by rowboat, peek at or reveal an event card, or trigger a role action: captain attack, first mate mutiny, or island governor brawl. When the Spanish Armada event appears, the side with more treasure wins; the Dutch loner wins tied loot. The fake-book box, cloth map, and chunky treasure tokens make the table look like a pirate prop chest.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:09.476Z",
  model: "gpt-5.5",
  durationMs: 27777,
  sources: [
    "https://facadegames.com/products/tortuga-1667",
    "https://www.geeksundergrace.com/tabletop/reviews-tabletop/review-tortuga-1667/",
    "https://www.ultraboardgames.com/tortuga-1667/game-rules.php",
    "https://www.polyhedroncollider.com/2017/11/tortuga-1667-review.html",
  ],
} as const;
