// GENERATED by scripts/gen-cpp-7wonders.ts — DO NOT EDIT. Run `pnpm gen-cpp-7wonders`.
#include "sw/edifice.hpp"

namespace sw {

const Edifice EDIFICES[] = {
  {1, 2, 1, {{EdRewardKind::PointsPerBrownGreySet, 2}}, {EdPenaltyKind::DiscardColor, 0, 3}},
  {1, 1, 1, {{EdRewardKind::PointsPerWonderStage}}, {EdPenaltyKind::DiscardColor, 0, 0}},
  {1, 2, 1, {{EdRewardKind::Shield, 1}}, {EdPenaltyKind::DiscardColor, 0, 1}},
  {1, 1, 1, {{EdRewardKind::Coins, 4}}, {EdPenaltyKind::Coins, 2}},
  {1, 1, 1, {{EdRewardKind::VictoryToken, 3}}, {EdPenaltyKind::DiscardColor, 0, 4}},
  {2, 3, 1, {{EdRewardKind::Production, 0, 112}}, {EdPenaltyKind::DiscardColor, 0, 0}},
  {2, 3, 1, {{EdRewardKind::PointsPerBlue}}, {EdPenaltyKind::DiscardColor, 0, 1}},
  {2, 2, 1, {{EdRewardKind::Coins, 7}}, {EdPenaltyKind::Coins, 5}},
  {2, 3, 1, {{EdRewardKind::VictoryToken, 5}}, {EdPenaltyKind::DiscardColor, 0, 4}},
  {2, 3, 1, {{EdRewardKind::Production, 0, 15}}, {EdPenaltyKind::DiscardColor, 0, 2}},
  {3, 3, 1, {{EdRewardKind::Coins, 15}}, {EdPenaltyKind::Coins, 9}},
  {3, 5, 1, {{EdRewardKind::PointsPerColor}}, {EdPenaltyKind::DiscardColor, 0, 2}},
  {3, 5, 1, {{EdRewardKind::Shield, 2}}, {EdPenaltyKind::LoseVictoryTokens, 2}},
  {3, 6, 1, {{EdRewardKind::DuplicateGuild}}, {EdPenaltyKind::DiscardColor, 0, 5}},
  {3, 5, 2, {{EdRewardKind::VictoryToken, 5}, {EdRewardKind::RemoveDefeatTokens}}, {EdPenaltyKind::DiscardColor, 0, 4}},
};
const char* const EDIFICE_NAMES[] = {
  "Artisan District",
  "Belvedere",
  "Curtain Wall",
  "Money Changer",
  "Outpost",
  "Factory",
  "Amphitheater",
  "Auction House",
  "Staging Camp",
  "River Port",
  "Gold Reserves",
  "Archives",
  "Concentric Castle",
  "Agora",
  "Military School",
};

}  // namespace sw
