// GENERATED by scripts/gen-cpp-7wonders.ts — DO NOT EDIT. Run `pnpm gen-cpp-7wonders`.
#include "sw/wonders.hpp"

namespace sw {

const Wonder WONDERS[] = {
  {0, {{1, 3, {{0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {0,3,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=5}}}, {0, {0,4,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {1, 4, {{0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {0,3,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=5}}}, {0, {0,0,3,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=5}}}, {0, {0,4,0,0,0,0,1}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}}},
  {1, {{2, 3, {{0, {0,0,2,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {3,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::ScienceWildcard}}}, {0, {0,0,4,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {2, 3, {{0, {0,0,1,0,0,1,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {2,0,0,0,1,0,0}, 1, {Effect{.kind=EffectKind::PlaySeventhCard}}}, {0, {0,0,3,0,0,0,1}, 1, {Effect{.kind=EffectKind::ScienceWildcard}}}}}}},
  {2, {{0, 3, {{0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {0,2,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::FreeBuildPerAge}}}, {0, {0,0,0,2,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {0, 3, {{0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::TradeDiscount, .tradeRaw=1, .neighbors=3}}}, {0, {0,2,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=5}}}, {0, {0,0,0,2,0,1,0}, 1, {Effect{.kind=EffectKind::CopyGuild}}}}}}},
  {3, {{3, 3, {{0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {0,0,3,0,0,0,0}, 1, {Effect{.kind=EffectKind::Shields, .amount=2}}}, {0, {0,0,0,4,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {3, 2, {{0, {0,3,0,0,0,0,0}, 3, {Effect{.kind=EffectKind::Shields, .amount=1}, Effect{.kind=EffectKind::Points, .amount=3}, Effect{.kind=EffectKind::Coins, .amount=3}}}, {0, {0,0,0,4,0,0,0}, 3, {Effect{.kind=EffectKind::Shields, .amount=1}, Effect{.kind=EffectKind::Points, .amount=4}, Effect{.kind=EffectKind::Coins, .amount=4}}}}}}},
  {4, {{6, 3, {{0, {0,2,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Coins, .amount=9}}}, {0, {0,0,0,0,0,0,2}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {6, 3, {{0, {0,2,0,0,0,0,0}, 2, {Effect{.kind=EffectKind::Points, .amount=2}, Effect{.kind=EffectKind::Coins, .amount=4}}}, {0, {2,0,0,0,0,0,0}, 2, {Effect{.kind=EffectKind::Points, .amount=3}, Effect{.kind=EffectKind::Coins, .amount=4}}}, {0, {0,0,0,0,1,1,1}, 2, {Effect{.kind=EffectKind::Points, .amount=5}, Effect{.kind=EffectKind::Coins, .amount=4}}}}}}},
  {5, {{4, 3, {{0, {0,2,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {0,0,0,2,0,0,0}, 1, {Effect{.kind=EffectKind::Production, .resMask=15, .count=1}}}, {0, {0,0,0,0,2,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {4, 3, {{0, {0,0,2,0,0,0,0}, 1, {Effect{.kind=EffectKind::Production, .resMask=15, .count=1}}}, {0, {2,0,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Production, .resMask=112, .count=1}}}, {0, {0,3,0,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}}},
  {6, {{5, 3, {{0, {0,0,2,0,0,0,0}, 1, {Effect{.kind=EffectKind::Points, .amount=3}}}, {0, {0,0,0,3,0,0,0}, 1, {Effect{.kind=EffectKind::PlayDiscarded}}}, {0, {0,0,0,0,0,2,0}, 1, {Effect{.kind=EffectKind::Points, .amount=7}}}}}, {5, 3, {{0, {0,0,0,2,0,0,0}, 2, {Effect{.kind=EffectKind::Points, .amount=2}, Effect{.kind=EffectKind::PlayDiscarded}}}, {0, {0,0,3,0,0,0,0}, 2, {Effect{.kind=EffectKind::Points, .amount=1}, Effect{.kind=EffectKind::PlayDiscarded}}}, {0, {0,0,0,0,1,1,1}, 1, {Effect{.kind=EffectKind::PlayDiscarded}}}}}}},
};
const char* const WONDER_NAMES[] = {
  "The Pyramids of Giza",
  "The Hanging Gardens of Babylon",
  "The Statue of Zeus in Olympia",
  "The Colossus of Rhodes",
  "The Temple of Artemis in Ephesos",
  "The Lighthouse of Alexandria",
  "The Mausoleum of Halikarnassos",
};

}  // namespace sw
