// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug intarsia
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Family-weight abstract puzzle where players spend color cards to nest wooden inlays and claim scoring tool tiles.",
  default:
    "Family-weight abstract puzzle about building patterned parquet on personal floor boards. On a turn, spend same-color material cards to place one wooden frame, inner piece, table, or connector. Tool tiles, connectors, and completed ornaments score points; after three rounds, most points wins.",
  loose:
    "Family-weight abstract puzzle about building patterned parquet on personal floor boards. On a turn, spend same-color material cards to place one wooden frame, midsection, core, table, or connector, then take replacement cards or a reward-track payout. Matching public tool-tile patterns scores during play; after three rounds, add connector points and ornament scores, and most points wins. The chunky wooden pieces physically nest from outer frame to tiny center table.",
};

export const meta = {
  generatedAt: "2026-07-11T21:06:31.326Z",
  model: "gpt-5.5",
  durationMs: 21162,
  sources: [
    "https://www.deep-print-games.com/en/spiele/intarsia/",
    "https://deep-print-games.com/wp-content/uploads/2024/07/Intarsia_Rules_EU_web_v1_0.pdf",
    "https://www.meeplemountain.com/reviews/intarsia/",
    "https://boardgame.de/reviews/intarsia.html",
  ],
} as const;
