// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug coup
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Bluffing card game where hidden influence cards power claims, steals, assassinations, blocks, and challenge-or-back-down moments.",
  default:
    "Bluffing and deduction card game where face-down character cards are both powers and lives. On a turn, claim a role to tax, steal, swap cards, assassinate, or spend coins on an unblockable coup. The last player with hidden influence wins.",
  loose:
    "Bluffing and deduction card game where every face-down character card is both a life and a claimed special power. On a turn, take income, foreign aid, tax as Duke, steal as Captain, swap cards as Ambassador, assassinate, or pay coins for an unblockable coup. Anyone can challenge a claimed role; a failed liar or false accuser flips one influence face up, and the last player with a hidden card wins. The tiny deck has three copies each of Duke, Assassin, Captain, Ambassador, and Contessa, so exposed cards make every confident lie easier to judge.",
};

export const meta = {
  generatedAt: "2026-08-17T00:31:48.188Z",
  model: "gpt-5.5",
  durationMs: 24080,
  sources: [
    "https://indieboardsandcards.com/our-games/coup/",
    "https://www.northstreetgames.com/images/Rulebooks/Coup-Rules.pdf",
    "https://dicetower.com/board-game-review/2491",
    "https://coups.app/rules",
    "https://www.rulespal.com/coup/rulebook",
  ],
} as const;
