// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug senso-battle-for-japan
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Light trick-taking area-control wargame where won tricks move clan cubes across Sengoku Japan’s province map.",
  default:
    "Light trick-taking area-control wargame set on a small Sengoku Japan map. Each round, players play a full hand with one favored clan as trump, then spend won tricks to move armies, add cubes, or remove enemy cubes. After eight rounds, controlled provinces score points, and the highest total wins.",
  loose:
    "Light trick-taking area-control wargame set on a small Sengoku Japan map. Each round, players play every card in hand like Whist, with one favored clan as trump, then spend won tricks to move armies, add cubes, or remove enemy cubes from provinces. After eight rounds, provinces score for the clans controlling them, and the highest victory-point total wins. The Emperor role has no armies and instead pushes rival clans around to keep the daimyo divided.",
};

export const meta = {
  generatedAt: "2026-05-13T20:21:44.087Z",
  model: "gpt-5.5",
  durationMs: 27266,
  sources: [
    "https://www.stoneswordgames.com/product-page/senso-battle-for-japan",
    "https://senjutsu.backerkit.com/hosted_preorders/project_updates?page=10",
    "https://whitespider1066.com/floating-in-the-air-like-a-dandelion-seed/",
    "https://www.philibertnet.com/en/stone-sword-games/105794-senso-battle-for-japan-5060756780057.html",
  ],
} as const;
