// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug senso-battle-for-japan
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Sengoku clans turn won hands into pressure on central Japan in a lean trick-taking fight over shifting provinces.",
  default:
    "Captured tricks do not just score cards; they send clans pushing across a small map of Japan. Trick-taking drives the game as won hands move, add, or remove clan cubes. After eight rounds, control of the richest provinces decides the throne.",
  loose:
    "Familiar card-play turns sharp because every captured trick becomes pressure on the map. Trick-taking drives the game: hands won become orders to shift clan cubes across central Japan. After eight rounds, the strongest holdings across the map decide the claimant to the throne. Its full 54-card deck has Raben White’s hand-painted courts for Oda, Takeda, Uesugi, and Mōri.",
};

export const meta = {
  generatedAt: "2026-05-13T16:40:02.323Z",
  model: "gpt-5.5",
  durationMs: 51554,
  sources: [
    "https://www.stoneswordgames.com/senso",
    "https://www.stoneswordgames.com/product-page/senso-battle-for-japan",
    "https://www.philibertnet.com/en/stone-sword-games/105794-senso-battle-for-japan-5060756780057.html",
    "https://www.nobleknight.com/P/2148118046/Senso-Battle-for-Japan",
  ],
} as const;
