// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug letter-jam
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative word-deduction game where players give numbered letter clues while seeing everyone’s hidden letters but their own.",
  default:
    "Cooperative word-deduction game about solving a secret anagram while everyone else can see the current letter. Each round, players offer clue lengths, pick a clue giver, and mark visible letters with numbered chips. The team wins if everyone rearranges their guessed letters into real words.",
  loose:
    "Cooperative word-deduction game about solving a secret anagram while everyone else can see the current letter. Each round, players scan the table for a useful word, announce only its length, then one clue giver marks visible letters with numbered chips. The team wins if everyone rearranges their guessed letters into real words before clues run out. The chunky poker-chip numbers make each clue land like a quiet table puzzle.",
};

export const meta = {
  generatedAt: "2026-08-17T00:32:13.597Z",
  model: "gpt-5.5",
  durationMs: 33422,
  sources: [
    "https://letterjam.game/tutorial",
    "https://coopboardgames.com/cooperative-board-game-reviews/letter-jam-review/",
    "https://czechgames.com/files/rules/letter-jam-rules-en.pdf",
  ],
} as const;
