// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug brass-birmingham
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Heavy economic network game where industrialists spend cards and cash to build mills, mines, breweries, canals, and rail links.",
  default:
    "Heavy economic strategy game about building a shared industrial network across the English Midlands. On a turn, spend two actions to play cards, place industry tiles, lay canal or rail links, sell goods, develop, scout, or take loans. After the canal era and rail era, flipped industries and links score points; highest total wins.",
  loose:
    "Heavy economic strategy game about building a shared industrial network across the English Midlands. On a turn, spend two actions to play a city or industry card, place an industry tile, lay a canal or rail link, sell goods, develop better tiles, scout, or take a loan. Scoring happens after the canal era and again after the rail era; flipped industries and links score points, and the highest total wins. Coal, iron, and beer often come from rivals’ tiles, so helping another factory flip can be the cheapest way to finish a plan.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:34.189Z",
  model: "gpt-5.5",
  durationMs: 15157,
  sources: [
    "https://roxley.com/products/brass-birmingham",
    "https://www.gamesradar.com/games/board-games/brass-birmingham-review/",
  ],
} as const;
