// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug brass-birmingham
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Industrial ambition becomes a shared supply trap where every coal cube or beer barrel taken helps a rival through hand management.",
  default:
    "Shared coal and beer make every rival useful and dangerous in a smoky West Midlands economy. Hand management drives turns, with cards spent to build, connect, sell, develop, or borrow. Victory comes from flipped industries and scored links across two eras.",
  loose:
    "Shared coal and beer make every rival useful and dangerous in a smoky West Midlands economy. Hand management drives turns, with cards spent to build industries, lay links, develop, sell, or take loans. Victory comes from flipped industries and canal or rail links scored after each era, after the rail reset sweeps away early networks. Beer is the signature bottleneck, unlocking sales and double-rail turns.",
};

export const meta = {
  generatedAt: "2026-05-13T16:33:10.110Z",
  model: "gpt-5.5",
  durationMs: 27422,
  sources: [
    "https://roxley.com/products/brass-birmingham",
    "https://boardgamegeek.com/wiki/page/thing%3A224517%3Amoreinfo",
    "https://www.gamesradar.com/games/board-games/brass-birmingham-review/",
  ],
} as const;
