// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug wavelength
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Social party guessing game where a clue-giver hints at a hidden dial position and teammates argue where to point the needle.",
  default:
    "Social party guessing game about finding a hidden target on a spectrum. Each round, one clue-giver sees the target, gives a clue between two opposite ideas, and teammates debate where to set the red dial. First team to reach 10 points wins.",
  loose:
    "Social party guessing game about placing a red dial on a hidden target along a spectrum. Each round, one clue-giver sees the target, chooses a card like Hot/Cold, gives one clue, then stays silent while teammates debate and set the dial. Reveal scores 2 to 4 points for closeness, and first team to reach 10 points wins. The plastic device sits in the box with a sliding screen, rotating wheel, red dial, and score markers.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:47.726Z",
  model: "gpt-5.5",
  durationMs: 31133,
  sources: [
    "https://www.cmyk.games/products/wavelength",
    "https://news.lincc.org/sites/default/files/lot-manuals/Wavelength%20rules.pdf",
    "https://www.reddit.com/r/boardgames/comments/ekx7vx/wavelength_is_an_amazing_party_game/",
  ],
} as const;
