// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug 7-wonders
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Ancient cities rise through three brisk ages, as drafting turns every card into growth for one city and denial for a neighbor.",
  default:
    "Ancient cities rise side by side, and every hand of cards makes progress feel like theft from the neighbors. Drafting drives each age: choose one card, pass the hand, then reveal builds at the same time. After the third age, the highest score wins.",
  loose:
    "Ancient cities rise side by side, and every hand of cards makes progress feel like theft from the neighbors. Drafting drives each age: choose one card, pass the hand, then reveal builds at the same time. After the third age, the high score across buildings, wonder stages, wars, science, guilds, and coins wins. The second edition redraws the cards and wonder boards with clearer iconography built from a decade of play.",
};

export const meta = {
  generatedAt: "2026-05-13T16:30:26.388Z",
  model: "gpt-5.5",
  durationMs: 23174,
  sources: [
    "https://www.rprod.com/en/games/7-wonders",
    "https://www.rprod.com/en/press/7-wonders",
    "https://cdn.svc.asmodee.net/production-rprod/storage/downloads/games/7wonders/en/sev-en02-rules-1716388903zBEZx.pdf",
  ],
} as const;
