// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug 7-wonders
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Civilization card-drafting game where players pick one building card, pass the hand, and grow resource, science, war, and point engines.",
  default:
    "Civilization card-drafting game about building an ancient city tableau over three Ages. Each turn, players secretly choose one card, then build it, tuck it under their wonder board, or discard it for coins. After the final Age, highest total score wins.",
  loose:
    "Civilization card-drafting game about building an ancient city tableau over three Ages. Each turn, players choose one card from a hand at the same time, then pay resources to build it, tuck it under their wonder board, or discard it for coins. After each Age, neighboring armies compare strength, and after the final Age the highest victory-point total wins. The second edition uses larger wonder boards and clearer card icons for the different building colors.",
};

export const meta = {
  generatedAt: "2026-05-13T20:17:17.591Z",
  model: "gpt-5.5",
  durationMs: 17251,
  sources: [
    "https://www.rprod.com/en/press/7-wonders",
    "https://www.rprod.com/en/games/7-wonders",
    "https://rollsinthefamily.com/reviewed-games/7-wonders-review",
  ],
} as const;
