// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug concordia-special-edition
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight: "Thinky card-driven euro where one played card moves colonists, builds houses, triggers production, or buys scoring cards.",
  default: "Thinky, low-luck economic euro about spreading colonists across a map to plant trading houses that make specific goods. Each turn, a player plays one hand card to move and build, trigger province-wide production, trade goods for coins, or buy new personality cards, then later plays Tribune to take all played cards back.",
  loose: "Thinky, low-luck economic euro about spreading colonists across a map to plant trading houses that make specific goods. Each turn, a player plays one hand card to move and build, trigger province-wide production, trade goods for coins, or buy new personality cards, then later plays Tribune to take all played cards back. When the last house is built or the card display runs out, players score by applying each personality card’s end-game formula to the board state, and high score wins.",
};

export const meta = {
  generatedAt: "2026-09-03T02:47:53.502Z",
  model: "openai/gpt-5.2",
  durationMs: 110880,
  sources: [
    "https://www.boardgameoracle.com/boardgame/price/83srXyhuW2/concordia-special-edition",
    "https://cdn.ultraboardgames.com/concordia/game-rules.php",
    "https://wuerfelreich.de/concordia-special-edition-awaken-realms-gamefound/",
    "https://brettspielbox.de/brettspiel-crowdfunding-news-21-26/",
    "https://forum.cwowd.com/t/concordia-special-edition-par-awaken-realms-livraison-en-juillet-2027/78705?page=3",
    "https://ludopedia.com.br/topico/99914/concordia-special-edition-o-que-ha-de-novo-na-nova-versao-pimpada",
    "https://www.pd-verlag.de/Concordia-Englisch",
    "https://tabletopinfo.com/board-games/concordia/"
  ],
} as const;
