// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug spot-it-super-mario
//
// To override one description by hand, set `bggOverrides.description` on
// this game's entry in `packages/core/src/games/catalog.json` — it will
// replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Real-time speed-matching party game where any two round cards share exactly one symbol and the first to shout it claims or dumps a card.",
  default:
    "Real-time speed-matching party game where any two round cards share exactly one of their eight symbols. Everyone races at once to shout the match, then claims the card or dumps one. Each mini-game goes to the biggest or smallest pile, and most mini-games won takes it all.",
  loose:
    "Real-time speed-matching party game where any two round cards share exactly one of their eight symbols. Everyone races at once to shout the match, then claims the card or dumps one. The Tower rewards the biggest pile, The Well the first empty hand, Poisoned Gift the fewest cards, and most mini-games won takes it all. This edition redraws the symbols as Mario, Peach, Toad, Yoshi, Bowser, mushrooms and Koopa shells, packed in a small round tin.",
};

export const meta = {
  generatedAt: "2026-09-14T12:37:29.000Z",
  model: "claude-opus-5 (simulated run — gateway throttled)",
  durationMs: 178000,
  sources: [
    "https://www.asmodee.co.uk/blogs/news/how-to-play-dobble",
    "https://www.rulespal.com/spot-it/rulebook",
    "https://puzzlewocky.com/games/the-math-of-spot-it/",
    "https://en.wikipedia.org/wiki/Dobble",
    "https://forbiddenplanet.com/428251-dobble-super-mario/",
    "https://spellenspektakel.nl/spellen/dobble-super-mario/?lang=en",
  ],
} as const;
