import type { TimelineEvent, TimelineKind } from "@boardgames/core/games/quiztopia/timeline";
import { type TimelineItem, toTimelineItem } from "../../logic/timeline-layout";

// Forty pinned moments for `/dev/quiztopia-preview?scene=timeline`: deep
// time, BC dates, day-precision events, lifespans (one of a living person),
// wars and reigns across all twelve districts, a mix of known and still
// learning — enough to judge the river without a member's real pins.

type Row = [
  id: string,
  kind: TimelineKind,
  start: string,
  end: string | null,
  labelEn: string,
  labelDe: string,
  question: string,
  answer: string,
  extra?: Partial<TimelineEvent> & { learning?: boolean; wiki?: string },
];

const ROWS: Row[] = [
  [
    "c010-s10-q0",
    "era",
    "-13800000000",
    null,
    "The Big Bang",
    "Der Urknall",
    "How old is the universe, roughly?",
    "13.8 billion years",
    { precision: "megayear", approx: true },
  ],
  [
    "c011-s10-q1",
    "event",
    "-4540000000",
    null,
    "The Earth forms",
    "Die Erde entsteht",
    "How old is the Earth?",
    "4.54 billion years",
    { precision: "megayear", approx: true },
  ],
  [
    "c012-s11-q0",
    "era",
    "-252000000",
    "-66000000",
    "The age of the dinosaurs",
    "Das Zeitalter der Dinosaurier",
    "Which era is called the age of reptiles?",
    "Mesozoic",
    { precision: "megayear", learning: true },
  ],
  [
    "c013-s10-q2",
    "event",
    "-66000000",
    null,
    "The Chicxulub impact",
    "Der Chicxulub-Einschlag",
    "Which crater marks the end of the dinosaurs?",
    "Chicxulub",
    { precision: "megayear" },
  ],
  [
    "c014-s09-q3",
    "discovery",
    "-300000",
    null,
    "Earliest Homo sapiens at Jebel Irhoud",
    "Früheste Homo sapiens in Jebel Irhoud",
    "Where were the oldest known Homo sapiens fossils found?",
    "Jebel Irhoud",
    { precision: "megayear", approx: true },
  ],
  [
    "c015-s03-q0",
    "creation",
    "-15000",
    null,
    "The Lascaux cave paintings",
    "Die Höhlenmalereien von Lascaux",
    "Which French cave is famous for its Palaeolithic paintings?",
    "Lascaux",
    { precision: "millennium", approx: true, learning: true },
  ],
  [
    "c016-s02-q1",
    "creation",
    "-3200",
    null,
    "Cuneiform writing appears in Sumer",
    "In Sumer entsteht die Keilschrift",
    "What is the oldest known writing system?",
    "Cuneiform",
    { precision: "century", approx: true },
  ],
  [
    "c017-s03-q2",
    "creation",
    "-2560",
    null,
    "The Great Pyramid of Giza is completed",
    "Die Cheops-Pyramide wird fertiggestellt",
    "For which pharaoh was the Great Pyramid built?",
    "Khufu",
    { approx: true },
  ],
  [
    "c018-s06-q0",
    "event",
    "-776",
    null,
    "The first recorded Olympic Games",
    "Die ersten überlieferten Olympischen Spiele",
    "In which year are the first Olympic Games recorded?",
    "776 BC",
  ],
  [
    "c019-s08-q4",
    "lifespan",
    "-470",
    "-399",
    "Socrates, philosopher",
    "Sokrates, Philosoph",
    "Which philosopher was sentenced to drink hemlock?",
    "Socrates",
    { learning: true },
  ],
  [
    "c020-s06-q1",
    "event",
    "-44-03-15",
    null,
    "Julius Caesar is assassinated",
    "Julius Caesar wird ermordet",
    "On which day was Caesar murdered?",
    "The Ides of March",
    { precision: "day" },
  ],
  [
    "c021-s06-q2",
    "reign",
    "-27",
    "14",
    "Augustus rules Rome",
    "Augustus herrscht über Rom",
    "Who was the first Roman emperor?",
    "Augustus",
  ],
  [
    "c022-s10-q3",
    "event",
    "79-08-24",
    null,
    "Vesuvius buries Pompeii",
    "Der Vesuv verschüttet Pompeji",
    "Which city did Vesuvius bury?",
    "Pompeii",
    { precision: "day", learning: true },
  ],
  [
    "c023-s06-q3",
    "event",
    "476",
    null,
    "The Western Roman Empire falls",
    "Das Weströmische Reich endet",
    "Who deposed the last Western Roman emperor?",
    "Odoacer",
  ],
  [
    "c024-s06-q4",
    "event",
    "800-12-25",
    null,
    "Charlemagne is crowned emperor",
    "Karl der Große wird zum Kaiser gekrönt",
    "Who was crowned emperor on Christmas Day 800?",
    "Charlemagne",
    { precision: "day" },
  ],
  [
    "c025-s07-q0",
    "event",
    "1215-06-15",
    null,
    "Magna Carta is sealed",
    "Die Magna Carta wird besiegelt",
    "Which English king sealed Magna Carta?",
    "King John",
    { precision: "day" },
  ],
  [
    "c026-s03-q3",
    "creation",
    "1200",
    null,
    "Gothic cathedrals spread across Europe",
    "Gotische Kathedralen verbreiten sich in Europa",
    "Which style followed the Romanesque?",
    "Gothic",
    { precision: "century", approx: true, learning: true },
  ],
  [
    "c027-s06-q0",
    "period",
    "1337",
    "1453",
    "The Hundred Years' War",
    "Der Hundertjährige Krieg",
    "Which war did Joan of Arc fight in?",
    "The Hundred Years' War",
  ],
  [
    "c028-s12-q1",
    "creation",
    "1450",
    null,
    "Gutenberg's printing press",
    "Gutenbergs Druckerpresse",
    "Who invented movable-type printing in Europe?",
    "Johannes Gutenberg",
    { approx: true },
  ],
  [
    "c029-s03-q4",
    "lifespan",
    "1452-04-15",
    "1519-05-02",
    "Leonardo da Vinci, painter and engineer",
    "Leonardo da Vinci, Maler und Ingenieur",
    "Who painted the Mona Lisa?",
    "Leonardo da Vinci",
    { precision: "day" },
  ],
  [
    "c030-s08-q0",
    "event",
    "1517-10-31",
    null,
    "Luther's Ninety-five Theses",
    "Luthers 95 Thesen",
    "Where did Luther post his theses?",
    "Wittenberg",
    { precision: "day" },
  ],
  [
    "c031-s01-q2",
    "lifespan",
    "1564-04",
    "1616-04-23",
    "William Shakespeare, playwright",
    "William Shakespeare, Dramatiker",
    "Who wrote Hamlet?",
    "William Shakespeare",
    { precision: "month" },
  ],
  [
    "c032-s06-q1",
    "period",
    "1618",
    "1648",
    "The Thirty Years' War",
    "Der Dreißigjährige Krieg",
    "Which treaty ended the Thirty Years' War?",
    "Peace of Westphalia",
    { learning: true },
  ],
  [
    "c033-s09-q2",
    "discovery",
    "1687",
    null,
    "Newton's Principia is published",
    "Newtons Principia erscheint",
    "Who formulated the law of universal gravitation?",
    "Isaac Newton",
  ],
  [
    "c034-s01-q0",
    "lifespan",
    "1756-01-27",
    "1791-12-05",
    "Wolfgang Amadeus Mozart, composer",
    "Wolfgang Amadeus Mozart, Komponist",
    "Who composed The Magic Flute?",
    "Mozart",
    { precision: "day" },
  ],
  [
    "c035-s07-q1",
    "event",
    "1789-07-14",
    null,
    "The storming of the Bastille",
    "Der Sturm auf die Bastille",
    "What is celebrated in France on 14 July?",
    "The storming of the Bastille",
    { precision: "day" },
  ],
  [
    "c036-s01-q1",
    "event",
    "1797-02-12",
    null,
    "Haydn's imperial hymn premieres in Vienna",
    "Haydns Kaiserhymne wird in Wien uraufgeführt",
    "Who composed „Gott erhalte Franz den Kaiser“?",
    "Joseph Haydn",
    { precision: "day" },
  ],
  [
    "c037-s01-q1",
    "creation",
    "1841-08-26",
    null,
    "Hoffmann von Fallersleben writes the „Lied der Deutschen“ on Heligoland",
    "Hoffmann von Fallersleben dichtet auf Helgoland das „Lied der Deutschen“",
    "Who wrote the lyrics of the „Lied der Deutschen“ on Heligoland in 1841?",
    "August Heinrich Hoffmann von Fallersleben",
    { precision: "day", wiki: "https://de.wikipedia.org/wiki/Das_Lied_der_Deutschen" },
  ],
  [
    "c038-s11-q0",
    "creation",
    "1859-11-24",
    null,
    "Darwin publishes On the Origin of Species",
    "Darwin veröffentlicht Über die Entstehung der Arten",
    "Who wrote On the Origin of Species?",
    "Charles Darwin",
    { precision: "day", learning: true },
  ],
  [
    "c039-s01-q3",
    "lifespan",
    "1898-07-06",
    "1962-09-06",
    "Hanns Eisler, composer",
    "Hanns Eisler, Komponist",
    "Who composed the music for Brecht's „Kinderhymne“?",
    "Hanns Eisler",
    { precision: "day" },
  ],
  [
    "c040-s06-q2",
    "period",
    "1914-07-28",
    "1918-11-11",
    "The First World War",
    "Der Erste Weltkrieg",
    "When did the First World War end?",
    "11 November 1918",
    { precision: "day" },
  ],
  [
    "c041-s04-q0",
    "creation",
    "1927-10",
    null,
    "The Jazz Singer, the first talkie",
    "Der Jazzsänger, der erste Tonfilm",
    "What was the first feature-length talkie?",
    "The Jazz Singer",
    { precision: "month" },
  ],
  [
    "c042-s01-q4",
    "creation",
    "1949-11-06",
    null,
    "„Auferstanden aus Ruinen“ is first published",
    "„Auferstanden aus Ruinen“ erscheint erstmals im Druck",
    "Who wrote the lyrics of the East German anthem?",
    "Johannes R. Becher",
    { precision: "day" },
  ],
  [
    "c043-s01-q0",
    "creation",
    "1950",
    null,
    "Brecht writes the „Kinderhymne“",
    "Brecht schreibt die „Kinderhymne“",
    "Who wrote the poem „Die Kinderhymne“?",
    "Bertolt Brecht",
  ],
  [
    "c044-s05-q3",
    "event",
    "1954-07-04",
    null,
    "The Miracle of Bern",
    "Das Wunder von Bern",
    "Whom did West Germany beat in the 1954 World Cup final?",
    "Hungary",
    { precision: "day" },
  ],
  [
    "c045-s07-q2",
    "lifespan",
    "1954-07-17",
    null,
    "Angela Merkel, chancellor",
    "Angela Merkel, Bundeskanzlerin",
    "Who was German chancellor from 2005 to 2021?",
    "Angela Merkel",
    { precision: "day", ongoing: true },
  ],
  [
    "c046-s10-q4",
    "event",
    "1969-07-20",
    null,
    "Apollo 11 lands on the Moon",
    "Apollo 11 landet auf dem Mond",
    "Who was the first person on the Moon?",
    "Neil Armstrong",
    { precision: "day" },
  ],
  [
    "c047-s12-q0",
    "creation",
    "1989-03",
    null,
    "Tim Berners-Lee proposes the World Wide Web",
    "Tim Berners-Lee schlägt das World Wide Web vor",
    "Where was the Web invented?",
    "CERN",
    { precision: "month", learning: true },
  ],
  [
    "c048-s07-q3",
    "event",
    "1989-11-09",
    null,
    "The Berlin Wall falls",
    "Die Berliner Mauer fällt",
    "On which day did the Berlin Wall fall?",
    "9 November 1989",
    { precision: "day" },
  ],
  [
    "c049-s04-q1",
    "period",
    "2008",
    null,
    "The Marvel Cinematic Universe begins",
    "Das Marvel Cinematic Universe beginnt",
    "Which film launched the MCU?",
    "Iron Man",
    { ongoing: true },
  ],
  [
    "c050-s09-q1",
    "discovery",
    "2012-07-04",
    null,
    "The Higgs boson is announced",
    "Das Higgs-Boson wird verkündet",
    "Which particle was announced at CERN in 2012?",
    "The Higgs boson",
    { precision: "day" },
  ],
];

const NOW = { year: 2026, month: 9, day: 24 };

function precisionOf(start: string): TimelineEvent["precision"] {
  const parts = start.replace(/^-/, "").split("-").length;
  return parts === 3 ? "day" : parts === 2 ? "month" : "year";
}

export const PREVIEW_TIMELINE: readonly TimelineItem[] = ROWS.flatMap(
  ([id, kind, start, end, labelEn, labelDe, question, answer, extra = {}]) => {
    const { learning, wiki, ...rest } = extra;
    const event: TimelineEvent = {
      kind,
      start,
      end,
      precision: precisionOf(start),
      approx: false,
      ongoing: false,
      labelEn,
      labelDe,
      ...rest,
    };
    const slug = labelEn.replace(/[^A-Za-z0-9]+/g, "_").replace(/^_|_$/g, "");
    const item = toTimelineItem(
      id,
      event,
      { known: !learning, lastReviewedAt: "2026-09-20T18:30:00.000Z" },
      NOW,
      {
        en: question,
        de: question,
        answerEn: answer,
        answerDe: answer,
        source: {
          url: wiki ?? `https://en.wikipedia.org/wiki/${slug}`,
          title: `${labelEn} – Wikipedia`,
          lang: wiki ? "de" : "en",
        },
      },
    );
    return item ? [item] : [];
  },
).sort((a, b) => a.parsed.startKey - b.parsed.startKey);
