// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug gloomhaven-jaws-of-the-lion
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Cooperative campaign dungeon-crawler where mercenaries pick two action cards, move on hex maps, and kill monsters.",
  default:
    "Cooperative campaign dungeon-crawler about tactical fights in linked city scenarios. Each round, players choose two ability cards, reveal initiative, then use one top action and one bottom action. The party wins a scenario by completing its objective before too many cards are lost.",
  loose:
    "Cooperative campaign dungeon-crawler about tactical fights in linked city scenarios. Each round, players secretly choose two ability cards, reveal initiative, then use one top action and one bottom action to move, attack, heal, loot, or push monsters around a hex map. The party wins a scenario by completing its printed objective before hands run dry, then spends gold and experience between chapters. Instead of loose room tiles, the map is the spiral scenario book opened flat on the table.",
};

export const meta = {
  generatedAt: "2026-05-13T20:19:31.957Z",
  model: "gpt-5.5",
  durationMs: 17344,
  sources: [
    "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",
    "https://cephalofair.com/",
    "https://gamesnightguru.com/games/gloomhaven-jaws-lion/",
    "https://www.gamesradar.com/tabletop-gaming/gloomhaven-jaws-of-the-lion-review-all-the-greatness-condensed/",
  ],
} as const;
