// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug gloomhaven-jaws-of-the-lion
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Dungeon combat becomes a shrinking hand of mercenary choices, with hand management driving each desperate room.",
  default:
    "Every dungeon fight is a rationing problem, where powerful attacks burn the same cards that keep mercenaries alive. Hand management drives each round of combat. The campaign advances by clearing scenario objectives before exhaustion empties the party's decks.",
  loose:
    "Every fight turns a fantasy dungeon crawl into a rationing problem, where big attacks burn the same cards needed to stay alive. Hand management drives combat, with two chosen cards setting initiative and actions each round. The campaign advances by clearing scenario objectives before exhaustion empties the party's decks. The book opens flat as the map, so rooms appear on printed hexes instead of loose tiles.",
};

export const meta = {
  generatedAt: "2026-05-13T16:36:25.132Z",
  model: "gpt-5.5",
  durationMs: 96736,
  sources: [
    "https://cephalofair.com/products/gloomhaven-jaws-of-the-lion",
    "https://boardgamegeek.com/boardgame/291457/gloomhaven-jaws-of-the-lion",
    "https://cs.uwaterloo.ca/~dtompkin/archive/dtlib/base/Gloomhaven%20-%20Jaws%20of%20the%20Lion.pdf",
  ],
} as const;
