// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-old-kings-crown
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Rival heirs telegraph claims with Heralds, then hide armies in face-down clashes driven by hand management.",
  default:
    "Rival heirs stake visible claims with Heralds, then spring hidden cards into three simultaneous clashes. The core is hand management. Influence crowns the claimant who can win locations without draining the hand that fuels every bluff.",
  loose:
    "Rival heirs stake visible claims with Heralds, then spring hidden cards into three simultaneous clashes across a ruined kingdom. The core is hand management. Influence crowns the claimant who can win locations without draining the hand that fuels every bluff. Each round follows Spring, Summer, Autumn, and Winter, so a card can fight, govern in council, or vanish on a Journey before cleanup.",
};

export const meta = {
  generatedAt: "2026-05-13T16:41:48.893Z",
  model: "gpt-5.5",
  durationMs: 25983,
  sources: [
    "https://www.wargamer.com/the-old-kings-crown/board-game-review",
    "https://www.meeplemountain.com/reviews/the-old-kings-crown/",
    "https://www.nopunincluded.com/npi/theoldkingscrown",
    "https://zatu.com/products/the-old-kings-crown",
  ],
} as const;
