// AUTO-GENERATED by `pnpm gen-descriptions`.
// Edit by re-running the script for this slug:
//   pnpm gen-descriptions --slug the-old-kings-crown
//
// To override one description by hand, set `bggOverrides.description` in
// this game's index.ts — it will replace all three variants uniformly.

import type { GameDescriptions } from "../types";

export const descriptions: GameDescriptions = {
  tight:
    "Thinky card-driven area-control game where players bluff facedown cards into regions, add supporters, and win influence.",
  default:
    "Thinky card-driven area-control game where rival factions bluff cards into three regions and fight for influence. Each round, players bid, place a Herald, assign facedown cards, then reveal clashes with supporters and powers. Highest influence after the final round wins.",
  loose:
    "Thinky card-driven area-control game where rival factions bluff cards into three regions and fight for influence. Each round, players bid for kingdom cards, place a Herald, seed facedown cards, then reveal clashes and add supporters and powers. Won clashes claim location rewards: influence, council seats, lore for new cards, or card recovery; highest influence after the final round wins. The seasonal track is the table cue for when tactics, faction cards, and favor powers can fire.",
};

export const meta = {
  generatedAt: "2026-05-13T20:23:06.536Z",
  model: "gpt-5.5",
  durationMs: 38886,
  sources: [
    "https://boardgamegeek.com/boardgame/357873/the-old-kings-crown",
    "https://www.eerieidolgames.com/",
    "https://www.wargamer.com/the-old-kings-crown/board-game-review",
    "https://www.meeplemountain.com/reviews/the-old-kings-crown/",
  ],
} as const;
